/**
 * The staff bulk-edit template contract: header names and what they write to.
 *
 * ONE source of truth for the template writer, the sheet parser and the error-sheet
 * writer. Columns are matched by HEADER NAME, never by position, so reordering columns
 * in Excel cannot corrupt an import.
 *
 * The vocabularies below are copied from the DB CHECK constraints, NOT from
 * staff-form-schema.ts. The constraint is what actually rejects the write; the Zod
 * schema is a copy and copies drift.
 *   staff_gender_check         male | female | bigender
 *   staff_marital_status_check single | married | divorced | widow
 *   staff_blood_group_check    A+ A- B+ B- AB+ AB- O+ O- A1+ A1B
 */

export const GENDERS = ['male', 'female', 'bigender'] as const;
export const MARITAL_STATUSES = ['single', 'married', 'divorced', 'widow'] as const;
export const BLOOD_GROUPS = [
  'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'A1+', 'A1B'
] as const;

export type StaffEditableField =
  | 'phone'
  | 'email'
  | 'date_of_birth'
  | 'gender'
  | 'marital_status'
  | 'blood_group'
  | 'address'
  | 'state'
  | 'district'
  | 'pincode'
  | 'designation'
  | 'date_of_joining'
  | 'department_id'
  | 'category_id'
  | 'biometric_id'
  | 'biometric_institution_id';

export interface BulkEditColumn {
  header: string;
  /** null = identify-only. Written to the sheet, ignored on import. */
  field: StaffEditableField | null;
  kind: 'text' | 'date' | 'enum' | 'lookup';
  enumValues?: readonly string[];
  /** Shown on the Instructions sheet. */
  note?: string;
}

export const MATCH_KEY_HEADER = 'Institution Email';

export const BULK_EDIT_COLUMNS: readonly BulkEditColumn[] = [
  // ── Identify (locked) ───────────────────────────────────────────────
  { header: MATCH_KEY_HEADER, field: null, kind: 'text',
    note: 'Match key. Do not edit. This is the raw stored address — for view-only staff it is a @nolog.jkkn.local placeholder, which is still the real key.' },
  // Identify-only, and now permanently so: since 2026-08-28 staff IDs are
  // generated by the database and frozen, so there is no "Staff ID (new)"
  // counterpart any more. Writing this column raises P0001.
  { header: 'Staff ID', field: null, kind: 'text', note: 'Do not edit. System-generated and permanent; shown so you can recognise the row.' },
  { header: 'Name',              field: null, kind: 'text', note: 'Do not edit.' },
  { header: 'Institution',       field: null, kind: 'text', note: 'Do not edit. Bulk edit cannot move a person between institutions.' },

  // ── Personal & contact ──────────────────────────────────────────────
  { header: 'Phone',          field: 'phone',          kind: 'text' },
  { header: 'Personal Email', field: 'email',          kind: 'text', note: 'Must be unique across all staff.' },
  { header: 'Date of Birth',  field: 'date_of_birth',  kind: 'date' },
  { header: 'Gender',         field: 'gender',         kind: 'enum', enumValues: GENDERS },
  { header: 'Marital Status', field: 'marital_status', kind: 'enum', enumValues: MARITAL_STATUSES },
  { header: 'Blood Group',    field: 'blood_group',    kind: 'enum', enumValues: BLOOD_GROUPS },
  { header: 'Address',        field: 'address',        kind: 'text' },
  // Validated against lib/data/locations.ts since 2026-08-28 and stored in the
  // dataset's spelling, so a bulk edit cannot re-introduce the free-text mess
  // the staff form was just cleaned of. Case and spacing are forgiven;
  // an unknown name is rejected.
  { header: 'State',          field: 'state',          kind: 'lookup',
    note: 'Must match a state in the staff form\'s State dropdown. Case does not matter.' },
  { header: 'District',       field: 'district',       kind: 'lookup',
    note: 'Must match a district in the staff form\'s District dropdown, within this person\'s state.' },
  { header: 'Pincode',        field: 'pincode',        kind: 'text', note: '6 digits.' },

  // ── Employment ──────────────────────────────────────────────────────
  { header: 'Designation',     field: 'designation',     kind: 'text' },
  { header: 'Date of Joining', field: 'date_of_joining', kind: 'date' },
  { header: 'Department',      field: 'department_id',   kind: 'lookup', note: 'Department NAME, resolved within this person\'s institution.' },
  { header: 'Category',        field: 'category_id',     kind: 'lookup', note: 'Employment category NAME.' },

  // ── Biometric attendance ────────────────────────────────────────────
  { header: 'Biometric Code',    field: 'biometric_id',             kind: 'text',
    note: 'Empcode from the machine. Leading zeros are ignored — 00002, 002 and 2 are one code.' },
  { header: 'Biometric Machine', field: 'biometric_institution_id', kind: 'lookup',
    note: 'Institution that OWNS the machine — often NOT this person\'s institution. Required whenever a code is given.' }
] as const;

export const EDITABLE_COLUMNS = BULK_EDIT_COLUMNS.filter(
  (c): c is BulkEditColumn & { field: StaffEditableField } => c.field !== null
);
