// ============================================================================
// GENERATED FILE — do not edit by hand.
// Source: scripts/director-desk/scan-route-gates.mjs
// Regenerate: node scripts/director-desk/scan-route-gates.mjs
// Drift guard: __tests__/director-desk/route-gate-map.test.ts
//
// Every route whose real gate is NOT simply its MENU_PERMISSIONS key.
// 118 routes cannot be handed over at all; 381 declare
// their own permission keys through PermissionGuard / PolicyPageShell.
// ============================================================================

/** Why a route refuses a handover. All three are gates a grant cannot satisfy. */
export type RouteGateBlock = 'superAdmin' | 'adminRole' | 'unreadable';

export interface RouteGateEntry {
  /** Present when no handover can ever open this page. */
  blocked?: RouteGateBlock;
  /** The page's own gate keys, from PermissionGuard / PolicyPageShell. */
  keys?: string[];
  /**
   * The route ALSO sits under a RoutePermissionGuard, so its
   * MENU_PERMISSIONS key is enforced too and must be granted alongside
   * the keys above. Absent means the menu key gates nothing here.
   */
  routeGuarded?: boolean;
}

export const ROUTE_GATE_MAP: Record<string, RouteGateEntry> = {
  "/academic/attendance/consolidation": { keys: ['academic.attendance.consolidation.view'] },
  "/academic/attendance/consolidation/facilitators": { keys: ['academic.attendance.facilitator-report.view'] },
  "/academic/attendance/history": { keys: ['academic.attendance.dashboard.view'] },
  "/academic/attendance/pending": { keys: ['academic.attendance.view'] },
  "/academic/attendance/reports": { keys: ['academic.attendance.reports.view'] },
  "/academic/batches": { keys: ['academic.batches.view'] },
  "/academic/leave-calendar": { keys: ['academic.leaves.view'] },
  "/academic/leaves": { keys: ['academic.leaves.view'] },
  "/academic/leaves/[id]": { keys: ['academic.leaves.view'] },
  "/academic/leaves/[id]/edit": { keys: ['academic.leaves.edit'] },
  "/academic/leaves/new": { keys: ['academic.leaves.create'] },
  "/academic/leaves/settings": { keys: ['academic.leaves.manage'] },
  "/academic/leaves/settings/types": { keys: ['academic.leaves.manage'] },
  "/academic/leaves/settings/workflows": { keys: ['academic.leaves.manage'] },
  "/academic/periods": { keys: ['academic.periods.view'] },
  "/academic/regulations": { keys: ['academic.regulations.view'] },
  "/academic/session-feedback/note-review": { keys: ['scf.notes.review'] },
  "/academic/staff-planning": { keys: ['academic.staff.planning.view'] },
  "/academic/timetables": { keys: ['academic.timetables.view'] },
  "/academic/timetables/faculty-calendar": { keys: ['faculty.calendar.view'] },
  "/academic/timetables/faculty-calendar/admin": { keys: ['faculty.calendar.view'] },
  "/academic/timetables/templates": { keys: ['academic.timetables.templates.view'] },
  "/academic/timetables/templates/[id]": { keys: ['academic.timetables.templates.view'] },
  "/academic/timetables/templates/analytics": { keys: ['academic.timetables.templates.analytics'] },
  "/academic/years": { keys: ['academic.years.view'] },
  "/accreditation/manage/collaborations": { keys: ['accreditation.collaborations.view'] },
  "/accreditation/manage/grievance-categories": { keys: ['grievance.categories.manage'] },
  "/accreditation/manage/metrics": { keys: ['accreditation.metrics.manage'] },
  "/accreditation/manage/utility-readings": { keys: ['accreditation.sustainability_readings.view'] },
  "/accreditation/naac/surveys/stakeholders": { keys: ['accreditation.naac.surveys.stakeholder.view'] },
  "/admin/ai-models": { blocked: 'superAdmin' },
  "/admin/ai-routines": { blocked: 'superAdmin' },
  "/admin/bug-reports": { blocked: 'adminRole' },
  "/admin/bug-reports/[id]": { blocked: 'adminRole' },
  "/admin/dashboard-drilldowns": { blocked: 'superAdmin' },
  "/admin/dashboard/widget-config": { blocked: 'superAdmin' },
  "/admin/id-cards/address-check": { keys: ['id_cards.jobs.view'] },
  "/admin/id-cards/batch-print": { keys: ['id_cards.jobs.manage'] },
  "/admin/id-cards/morning": { keys: ['id_cards.jobs.view'] },
  "/admin/id-cards/policy": { blocked: 'superAdmin' },
  "/admin/id-cards/print-queue": { blocked: 'adminRole' },
  "/admin/id-cards/template": { keys: ['id_cards.templates.edit'] },
  "/admin/landing-pages": { blocked: 'superAdmin' },
  "/admin/learner-notes": { blocked: 'superAdmin' },
  "/admin/nav-config": { blocked: 'superAdmin' },
  "/admin/page-metadata": { keys: ['system.view'] },
  "/admin/reset-driver-passwords": { blocked: 'superAdmin' },
  "/admin/retention-policies": { blocked: 'superAdmin' },
  "/admin/saml": { blocked: 'superAdmin' },
  "/admin/whatsapp-byow/secret-rotation": { blocked: 'superAdmin' },
  "/admin/whatsapp-limits": { blocked: 'superAdmin' },
  "/admission/analytics": { keys: ['admission.view'] },
  "/admission/applications": { keys: ['admission.view'] },
  "/admission/consultants": { keys: ['admission.consultants.view'] },
  "/admission/consultants/[id]": { keys: ['admission.consultants.view'] },
  "/admission/consultants/[id]/edit": { keys: ['admission.consultants.edit'] },
  "/admission/consultants/admin": { blocked: 'superAdmin' },
  "/admission/consultants/admin/commission-triggers": { blocked: 'superAdmin' },
  "/admission/consultants/admin/portal-access": { blocked: 'superAdmin' },
  "/admission/consultants/admin/tier-policy": { blocked: 'superAdmin' },
  "/admission/consultants/analytics": { keys: ['admission.consultants.analytics.view'] },
  "/admission/consultants/commissions": { keys: ['admission.consultants.view'] },
  "/admission/consultants/import": { keys: ['admission.consultants.commissions.view'] },
  "/admission/consultants/new": { keys: ['admission.consultants.create'] },
  "/admission/consultants/payouts": { keys: ['admission.consultants.commissions.view'] },
  "/admission/consultants/reconciliation": { keys: ['admission.consultants.commissions.view'] },
  "/admission/consultants/referral-rates": { keys: ['admission.consultants.commissions.view'] },
  "/admission/consultants/referrals": { keys: ['admission.consultants.view'] },
  "/admission/consultants/review-worklist": { keys: ['admission.leads.view'] },
  "/admission/consultants/rewards": { keys: ['admission.consultants.view'] },
  "/admission/consultants/unlinked-referrals": { keys: ['admission.consultants.commissions.view'] },
  "/admission/counselors": { keys: ['admission.counselors.view'] },
  "/admission/counselors/admin": { blocked: 'superAdmin' },
  "/admission/counselors/admin/alert-thresholds": { blocked: 'superAdmin' },
  "/admission/counselors/admin/routing-errors": { blocked: 'superAdmin' },
  "/admission/counselors/admin/rule-types": { blocked: 'superAdmin' },
  "/admission/counselors/admin/tier-policy": { blocked: 'superAdmin' },
  "/admission/counselors/alerts": { keys: ['admission.view'] },
  "/admission/counselors/briefing": { keys: ['admission.view'] },
  "/admission/counselors/calls": { keys: ['admission.view'] },
  "/admission/counselors/calls/[id]": { keys: ['admission.view'] },
  "/admission/counselors/daily-view": { keys: ['admission.view'] },
  "/admission/counselors/director-pulse": { keys: ['admission.view'] },
  "/admission/counselors/lead-mood": { keys: ['admission.view'] },
  "/admission/counselors/productivity": { keys: ['admission.counselors.view'] },
  "/admission/counselors/reminders": { keys: ['admission.view'] },
  "/admission/counselors/team": { keys: ['admission.counselors.team.view'] },
  "/admission/counselors/team/activity": { keys: ['admission.counselors.team.view'] },
  "/admission/counselors/team/allocation": { keys: ['admission.counselors.team.manage', 'admission.counselors.team.view'] },
  "/admission/counselors/team/allocation/[id]": { keys: ['admission.counselors.team.manage', 'admission.counselors.team.view'] },
  "/admission/counselors/team/roster": { keys: ['admission.counselors.team.view'] },
  "/admission/counselors/team/rules": { keys: ['admission.counselors.team.manage', 'admission.counselors.team.view'] },
  "/admission/counselors/voice-memos": { keys: ['admission.view'] },
  "/admission/dashboard": { keys: ['admission.view'] },
  "/admission/data-quality/data-profiling": { keys: ['admission.view'] },
  "/admission/data-quality/deduplication": { keys: ['admission.view'] },
  "/admission/data-quality/phone-validation": { keys: ['admission.view'] },
  "/admission/gate-entry": { keys: ['admission.gate_entry.create'] },
  "/admission/gate-entry/today": { keys: ['admission.gate_entry.view'] },
  "/admission/gd-pi": { keys: ['admission.gd_pi.view'] },
  "/admission/gd-pi/[id]": { keys: ['admission.gd_pi.view'] },
  "/admission/gd-pi/[id]/evaluate": { keys: ['admission.gd_pi.evaluate'] },
  "/admission/gd-pi/new": { keys: ['admission.gd_pi.manage'] },
  "/admission/group-dashboard": { keys: ['admission.view'] },
  "/admission/group-dashboard/actions": { blocked: 'unreadable' },
  "/admission/group-dashboard/setup": { keys: ['admission.group_dashboard.view'] },
  "/admission/insights": { keys: ['admission.view'] },
  "/admission/insights/status": { keys: ['admission.view'] },
  "/admission/leads": { keys: ['admission.leads.view'] },
  "/admission/leads/[id]": { keys: ['admission.leads.view'] },
  "/admission/leads/new": { keys: ['admission.leads.create'] },
  "/admission/leads/work": { keys: ['admission.leads.view'] },
  "/admission/marketing/automations/monitoring": { keys: ['admission.marketing.view'] },
  "/admission/marketing/automations/roi": { keys: ['admission.view'] },
  "/admission/marketing/automations/segments": { keys: ['admission.view'] },
  "/admission/marketing/campaigns": { keys: ['admission.marketing.view'] },
  "/admission/marketing/campaigns/[id]": { keys: ['admission.marketing.view'] },
  "/admission/marketing/campaigns/[id]/edit": { keys: ['admission.marketing.edit'] },
  "/admission/marketing/campaigns/[id]/leads": { keys: ['admission.marketing.view'] },
  "/admission/marketing/campaigns/[id]/links": { keys: ['admission.marketing.view'] },
  "/admission/marketing/campaigns/compare": { keys: ['admission.marketing.view'] },
  "/admission/marketing/campaigns/monitoring": { keys: ['admission.marketing.view'] },
  "/admission/marketing/campaigns/new": { keys: ['admission.marketing.create'] },
  "/admission/marketing/chat": { keys: ['admission.view'] },
  "/admission/marketing/chat/performance": { keys: ['admission.view'] },
  "/admission/marketing/chat/settings": { keys: ['admission.manage'] },
  "/admission/marketing/chatbot": { keys: ['admission.view'] },
  "/admission/marketing/chatbot/analytics": { keys: ['admission.view'] },
  "/admission/marketing/chatbot/knowledge": { keys: ['admission.view'] },
  "/admission/marketing/database": { keys: ['admission.marketing.view'] },
  "/admission/marketing/expos/[id]": { keys: ['admission.marketing.expos.view'] },
  "/admission/marketing/expos/[id]/edit": { keys: ['admission.marketing.expos.edit'] },
  "/admission/marketing/expos/analytics": { keys: ['admission.marketing.expos.view'] },
  "/admission/marketing/expos/masters": { keys: ['admission.marketing.expos.view'] },
  "/admission/marketing/expos/new": { keys: ['admission.marketing.expos.create'] },
  "/admission/marketing/publishers": { keys: ['admission.marketing.view'] },
  "/admission/marketing/re-engagement": { keys: ['admission.view'] },
  "/admission/marketing/remarketing": { keys: ['admission.view'] },
  "/admission/marketing/voice-agents": { keys: ['admission.view'] },
  "/admission/marketing/voice-broadcast": { keys: ['admission.view'] },
  "/admission/marketing/whatsapp-broadcast": { keys: ['admission.manage'] },
  "/admission/schools-network": { keys: ['schools_network.schools.view'] },
  "/admission/schools-network/[schoolId]": { keys: ['schools_network.schools.view'] },
  "/admission/schools-network/[schoolId]/contacts/new": { keys: ['schools_network.contacts.create'] },
  "/admission/schools-network/[schoolId]/contributions/new": { keys: ['schools_network.contributions.create'] },
  "/admission/schools-network/[schoolId]/edit": { keys: ['schools_network.schools.edit'] },
  "/admission/schools-network/[schoolId]/owners/assign": { keys: ['schools_network.owners.manage'] },
  "/admission/schools-network/[schoolId]/sessions/log": { keys: ['schools_network.sessions.create'] },
  "/admission/schools-network/duplicates": { keys: ['schools_network.schools.edit'] },
  "/admission/schools-network/new": { keys: ['schools_network.schools.create'] },
  "/admission/schools-network/partners": { keys: ['schools_network.partners.view'] },
  "/admission/schools-network/partners/[partnerId]": { keys: ['schools_network.partners.view'] },
  "/admission/schools-network/partners/new": { keys: ['schools_network.partners.manage'] },
  "/admission/schools-network/qualify": { keys: ['schools_network.schools.edit'] },
  "/admission/schools-network/scoreboard": { keys: ['schools_network.schools.view'] },
  "/admission/schools-network/worklist": { keys: ['schools_network.schools.view'] },
  "/admission/settings": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/assignment-rules": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/checklists": { keys: ['admission.settings.checklists.view'], routeGuarded: true },
  "/admission/settings/fees-structure": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/fees-structure/[id]": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/fees-structure/[id]/clone": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/fees-structure/new": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/forms": { keys: ['admission.settings.forms.view'], routeGuarded: true },
  "/admission/settings/forms/[id]": { keys: ['admission.settings.forms.view'], routeGuarded: true },
  "/admission/settings/forms/[id]/analytics": { keys: ['admission.settings.forms.view'], routeGuarded: true },
  "/admission/settings/general": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/lead-stages-policy": { blocked: 'superAdmin' },
  "/admission/settings/lookups": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/lookups/accommodation-types": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/lookups/castes": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/lookups/community-categories": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/lookups/data-quality": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/lookups/quotas": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/seat-config": { keys: ['admission.settings.seats.view'], routeGuarded: true },
  "/admission/settings/sources": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/statuses": { keys: ['admission.settings.statuses.view'], routeGuarded: true },
  "/admission/settings/telephony-policies": { blocked: 'superAdmin' },
  "/admission/settings/templates": { keys: ['admission.view'], routeGuarded: true },
  "/admission/settings/templates/analytics": { keys: ['admission.view'], routeGuarded: true },
  "/admission/settings/templates/documents": { keys: ['admission.view'], routeGuarded: true },
  "/admission/settings/templates/email-builder": { keys: ['admission.manage'], routeGuarded: true },
  "/admission/settings/voice-memo-monitor": { blocked: 'superAdmin' },
  "/admission/settings/whatsapp-numbers": { keys: ['admission.manage'], routeGuarded: true },
  "/admission/settings/workflow-config": { keys: ['admission.settings.view'], routeGuarded: true },
  "/admission/settings/workflows": { keys: ['admission.view'], routeGuarded: true },
  "/admission/settings/years": { keys: ['admission.settings.years.view'], routeGuarded: true },
  "/admission/social": { keys: ['social.view'] },
  "/admission/social/attribution": { keys: ['social.attribution.view'] },
  "/admission/social/departments": { keys: ['social.departments.view'] },
  "/admission/social/engagement": { keys: ['social.view'] },
  "/admission/social/facebook": { keys: ['social.facebook.view'] },
  "/admission/social/facebook/[id]": { keys: ['social.facebook.view'] },
  "/admission/social/governance": { keys: ['social.view'] },
  "/admission/social/insights": { keys: ['social.insights.view'] },
  "/admission/social/instagram": { keys: ['social.instagram.view'] },
  "/admission/social/instagram/[id]": { keys: ['social.instagram.view'] },
  "/admission/social/lead-ads": { keys: ['social.lead_ads.view'] },
  "/admission/social/loop": { keys: ['social.view'] },
  "/admission/social/meta-audiences": { keys: ['social.meta_audiences.view'] },
  "/admission/tools/re-evaluate-learner": { keys: ['admission.settings.statuses.manage'] },
  "/ai-pulse/admin/policies": { blocked: 'superAdmin' },
  "/ai-query/admin": { blocked: 'superAdmin' },
  "/applications": { keys: ['applications.view'] },
  "/audit/cycles/[id]/adapt": { keys: ['audit.parameter.view'], routeGuarded: true },
  "/audit/cycles/[id]/attestations": { keys: ['audit.attestation.view'], routeGuarded: true },
  "/audit/cycles/[id]/findings": { keys: ['audit.finding.view'], routeGuarded: true },
  "/audit/cycles/[id]/parameters": { keys: ['audit.parameter.view'], routeGuarded: true },
  "/audit/cycles/[id]/report-card": { keys: ['audit.parameter.view'], routeGuarded: true },
  "/audit/finding-types/settings": { keys: ['audit.finding_type.manage'], routeGuarded: true },
  "/audit/parameters": { keys: ['audit.parameter.view'], routeGuarded: true },
  "/audit/parameters/[code]": { keys: ['audit.parameter.view'], routeGuarded: true },
  "/audit/parameters/[code]/overrides": { keys: ['audit.parameter.manage'], routeGuarded: true },
  "/audit/parameters/settings": { keys: ['audit.parameter.manage'], routeGuarded: true },
  "/billing/activities": { keys: ['billing.activities.view'], routeGuarded: true },
  "/billing/analytics": { keys: ['billing.analytics.view'], routeGuarded: true },
  "/billing/apportionment": { keys: ['billing.apportionment.view'], routeGuarded: true },
  "/billing/apportionment/rules": { keys: ['billing.apportionment.view'], routeGuarded: true },
  "/billing/coverage": { keys: ['billing.coverage.view'], routeGuarded: true },
  "/billing/late-charges": { keys: ['billing.late_charges.view'], routeGuarded: true },
  "/billing/onboarding": { keys: ['billing.onboarding.view'], routeGuarded: true },
  "/billing/payment-accounts": { keys: ['billing.payment_accounts.view'], routeGuarded: true },
  "/billing/receipt-cancellations": { keys: ['billing.receipts.cancel.request'], routeGuarded: true },
  "/billing/refund-approvals": { keys: ['billing.refunds.configure'], routeGuarded: true },
  "/billing/schedule": { keys: ['billing.schedule.view'], routeGuarded: true },
  "/billing/schedule/bulk-create/upload": { keys: ['billing.schedule.bulk_create', 'billing.schedule.create'], routeGuarded: true },
  "/billing/schedule/bulk-edit": { keys: ['billing.schedule.update'], routeGuarded: true },
  "/billing/school-fees": { keys: ['school_fees.read'], routeGuarded: true },
  "/billing/school-fees/[id]": { keys: ['school_fees.read'], routeGuarded: true },
  "/billing/school-fees/concessions": { keys: ['school_fees.read'], routeGuarded: true },
  "/billing/school-fees/generate": { keys: ['school_fees.generate'], routeGuarded: true },
  "/billing/school-fees/new": { keys: ['school_fees.manage'], routeGuarded: true },
  "/billing/school-fees/term-calendar": { keys: ['school_fees.read'], routeGuarded: true },
  "/billing/transport": { keys: ['billing.transport.view'], routeGuarded: true },
  "/bos/academic-council": { keys: ['academic.bos-academic-council.manage'] },
  "/bos/academic-council/[meetingId]/edit": { keys: ['academic.bos-academic-council.manage'] },
  "/bos/academic-council/new": { keys: ['academic.bos-academic-council.manage'] },
  "/bos/committees": { keys: ['academic.bos-compositions.view'] },
  "/bos/courses/[id]/edit": { keys: ['academic.bos-courses.edit'] },
  "/bos/experts": { keys: ['academic.bos-experts.view'] },
  "/bos/governing-body": { keys: ['academic.bos-governing-body.manage'] },
  "/bos/governing-body/[meetingId]/edit": { keys: ['academic.bos-governing-body.manage'] },
  "/bos/governing-body/new": { keys: ['academic.bos-governing-body.manage'] },
  "/bos/meetings": { keys: ['academic.bos-meetings.view'] },
  "/bos/member-types": { keys: ['academic.bos-compositions.view'] },
  "/bos/sop": { keys: ['academic.bos-sop.view'] },
  "/bos/taxonomy": { keys: ['academic.bos-taxonomy.view'] },
  "/bos/taxonomy/new": { keys: ['academic.bos-taxonomy.create'] },
  "/campus-living/allocations/audit": { keys: ['campus_living.allocations.audit'] },
  "/campus-living/mess/caterer-management": { blocked: 'superAdmin' },
  "/campus-living/mess/insights": { blocked: 'superAdmin' },
  "/campus-living/mess/library": { blocked: 'superAdmin' },
  "/campus-living/mess/menu-editor/[tier]": { blocked: 'superAdmin' },
  "/campus-living/mess/menu-loop": { keys: ['campus_living.settings.view'] },
  "/campus-living/mess/policies": { blocked: 'superAdmin' },
  "/campus-living/premium/allocation-rules": { blocked: 'superAdmin' },
  "/campus-living/premium/audit-log": { blocked: 'adminRole' },
  "/campus-living/premium/dashboard": { blocked: 'superAdmin' },
  "/campus-living/premium/override": { blocked: 'adminRole' },
  "/campus-living/premium/tier-policy": { blocked: 'superAdmin' },
  "/campus-living/settings/allocations": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/amenities": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/billable-amenities": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/categories": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/curfew": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/fees-economics": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/hostel-years": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/leave-types": { keys: ['campus_living.leave_types.view'] },
  "/campus-living/settings/mess-services": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/packages": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/policies-workflows": { keys: ['campus_living.settings.view'] },
  "/campus-living/settings/program-eligibility": { keys: ['campus_living.settings.view'] },
  "/campus-living/settle-preview": { keys: ['campus_living.fees.config'] },
  "/cdc": { keys: ['cdc.view'] },
  "/cdc/bulletin": { keys: ['cdc.bulletin.view'] },
  "/cdc/bulletin/[id]": { keys: ['cdc.bulletin.view'] },
  "/cdc/bulletin/new": { keys: ['cdc.bulletin.create'] },
  "/cdc/career-guidance": { keys: ['cdc.view'] },
  "/cdc/clubs": { keys: ['cdc.clubs.view'] },
  "/cdc/clubs/[id]": { keys: ['cdc.clubs.view'] },
  "/cdc/clubs/new": { keys: ['cdc.clubs.create'] },
  "/cdc/drives": { keys: ['cdc.drives.view'] },
  "/cdc/drives/[id]": { keys: ['cdc.drives.view'] },
  "/cdc/drives/new": { keys: ['cdc.drives.create'] },
  "/cdc/exports": { keys: ['cdc.exports.view'] },
  "/cdc/govt-readiness": { keys: ['cdc.govt_readiness.view'] },
  "/cdc/idp": { keys: ['cdc.idp.view'] },
  "/cdc/idp/[id]": { keys: ['cdc.idp.view'] },
  "/cdc/idp/new": { keys: ['cdc.idp.create'] },
  "/cdc/industry-mentors": { keys: ['cdc.industry_mentors.view'] },
  "/cdc/industry-mentors/[id]": { keys: ['cdc.industry_mentors.view'] },
  "/cdc/industry-mentors/new": { keys: ['cdc.industry_mentors.create'] },
  "/cdc/internships": { keys: ['cdc.internships.view'] },
  "/cdc/internships/[id]": { keys: ['cdc.internships.view'] },
  "/cdc/internships/new": { keys: ['cdc.internships.create'] },
  "/cdc/mentors": { keys: ['cdc.mentors.view'] },
  "/cdc/mentors/[id]": { keys: ['cdc.mentors.view'] },
  "/cdc/mentors/new": { keys: ['cdc.mentors.create'] },
  "/cdc/mentors/rollups": { keys: ['cdc.mentors.view'] },
  "/cdc/placements": { keys: ['cdc.placements.view'] },
  "/cdc/placements/[id]": { keys: ['cdc.placements.view'] },
  "/cdc/placements/new": { keys: ['cdc.placements.create'] },
  "/cdc/requirements": { keys: ['cdc.requirements.view'] },
  "/cdc/requirements/[id]": { keys: ['cdc.requirements.view'] },
  "/cdc/requirements/new": { keys: ['cdc.requirements.create'] },
  "/cdc/training": { keys: ['cdc.training.view'] },
  "/cdc/training/[id]": { keys: ['cdc.training.view'] },
  "/cdc/training/[id]/edit": { keys: ['cdc.training.edit'] },
  "/cdc/training/new": { keys: ['cdc.training.create'] },
  "/cdc/udyog": { keys: ['cdc.udyog.view'] },
  "/courses": { keys: ['courses.view'] },
  "/courses/[id]": { keys: ['courses.edit'] },
  "/courses/new": { keys: ['courses.create'] },
  "/faculty/innovation": { keys: ['faculty_innovation.initiative.submit'] },
  "/faculty/innovation/approval-queue": { keys: ['faculty_innovation.initiative.approve'] },
  "/faculty/innovation/collab-request": { keys: ['faculty_innovation.collab_request.create'] },
  "/faculty/innovation/portfolio": { keys: ['faculty_innovation.initiative.view_own'] },
  "/faculty/innovation/submit": { keys: ['faculty_innovation.initiative.submit'] },
  "/feedback": { keys: ['feedback.view'] },
  "/health/admin/programs": { keys: ['health.programs.manage'] },
  "/health/admin/programs/[id]": { keys: ['health.programs.manage'] },
  "/health/admin/programs/[id]/impact": { keys: ['health.programs.manage'] },
  "/health/admin/programs/[id]/responses": { keys: ['health.programs.manage'] },
  "/hr/admin": { keys: ['hr.dashboard.view'], routeGuarded: true },
  "/hr/admin/academic-years": { keys: ['hr.academic_years.manage'], routeGuarded: true },
  "/hr/admin/automation-rules": { blocked: 'superAdmin' },
  "/hr/admin/disciplinary": { blocked: 'superAdmin' },
  "/hr/admin/disciplinary/[id]": { blocked: 'superAdmin' },
  "/hr/admin/disciplinary/new": { blocked: 'superAdmin' },
  "/hr/admin/fdp": { blocked: 'superAdmin' },
  "/hr/admin/fdp/[id]": { blocked: 'superAdmin' },
  "/hr/admin/forms": { blocked: 'superAdmin' },
  "/hr/admin/forms/[id]/builder": { blocked: 'superAdmin' },
  "/hr/admin/forms/[id]/workflow": { blocked: 'superAdmin' },
  "/hr/admin/forms/submissions": { blocked: 'superAdmin' },
  "/hr/admin/forms/submissions/[id]": { blocked: 'superAdmin' },
  "/hr/admin/leave-balances": { keys: ['hr.leave.balance.manage'], routeGuarded: true },
  "/hr/admin/leave-types": { keys: ['hr.leave.types.manage'], routeGuarded: true },
  "/hr/admin/memos": { blocked: 'superAdmin' },
  "/hr/admin/memos/[id]": { blocked: 'superAdmin' },
  "/hr/admin/offboarding": { blocked: 'superAdmin' },
  "/hr/admin/offboarding/[id]/fnf": { blocked: 'superAdmin' },
  "/hr/admin/offboarding/retirements": { blocked: 'superAdmin' },
  "/hr/admin/onboarding-checklists": { blocked: 'adminRole' },
  "/hr/admin/payroll": { blocked: 'superAdmin' },
  "/hr/admin/payroll/periods": { blocked: 'superAdmin' },
  "/hr/admin/payroll/periods/[id]": { blocked: 'superAdmin' },
  "/hr/admin/payroll/periods/new": { blocked: 'superAdmin' },
  "/hr/admin/payroll/preview": { blocked: 'superAdmin' },
  "/hr/admin/performance-reviews": { blocked: 'superAdmin' },
  "/hr/admin/performance-reviews/cycles": { blocked: 'superAdmin' },
  "/hr/admin/performance-reviews/cycles/[id]": { blocked: 'superAdmin' },
  "/hr/admin/policies": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/academic-scope": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/allowances-and-increments": { blocked: 'superAdmin' },
  "/hr/admin/policies/audit": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/audit-log": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/cadres": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/code-of-conduct": { blocked: 'superAdmin' },
  "/hr/admin/policies/disciplinary-action": { blocked: 'superAdmin' },
  "/hr/admin/policies/excursion-general": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/facilities": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/feedback-evaluation": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/grievance-cell": { blocked: 'superAdmin' },
  "/hr/admin/policies/institution-meta": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/joining-and-appointment": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/leave": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/leave/casual": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/leave/compensatory": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/leave/half-pay": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/leave/holidays-and-lop": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/leave/marriage": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/leave/on-duty": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/leave/vacation": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/memo-termination": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/motivation-fund": { blocked: 'superAdmin' },
  "/hr/admin/policies/new": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/new/data-privacy-it-acceptable-use": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/new/genai-usage": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/new/remote-hybrid-work": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/new/social-media-conduct": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/pay-scales": { blocked: 'superAdmin' },
  "/hr/admin/policies/performance-review": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/promotion-policy": { blocked: 'superAdmin' },
  "/hr/admin/policies/promotion-suggestions": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/rd": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/rd/excursion": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/rd/incentive-authority": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/rd/publication-incentives": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/rd/research-leave": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/rd/wfh-rules": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/reimbursement-workflow": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/resignation-workflow": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/roles-responsibilities": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/staff-development": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/teaching-artifacts": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/welfare": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/policies/working-schedule": { keys: ['hr.policies.view'], routeGuarded: true },
  "/hr/admin/promotions": { blocked: 'superAdmin' },
  "/hr/admin/promotions/[id]": { blocked: 'superAdmin' },
  "/hr/admin/recruitment-approval-flows": { keys: ['hr.recruitment.edit'], routeGuarded: true },
  "/hr/admin/recruitment-approval-flows/[id]": { keys: ['hr.recruitment.edit'], routeGuarded: true },
  "/hr/admin/recruitment-approval-flows/new": { keys: ['hr.recruitment.edit'], routeGuarded: true },
  "/hr/admin/recruitment-maintenance": { blocked: 'superAdmin' },
  "/hr/admin/recruitment-need": { blocked: 'adminRole' },
  "/hr/admin/recruitment-need/allocations": { blocked: 'adminRole' },
  "/hr/admin/recruitment-need/approvals": { blocked: 'adminRole' },
  "/hr/admin/recruitment-need/bodies": { blocked: 'adminRole' },
  "/hr/admin/recruitment-need/norms": { blocked: 'adminRole' },
  "/hr/admin/recruitment-need/peer-benchmarks": { blocked: 'adminRole' },
  "/hr/admin/recruitment-need/snapshots": { blocked: 'superAdmin' },
  "/hr/admin/recruitment-need/specializations": { blocked: 'adminRole' },
  "/hr/admin/recruitment-need/thresholds": { blocked: 'adminRole' },
  "/hr/admin/recruitment-need/weights": { blocked: 'adminRole' },
  "/hr/admin/required-documents": { blocked: 'adminRole' },
  "/hr/admin/sanctioned-posts": { keys: ['hr.sanctioned_posts.view'], routeGuarded: true },
  "/hr/admin/shift-timings": { keys: ['hr.shift_timings.manage'], routeGuarded: true },
  "/hr/admin/terminations": { blocked: 'superAdmin' },
  "/hr/admin/terminations/[id]/initiate": { blocked: 'superAdmin' },
  "/hr/admin/terminations/[id]/review": { blocked: 'superAdmin' },
  "/hr/admin/training": { blocked: 'superAdmin' },
  "/hr/admin/training/[id]": { blocked: 'superAdmin' },
  "/hr/admin/training/new": { blocked: 'superAdmin' },
  "/hr/recruitment/jobs": { keys: ['hr.recruitment.view'], routeGuarded: true },
  "/industry-partners": { keys: ['cdc.industry_partners.view'] },
  "/industry-partners/[id]": { keys: ['cdc.industry_partners.view'] },
  "/internships/cycles": { keys: ['internship.cycles.view'] },
  "/internships/cycles/[id]": { keys: ['internship.cycles.view'] },
  "/internships/cycles/new": { keys: ['internship.cycles.create'] },
  "/internships/preceptors": { keys: ['internship.preceptors.view'] },
  "/internships/preceptors/[id]": { keys: ['internship.preceptors.view'] },
  "/internships/preceptors/new": { keys: ['internship.preceptors.create'] },
  "/internships/sites": { keys: ['internship.sites.view'] },
  "/internships/sites/[id]": { keys: ['internship.sites.view'] },
  "/internships/sites/new": { keys: ['internship.sites.create'] },
  "/internships/vehicles": { keys: ['internship.vehicles.view'] },
  "/internships/vehicles/[id]": { keys: ['internship.vehicles.view'] },
  "/internships/vehicles/new": { keys: ['internship.vehicles.create'] },
  "/learners/postal-codes": { keys: ['learners.postal_codes.view'] },
  "/learners/school-master": { keys: ['learners.school_master.view'] },
  "/meetings/analytics": { keys: ['meetings.analytics.view'] },
  "/meetings/contacts": { keys: ['meetings.contacts.view'] },
  "/meetings/contacts/scan": { keys: ['meetings.contacts.scan'] },
  "/meetings/contacts/scan/saved": { keys: ['meetings.contacts.scan'] },
  "/meetings/embed": { keys: ['meetings.embed.manage'] },
  "/meetings/polls": { keys: ['meetings.polls.view'] },
  "/meetings/polls/[id]": { keys: ['meetings.polls.view'] },
  "/meetings/routing-forms": { keys: ['meetings.routing.view'] },
  "/meetings/routing-forms/[id]": { keys: ['meetings.routing.view'] },
  "/meetings/webhooks": { keys: ['meetings.webhooks.view'] },
  "/meetings/workflows": { keys: ['meetings.workflows.view'] },
  "/meetings/workflows/[id]": { keys: ['meetings.workflows.view'] },
  "/moments/campaigns": { keys: ['moments.campaigns.view'] },
  "/moments/submit": { keys: ['moments.submissions.create'] },
  "/notifications/admin": { keys: ['notifications.view'] },
  "/notifications/admin/[id]": { keys: ['notifications.view'] },
  "/notifications/admin/audiences": { keys: ['notifications.view'] },
  "/notifications/admin/audiences/new": { keys: ['notifications.create'] },
  "/notifications/admin/compliance": { keys: ['notifications.view'] },
  "/notifications/admin/new": { keys: ['notifications.create'] },
  "/notifications/admin/recipients": { keys: ['notifications.view'] },
  "/organizations/departments/hod-assignment": { blocked: 'adminRole' },
  "/organizations/institutions/[id]/edit": { blocked: 'superAdmin' },
  "/organizations/institutions/new": { blocked: 'superAdmin' },
  "/organizations/leadership": { keys: ['organizations.leadership.manage'] },
  "/pde/admin/assessments": { keys: ['pde.admin.assessments.view'] },
  "/pde/admin/assessments/create": { keys: ['pde.admin.assessments.view'] },
  "/pde/admin/at-risk": { keys: ['pde.admin.at_risk.view'] },
  "/pde/admin/bos-evidence": { blocked: 'superAdmin' },
  "/pde/admin/bos-evidence/[reviewId]": { blocked: 'superAdmin' },
  "/pde/admin/bridge": { blocked: 'superAdmin' },
  "/pde/admin/capabilities": { keys: ['pde.admin.capabilities.view'] },
  "/pde/admin/cohort": { blocked: 'superAdmin' },
  "/pde/admin/compliance/per-college": { blocked: 'superAdmin' },
  "/pde/admin/engagement": { keys: ['pde.admin.engagement.view'] },
  "/pde/admin/feedback-moderation": { blocked: 'superAdmin' },
  "/pde/admin/kpi": { blocked: 'superAdmin' },
  "/pde/admin/lti": { keys: ['pde.admin.lti.view'] },
  "/pde/admin/placement-signals": { blocked: 'superAdmin' },
  "/pde/admin/policies": { blocked: 'superAdmin' },
  "/pde/admin/policies/clinical-reasoning": { keys: ['pde.admin.view'] },
  "/pde/admin/policies/governance": { blocked: 'superAdmin' },
  "/pde/admin/policies/quests": { blocked: 'superAdmin' },
  "/pde/admin/policies/rollout": { blocked: 'superAdmin' },
  "/pde/admin/policies/scoring": { blocked: 'superAdmin' },
  "/pde/admin/policies/visibility": { blocked: 'superAdmin' },
  "/pde/admin/quest-supply": { blocked: 'superAdmin' },
  "/pde/admin/quests": { keys: ['pde.admin.quests.view'] },
  "/pde/admin/quests/create": { keys: ['pde.admin.quests.view'] },
  "/pde/admin/rubrics": { blocked: 'superAdmin' },
  "/pde/admin/rubrics/cultural-civic": { blocked: 'superAdmin' },
  "/pde/admin/rubrics/embodied": { blocked: 'superAdmin' },
  "/pde/admin/rubrics/social-leadership": { blocked: 'superAdmin' },
  "/pde/admin/transcript": { blocked: 'superAdmin' },
  "/rcltp/admin/policies": { blocked: 'superAdmin' },
  "/reference": { keys: ['reference.catalogs.view'] },
  "/startup-studio/events/[id]/dashboard": { blocked: 'superAdmin' },
  "/startup-studio/school-of-influence/admin/settings": { keys: ['startup_studio.school_of_influence.configure'], routeGuarded: true },
  "/users/jkkn-id": { keys: ['users.jkkn_id.view'], routeGuarded: true },
};
