// ============================================================================
// Route -> permission key(s), for the Director's hand-over control.
//
// THE WHOLE FEATURE TURNS ON THIS FILE.
// A handover row IS a permission grant (specs/director-desk/SPEC.md). So the
// key written onto the row has to be the SAME key the page's own gate demands,
// or the receiver gets a link that opens onto an access-denied panel and the
// Director believes he delegated something he did not.
//
// ROUND 1 READ ONLY MENU_PERMISSIONS, AND THAT WAS THE BUG
// --------------------------------------------------------
// This file used to resolve every route through `routeMatcher`, a trie built
// from MENU_PERMISSIONS, and claim the result was "exactly the key the page
// demands". Measured on this tree, that is true for a minority of pages:
//
//     1,446  page.tsx files under app/(routes)
//        37  mount RoutePermissionGuard  <- the ONLY gate that reads the trie
//       112  mount SuperAdminOnly        <- reads profiles.is_super_admin
//       359  mount PermissionGuard       <- its OWN module/action pair
//
// A handover row can never set `is_super_admin`, so a SuperAdminOnly page is
// not handable at all — and 19 such pages carry a non-'super_admin'
// MENU_PERMISSIONS key. /hr/admin/payroll resolved to ['hr.dashboard.view'],
// which is unwalled and legal even at Watch: both server refusals passed, the
// dialog showed the green "Handed over" screen with a copy-link button, and the
// receiver got access-denied. Same for /hr/admin/memos, /disciplinary,
// /terminations, /performance-reviews, /promotions, /offboarding, /admin/saml,
// /rcltp/admin/policies and more.
//
// SO THE RESOLVER NOW READS THE PAGE'S ACTUAL GATE
// ------------------------------------------------
// `ROUTE_GATE_MAP` is generated by scripts/director-desk/scan-route-gates.mjs,
// which walks every page.tsx and its ancestor layouts and records what actually
// wraps them. Three outcomes:
//
//   blocked          -> no handover can ever open this page. Refuse, in plain
//                       English, BEFORE the Director picks anyone. Never show a
//                       success screen for a grant that cannot work.
//   own gate keys    -> resolve THOSE, not the menu key. Plus the menu key when
//                       the route ALSO sits under a RoutePermissionGuard, since
//                       both gates then have to pass.
//   nothing recorded -> the page is plain, and routeMatcher is correct for it.
//                       This is the old behaviour, kept for the ~970 pages it
//                       actually fits.
//
// WHY routeMatcher AND NOT A FRESH LOOKUP IN MENU_PERMISSIONS
// -----------------------------------------------------------
// Where MENU_PERMISSIONS is the authority, RoutePermissionGuard resolves it
// through `routeMatcher.match(pathname)?.permission` — a trie with two
// behaviours a plain `MENU_PERMISSIONS[path]` lookup does not have: `[id]`
// segments match any concrete value, and the most-specific ANCESTOR wins when
// there is no exact entry. Reading the gate's own resolver is the only way the
// two cannot drift (feedback_widening_a_permission_is_four_layers).
//
// The trade this still makes, stated plainly: a page whose BUTTONS need a key
// beyond its gate key (a page gated on `x.view` whose save button calls an RPC
// wanting `x.manage`) hands over the gate keys only. The receiver opens the page
// and that button 403s. We do NOT guess — inventing a key is how a handover
// silently grants more than the Director chose.
// ============================================================================

import { routeMatcher } from '@/lib/auth/route-matcher';

import { ROUTE_GATE_MAP, type RouteGateBlock, type RouteGateEntry } from './route-gate-map.generated';

/** The three things a receiver can be given. Mirrors the DB CHECK constraint. */
export type HandoverAccessLevel = 'watch' | 'update' | 'full';

export type { RouteGateBlock };

/**
 * The permission key that gates the hand-over control itself. Defined on the
 * spine branch in lib/constants/permissions.ts and deliberately NOT re-declared
 * here. Server-side, `fn_can_hand_over()` is the authority — it consults this
 * key, the `director` role, and the super-admin flag.
 */
export const HANDOVER_PERMISSION_KEY = 'director.handover.create';

export interface RouteResolution {
  /**
   * Keys to write onto the handover. Empty means the page declares no
   * permission of its own — submit must be blocked, NOT filled with a guess.
   */
  keys: string[];
  /**
   * The concrete path prefix the matcher stopped on, e.g. '/hr/employees' for
   * '/hr/employees/123/documents'. Shown to the Director so it is visible when
   * a key was inherited from a section rather than declared on the page.
   */
  matchedAt: string | null;
  /** True when the key came from an ancestor rather than the route itself. */
  inherited: boolean;
  /**
   * Non-null when this page's real gate is one a handover can never satisfy.
   * The dialog must refuse — no person picker, no submit, no success screen.
   */
  blocked: RouteGateBlock | null;
  /** Plain English for the Director. Shown verbatim. Null when not blocked. */
  blockedReason: string | null;
  /** Where `keys` came from. Drives the "unlocked by" line in the dialog. */
  source: 'page-gate' | 'page-gate+menu' | 'menu' | 'none';
}

/**
 * Why a page refuses a handover, in the Director's words rather than the
 * codebase's. He is standing on the page and has just been told no; the message
 * has to say what would actually fix it.
 */
const BLOCK_REASONS: Record<RouteGateBlock, string> = {
  superAdmin:
    'This page is restricted to super administrators, and a handover cannot make anyone one. Nothing you choose here would open it for them — they would get an access-denied panel. If someone needs this page, it has to go through Role Management.',
  adminRole:
    'This page is restricted to administrators by role, and a handover grants permissions, not roles. Nothing you choose here would open it for them. If someone needs this page, it has to go through Role Management.',
  unreadable:
    'This page checks access in a way this control cannot read, so there is no way to be sure a handover would actually open it. Rather than hand over something that might not work, it is refused. Send them the link and give them the access they need in Role Management.',
};

/**
 * Look a live pathname up in the generated gate map.
 *
 * The map is keyed by Next route patterns, so `[id]` and `[...slug]` segments
 * have to match concrete values — `/hr/admin/payroll/periods/9f3a` resolves
 * through `/hr/admin/payroll/periods/[id]`. Most specific wins: a literal
 * segment beats a wildcard, so an exact entry is never shadowed.
 */
function lookupGateEntry(path: string): RouteGateEntry | null {
  const direct = ROUTE_GATE_MAP[path];
  if (direct) return direct;

  const segs = path.split('/').filter(Boolean);
  let best: { entry: RouteGateEntry; wildcards: number } | null = null;

  for (const pattern of Object.keys(ROUTE_GATE_MAP)) {
    if (!pattern.includes('[')) continue;
    const pSegs = pattern.split('/').filter(Boolean);
    const catchAllAt = pSegs.findIndex((s) => s.startsWith('[...'));
    if (catchAllAt === -1 ? pSegs.length !== segs.length : segs.length < catchAllAt) continue;

    let wildcards = 0;
    let ok = true;
    for (let i = 0; i < pSegs.length; i++) {
      const p = pSegs[i];
      if (p.startsWith('[...')) {
        wildcards += 10; // a catch-all is the least specific thing there is
        break;
      }
      if (p.startsWith('[')) {
        wildcards += 1;
        continue;
      }
      if (p !== segs[i]) {
        ok = false;
        break;
      }
    }
    if (!ok) continue;
    if (!best || wildcards < best.wildcards) best = { entry: ROUTE_GATE_MAP[pattern], wildcards };
  }
  if (best) return best.entry;

  // No page of our own at this path. Inherit a REFUSAL from the nearest ancestor
  // that has one, and nothing else. Fail closed on the un-handable gates; never
  // inherit another page's keys, which would grant something this route's own
  // gate never asked for.
  const parts = path.split('/').filter(Boolean);
  for (let i = parts.length - 1; i >= 1; i--) {
    const ancestor = `/${parts.slice(0, i).join('/')}`;
    const entry = ROUTE_GATE_MAP[ancestor];
    if (entry?.blocked) return { blocked: entry.blocked };
  }
  return null;
}

/**
 * Strip query string, hash and any trailing slash. Next's usePathname() does
 * not include search params, but this control is mounted globally and can be
 * handed any string, so normalise defensively.
 */
export function normalizePathname(raw: string | null | undefined): string {
  if (!raw) return '/';
  let path = raw.split('#')[0].split('?')[0].trim();
  if (!path.startsWith('/')) path = `/${path}`;
  if (path.length > 1 && path.endsWith('/')) path = path.replace(/\/+$/, '');
  return path === '' ? '/' : path;
}

/**
 * Resolve a live pathname to the permission key(s) that unlock it.
 *
 * Outcomes, all of them explicit:
 *   blocked gate      -> keys: [], blocked set — the dialog must refuse outright
 *   page's own gate   -> that gate's keys (+ the menu key when the route also
 *                        sits under a RoutePermissionGuard, since both apply)
 *   plain page        -> the routeMatcher key, exactly as before
 *   nothing anywhere  -> keys: [] — the caller must refuse to submit
 */
export function resolveRoutePermissionKeys(pathname: string): RouteResolution {
  const path = normalizePathname(pathname);

  const gate = lookupGateEntry(path);

  // A gate a grant cannot satisfy. Answer before anything else: there is no
  // key, no level and no person that makes this handover work, and saying so
  // now is the difference between a refusal and a green screen that lies.
  if (gate?.blocked) {
    return {
      keys: [],
      matchedAt: null,
      inherited: false,
      blocked: gate.blocked,
      blockedReason: BLOCK_REASONS[gate.blocked],
      source: 'none',
    };
  }

  let match: { permission?: string; matchedPath: string } | null = null;
  try {
    match = routeMatcher.match(path);
  } catch {
    // The matcher builds a trie at import time over ~1,000 entries. If that ever
    // throws we refuse rather than guess: an empty resolution disables submit.
    match = null;
  }

  const menuKey = match?.permission ?? null;
  const matchedAt = menuKey ? normalizePathname(match?.matchedPath ?? null) : null;
  const pageKeys = gate?.keys ?? [];

  if (pageKeys.length > 0) {
    // The page's own gate is the authority. The menu key joins it only where a
    // RoutePermissionGuard actually enforces it — granting it everywhere "just
    // in case" would widen every handover by a whole section's key for nothing.
    const alsoMenu = Boolean(gate?.routeGuarded && menuKey);
    const keys = alsoMenu && menuKey ? [...new Set([...pageKeys, menuKey])] : [...pageKeys];
    return {
      keys,
      matchedAt: alsoMenu ? matchedAt : null,
      inherited: alsoMenu ? matchedAt !== path : false,
      blocked: null,
      blockedReason: null,
      source: alsoMenu ? 'page-gate+menu' : 'page-gate',
    };
  }

  if (!menuKey) {
    return {
      keys: [],
      matchedAt: null,
      inherited: false,
      blocked: null,
      blockedReason: null,
      source: 'none',
    };
  }

  return {
    keys: [menuKey],
    matchedAt,
    inherited: matchedAt !== path,
    blocked: null,
    blockedReason: null,
    source: 'menu',
  };
}

// ============================================================================
// ACCESS LEVELS
//
// The strings below are what the Director actually reads. Plain English at a
// 10th-grade reading level, because the person receiving this is a colleague
// deciding whether to accept a job, not an engineer reading a permission key.
// ============================================================================

export interface AccessLevelOption {
  value: HandoverAccessLevel;
  label: string;
  /** One line. What the receiver will be able to do, in words. */
  description: string;
}

export const ACCESS_LEVELS: AccessLevelOption[] = [
  {
    value: 'watch',
    label: 'Watch',
    description: 'They can open the page and read it. They cannot change anything.',
  },
  {
    value: 'update',
    label: 'Update',
    description: 'They can read it and move the work along — but not create or delete.',
  },
  {
    value: 'full',
    label: 'Full',
    description: 'They can do everything on this page, as if it were theirs.',
  },
];

// ---------------------------------------------------------------------------
// A CLIENT-SIDE MIRROR OF fn_handover_key_allowed_at_level(key, level).
//
// READ THIS BEFORE TOUCHING IT. The database is the authority: the create RPC
// rejects a key the level cannot carry, and fn_handover_grants_key re-checks it
// on every permission read. This mirror exists ONLY to warn the Director BEFORE
// he submits, so he does not send a handover that would grant nothing.
//
// It therefore NEVER blocks submit. If this mirror and the database ever
// disagree, the database wins and its message is shown verbatim — a mirror that
// blocked would turn its own drift into an unfixable dead end.
//
// SQL LIKE subtlety, faithfully reproduced: the spine writes `'%.mark_%'`, and
// `_` is a single-character wildcard in LIKE — so that clause matches ".mark"
// followed by at least one more character (".marks", ".mark_bulk"), not a
// literal underscore. Getting this wrong in either direction produces warnings
// the server does not agree with.
// ---------------------------------------------------------------------------

const WATCH_SUFFIXES = ['.view', '.read', '.export'];
const UPDATE_EXTRA_SUFFIXES = [
  '.edit',
  '.update',
  '.submit',
  '.mark',
  '.respond',
  '.acknowledge',
];
/** `'%.mark_%'` — ".mark" plus at least one further character. */
const MARK_WILDCARD = /\.mark[\s\S]/;

export function keyAllowedAtLevel(key: string, level: HandoverAccessLevel): boolean {
  if (level === 'full') return true;

  const endsWithAny = (suffixes: string[]) => suffixes.some((s) => key.endsWith(s));

  if (level === 'watch') return endsWithAny(WATCH_SUFFIXES);

  // 'update'
  return (
    endsWithAny(WATCH_SUFFIXES) ||
    endsWithAny(UPDATE_EXTRA_SUFFIXES) ||
    MARK_WILDCARD.test(key)
  );
}

/** Keys the chosen level cannot carry. Empty means the level is a fit. */
export function keysNotAllowedAtLevel(
  keys: string[],
  level: HandoverAccessLevel
): string[] {
  return keys.filter((k) => !keyAllowedAtLevel(k, level));
}

/**
 * The lowest level that carries every key. Null when only Full will do.
 * Used to suggest a fix rather than just reporting a problem.
 */
export function lowestLevelThatCarries(keys: string[]): HandoverAccessLevel {
  if (keysNotAllowedAtLevel(keys, 'watch').length === 0) return 'watch';
  if (keysNotAllowedAtLevel(keys, 'update').length === 0) return 'update';
  return 'full';
}

// ============================================================================
// TITLE
// ============================================================================

const TITLE_TAIL = /\s*[|–—-]\s*MyJKKN\s*$/i;
/**
 * Observed live on /learners/profiles, 2026-08-05: document.title is the bare
 * app name on plenty of pages, not a page name. Prefilling "MyJKKN" as the job
 * is worse than prefilling nothing, so the app name is treated as absent.
 */
const APP_NAME_ONLY = /^\s*my\s*jkkn\s*$/i;

/**
 * Pre-fill the title so the Director types nothing he does not have to.
 * Prefers the real document title (pages set descriptive ones), and falls back
 * to the last meaningful path segment turned into words.
 */
export function deriveHandoverTitle(
  pathname: string,
  documentTitle?: string | null
): string {
  const fromDoc = (documentTitle ?? '').replace(TITLE_TAIL, '').trim();
  if (fromDoc.length > 2 && !APP_NAME_ONLY.test(fromDoc)) return fromDoc;

  const segments = normalizePathname(pathname).split('/').filter(Boolean);
  // Walk back past concrete ids (uuids, numbers) to the last word-ish segment.
  for (let i = segments.length - 1; i >= 0; i--) {
    const seg = segments[i];
    if (/^[0-9a-f-]{8,}$/i.test(seg) || /^\d+$/.test(seg)) continue;
    return seg
      .split('-')
      .filter(Boolean)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  }
  return 'Dashboard';
}
