// app/(routes)/whats-new/page.tsx
//
// What's New — MyJKKN's product changelog, in the SaaS sense: every change
// shipped to production, newest first, credited to the person who shipped it.
//
// Two decisions shape this page (Director, 2026-09-05):
//   1. Everyone signed in can open it.
//   2. Entries are generated automatically from git history — nobody writes
//      them, nobody approves them, so the page cannot go stale or be abandoned.
//
// Role scoping: a reader sees changes to the parts of MyJKKN they work in,
// matching the on-screen guide's permission-scoped lanes. The rules come from
// the app's existing permission namespaces (lib/changelog/use-changelog.ts) —
// this page defines no access rules of its own.
//
// The data lives in lib/changelog/data/*.json (regenerated by `npm run changelog`)
// and is served only through the authenticated route /api/whats-new — it is
// deliberately NOT under public/, where any .json bypasses auth.

import type { Metadata } from 'next';
import { ContentLayout } from '@/components/layout/content-layout';
import { PageHeader } from '@/components/page-header';
import { WhatsNewView } from '@/components/changelog/whats-new-view';

export const metadata: Metadata = {
  title: "What's New | MyJKKN",
  description: 'Every change shipped to MyJKKN, newest first.',
};

export default function WhatsNewPage() {
  return (
    <ContentLayout title="What's New">
      <PageHeader
        title="What's New"
        description="Everything we have shipped to MyJKKN, newest first — and who shipped it."
      />
      <WhatsNewView />
    </ContentLayout>
  );
}
