/**
 * AUTO-GENERATED by scripts/generate-route-manifest.ts
 * Run: npm run gen:routes
 *
 * Do NOT edit by hand. Adding/removing/renaming a page.tsx anywhere under
 * app/(routes) will change this file; commit the change with your PR.
 *
 * Consumed by components/navigation/auto-tab-nav.tsx — every entry here
 * becomes a candidate tab in the in-page nav, automatically.
 */

export interface RouteNode {
  path: string;
  label: string;
  iconName: string;
  children: RouteNode[];
}

export const ROUTE_MANIFEST: RouteNode[] = [
  {
    "path": "/academic",
    "label": "Academic",
    "iconName": "FileText",
    "children": [
      {
        "path": "/academic/attendance",
        "label": "Attendance",
        "iconName": "CheckSquare",
        "children": [
          {
            "path": "/academic/attendance/consolidation",
            "label": "Consolidation",
            "iconName": "CheckSquare",
            "children": [
              {
                "path": "/academic/attendance/consolidation/facilitators",
                "label": "Facilitators",
                "iconName": "CheckSquare",
                "children": []
              }
            ]
          },
          {
            "path": "/academic/attendance/dashboard",
            "label": "Dashboard",
            "iconName": "LayoutGrid",
            "children": []
          },
          {
            "path": "/academic/attendance/mark",
            "label": "Mark",
            "iconName": "CheckSquare",
            "children": []
          },
          {
            "path": "/academic/attendance/pending",
            "label": "Pending",
            "iconName": "CheckSquare",
            "children": []
          },
          {
            "path": "/academic/attendance/reports",
            "label": "Reports",
            "iconName": "FileBarChart",
            "children": []
          }
        ]
      },
      {
        "path": "/academic/batches",
        "label": "Batches",
        "iconName": "Boxes",
        "children": [
          {
            "path": "/academic/batches/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/academic/course-grades",
        "label": "Course Grades",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/academic/internal-marks",
        "label": "Internal Marks",
        "iconName": "Star",
        "children": [
          {
            "path": "/academic/internal-marks/report",
            "label": "Report",
            "iconName": "Star",
            "children": []
          }
        ]
      },
      {
        "path": "/academic/leave-calendar",
        "label": "Leave Calendar",
        "iconName": "CalendarOff",
        "children": []
      },
      {
        "path": "/academic/leave-onduty",
        "label": "Leave Onduty",
        "iconName": "CalendarOff",
        "children": [
          {
            "path": "/academic/leave-onduty/approvals",
            "label": "Approvals",
            "iconName": "CalendarOff",
            "children": []
          },
          {
            "path": "/academic/leave-onduty/reports",
            "label": "Reports",
            "iconName": "FileBarChart",
            "children": []
          },
          {
            "path": "/academic/leave-onduty/settings",
            "label": "Settings",
            "iconName": "Settings",
            "children": []
          }
        ]
      },
      {
        "path": "/academic/leaves",
        "label": "Leaves",
        "iconName": "CalendarOff",
        "children": [
          {
            "path": "/academic/leaves/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/academic/leaves/settings",
            "label": "Settings",
            "iconName": "Settings",
            "children": [
              {
                "path": "/academic/leaves/settings/types",
                "label": "Types",
                "iconName": "CalendarOff",
                "children": []
              },
              {
                "path": "/academic/leaves/settings/workflows",
                "label": "Workflows",
                "iconName": "CalendarOff",
                "children": []
              }
            ]
          }
        ]
      },
      {
        "path": "/academic/periods",
        "label": "Periods",
        "iconName": "Clock",
        "children": [
          {
            "path": "/academic/periods/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/academic/privileges",
        "label": "Privileges",
        "iconName": "KeyRound",
        "children": [
          {
            "path": "/academic/privileges/my",
            "label": "My",
            "iconName": "KeyRound",
            "children": [
              {
                "path": "/academic/privileges/my/report",
                "label": "Report",
                "iconName": "KeyRound",
                "children": []
              }
            ]
          },
          {
            "path": "/academic/privileges/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/academic/privileges/templates",
            "label": "Templates",
            "iconName": "KeyRound",
            "children": []
          }
        ]
      },
      {
        "path": "/academic/regulations",
        "label": "Regulations",
        "iconName": "Scale",
        "children": [
          {
            "path": "/academic/regulations/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/academic/staff-planning",
        "label": "Staff Planning",
        "iconName": "Users",
        "children": [
          {
            "path": "/academic/staff-planning/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/academic/timetables",
        "label": "Timetables",
        "iconName": "CalendarClock",
        "children": [
          {
            "path": "/academic/timetables/conflicts",
            "label": "Conflicts",
            "iconName": "CalendarClock",
            "children": []
          },
          {
            "path": "/academic/timetables/faculty-calendar",
            "label": "Faculty Calendar",
            "iconName": "CalendarClock",
            "children": [
              {
                "path": "/academic/timetables/faculty-calendar/admin",
                "label": "Admin",
                "iconName": "CalendarClock",
                "children": []
              }
            ]
          },
          {
            "path": "/academic/timetables/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/academic/timetables/templates",
            "label": "Templates",
            "iconName": "CalendarClock",
            "children": [
              {
                "path": "/academic/timetables/templates/analytics",
                "label": "Analytics",
                "iconName": "BarChart",
                "children": []
              }
            ]
          }
        ]
      },
      {
        "path": "/academic/years",
        "label": "Years",
        "iconName": "CalendarRange",
        "children": [
          {
            "path": "/academic/years/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/accreditation",
    "label": "Accreditation",
    "iconName": "FileText",
    "children": [
      {
        "path": "/accreditation/aicte",
        "label": "Aicte",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/coverage",
        "label": "Coverage",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/dci",
        "label": "Dci",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/inc",
        "label": "Inc",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/manage",
        "label": "Manage",
        "iconName": "Settings",
        "children": [
          {
            "path": "/accreditation/manage/grievance-categories",
            "label": "Grievance Categories",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/accreditation/manage/metrics",
            "label": "Metrics",
            "iconName": "FileText",
            "children": []
          }
        ]
      },
      {
        "path": "/accreditation/naac",
        "label": "Naac",
        "iconName": "FileText",
        "children": [
          {
            "path": "/accreditation/naac/committees",
            "label": "Committees",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/accreditation/naac/dcf-export",
            "label": "Dcf Export",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/accreditation/naac/grievance",
            "label": "Grievance",
            "iconName": "FileText",
            "children": [
              {
                "path": "/accreditation/naac/grievance/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/accreditation/naac/surveys",
            "label": "Surveys",
            "iconName": "FileText",
            "children": [
              {
                "path": "/accreditation/naac/surveys/8.4-export",
                "label": "8.4 Export",
                "iconName": "FileText",
                "children": []
              },
              {
                "path": "/accreditation/naac/surveys/consent",
                "label": "Consent",
                "iconName": "FileText",
                "children": []
              }
            ]
          }
        ]
      },
      {
        "path": "/accreditation/nba",
        "label": "Nba",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/ncte",
        "label": "Ncte",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/nirf",
        "label": "Nirf",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/pci",
        "label": "Pci",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/qs",
        "label": "Qs",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/accreditation/ugc",
        "label": "Ugc",
        "iconName": "FileText",
        "children": []
      }
    ]
  },
  {
    "path": "/admin",
    "label": "Admin",
    "iconName": "FileText",
    "children": [
      {
        "path": "/admin/ai-query-tools",
        "label": "Ai Query Tools",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/bug-reports",
        "label": "Bug Reports",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/counselors",
        "label": "Counselors",
        "iconName": "Users",
        "children": [
          {
            "path": "/admin/counselors/alert-thresholds",
            "label": "Alert Thresholds",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admin/counselors/routing-config",
            "label": "Routing Config",
            "iconName": "Users",
            "children": []
          }
        ]
      },
      {
        "path": "/admin/exophone-mapping",
        "label": "Exophone Mapping",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/landing-pages",
        "label": "Landing Pages",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/lifecycle",
        "label": "Lifecycle",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/lti",
        "label": "Lti",
        "iconName": "PlugZap",
        "children": [
          {
            "path": "/admin/lti/analytics",
            "label": "Analytics",
            "iconName": "BarChart",
            "children": []
          },
          {
            "path": "/admin/lti/grade-sync",
            "label": "Grade Sync",
            "iconName": "PlugZap",
            "children": []
          },
          {
            "path": "/admin/lti/launches",
            "label": "Launches",
            "iconName": "PlugZap",
            "children": []
          }
        ]
      },
      {
        "path": "/admin/nav-config",
        "label": "Nav Config",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/notifications",
        "label": "Notifications",
        "iconName": "Bell",
        "children": [
          {
            "path": "/admin/notifications/audiences",
            "label": "Audiences",
            "iconName": "Bell",
            "children": [
              {
                "path": "/admin/notifications/audiences/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/admin/notifications/compliance",
            "label": "Compliance",
            "iconName": "Bell",
            "children": []
          },
          {
            "path": "/admin/notifications/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/admin/notifications/recipients",
            "label": "Recipients",
            "iconName": "Bell",
            "children": []
          }
        ]
      },
      {
        "path": "/admin/page-metadata",
        "label": "Page Metadata",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/pde",
        "label": "Pde",
        "iconName": "FileText",
        "children": [
          {
            "path": "/admin/pde/assessments",
            "label": "Assessments",
            "iconName": "ClipboardCheck",
            "children": [
              {
                "path": "/admin/pde/assessments/create",
                "label": "Create",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/admin/pde/at-risk",
            "label": "At Risk",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/admin/pde/capabilities",
            "label": "Capabilities",
            "iconName": "Cpu",
            "children": []
          },
          {
            "path": "/admin/pde/engagement",
            "label": "Engagement",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/admin/pde/lti",
            "label": "Lti",
            "iconName": "PlugZap",
            "children": []
          },
          {
            "path": "/admin/pde/quests",
            "label": "Quests",
            "iconName": "Trophy",
            "children": [
              {
                "path": "/admin/pde/quests/create",
                "label": "Create",
                "iconName": "Plus",
                "children": []
              }
            ]
          }
        ]
      },
      {
        "path": "/admin/reset-driver-passwords",
        "label": "Reset Driver Passwords",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/retention-policies",
        "label": "Retention Policies",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/saml",
        "label": "Saml",
        "iconName": "KeyRound",
        "children": []
      },
      {
        "path": "/admin/telephony-policies",
        "label": "Telephony Policies",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/admin/whatsapp-limits",
        "label": "Whatsapp Limits",
        "iconName": "FileText",
        "children": []
      }
    ]
  },
  {
    "path": "/admission",
    "label": "Admission",
    "iconName": "GraduationCap",
    "children": [
      {
        "path": "/admission/analytics",
        "label": "Analytics",
        "iconName": "BarChart",
        "children": []
      },
      {
        "path": "/admission/applications",
        "label": "Applications",
        "iconName": "ClipboardList",
        "children": []
      },
      {
        "path": "/admission/consultants",
        "label": "Consultants",
        "iconName": "Users",
        "children": [
          {
            "path": "/admission/consultants/analytics",
            "label": "Analytics",
            "iconName": "BarChart",
            "children": []
          },
          {
            "path": "/admission/consultants/commissions",
            "label": "Commissions",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admission/consultants/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/admission/consultants/referrals",
            "label": "Referrals",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admission/consultants/rewards",
            "label": "Rewards",
            "iconName": "Users",
            "children": []
          }
        ]
      },
      {
        "path": "/admission/counselors",
        "label": "Counselors",
        "iconName": "Users",
        "children": [
          {
            "path": "/admission/counselors/alerts",
            "label": "Alerts",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admission/counselors/briefing",
            "label": "Briefing",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admission/counselors/calls",
            "label": "Calls",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admission/counselors/daily-view",
            "label": "Daily View",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admission/counselors/productivity",
            "label": "Productivity",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admission/counselors/reminders",
            "label": "Reminders",
            "iconName": "Users",
            "children": []
          },
          {
            "path": "/admission/counselors/team",
            "label": "Team",
            "iconName": "Users",
            "children": [
              {
                "path": "/admission/counselors/team/activity",
                "label": "Activity",
                "iconName": "History",
                "children": []
              },
              {
                "path": "/admission/counselors/team/allocation",
                "label": "Allocation",
                "iconName": "Users",
                "children": []
              },
              {
                "path": "/admission/counselors/team/roster",
                "label": "Roster",
                "iconName": "Users",
                "children": []
              },
              {
                "path": "/admission/counselors/team/rules",
                "label": "Rules",
                "iconName": "Users",
                "children": []
              }
            ]
          }
        ]
      },
      {
        "path": "/admission/dashboard",
        "label": "Dashboard",
        "iconName": "LayoutGrid",
        "children": []
      },
      {
        "path": "/admission/data-quality",
        "label": "Data Quality",
        "iconName": "CheckCircle2",
        "children": [
          {
            "path": "/admission/data-quality/data-profiling",
            "label": "Data Profiling",
            "iconName": "CheckCircle2",
            "children": []
          },
          {
            "path": "/admission/data-quality/deduplication",
            "label": "Deduplication",
            "iconName": "CheckCircle2",
            "children": []
          },
          {
            "path": "/admission/data-quality/phone-validation",
            "label": "Phone Validation",
            "iconName": "CheckCircle2",
            "children": []
          }
        ]
      },
      {
        "path": "/admission/gd-pi",
        "label": "Gd Pi",
        "iconName": "MessagesSquare",
        "children": [
          {
            "path": "/admission/gd-pi/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/admission/group-dashboard",
        "label": "Group Dashboard",
        "iconName": "LayoutGrid",
        "children": []
      },
      {
        "path": "/admission/insights",
        "label": "Insights",
        "iconName": "Lightbulb",
        "children": [
          {
            "path": "/admission/insights/status",
            "label": "Status",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      },
      {
        "path": "/admission/leads",
        "label": "Leads",
        "iconName": "UserPlus",
        "children": [
          {
            "path": "/admission/leads/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/admission/leads/work",
            "label": "Work",
            "iconName": "UserPlus",
            "children": []
          }
        ]
      },
      {
        "path": "/admission/marketing",
        "label": "Marketing",
        "iconName": "Megaphone",
        "children": [
          {
            "path": "/admission/marketing/campaigns",
            "label": "Campaigns",
            "iconName": "Megaphone",
            "children": [
              {
                "path": "/admission/marketing/campaigns/monitoring",
                "label": "Monitoring",
                "iconName": "Megaphone",
                "children": []
              },
              {
                "path": "/admission/marketing/campaigns/roi",
                "label": "Roi",
                "iconName": "Megaphone",
                "children": []
              },
              {
                "path": "/admission/marketing/campaigns/segments",
                "label": "Segments",
                "iconName": "Megaphone",
                "children": []
              }
            ]
          },
          {
            "path": "/admission/marketing/chat",
            "label": "Chat",
            "iconName": "MessageSquare",
            "children": [
              {
                "path": "/admission/marketing/chat/performance",
                "label": "Performance",
                "iconName": "MessageSquare",
                "children": []
              },
              {
                "path": "/admission/marketing/chat/settings",
                "label": "Settings",
                "iconName": "Settings",
                "children": []
              }
            ]
          },
          {
            "path": "/admission/marketing/chatbot",
            "label": "Chatbot",
            "iconName": "MessageSquare",
            "children": [
              {
                "path": "/admission/marketing/chatbot/analytics",
                "label": "Analytics",
                "iconName": "BarChart",
                "children": []
              },
              {
                "path": "/admission/marketing/chatbot/knowledge",
                "label": "Knowledge",
                "iconName": "MessageSquare",
                "children": []
              }
            ]
          },
          {
            "path": "/admission/marketing/database",
            "label": "Database",
            "iconName": "Megaphone",
            "children": []
          },
          {
            "path": "/admission/marketing/expos",
            "label": "Expos",
            "iconName": "Megaphone",
            "children": [
              {
                "path": "/admission/marketing/expos/analytics",
                "label": "Analytics",
                "iconName": "BarChart",
                "children": []
              },
              {
                "path": "/admission/marketing/expos/masters",
                "label": "Masters",
                "iconName": "Megaphone",
                "children": []
              },
              {
                "path": "/admission/marketing/expos/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/admission/marketing/parent-communication",
            "label": "Parent Communication",
            "iconName": "Megaphone",
            "children": []
          },
          {
            "path": "/admission/marketing/publishers",
            "label": "Publishers",
            "iconName": "Megaphone",
            "children": []
          },
          {
            "path": "/admission/marketing/re-engagement",
            "label": "Re Engagement",
            "iconName": "Megaphone",
            "children": []
          },
          {
            "path": "/admission/marketing/remarketing",
            "label": "Remarketing",
            "iconName": "Megaphone",
            "children": []
          },
          {
            "path": "/admission/marketing/voice-agents",
            "label": "Voice Agents",
            "iconName": "Megaphone",
            "children": []
          },
          {
            "path": "/admission/marketing/voice-broadcast",
            "label": "Voice Broadcast",
            "iconName": "Megaphone",
            "children": []
          },
          {
            "path": "/admission/marketing/whatsapp-broadcast",
            "label": "Whatsapp Broadcast",
            "iconName": "Megaphone",
            "children": []
          }
        ]
      },
      {
        "path": "/admission/settings",
        "label": "Settings",
        "iconName": "Settings",
        "children": [
          {
            "path": "/admission/settings/assignment-rules",
            "label": "Assignment Rules",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/admission/settings/forms",
            "label": "Forms",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/admission/settings/seat-config",
            "label": "Seat Config",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/admission/settings/sources",
            "label": "Sources",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/admission/settings/templates",
            "label": "Templates",
            "iconName": "GraduationCap",
            "children": [
              {
                "path": "/admission/settings/templates/analytics",
                "label": "Analytics",
                "iconName": "BarChart",
                "children": []
              },
              {
                "path": "/admission/settings/templates/documents",
                "label": "Documents",
                "iconName": "GraduationCap",
                "children": []
              },
              {
                "path": "/admission/settings/templates/email-builder",
                "label": "Email Builder",
                "iconName": "GraduationCap",
                "children": []
              }
            ]
          },
          {
            "path": "/admission/settings/whatsapp-numbers",
            "label": "Whatsapp Numbers",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/admission/settings/workflow-config",
            "label": "Workflow Config",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/admission/settings/workflows",
            "label": "Workflows",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/admission/settings/years",
            "label": "Years",
            "iconName": "CalendarRange",
            "children": [
              {
                "path": "/admission/settings/years/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "path": "/ai-query",
    "label": "Ai Query",
    "iconName": "FileText",
    "children": []
  },
  {
    "path": "/application-hub",
    "label": "Application Hub",
    "iconName": "FileText",
    "children": [
      {
        "path": "/application-hub/api-guidelines",
        "label": "Api Guidelines",
        "iconName": "Code2",
        "children": [
          {
            "path": "/application-hub/api-guidelines/b2a",
            "label": "B2a",
            "iconName": "Code2",
            "children": []
          },
          {
            "path": "/application-hub/api-guidelines/endpoints",
            "label": "Endpoints",
            "iconName": "Code2",
            "children": []
          },
          {
            "path": "/application-hub/api-guidelines/mcp",
            "label": "Mcp",
            "iconName": "Code2",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/applications",
    "label": "Applications",
    "iconName": "ClipboardList",
    "children": [
      {
        "path": "/applications/categories",
        "label": "Categories",
        "iconName": "ClipboardList",
        "children": []
      },
      {
        "path": "/applications/new",
        "label": "New",
        "iconName": "Plus",
        "children": []
      }
    ]
  },
  {
    "path": "/audit",
    "label": "Audit",
    "iconName": "ClipboardCheck",
    "children": [
      {
        "path": "/audit/cycles",
        "label": "Cycles",
        "iconName": "RotateCw",
        "children": [
          {
            "path": "/audit/cycles/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/audit/dashboard",
        "label": "Dashboard",
        "iconName": "LayoutGrid",
        "children": []
      },
      {
        "path": "/audit/external-auditors",
        "label": "External Auditors",
        "iconName": "ClipboardCheck",
        "children": []
      },
      {
        "path": "/audit/finding-types",
        "label": "Finding Types",
        "iconName": "ClipboardCheck",
        "children": [
          {
            "path": "/audit/finding-types/settings",
            "label": "Settings",
            "iconName": "Settings",
            "children": []
          }
        ]
      },
      {
        "path": "/audit/findings",
        "label": "Findings",
        "iconName": "Search",
        "children": []
      },
      {
        "path": "/audit/my-findings",
        "label": "My Findings",
        "iconName": "ClipboardCheck",
        "children": []
      },
      {
        "path": "/audit/parameters",
        "label": "Parameters",
        "iconName": "Sliders",
        "children": [
          {
            "path": "/audit/parameters/settings",
            "label": "Settings",
            "iconName": "Settings",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/audit-trail",
    "label": "Audit Trail",
    "iconName": "History",
    "children": []
  },
  {
    "path": "/billing",
    "label": "Billing",
    "iconName": "Wallet",
    "children": [
      {
        "path": "/billing/categories",
        "label": "Categories",
        "iconName": "Wallet",
        "children": [
          {
            "path": "/billing/categories/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/billing/discounts",
        "label": "Discounts",
        "iconName": "Wallet",
        "children": [
          {
            "path": "/billing/discounts/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/billing/invoices",
        "label": "Invoices",
        "iconName": "Wallet",
        "children": []
      },
      {
        "path": "/billing/onboarding",
        "label": "Onboarding",
        "iconName": "UserPlus",
        "children": []
      },
      {
        "path": "/billing/payment",
        "label": "Payment",
        "iconName": "Wallet",
        "children": [
          {
            "path": "/billing/payment/failed",
            "label": "Failed",
            "iconName": "Wallet",
            "children": []
          },
          {
            "path": "/billing/payment/success",
            "label": "Success",
            "iconName": "Wallet",
            "children": []
          }
        ]
      },
      {
        "path": "/billing/receipts",
        "label": "Receipts",
        "iconName": "Wallet",
        "children": [
          {
            "path": "/billing/receipts/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/billing/receipts/templates",
            "label": "Templates",
            "iconName": "Wallet",
            "children": []
          }
        ]
      },
      {
        "path": "/billing/refunds",
        "label": "Refunds",
        "iconName": "Wallet",
        "children": [
          {
            "path": "/billing/refunds/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/billing/reports",
        "label": "Reports",
        "iconName": "FileBarChart",
        "children": []
      },
      {
        "path": "/billing/schedule",
        "label": "Schedule",
        "iconName": "CalendarClock",
        "children": [
          {
            "path": "/billing/schedule/bulk-create",
            "label": "Bulk Create",
            "iconName": "CalendarClock",
            "children": []
          },
          {
            "path": "/billing/schedule/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/billing/schedule/students",
            "label": "Students",
            "iconName": "CalendarClock",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/bos",
    "label": "Bos",
    "iconName": "FileText",
    "children": [
      {
        "path": "/bos/compositions",
        "label": "Compositions",
        "iconName": "Layers",
        "children": [
          {
            "path": "/bos/compositions/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/bos/experts",
        "label": "Experts",
        "iconName": "UserCheck",
        "children": [
          {
            "path": "/bos/experts/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/bos/meetings",
        "label": "Meetings",
        "iconName": "FileText",
        "children": [
          {
            "path": "/bos/meetings/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/bos/reports",
        "label": "Reports",
        "iconName": "FileBarChart",
        "children": []
      },
      {
        "path": "/bos/ta-da",
        "label": "Ta Da",
        "iconName": "DollarSign",
        "children": []
      }
    ]
  },
  {
    "path": "/bug-leaderboard",
    "label": "Bug Leaderboard",
    "iconName": "FileText",
    "children": []
  },
  {
    "path": "/campus-living",
    "label": "Campus Living",
    "iconName": "FileText",
    "children": [
      {
        "path": "/campus-living/activity",
        "label": "Activity",
        "iconName": "History",
        "children": []
      },
      {
        "path": "/campus-living/allocations",
        "label": "Allocations",
        "iconName": "PackageCheck",
        "children": [
          {
            "path": "/campus-living/allocations/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/campus-living/allocations/onboarding",
            "label": "Onboarding",
            "iconName": "UserPlus",
            "children": [
              {
                "path": "/campus-living/allocations/onboarding/templates",
                "label": "Templates",
                "iconName": "UserPlus",
                "children": []
              }
            ]
          },
          {
            "path": "/campus-living/allocations/roommate-matching",
            "label": "Roommate Matching",
            "iconName": "PackageCheck",
            "children": []
          },
          {
            "path": "/campus-living/allocations/waitlist",
            "label": "Waitlist",
            "iconName": "PackageCheck",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/analytics",
        "label": "Analytics",
        "iconName": "BarChart",
        "children": [
          {
            "path": "/campus-living/analytics/alert-rules",
            "label": "Alert Rules",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/campus-living/analytics/alerts",
            "label": "Alerts",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/campus-living/analytics/attendance",
            "label": "Attendance",
            "iconName": "CheckSquare",
            "children": []
          },
          {
            "path": "/campus-living/analytics/cross-domain",
            "label": "Cross Domain",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/campus-living/analytics/fees",
            "label": "Fees",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/campus-living/analytics/maintenance",
            "label": "Maintenance",
            "iconName": "Wrench",
            "children": []
          },
          {
            "path": "/campus-living/analytics/mess",
            "label": "Mess",
            "iconName": "Utensils",
            "children": []
          },
          {
            "path": "/campus-living/analytics/occupancy",
            "label": "Occupancy",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/campus-living/analytics/safety",
            "label": "Safety",
            "iconName": "ShieldAlert",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/attendance",
        "label": "Attendance",
        "iconName": "CheckSquare",
        "children": [
          {
            "path": "/campus-living/attendance/absentees",
            "label": "Absentees",
            "iconName": "CheckSquare",
            "children": []
          },
          {
            "path": "/campus-living/attendance/history",
            "label": "History",
            "iconName": "CheckSquare",
            "children": []
          },
          {
            "path": "/campus-living/attendance/mark",
            "label": "Mark",
            "iconName": "CheckSquare",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/blocks",
        "label": "Blocks",
        "iconName": "Building",
        "children": [
          {
            "path": "/campus-living/blocks/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/calendar",
        "label": "Calendar",
        "iconName": "Calendar",
        "children": []
      },
      {
        "path": "/campus-living/community",
        "label": "Community",
        "iconName": "Users2",
        "children": [
          {
            "path": "/campus-living/community/settings",
            "label": "Settings",
            "iconName": "Settings",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/dashboard",
        "label": "Dashboard",
        "iconName": "LayoutGrid",
        "children": []
      },
      {
        "path": "/campus-living/gate-passes",
        "label": "Gate Passes",
        "iconName": "Ticket",
        "children": []
      },
      {
        "path": "/campus-living/health",
        "label": "Health",
        "iconName": "Heart",
        "children": []
      },
      {
        "path": "/campus-living/housekeeping",
        "label": "Housekeeping",
        "iconName": "SprayCan",
        "children": [
          {
            "path": "/campus-living/housekeeping/schedules",
            "label": "Schedules",
            "iconName": "CalendarClock",
            "children": []
          },
          {
            "path": "/campus-living/housekeeping/tasks",
            "label": "Tasks",
            "iconName": "SprayCan",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/laundry",
        "label": "Laundry",
        "iconName": "Shirt",
        "children": [
          {
            "path": "/campus-living/laundry/orders",
            "label": "Orders",
            "iconName": "Shirt",
            "children": []
          },
          {
            "path": "/campus-living/laundry/schedule",
            "label": "Schedule",
            "iconName": "CalendarClock",
            "children": []
          },
          {
            "path": "/campus-living/laundry/settings",
            "label": "Settings",
            "iconName": "Settings",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/leave",
        "label": "Leave",
        "iconName": "CalendarOff",
        "children": [
          {
            "path": "/campus-living/leave/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/maintenance",
        "label": "Maintenance",
        "iconName": "Wrench",
        "children": [
          {
            "path": "/campus-living/maintenance/contracts",
            "label": "Contracts",
            "iconName": "Wrench",
            "children": []
          },
          {
            "path": "/campus-living/maintenance/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/campus-living/maintenance/preventive",
            "label": "Preventive",
            "iconName": "Wrench",
            "children": [
              {
                "path": "/campus-living/maintenance/preventive/tasks",
                "label": "Tasks",
                "iconName": "Wrench",
                "children": []
              }
            ]
          }
        ]
      },
      {
        "path": "/campus-living/mess",
        "label": "Mess",
        "iconName": "Utensils",
        "children": [
          {
            "path": "/campus-living/mess/billing",
            "label": "Billing",
            "iconName": "Wallet",
            "children": []
          },
          {
            "path": "/campus-living/mess/bookings",
            "label": "Bookings",
            "iconName": "Utensils",
            "children": []
          },
          {
            "path": "/campus-living/mess/caterers",
            "label": "Caterers",
            "iconName": "Utensils",
            "children": [
              {
                "path": "/campus-living/mess/caterers/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/campus-living/mess/feedback",
            "label": "Feedback",
            "iconName": "MessageCircle",
            "children": []
          },
          {
            "path": "/campus-living/mess/meals",
            "label": "Meals",
            "iconName": "Utensils",
            "children": [
              {
                "path": "/campus-living/mess/meals/scan",
                "label": "Scan",
                "iconName": "Utensils",
                "children": []
              }
            ]
          },
          {
            "path": "/campus-living/mess/menu",
            "label": "Menu",
            "iconName": "Utensils",
            "children": []
          },
          {
            "path": "/campus-living/mess/waste",
            "label": "Waste",
            "iconName": "Utensils",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/my-hostel",
        "label": "My Hostel",
        "iconName": "FileText",
        "children": [
          {
            "path": "/campus-living/my-hostel/vacate-request",
            "label": "Vacate Request",
            "iconName": "LogOut",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/reports",
        "label": "Reports",
        "iconName": "FileBarChart",
        "children": [
          {
            "path": "/campus-living/reports/anti-ragging-compliance",
            "label": "Anti Ragging Compliance",
            "iconName": "FileBarChart",
            "children": []
          },
          {
            "path": "/campus-living/reports/attendance-register",
            "label": "Attendance Register",
            "iconName": "FileBarChart",
            "children": []
          },
          {
            "path": "/campus-living/reports/fee-collection",
            "label": "Fee Collection",
            "iconName": "FileBarChart",
            "children": []
          },
          {
            "path": "/campus-living/reports/occupancy",
            "label": "Occupancy",
            "iconName": "FileBarChart",
            "children": []
          },
          {
            "path": "/campus-living/reports/safety-audit",
            "label": "Safety Audit",
            "iconName": "FileBarChart",
            "children": []
          },
          {
            "path": "/campus-living/reports/visitor-register",
            "label": "Visitor Register",
            "iconName": "FileBarChart",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/residents",
        "label": "Residents",
        "iconName": "BedDouble",
        "children": []
      },
      {
        "path": "/campus-living/safety",
        "label": "Safety",
        "iconName": "ShieldAlert",
        "children": [
          {
            "path": "/campus-living/safety/access-log",
            "label": "Access Log",
            "iconName": "ShieldAlert",
            "children": []
          },
          {
            "path": "/campus-living/safety/anti-ragging",
            "label": "Anti Ragging",
            "iconName": "ShieldAlert",
            "children": []
          },
          {
            "path": "/campus-living/safety/curfew-exceptions",
            "label": "Curfew Exceptions",
            "iconName": "ShieldAlert",
            "children": []
          },
          {
            "path": "/campus-living/safety/emergency-contacts",
            "label": "Emergency Contacts",
            "iconName": "ShieldAlert",
            "children": []
          },
          {
            "path": "/campus-living/safety/incidents",
            "label": "Incidents",
            "iconName": "ShieldAlert",
            "children": [
              {
                "path": "/campus-living/safety/incidents/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/campus-living/safety/inspections",
            "label": "Inspections",
            "iconName": "ShieldAlert",
            "children": [
              {
                "path": "/campus-living/safety/inspections/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          }
        ]
      },
      {
        "path": "/campus-living/settings",
        "label": "Settings",
        "iconName": "Settings",
        "children": [
          {
            "path": "/campus-living/settings/approval-chains",
            "label": "Approval Chains",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/campus-living/settings/fee-config",
            "label": "Fee Config",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/campus-living/settings/general",
            "label": "General",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/campus-living/settings/leave-types",
            "label": "Leave Types",
            "iconName": "CalendarOff",
            "children": []
          },
          {
            "path": "/campus-living/settings/maintenance-sla",
            "label": "Maintenance Sla",
            "iconName": "Wrench",
            "children": []
          },
          {
            "path": "/campus-living/settings/notification-rules",
            "label": "Notification Rules",
            "iconName": "FileText",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/vacate-requests",
        "label": "Vacate Requests",
        "iconName": "LogOut",
        "children": []
      },
      {
        "path": "/campus-living/visitors",
        "label": "Visitors",
        "iconName": "UserCog",
        "children": [
          {
            "path": "/campus-living/visitors/known",
            "label": "Known",
            "iconName": "UserCog",
            "children": []
          },
          {
            "path": "/campus-living/visitors/register",
            "label": "Register",
            "iconName": "UserCog",
            "children": []
          }
        ]
      },
      {
        "path": "/campus-living/wellness",
        "label": "Wellness",
        "iconName": "HeartPulse",
        "children": [
          {
            "path": "/campus-living/wellness/surveys",
            "label": "Surveys",
            "iconName": "HeartPulse",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/dashboard",
    "label": "Dashboard",
    "iconName": "LayoutGrid",
    "children": [
      {
        "path": "/dashboard/classic",
        "label": "Classic",
        "iconName": "FileText",
        "children": []
      }
    ]
  },
  {
    "path": "/events",
    "label": "Events",
    "iconName": "CalendarHeart",
    "children": [
      {
        "path": "/events/marathon",
        "label": "Marathon",
        "iconName": "CalendarHeart",
        "children": [
          {
            "path": "/events/marathon/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/events/propose",
        "label": "Propose",
        "iconName": "CalendarHeart",
        "children": []
      }
    ]
  },
  {
    "path": "/faculty",
    "label": "Faculty",
    "iconName": "FileText",
    "children": [
      {
        "path": "/faculty/innovation",
        "label": "Innovation",
        "iconName": "Lightbulb",
        "children": [
          {
            "path": "/faculty/innovation/approval-queue",
            "label": "Approval Queue",
            "iconName": "Lightbulb",
            "children": []
          },
          {
            "path": "/faculty/innovation/collab-request",
            "label": "Collab Request",
            "iconName": "Lightbulb",
            "children": []
          },
          {
            "path": "/faculty/innovation/portfolio",
            "label": "Portfolio",
            "iconName": "Lightbulb",
            "children": []
          },
          {
            "path": "/faculty/innovation/submit",
            "label": "Submit",
            "iconName": "Lightbulb",
            "children": []
          }
        ]
      },
      {
        "path": "/faculty/pde",
        "label": "Pde",
        "iconName": "FileText",
        "children": [
          {
            "path": "/faculty/pde/analytics",
            "label": "Analytics",
            "iconName": "BarChart",
            "children": []
          },
          {
            "path": "/faculty/pde/assessments",
            "label": "Assessments",
            "iconName": "ClipboardCheck",
            "children": []
          },
          {
            "path": "/faculty/pde/dashboard",
            "label": "Dashboard",
            "iconName": "LayoutGrid",
            "children": []
          },
          {
            "path": "/faculty/pde/demonstrations",
            "label": "Demonstrations",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/faculty/pde/quests",
            "label": "Quests",
            "iconName": "Trophy",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/health",
    "label": "Health",
    "iconName": "Heart",
    "children": [
      {
        "path": "/health/achievements",
        "label": "Achievements",
        "iconName": "Heart",
        "children": []
      },
      {
        "path": "/health/assessments",
        "label": "Assessments",
        "iconName": "Heart",
        "children": []
      },
      {
        "path": "/health/counselor",
        "label": "Counselor",
        "iconName": "Heart",
        "children": []
      },
      {
        "path": "/health/dashboard",
        "label": "Dashboard",
        "iconName": "LayoutGrid",
        "children": []
      },
      {
        "path": "/health/fitness",
        "label": "Fitness",
        "iconName": "Heart",
        "children": []
      },
      {
        "path": "/health/leaderboard",
        "label": "Leaderboard",
        "iconName": "Trophy",
        "children": []
      },
      {
        "path": "/health/profile",
        "label": "Profile",
        "iconName": "UserCircle",
        "children": []
      },
      {
        "path": "/health/sports",
        "label": "Sports",
        "iconName": "Heart",
        "children": []
      },
      {
        "path": "/health/training",
        "label": "Training",
        "iconName": "Heart",
        "children": []
      }
    ]
  },
  {
    "path": "/hr",
    "label": "Hr",
    "iconName": "FileText",
    "children": [
      {
        "path": "/hr/employees",
        "label": "Employees",
        "iconName": "Users",
        "children": [
          {
            "path": "/hr/employees/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/hr/leave",
        "label": "Leave",
        "iconName": "CalendarOff",
        "children": [
          {
            "path": "/hr/leave/apply",
            "label": "Apply",
            "iconName": "CalendarOff",
            "children": []
          },
          {
            "path": "/hr/leave/approve",
            "label": "Approve",
            "iconName": "CalendarOff",
            "children": []
          },
          {
            "path": "/hr/leave/balance",
            "label": "Balance",
            "iconName": "CalendarOff",
            "children": []
          },
          {
            "path": "/hr/leave/calendar",
            "label": "Calendar",
            "iconName": "Calendar",
            "children": []
          },
          {
            "path": "/hr/leave/encashment",
            "label": "Encashment",
            "iconName": "CalendarOff",
            "children": []
          },
          {
            "path": "/hr/leave/my-applications",
            "label": "My Applications",
            "iconName": "CalendarOff",
            "children": []
          }
        ]
      },
      {
        "path": "/hr/policies",
        "label": "Policies",
        "iconName": "BookText",
        "children": []
      },
      {
        "path": "/hr/recruitment",
        "label": "Recruitment",
        "iconName": "UserSearch",
        "children": [
          {
            "path": "/hr/recruitment/approvals",
            "label": "Approvals",
            "iconName": "UserSearch",
            "children": []
          },
          {
            "path": "/hr/recruitment/my",
            "label": "My",
            "iconName": "UserSearch",
            "children": []
          },
          {
            "path": "/hr/recruitment/submit",
            "label": "Submit",
            "iconName": "UserSearch",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/learn",
    "label": "Learn",
    "iconName": "FileText",
    "children": [
      {
        "path": "/learn/build",
        "label": "Build",
        "iconName": "Hammer",
        "children": []
      },
      {
        "path": "/learn/capabilities",
        "label": "Capabilities",
        "iconName": "Cpu",
        "children": []
      },
      {
        "path": "/learn/channels",
        "label": "Channels",
        "iconName": "Tv",
        "children": []
      },
      {
        "path": "/learn/leaderboard",
        "label": "Leaderboard",
        "iconName": "Trophy",
        "children": []
      },
      {
        "path": "/learn/profile",
        "label": "Profile",
        "iconName": "UserCircle",
        "children": [
          {
            "path": "/learn/profile/activity",
            "label": "Activity",
            "iconName": "History",
            "children": []
          },
          {
            "path": "/learn/profile/badges",
            "label": "Badges",
            "iconName": "UserCircle",
            "children": []
          }
        ]
      },
      {
        "path": "/learn/quests",
        "label": "Quests",
        "iconName": "Trophy",
        "children": []
      }
    ]
  },
  {
    "path": "/learners",
    "label": "Learners",
    "iconName": "GraduationCap",
    "children": [
      {
        "path": "/learners/alumni",
        "label": "Alumni",
        "iconName": "GraduationCap",
        "children": []
      },
      {
        "path": "/learners/analytics",
        "label": "Analytics",
        "iconName": "BarChart",
        "children": []
      },
      {
        "path": "/learners/change-requests",
        "label": "Change Requests",
        "iconName": "GraduationCap",
        "children": []
      },
      {
        "path": "/learners/enquiries",
        "label": "Enquiries",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners/enquiries/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/learners/leave-onduty",
        "label": "Leave Onduty",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners/leave-onduty/apply",
            "label": "Apply",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners/leave-onduty/my-applications",
            "label": "My Applications",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      },
      {
        "path": "/learners/my-attendance",
        "label": "My Attendance",
        "iconName": "GraduationCap",
        "children": []
      },
      {
        "path": "/learners/my-profile",
        "label": "My Profile",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners/my-profile/status",
            "label": "Status",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      },
      {
        "path": "/learners/my-timetable",
        "label": "My Timetable",
        "iconName": "GraduationCap",
        "children": []
      },
      {
        "path": "/learners/profiles",
        "label": "Profiles",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners/profiles/promotion",
            "label": "Promotion",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/learners-council",
    "label": "Learners Council",
    "iconName": "GraduationCap",
    "children": [
      {
        "path": "/learners-council/communication",
        "label": "Communication",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners-council/communication/chat",
            "label": "Chat",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/communication/forums",
            "label": "Forums",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/communication/polls",
            "label": "Polls",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      },
      {
        "path": "/learners-council/events",
        "label": "Events",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners-council/events/calendar",
            "label": "Calendar",
            "iconName": "Calendar",
            "children": []
          },
          {
            "path": "/learners-council/events/proposals",
            "label": "Proposals",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      },
      {
        "path": "/learners-council/issues",
        "label": "Issues",
        "iconName": "GraduationCap",
        "children": []
      },
      {
        "path": "/learners-council/od",
        "label": "Od",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners-council/od/approvals",
            "label": "Approvals",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/od/chains",
            "label": "Chains",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      },
      {
        "path": "/learners-council/selection",
        "label": "Selection",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners-council/selection/elections",
            "label": "Elections",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/selection/interviews",
            "label": "Interviews",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/selection/nominations",
            "label": "Nominations",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      },
      {
        "path": "/learners-council/settings",
        "label": "Settings",
        "iconName": "Settings",
        "children": []
      },
      {
        "path": "/learners-council/structure",
        "label": "Structure",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners-council/structure/committees",
            "label": "Committees",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/structure/members",
            "label": "Members",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/structure/positions",
            "label": "Positions",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/structure/terms",
            "label": "Terms",
            "iconName": "GraduationCap",
            "children": []
          },
          {
            "path": "/learners-council/structure/verticals",
            "label": "Verticals",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      },
      {
        "path": "/learners-council/yuva",
        "label": "Yuva",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/learners-council/yuva/members",
            "label": "Members",
            "iconName": "GraduationCap",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/meetings",
    "label": "Meetings",
    "iconName": "FileText",
    "children": [
      {
        "path": "/meetings/availability",
        "label": "Availability",
        "iconName": "CalendarCheck",
        "children": []
      },
      {
        "path": "/meetings/inbox",
        "label": "Inbox",
        "iconName": "Inbox",
        "children": []
      },
      {
        "path": "/meetings/manage",
        "label": "Manage",
        "iconName": "Settings",
        "children": []
      }
    ]
  },
  {
    "path": "/my-bug-reports",
    "label": "My Bug Reports",
    "iconName": "FileText",
    "children": []
  },
  {
    "path": "/notifications",
    "label": "Notifications",
    "iconName": "Bell",
    "children": [
      {
        "path": "/notifications/settings",
        "label": "Settings",
        "iconName": "Settings",
        "children": []
      }
    ]
  },
  {
    "path": "/okr",
    "label": "Okr",
    "iconName": "FileText",
    "children": [
      {
        "path": "/okr/abcd",
        "label": "Abcd",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/okr/admin",
        "label": "Admin",
        "iconName": "FileText",
        "children": [
          {
            "path": "/okr/admin/compliance",
            "label": "Compliance",
            "iconName": "FileText",
            "children": []
          }
        ]
      },
      {
        "path": "/okr/analytics",
        "label": "Analytics",
        "iconName": "BarChart",
        "children": []
      },
      {
        "path": "/okr/cascade",
        "label": "Cascade",
        "iconName": "Network",
        "children": []
      },
      {
        "path": "/okr/check-in",
        "label": "Check In",
        "iconName": "CheckCircle",
        "children": []
      },
      {
        "path": "/okr/department",
        "label": "Department",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/okr/elective",
        "label": "Elective",
        "iconName": "FileText",
        "children": [
          {
            "path": "/okr/elective/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/okr/manage",
        "label": "Manage",
        "iconName": "Settings",
        "children": []
      },
      {
        "path": "/okr/objectives",
        "label": "Objectives",
        "iconName": "Target",
        "children": [
          {
            "path": "/okr/objectives/create",
            "label": "Create",
            "iconName": "Plus",
            "children": [
              {
                "path": "/okr/objectives/create/organization",
                "label": "Organization",
                "iconName": "Plus",
                "children": []
              },
              {
                "path": "/okr/objectives/create/tier1",
                "label": "Tier1",
                "iconName": "Plus",
                "children": []
              },
              {
                "path": "/okr/objectives/create/tier2",
                "label": "Tier2",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/okr/objectives/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/okr/organization",
        "label": "Organization",
        "iconName": "Building2",
        "children": []
      },
      {
        "path": "/okr/team",
        "label": "Team",
        "iconName": "Users",
        "children": []
      }
    ]
  },
  {
    "path": "/organizations",
    "label": "Organizations",
    "iconName": "Building2",
    "children": [
      {
        "path": "/organizations/courses",
        "label": "Courses",
        "iconName": "BookOpen",
        "children": [
          {
            "path": "/organizations/courses/mappings",
            "label": "Mappings",
            "iconName": "BookOpen",
            "children": [
              {
                "path": "/organizations/courses/mappings/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/organizations/courses/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/organizations/dashboard",
        "label": "Dashboard",
        "iconName": "LayoutGrid",
        "children": []
      },
      {
        "path": "/organizations/degrees",
        "label": "Degrees",
        "iconName": "GraduationCap",
        "children": [
          {
            "path": "/organizations/degrees/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/organizations/departments",
        "label": "Departments",
        "iconName": "Building2",
        "children": [
          {
            "path": "/organizations/departments/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/organizations/institutions",
        "label": "Institutions",
        "iconName": "Building",
        "children": [
          {
            "path": "/organizations/institutions/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/organizations/programs",
        "label": "Programs",
        "iconName": "BookOpen",
        "children": [
          {
            "path": "/organizations/programs/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/organizations/sections",
        "label": "Sections",
        "iconName": "LayoutGrid",
        "children": [
          {
            "path": "/organizations/sections/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/organizations/semesters",
        "label": "Semesters",
        "iconName": "CalendarDays",
        "children": [
          {
            "path": "/organizations/semesters/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/profile",
    "label": "Profile",
    "iconName": "UserCircle",
    "children": []
  },
  {
    "path": "/resource-management",
    "label": "Resource Management",
    "iconName": "FileText",
    "children": [
      {
        "path": "/resource-management/analytics-dashboard",
        "label": "Analytics Dashboard",
        "iconName": "BarChart",
        "children": []
      },
      {
        "path": "/resource-management/categories",
        "label": "Categories",
        "iconName": "Tags",
        "children": [
          {
            "path": "/resource-management/categories/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/resource-management/categories/sub-categories",
            "label": "Sub Categories",
            "iconName": "Tags",
            "children": [
              {
                "path": "/resource-management/categories/sub-categories/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          }
        ]
      },
      {
        "path": "/resource-management/maintenance",
        "label": "Maintenance",
        "iconName": "Wrench",
        "children": [
          {
            "path": "/resource-management/maintenance/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/resource-management/reservations",
        "label": "Reservations",
        "iconName": "Boxes",
        "children": [
          {
            "path": "/resource-management/reservations/approvals",
            "label": "Approvals",
            "iconName": "Boxes",
            "children": []
          },
          {
            "path": "/resource-management/reservations/my-reservations",
            "label": "My Reservations",
            "iconName": "Boxes",
            "children": []
          },
          {
            "path": "/resource-management/reservations/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/resource-management/resources",
        "label": "Resources",
        "iconName": "Boxes",
        "children": [
          {
            "path": "/resource-management/resources/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/service-requests",
    "label": "Service Requests",
    "iconName": "FileText",
    "children": [
      {
        "path": "/service-requests/all-services",
        "label": "All Services",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/service-requests/analytics",
        "label": "Analytics",
        "iconName": "BarChart",
        "children": []
      },
      {
        "path": "/service-requests/approvals",
        "label": "Approvals",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/service-requests/my-requests",
        "label": "My Requests",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/service-requests/new",
        "label": "New",
        "iconName": "Plus",
        "children": []
      },
      {
        "path": "/service-requests/types",
        "label": "Types",
        "iconName": "FileText",
        "children": [
          {
            "path": "/service-requests/types/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/solutions",
    "label": "Solutions",
    "iconName": "FileText",
    "children": [
      {
        "path": "/solutions/ai-solution-compliance",
        "label": "Ai Solution Compliance",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/solutions/builders",
        "label": "Builders",
        "iconName": "Hammer",
        "children": [
          {
            "path": "/solutions/builders/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/clients",
        "label": "Clients",
        "iconName": "FileText",
        "children": [
          {
            "path": "/solutions/clients/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/content",
        "label": "Content",
        "iconName": "FileText",
        "children": [
          {
            "path": "/solutions/content/deliverables",
            "label": "Deliverables",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/solutions/content/orders",
            "label": "Orders",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/solutions/content/production",
            "label": "Production",
            "iconName": "FileText",
            "children": [
              {
                "path": "/solutions/content/production/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/solutions/content/queue",
            "label": "Queue",
            "iconName": "FileText",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/discovery",
        "label": "Discovery",
        "iconName": "Search",
        "children": [
          {
            "path": "/solutions/discovery/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/earnings",
        "label": "Earnings",
        "iconName": "DollarSign",
        "children": []
      },
      {
        "path": "/solutions/list",
        "label": "List",
        "iconName": "List",
        "children": []
      },
      {
        "path": "/solutions/matlab",
        "label": "Matlab",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/solutions/new",
        "label": "New",
        "iconName": "Plus",
        "children": []
      },
      {
        "path": "/solutions/paradigm-shift",
        "label": "Paradigm Shift",
        "iconName": "FileText",
        "children": [
          {
            "path": "/solutions/paradigm-shift/leaderboard",
            "label": "Leaderboard",
            "iconName": "Trophy",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/payments",
        "label": "Payments",
        "iconName": "Wallet",
        "children": [
          {
            "path": "/solutions/payments/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/pipeline",
        "label": "Pipeline",
        "iconName": "FileText",
        "children": [
          {
            "path": "/solutions/pipeline/analytics",
            "label": "Analytics",
            "iconName": "BarChart",
            "children": []
          },
          {
            "path": "/solutions/pipeline/list",
            "label": "List",
            "iconName": "List",
            "children": []
          },
          {
            "path": "/solutions/pipeline/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/products",
        "label": "Products",
        "iconName": "FileText",
        "children": [
          {
            "path": "/solutions/products/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          },
          {
            "path": "/solutions/products/rdif",
            "label": "Rdif",
            "iconName": "FileText",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/publications",
        "label": "Publications",
        "iconName": "FileText",
        "children": [
          {
            "path": "/solutions/publications/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/settings",
        "label": "Settings",
        "iconName": "Settings",
        "children": [
          {
            "path": "/solutions/settings/types",
            "label": "Types",
            "iconName": "FileText",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/software",
        "label": "Software",
        "iconName": "FileText",
        "children": [
          {
            "path": "/solutions/software/builders",
            "label": "Builders",
            "iconName": "Hammer",
            "children": [
              {
                "path": "/solutions/software/builders/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/solutions/software/phases",
            "label": "Phases",
            "iconName": "FileText",
            "children": []
          }
        ]
      },
      {
        "path": "/solutions/training",
        "label": "Training",
        "iconName": "Dumbbell",
        "children": [
          {
            "path": "/solutions/training/cohort",
            "label": "Cohort",
            "iconName": "Dumbbell",
            "children": [
              {
                "path": "/solutions/training/cohort/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/solutions/training/programs",
            "label": "Programs",
            "iconName": "BookOpen",
            "children": []
          },
          {
            "path": "/solutions/training/sessions",
            "label": "Sessions",
            "iconName": "Dumbbell",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/staff",
    "label": "Staff",
    "iconName": "Users",
    "children": [
      {
        "path": "/staff/category",
        "label": "Category",
        "iconName": "Users",
        "children": [
          {
            "path": "/staff/category/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/staff/class-incharges",
        "label": "Class Incharges",
        "iconName": "Users",
        "children": []
      },
      {
        "path": "/staff/dashboard",
        "label": "Dashboard",
        "iconName": "LayoutGrid",
        "children": []
      },
      {
        "path": "/staff/list",
        "label": "List",
        "iconName": "List",
        "children": [
          {
            "path": "/staff/list/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      }
    ]
  },
  {
    "path": "/startup-studio",
    "label": "Startup Studio",
    "iconName": "FileText",
    "children": [
      {
        "path": "/startup-studio/alumni",
        "label": "Alumni",
        "iconName": "GraduationCap",
        "children": []
      },
      {
        "path": "/startup-studio/analytics",
        "label": "Analytics",
        "iconName": "BarChart",
        "children": []
      },
      {
        "path": "/startup-studio/cycles",
        "label": "Cycles",
        "iconName": "RotateCw",
        "children": [
          {
            "path": "/startup-studio/cycles/new",
            "label": "New",
            "iconName": "Plus",
            "children": []
          }
        ]
      },
      {
        "path": "/startup-studio/events",
        "label": "Events",
        "iconName": "CalendarHeart",
        "children": []
      },
      {
        "path": "/startup-studio/finance",
        "label": "Finance",
        "iconName": "DollarSign",
        "children": []
      },
      {
        "path": "/startup-studio/governance",
        "label": "Governance",
        "iconName": "Building",
        "children": []
      },
      {
        "path": "/startup-studio/kpi",
        "label": "Kpi",
        "iconName": "FileText",
        "children": [
          {
            "path": "/startup-studio/kpi/reports",
            "label": "Reports",
            "iconName": "FileBarChart",
            "children": []
          }
        ]
      },
      {
        "path": "/startup-studio/marketing",
        "label": "Marketing",
        "iconName": "Megaphone",
        "children": []
      },
      {
        "path": "/startup-studio/mentors",
        "label": "Mentors",
        "iconName": "UserCheck",
        "children": []
      },
      {
        "path": "/startup-studio/nif",
        "label": "Nif",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/startup-studio/portfolio",
        "label": "Portfolio",
        "iconName": "Briefcase",
        "children": []
      },
      {
        "path": "/startup-studio/problem-bank",
        "label": "Problem Bank",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/startup-studio/solve-for-100",
        "label": "Solve For 100",
        "iconName": "FileText",
        "children": [
          {
            "path": "/startup-studio/solve-for-100/admin",
            "label": "Admin",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/startup-studio/solve-for-100/dashboard",
            "label": "Dashboard",
            "iconName": "LayoutGrid",
            "children": [
              {
                "path": "/startup-studio/solve-for-100/dashboard/checkin",
                "label": "Checkin",
                "iconName": "FileText",
                "children": []
              }
            ]
          },
          {
            "path": "/startup-studio/solve-for-100/exercises",
            "label": "Exercises",
            "iconName": "FileText",
            "children": [
              {
                "path": "/startup-studio/solve-for-100/exercises/create",
                "label": "Create",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/startup-studio/solve-for-100/leaderboard",
            "label": "Leaderboard",
            "iconName": "Trophy",
            "children": []
          },
          {
            "path": "/startup-studio/solve-for-100/mentor",
            "label": "Mentor",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/startup-studio/solve-for-100/programs",
            "label": "Programs",
            "iconName": "BookOpen",
            "children": []
          }
        ]
      },
      {
        "path": "/startup-studio/submissions",
        "label": "Submissions",
        "iconName": "FileText",
        "children": []
      }
    ]
  },
  {
    "path": "/system",
    "label": "System",
    "iconName": "FileText",
    "children": [
      {
        "path": "/system/api-management",
        "label": "Api Management",
        "iconName": "Code2",
        "children": []
      },
      {
        "path": "/system/attention-bar",
        "label": "Attention Bar",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/system/lti-tools",
        "label": "Lti Tools",
        "iconName": "PlugZap",
        "children": []
      }
    ]
  },
  {
    "path": "/users",
    "label": "Users",
    "iconName": "Users",
    "children": [
      {
        "path": "/users/activity",
        "label": "Activity",
        "iconName": "History",
        "children": []
      },
      {
        "path": "/users/dashboard",
        "label": "Dashboard",
        "iconName": "LayoutGrid",
        "children": []
      },
      {
        "path": "/users/new",
        "label": "New",
        "iconName": "Plus",
        "children": []
      },
      {
        "path": "/users/permissions-audit",
        "label": "Permissions Audit",
        "iconName": "Users",
        "children": []
      },
      {
        "path": "/users/role-management",
        "label": "Role Management",
        "iconName": "Users",
        "children": []
      },
      {
        "path": "/users/roles",
        "label": "Roles",
        "iconName": "Users",
        "children": []
      }
    ]
  },
  {
    "path": "/vac",
    "label": "Vac",
    "iconName": "FileText",
    "children": [
      {
        "path": "/vac/admin",
        "label": "Admin",
        "iconName": "FileText",
        "children": [
          {
            "path": "/vac/admin/analytics",
            "label": "Analytics",
            "iconName": "BarChart",
            "children": []
          },
          {
            "path": "/vac/admin/case",
            "label": "Case",
            "iconName": "FileText",
            "children": [
              {
                "path": "/vac/admin/case/batches",
                "label": "Batches",
                "iconName": "Boxes",
                "children": []
              },
              {
                "path": "/vac/admin/case/readiness",
                "label": "Readiness",
                "iconName": "FileText",
                "children": []
              },
              {
                "path": "/vac/admin/case/tracks",
                "label": "Tracks",
                "iconName": "FileText",
                "children": []
              }
            ]
          },
          {
            "path": "/vac/admin/courses",
            "label": "Courses",
            "iconName": "BookOpen",
            "children": [
              {
                "path": "/vac/admin/courses/new",
                "label": "New",
                "iconName": "Plus",
                "children": []
              }
            ]
          },
          {
            "path": "/vac/admin/enrollments",
            "label": "Enrollments",
            "iconName": "FileText",
            "children": []
          },
          {
            "path": "/vac/admin/settings",
            "label": "Settings",
            "iconName": "Settings",
            "children": []
          }
        ]
      },
      {
        "path": "/vac/case",
        "label": "Case",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/vac/my-courses",
        "label": "My Courses",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/vac/progress",
        "label": "Progress",
        "iconName": "FileText",
        "children": []
      }
    ]
  },
  {
    "path": "/work-pulse",
    "label": "Work Pulse",
    "iconName": "FileText",
    "children": [
      {
        "path": "/work-pulse/agents",
        "label": "Agents",
        "iconName": "FileText",
        "children": []
      },
      {
        "path": "/work-pulse/all",
        "label": "All",
        "iconName": "List",
        "children": []
      },
      {
        "path": "/work-pulse/impact",
        "label": "Impact",
        "iconName": "FileText",
        "children": []
      }
    ]
  }
];
