'use client';

// Let a participant replace the temporary password they were given.
//
// The password they hold was generated by an administrator and read out, texted
// or emailed — so a third party has seen it. This is the only way to get off it:
// /auth/login is Google-only, and the participant login has no self-service
// reset because someone with no email cannot receive one.
//
// Validation here is for the person's benefit; the route re-checks everything
// and, crucially, re-verifies the CURRENT password server-side. Nothing in this
// component is a security control.

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Eye, EyeOff, Loader2 } from 'lucide-react';

import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

const MIN_LENGTH = 8;

/** One password field with a show/hide toggle. Typing a password you cannot see
 *  on a phone keyboard is how people end up locked out of their own account. */
function SecretField({
  id,
  label,
  value,
  onChange,
  autoComplete,
}: {
  id: string;
  label: string;
  value: string;
  onChange: (v: string) => void;
  autoComplete: string;
}) {
  const [shown, setShown] = useState(false);
  return (
    <div className="space-y-1.5">
      <Label htmlFor={id}>{label}</Label>
      <div className="relative">
        <Input
          id={id}
          type={shown ? 'text' : 'password'}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          autoComplete={autoComplete}
          className="pr-10"
        />
        <button
          type="button"
          onClick={() => setShown((s) => !s)}
          aria-label={shown ? `Hide ${label.toLowerCase()}` : `Show ${label.toLowerCase()}`}
          className="absolute right-2 top-1/2 -translate-y-1/2 p-1 text-muted-foreground hover:text-foreground"
        >
          {shown ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
        </button>
      </div>
    </div>
  );
}

/** CONTROLLED. Its trigger lives in the participant menu, so the dialog cannot
 *  own its own open state — a Radix dropdown closes on item select, which would
 *  unmount an uncontrolled trigger before the dialog ever opened. */
export function ChangePasswordDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const router = useRouter();
  const [current, setCurrent] = useState('');
  const [next, setNext] = useState('');
  const [confirm, setConfirm] = useState('');
  const [busy, setBusy] = useState(false);

  const reset = () => {
    setCurrent('');
    setNext('');
    setConfirm('');
  };

  const mismatch = confirm.length > 0 && next !== confirm;
  const tooShort = next.length > 0 && next.length < MIN_LENGTH;
  const canSubmit =
    Boolean(current) && next.length >= MIN_LENGTH && next === confirm && !busy;

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!canSubmit) return;
    setBusy(true);
    try {
      const res = await fetch('/api/auth/participant-password', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ currentPassword: current, newPassword: next }),
      });
      const json = await res.json().catch(() => ({}));

      if (!res.ok || !json?.ok) {
        toast.error(json?.error ?? 'Could not change your password.');
        return;
      }

      reset();
      onOpenChange(false);

      if (json.signedOut) {
        // The change worked but the session could not be re-established, so the
        // next navigation would bounce to login anyway. Send them there with an
        // explanation rather than letting them discover it.
        toast.success('Password changed. Please sign in again with your new password.');
        router.replace('/auth/participant-login');
        return;
      }

      toast.success('Password changed.');
      // The session cookies were rotated server-side; refresh so the client
      // router is not holding the previous ones.
      router.refresh();
    } catch {
      toast.error('Could not reach the server. Please check your connection.');
    } finally {
      setBusy(false);
    }
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        // Never leave typed passwords sitting in state behind a closed dialog.
        if (!o) reset();
        onOpenChange(o);
      }}
    >
      <DialogContent className="max-h-[90vh] max-w-sm overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Change your password</DialogTitle>
          <DialogDescription>
            You sign in with your JKKN ID and this password.
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={submit} className="space-y-4">
          <SecretField
            id="current-password"
            label="Current password"
            value={current}
            onChange={setCurrent}
            autoComplete="current-password"
          />

          <div className="space-y-1.5">
            <SecretField
              id="new-password"
              label="New password"
              value={next}
              onChange={setNext}
              autoComplete="new-password"
            />
            <p className={`text-xs ${tooShort ? 'text-destructive' : 'text-muted-foreground'}`}>
              At least {MIN_LENGTH} characters.
            </p>
          </div>

          <div className="space-y-1.5">
            <SecretField
              id="confirm-password"
              label="Confirm new password"
              value={confirm}
              onChange={setConfirm}
              autoComplete="new-password"
            />
            {mismatch && (
              <p className="text-xs text-destructive">Both new passwords must match.</p>
            )}
          </div>

          <DialogFooter className="flex-col gap-2 sm:flex-row">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={busy}
              className="w-full sm:w-auto"
            >
              Cancel
            </Button>
            <Button type="submit" disabled={!canSubmit} className="w-full sm:w-auto">
              {busy && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Change password
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
