// lib/services/integrations/jicate-booking-provision-service.ts
//
// Auto-provisioning service for Path W. Given a MyJKKN user, ensures they have:
//   1. A Cal.com User on jicate-booking-prod (created via direct DB insert, idempotent on email)
//   2. A per-user Cal.com API key generated + stored encrypted in profiles via CalApiKeyVault
//   3. profiles.cal_user_id populated
//
// Idempotent: if CalApiKeyVault.get() returns a record, returns 'already_provisioned' fast.
//
// Auth invocation point: MyJKKN auth callback / first-page-after-login middleware.
// (Wiring is a separate small PR — this service is shipped in isolation.)
//
// Spec: specs/cal-com-rest-api-for-path-w.md §Provisioning + §Auth Model
//
// Companion services (parallel Phase-1 PRs):
//   - lib/services/integrations/cal-com-api-client.ts  (Agent A) — REST calls
//   - lib/services/integrations/cal-api-key-vault.ts   (Agent B) — encrypted storage
//
// ============================================================================
// API KEY GENERATION — DESIGN DECISION
// ============================================================================
//
// Spec §1a recommends direct DB insert into Cal.com's `users` + `ApiKey` tables
// on jicate-booking-prod (project_ref fkihmsuwruohdgsqvnxg) via Supabase service-role.
//
// We implement that approach here rather than the /v2/api-keys endpoint because:
//   a. The v2 API (separate NestJS app, `jicate-booking-api`) is NOT yet deployed —
//      provisioning must not block on that deployment gate.
//   b. Direct DB insert is atomic: user row + API key row in one CTE, idempotent
//      on email via ON CONFLICT DO UPDATE (no-op).
//   c. The v2 /v2/api-keys module only exposes /refresh — it has no POST-create
//      endpoint for fresh keys (verified: apps/api/v2/src/modules/api-keys/controllers/
//      api-keys.controller.ts).
//
// Trade-off: couples MyJKKN to Cal.com's internal Prisma schema. Mitigated by:
//   - version-pin jicate-booking to v6.2.0 in package.json
//   - daily smoke-test cron: GET /v2/me for one canary user, Sentry-alert on shape change
//     (see specs/cal-com-rest-api-for-path-w.md §Gaps)
//
// ============================================================================
// DB CONNECTION PATTERN
// ============================================================================
//
// jicate-booking-prod Supabase (project_ref fkihmsuwruohdgsqvnxg) connection string
// is separate from MyJKKN's own Supabase. We connect via the direct pooler URL
// (not pgbouncer) because we use a CTE with RETURNING — pgbouncer transaction-mode
// doesn't support multi-statement transactions reliably.
//
// Env var required: CAL_BOOKING_DB_URL
//   Value pattern: postgresql://postgres.fkihmsuwruohdgsqvnxg:<PASSWORD>@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
//   Source: ~/.claude/skills/jicate-booking-deploy/state/secrets.env (DATABASE_DIRECT_URL)
//   NEVER commit this value. Add to Vercel env vars under the MyJKKN project.
//
// ============================================================================
// SQL executed (CTE — single round-trip)
// ============================================================================
//
//   WITH new_user AS (
//     INSERT INTO "users" (email, username, name, "timeZone", "weekStart", locale, theme,
//                          "emailVerified", "createdDate")
//     VALUES ($1, $2, $3, 'Asia/Kolkata', 'Monday', 'en', 'light', NOW(), NOW())
//     ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email   -- no-op, idempotent
//     RETURNING id, email
//   ),
//   new_key AS (
//     INSERT INTO "ApiKey" (id, "userId", note, "hashedKey", "createdAt")
//     SELECT gen_random_uuid()::text, id,
//            'MyJKKN auto-provisioned',
//            encode(digest($4, 'sha256'), 'hex'),
//            NOW()
//     FROM new_user
//     WHERE NOT EXISTS (
//       SELECT 1 FROM "ApiKey" k WHERE k."userId" = (SELECT id FROM new_user)
//         AND k.note = 'MyJKKN auto-provisioned'
//     )
//   )
//   SELECT id FROM new_user;
//
// $1 = email, $2 = username (slugified), $3 = display name, $4 = plaintext API key
//
// The plaintext key is generated by this service (crypto.randomBytes) and returned
// to ensureProvisioned which hands it to CalApiKeyVault.set() for encrypted storage.
// The SHA-256 hash stored in Cal.com's ApiKey table is what Cal.com verifies on
// every API call — it never sees the plaintext. Reference: Cal.com source
// packages/features/ee/api-keys/lib/apiKeys.ts (generateUniqueAPIKey + hashAPIKey).

import crypto from 'crypto';
import { Client as PgClient } from 'pg';

// Sibling Agent A contract — import CalComUser type
// Implementation ships in Agent A's PR; we depend on the interface only.
import type { CalComUser } from '@/lib/services/integrations/cal-com-api-client';

// Sibling Agent B contract — CalApiKeyVault for encrypted storage
// Implementation ships in Agent B's PR; we depend on the interface only.
import { CalApiKeyVault } from '@/lib/services/integrations/cal-api-key-vault';

// ============================================================================
// ENV VALIDATION
// ============================================================================

const ADMIN_API_KEY_ENV = 'CAL_BOOKING_ADMIN_API_KEY';
const CAL_BOOKING_DB_URL_ENV = 'CAL_BOOKING_DB_URL';

function getAdminApiKey(): string {
  const k = process.env[ADMIN_API_KEY_ENV];
  if (!k) {
    throw new Error(
      `[jicate-booking/provision] ${ADMIN_API_KEY_ENV} not configured. ` +
        `Need a Cal.com admin-scoped API key for future REST operations. ` +
        `See specs/cal-com-rest-api-for-path-w.md §Auth Model.`,
    );
  }
  return k;
}

function getCalDbUrl(): string {
  const url = process.env[CAL_BOOKING_DB_URL_ENV];
  if (!url) {
    throw new Error(
      `[jicate-booking/provision] ${CAL_BOOKING_DB_URL_ENV} not configured. ` +
        `Must be set to the direct (non-pgbouncer) connection URL for ` +
        `jicate-booking-prod Supabase (project_ref fkihmsuwruohdgsqvnxg). ` +
        `Value: DATABASE_DIRECT_URL from skills/jicate-booking-deploy/state/secrets.env. ` +
        `Add to Vercel env vars — NEVER commit.`,
    );
  }
  return url;
}

// ============================================================================
// PUBLIC TYPES
// ============================================================================

export interface ProvisionResult {
  /** MyJKKN profiles.id (Supabase auth UUID) */
  myjkkn_user_id: string;
  /** Cal.com numeric User.id */
  cal_user_id: number;
  /** Whether this call created a new Cal.com user + key, or found one already. */
  action: 'already_provisioned' | 'created';
  /** Wall-clock time for the entire operation, in milliseconds. */
  elapsed_ms: number;
}

// ============================================================================
// HELPERS
// ============================================================================

/**
 * Derive a Cal.com-safe username slug from an email address.
 *
 * Cal.com's own slugify function (packages/lib/slugify.ts) lowercases and
 * replaces non-word chars with hyphens. We replicate the minimal variant:
 * strip the domain, lowercase, replace non-alphanumerics with hyphens,
 * collapse multiple hyphens, strip leading/trailing hyphens.
 *
 * Example: "Omm.S@JKKN.ac.in" → "omm-s"
 */
function slugifyEmail(email: string): string {
  const local = email.split('@')[0] ?? email;
  return local
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 32); // Cal.com username max length (Prisma schema)
}

/**
 * Generate a random API key in Cal.com's expected format.
 *
 * Cal.com format (packages/features/ee/api-keys/lib/apiKeys.ts):
 *   "cal_" + 32 random hex chars  (crypto.randomBytes(16).toString("hex"))
 *
 * Returns { plaintext, hashedKey } — only hashedKey is stored on Cal.com's
 * ApiKey table; plaintext goes to CalApiKeyVault.set() for encrypted storage.
 */
function generateApiKey(): { plaintext: string; hashedKey: string } {
  const plaintext = 'cal_' + crypto.randomBytes(16).toString('hex');
  const hashedKey = crypto.createHash('sha256').update(plaintext).digest('hex');
  return { plaintext, hashedKey };
}

// ============================================================================
// SERVICE
// ============================================================================

export class JicateBookingProvisionService {
  /**
   * Ensure the MyJKKN user has a Cal.com User + stored API key.
   *
   * Idempotent — if CalApiKeyVault.get() returns a stored record, this method
   * returns 'already_provisioned' in < 5 ms without touching jicate-booking-prod.
   *
   * On first call:
   *   1. Connects to jicate-booking-prod Supabase via CAL_BOOKING_DB_URL
   *   2. Upserts a row in Cal.com's `users` table (ON CONFLICT DO UPDATE — no-op if
   *      email already exists, e.g. from a prior partial provision or manual admin create)
   *   3. Inserts a row in Cal.com's `ApiKey` table (skipped if note='MyJKKN auto-provisioned'
   *      key already exists for this user — double-idempotency guard)
   *   4. Stores the encrypted plaintext key + cal_user_id in MyJKKN profiles via CalApiKeyVault.set()
   *
   * Throws (never swallows) on:
   *   - Missing env vars
   *   - DB connection failure to jicate-booking-prod
   *   - SQL errors from user/key insert
   *   - CalApiKeyVault.set() failure
   *
   * @param opts.myjkknUserId  MyJKKN profiles.id (Supabase auth UUID)
   * @param opts.email         User's email — used as Cal.com username basis + idempotency key
   * @param opts.name          Display name (optional; falls back to email local-part)
   */
  static async ensureProvisioned(opts: {
    myjkknUserId: string;
    email: string;
    name?: string;
  }): Promise<ProvisionResult> {
    const start = Date.now();

    // ─── Fast path: already provisioned ────────────────────────────────────
    const existing = await CalApiKeyVault.get(opts.myjkknUserId);
    if (existing) {
      return {
        myjkkn_user_id: opts.myjkknUserId,
        cal_user_id: existing.cal_user_id,
        action: 'already_provisioned',
        elapsed_ms: Date.now() - start,
      };
    }

    // ─── Slow path: provision ───────────────────────────────────────────────
    // Generate the random key before opening the DB connection so we can clean
    // up the pg Client in finally{} without key leaking.
    const { plaintext, hashedKey } = generateApiKey();
    const username = slugifyEmail(opts.email);
    const displayName = opts.name ?? opts.email.split('@')[0] ?? opts.email;

    const calUserId = await JicateBookingProvisionService.provisionCalUser({
      email: opts.email,
      username,
      displayName,
      hashedKey,
    });

    // Store encrypted plaintext in MyJKKN profiles via Agent B's vault.
    await CalApiKeyVault.set(opts.myjkknUserId, calUserId, plaintext);

    console.log('[jicate-booking/provision] CREATED', {
      myjkkn_user_id: opts.myjkknUserId,
      cal_user_id: calUserId,
      email: opts.email,
      elapsed_ms: Date.now() - start,
    });

    return {
      myjkkn_user_id: opts.myjkknUserId,
      cal_user_id: calUserId,
      action: 'created',
      elapsed_ms: Date.now() - start,
    };
  }

  /**
   * Insert (or no-op) a Cal.com User + ApiKey row in jicate-booking-prod's DB.
   *
   * Uses a single CTE for atomicity. Idempotent:
   *   - users: ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email (no-op)
   *   - ApiKey: WHERE NOT EXISTS guard prevents duplicate key rows
   *
   * Returns the numeric Cal.com User.id.
   *
   * CONNECTION NOTE: uses CAL_BOOKING_DB_URL (direct, port 5432, not pgbouncer)
   * because the CTE uses RETURNING inside a sub-SELECT, which requires a real
   * connection (pgbouncer transaction-mode silently drops multi-statement CTEs).
   *
   * SQL explained:
   *   new_user CTE  — upsert the Cal.com user row; RETURNING id guarantees we get
   *                   the numeric id whether the row was inserted OR already existed.
   *   new_key CTE   — insert the ApiKey row only if one with note='MyJKKN auto-provisioned'
   *                   doesn't already exist for this userId.
   *   SELECT        — return the id from new_user.
   */
  private static async provisionCalUser(args: {
    email: string;
    username: string;
    displayName: string;
    hashedKey: string;
  }): Promise<number> {
    const pg = new PgClient({ connectionString: getCalDbUrl(), ssl: { rejectUnauthorized: false } });

    try {
      await pg.connect();

      // Single-CTE atomic upsert — see file-level doc block for full SQL
      const result = await pg.query<{ id: number }>(
        `
        WITH new_user AS (
          INSERT INTO "users" (
            email,
            username,
            name,
            "timeZone",
            "weekStart",
            locale,
            theme,
            "emailVerified",
            "createdDate"
          )
          VALUES ($1, $2, $3, 'Asia/Kolkata', 'Monday', 'en', 'light', NOW(), NOW())
          ON CONFLICT (email) DO UPDATE
            SET email = EXCLUDED.email
          RETURNING id, email
        ),
        new_key AS (
          INSERT INTO "ApiKey" (id, "userId", note, "hashedKey", "createdAt")
          SELECT
            gen_random_uuid()::text,
            new_user.id,
            'MyJKKN auto-provisioned',
            $4,
            NOW()
          FROM new_user
          WHERE NOT EXISTS (
            SELECT 1
            FROM "ApiKey" k
            WHERE k."userId" = new_user.id
              AND k.note = 'MyJKKN auto-provisioned'
          )
          RETURNING "userId"
        )
        SELECT id FROM new_user;
        `,
        [args.email, args.username, args.displayName, args.hashedKey],
      );

      const row = result.rows[0];
      if (!row) {
        // This should never happen: ON CONFLICT DO UPDATE always RETURNING a row
        throw new Error(
          `[jicate-booking/provision] provisionCalUser returned no rows ` +
            `for email=${args.email}. Unexpected — CTE RETURNING must yield at least one row.`,
        );
      }

      return row.id;
    } finally {
      // Always close the pg connection — pg Client does NOT auto-release
      await pg.end().catch((err: unknown) => {
        console.warn('[jicate-booking/provision] pg.end() warning', err);
      });
    }
  }

  /**
   * Smoke-test helper: verify a provisioned user's API key still works.
   *
   * Calls GET /v2/me on jicate-booking-api using the stored key.
   * Returns true if the key is valid, false on 401.
   * Throws on network errors or unexpected status codes.
   *
   * Usage: daily canary cron (see spec §Gaps — "smoke-test cron").
   * NOT called from ensureProvisioned() — only for health-check routes.
   *
   * @param apiKeyPlaintext  Decrypted plaintext key from CalApiKeyVault.get()
   */
  static async smokeTestApiKey(apiKeyPlaintext: string): Promise<boolean> {
    const baseUrl =
      process.env.CAL_BOOKING_API_URL ?? 'https://jicate-booking-api.vercel.app';

    const res = await fetch(`${baseUrl}/v2/me`, {
      headers: {
        Authorization: `Bearer ${apiKeyPlaintext}`,
        'cal-api-version': '2024-08-13',
      },
    });

    if (res.status === 401) {
      return false;
    }

    if (!res.ok) {
      const body = await res.text().catch(() => '');
      throw new Error(
        `[jicate-booking/provision] smokeTestApiKey unexpected status ${res.status}: ${body}`,
      );
    }

    return true;
  }
}
