// lib/services/grievance/grievance-service.ts
// ============================================================================
// Grievance Module — PR-A6a (Compliance Unification Program, 6/15)
//
// Client-side service for /accreditation/naac/grievance/* pages.
// Emits NAAC 7.7.1 + UGC grievance evidence via the AFTER-UPDATE trigger
// installed by the companion migration (not implemented in this service).
//
// Not yet implemented here (deferred to A6b / A6c):
//   - Business-day SLA calculator (reads institution_leaves)
//   - PDF generation (acknowledgment + resolution letter)
//   - Supersede-on-withdrawal + auto-reopen on low satisfaction
//   - Federation from hostel_incidents / hostel_maintenance_requests
// ============================================================================

import { createClientSupabaseClient } from '@/lib/supabase/client';
import type {
  GrievanceTicket,
  GrievanceTicketDetail,
  GrievanceCategory,
  GrievanceComment,
  GrievanceStatus,
  GrievancePriority,
  GrievanceDashboardStats,
  CreateGrievanceInput,
} from '@/lib/types/grievance';

export class GrievanceService {
  private static supabase = createClientSupabaseClient();

  /**
   * Paginated list — filters are optional. RLS scopes to the caller's
   * institution (staff policies check institution_id match).
   */
  static async listTickets(params: {
    institutionId?: string;
    status?: GrievanceStatus;
    priority?: GrievancePriority;
    isEmergency?: boolean;
    page?: number;
    limit?: number;
  }): Promise<{ items: GrievanceTicket[]; total: number }> {
    const page = Math.max(1, params.page ?? 1);
    const limit = Math.min(100, Math.max(1, params.limit ?? 20));
    const offset = (page - 1) * limit;

    let query = (this.supabase as any)
      .from('grievance_tickets')
      .select(
        'id, ticket_number, category_id, institution_id, subject, priority, status, ' +
          'raised_by_type, raised_by_name, sla_deadline, sla_status, resolved_at, ' +
          'is_emergency, is_anonymous, escalation_level, created_at',
        { count: 'exact' }
      );

    if (params.institutionId) query = query.eq('institution_id', params.institutionId);
    if (params.status) query = query.eq('status', params.status);
    if (params.priority) query = query.eq('priority', params.priority);
    if (typeof params.isEmergency === 'boolean') query = query.eq('is_emergency', params.isEmergency);

    query = query.order('created_at', { ascending: false }).range(offset, offset + limit - 1);

    const { data, error, count } = await query;
    if (error) throw error;

    return { items: (data ?? []) as GrievanceTicket[], total: count ?? 0 };
  }

  static async getTicket(id: string): Promise<GrievanceTicketDetail> {
    const { data, error } = await (this.supabase as any)
      .from('grievance_tickets')
      .select('*')
      .eq('id', id)
      .single();

    if (error) throw error;
    return data as GrievanceTicketDetail;
  }

  static async getCategories(institutionId: string): Promise<GrievanceCategory[]> {
    const { data, error } = await (this.supabase as any)
      .from('grievance_categories')
      .select('id, name, default_sla_hours, default_assignee_role, is_emergency, attachment_required, default_naac_metric_code, sort_order')
      .eq('institution_id', institutionId)
      .eq('is_active', true)
      .order('sort_order', { ascending: true });

    if (error) throw error;
    return (data ?? []) as GrievanceCategory[];
  }

  /**
   * Creates a new ticket. The ticket_number is generated by the BEFORE-INSERT
   * trigger set_grievance_ticket_number (format: GRV-YYYYMMDD-NNNN).
   *
   * sla_deadline is required by the schema — caller must compute it from the
   * selected category's default_sla_hours. PR-A6b swapped the wall-clock
   * calculation for business-hour calculation via the
   * calculate_grievance_sla_deadline RPC (9am-6pm IST, Mon-Fri, holidays from
   * hr_public_holidays). Use GrievanceService.calculateSlaDeadline() if the
   * caller wants the business-hour deadline; otherwise pass any timestamptz.
   */
  static async createTicket(input: CreateGrievanceInput): Promise<GrievanceTicket> {
    const { data, error } = await (this.supabase as any)
      .from('grievance_tickets')
      .insert({
        institution_id: input.institution_id,
        category_id: input.category_id,
        subject: input.subject,
        description: input.description,
        priority: input.priority ?? 'medium',
        status: 'open',
        raised_by_type: input.raised_by_type,
        raised_by_id: input.raised_by_id ?? null,
        raised_by_name: input.raised_by_name ?? null,
        raised_by_email: input.raised_by_email ?? null,
        raised_by_phone: input.raised_by_phone ?? null,
        is_anonymous: input.is_anonymous ?? false,
        anonymous_token: input.is_anonymous
          ? `anon_${crypto.randomUUID()}`
          : null,
        filed_by: input.filed_by ?? null,
        is_emergency: input.is_emergency ?? false,
        is_icc_only: input.is_icc_only ?? false,
        sla_hours: input.sla_hours,
        sla_deadline: input.sla_deadline,
        metadata: input.metadata ?? {},
      })
      .select('id, ticket_number, category_id, institution_id, subject, priority, status, raised_by_type, raised_by_name, sla_deadline, sla_status, resolved_at, is_emergency, is_anonymous, escalation_level, created_at')
      .single();

    if (error) throw error;
    return data as GrievanceTicket;
  }

  static async updateStatus(
    id: string,
    input: {
      status: GrievanceStatus;
      resolution?: string;
      resolved_by?: string;
    }
  ): Promise<void> {
    const patch: Record<string, unknown> = { status: input.status };
    if (input.status === 'resolved') {
      patch.resolution = input.resolution ?? null;
      patch.resolved_at = new Date().toISOString();
      patch.resolved_by = input.resolved_by ?? null;
    }
    const { error } = await (this.supabase as any)
      .from('grievance_tickets')
      .update(patch)
      .eq('id', id);

    if (error) throw error;
  }

  static async listComments(ticketId: string): Promise<GrievanceComment[]> {
    const { data, error } = await (this.supabase as any)
      .from('grievance_comments')
      .select('id, ticket_id, author_id, author_name, author_type, content, is_internal, created_at')
      .eq('ticket_id', ticketId)
      .order('created_at', { ascending: true });

    if (error) throw error;
    return (data ?? []) as GrievanceComment[];
  }

  static async addComment(input: {
    ticket_id: string;
    content: string;
    author_id?: string;
    author_name: string;
    author_type: 'staff' | 'learner' | 'parent' | 'alumni';
    is_internal?: boolean;
  }): Promise<GrievanceComment> {
    const { data, error } = await (this.supabase as any)
      .from('grievance_comments')
      .insert({
        ticket_id: input.ticket_id,
        content: input.content,
        author_id: input.author_id ?? null,
        author_name: input.author_name,
        author_type: input.author_type,
        is_internal: input.is_internal ?? false,
      })
      .select('id, ticket_id, author_id, author_name, author_type, content, is_internal, created_at')
      .single();

    if (error) throw error;
    return data as GrievanceComment;
  }

  /**
   * Dashboard stats — calls the production function get_grievance_sla_stats.
   * Already exists on prod; returns JSON with breakdowns by status + SLA.
   */
  static async getDashboardStats(institutionId: string): Promise<GrievanceDashboardStats> {
    const { data, error } = await (this.supabase as any).rpc('get_grievance_sla_stats', {
      p_institution_id: institutionId,
    });
    if (error) throw error;
    return data as GrievanceDashboardStats;
  }
}
