/**
 * THE TRIPWIRE FOR A DENYLIST THAT DEFAULTS OPEN.
 *
 * `fn_handover_key_is_blocked` ends in `ELSE false`. Every permission key that
 * matches none of its clauses is HANDABLE — so a key invented by a future PR is
 * handable by default, and nothing in code review is guaranteed to notice. That
 * is the correct default (an allowlist would break the feature every time a
 * module ships) but it needs something that fails loudly.
 *
 * This is that something. It asserts that EVERY key in
 * lib/constants/permissions.ts is explicitly classified in
 * specs/director-desk/handover-key-classification.json, and that each key's
 * recorded classification still matches what the SQL walls actually say.
 *
 * Add a permission key → this test fails until you classify it. Widen or narrow
 * a wall → this test fails until you re-record which keys moved. Either way a
 * human has to look at the list of keys that changed side, which is the entire
 * point.
 *
 * The classification is NOT re-derived from a TypeScript copy of the wall rules.
 * `handover-wall-eval.ts` parses and evaluates the real CASE expression out of
 * the migration file. A test that restates the rules would only prove the author
 * agreed with themselves twice — this repo has already shipped 40 green
 * assertions over a live bug that way.
 *
 * TO UPDATE after a deliberate change:
 *   UPDATE_HANDOVER_CLASSIFICATION=1 npx vitest run __tests__/director-desk
 * then READ the diff on the JSON before committing it. Regenerating without
 * reading it converts this gate back into decoration.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { PERMISSION_CATEGORIES } from '@/lib/constants/permissions';
import { loadWalls, isBlocked, WALL_MIGRATION } from './handover-wall-eval';

const MANIFEST = 'specs/director-desk/handover-key-classification.json';

type Manifest = {
  walled: string[];
  handable: string[];
};

/** Every permission key the platform can grant, from the single source of truth. */
function allPermissionKeys(): string[] {
  const keys: string[] = [];
  for (const category of PERMISSION_CATEGORIES as ReadonlyArray<{
    permissions?: ReadonlyArray<{ key: string }>;
  }>) {
    for (const p of category.permissions ?? []) {
      if (typeof p?.key === 'string' && p.key) keys.push(p.key);
    }
  }
  return [...new Set(keys)].sort();
}

const walls = loadWalls();
const keys = allPermissionKeys();

// Regeneration path. Runs before the assertions so a deliberate update is one
// command, and is inert in CI (the env var is never set there).
if (process.env.UPDATE_HANDOVER_CLASSIFICATION === '1') {
  const next: Manifest = {
    walled: keys.filter((k) => isBlocked(k, walls)),
    handable: keys.filter((k) => !isBlocked(k, walls))
  };
  writeFileSync(
    MANIFEST,
    `${JSON.stringify(
      {
        $comment:
          'Generated by __tests__/director-desk/handover-key-classification.test.ts. ' +
          'Every permission key in lib/constants/permissions.ts, classified against the ' +
          'walls in ' +
          WALL_MIGRATION +
          '. Regenerate with UPDATE_HANDOVER_CLASSIFICATION=1 npx vitest run __tests__/director-desk — ' +
          'then read the diff. A key moving from walled to handable is a security change.',
        ...next
      },
      null,
      2
    )}\n`,
    'utf8'
  );
}

describe('Director handover — every permission key is explicitly classified', () => {
  it('the wall function is still parseable (if this fails, nothing below means anything)', () => {
    expect(walls.clauses.length).toBeGreaterThan(10);
    // The denylist defaults OPEN. If this ever flips to a default-deny the whole
    // premise of this test changes and it should be rewritten, not adjusted.
    expect(walls.fallback).toBe(false);
  });

  it('has a classification manifest', () => {
    expect(
      existsSync(MANIFEST),
      `${MANIFEST} is missing. Generate it with:\n  UPDATE_HANDOVER_CLASSIFICATION=1 npx vitest run __tests__/director-desk`
    ).toBe(true);
  });

  it('classifies every key in lib/constants/permissions.ts — no key is left to the default', () => {
    const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8')) as Manifest;
    const classified = new Set([...manifest.walled, ...manifest.handable]);
    const unclassified = keys.filter((k) => !classified.has(k));

    expect(
      unclassified,
      unclassified.length === 0
        ? ''
        : [
            `${unclassified.length} permission key(s) are not classified against the handover walls.`,
            '',
            'These keys are HANDABLE right now, because fn_handover_key_is_blocked ends in',
            'ELSE false. Decide that on purpose:',
            '  - if the key must never be delegated, add it to a wall in',
            `    ${WALL_MIGRATION};`,
            '  - if it is fine to delegate, record it by running',
            '    UPDATE_HANDOVER_CLASSIFICATION=1 npx vitest run __tests__/director-desk',
            '',
            unclassified.map((k) => `  • ${k}`).join('\n')
          ].join('\n')
    ).toEqual([]);
  });

  it('every recorded classification still matches what the SQL walls say', () => {
    const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8')) as Manifest;
    const walledInManifest = new Set(manifest.walled);

    const drifted = keys
      .filter((k) => walledInManifest.has(k) !== isBlocked(k, walls))
      .map((k) =>
        walledInManifest.has(k)
          ? `  • ${k}  — recorded WALLED, the SQL now lets it through`
          : `  • ${k}  — recorded HANDABLE, the SQL now blocks it`
      );

    expect(
      drifted,
      drifted.length === 0
        ? ''
        : [
            'The walls moved. Every line below is a key that changed side:',
            '',
            ...drifted,
            '',
            'A key going from walled to handable widens what the Director may delegate.',
            'If that is intended, regenerate the manifest and say so in the PR body.'
          ].join('\n')
    ).toEqual([]);
  });

  it('carries no stale keys (a permission that no longer exists must leave the manifest)', () => {
    const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8')) as Manifest;
    const live = new Set(keys);
    const stale = [...manifest.walled, ...manifest.handable].filter((k) => !live.has(k));
    expect(stale).toEqual([]);
  });
});

describe('Director handover — walls that must hold regardless of the manifest', () => {
  // Hard-coded on purpose. Regenerating the manifest can bless anything; these
  // cannot be regenerated away. Each one is a decision from the Director
  // interview, not an implementation detail.
  const MUST_BE_WALLED = [
    // Wall 1 — access control. Every one of these outlives the handover.
    'roles',
    'roles.view',
    'roles.assign',
    'users',
    'users.create',
    'users.edit',
    'users.permissions_audit.view',
    'settings',
    'settings.general.edit',
    'director.handover',
    'director.handover.create',
    'some_module.user_roles.manage',
    'some_module.role.assign',
    // Wall 2 — salary and team-member files.
    'hr.payroll',
    'hr.payroll.view',
    'hr.employees.edit',
    'staff.status_update',
    // Wall 3 — exam marks, both spellings that exist in production.
    'academic.internal-marks.view',
    'academic.internal_marks.edit',
    'academic.course-grades.view',
    // Wall 4 — money movement.
    'billing',
    'billing.payments.create',
    'admission_fees',
    'admission_fees.waive',
    'campus_living.deposits.refund'
  ];

  const MUST_BE_HANDABLE = [
    // The key this entire feature exists for.
    'accreditation.naac.narrative.manage',
    // Verb collision: this is marking ATTENDANCE, not exam marks.
    'academic.attendance.mark',
    // Money REPORTS stay handable — an explicit Director decision.
    'billing.analytics.view',
    'billing.coverage.view',
    'billing.invoices.export',
    'admission_fees.view',
    'admission_fees.read',
    'admission_fees.export',
    // Routine delegated work, deliberately outside wall 2.
    'hr.leave.approve',
    'hr.attendance.view'
  ];

  it.each(MUST_BE_WALLED)('walls %s', (key) => {
    expect(isBlocked(key, walls)).toBe(true);
  });

  it.each(MUST_BE_HANDABLE)('leaves %s handable', (key) => {
    expect(isBlocked(key, walls)).toBe(false);
  });

  it('walls the bare prefix key, not just the dotted children', () => {
    // `LIKE 'prefix.%'` does not match `prefix`. Every wall is written as
    // `p_key = 'prefix' OR p_key LIKE 'prefix.%'` for this reason, and this is
    // the assertion that keeps it that way.
    for (const bare of ['roles', 'users', 'settings', 'billing', 'hr.payroll']) {
      expect(isBlocked(bare, walls), `bare prefix "${bare}" slipped through`).toBe(true);
    }
  });

  it('treats a null or empty key as walled', () => {
    expect(isBlocked(null, walls)).toBe(true);
    expect(isBlocked('', walls)).toBe(true);
  });
});
