/**
 * THE WALL THAT IS NOT KEYED ON A NAME.
 *
 * Defect B4, proven end to end on Postgres 16 before this test existed:
 *
 *   Director hands /organizations/leadership to Bob (a junior team member) at level
 *   `full`. Bob calls fn_set_college_leadership(college,'principal',bob). Its
 *   authorisation is user_has_permission('organizations.leadership.manage'),
 *   which the handover makes true. It DELETEs the sitting Principal's user_roles
 *   row and INSERTs Bob's with is_primary=true, firing sync_primary_role_trigger,
 *   which writes profiles.role='principal'. Day 8, the handover expires. The
 *   user_roles row and profiles.role DO NOT. Bob is permanently Principal and the
 *   real Principal has been stripped.
 *
 * The key crossed every wall because the walls are keyed on names and its name
 * says "organizations", not "rewrites role assignments".
 *
 * This test closes that class rather than that instance: it re-derives, from the
 * SQL, every SECURITY DEFINER function that writes an access table, works out
 * which permission keys authorise it, and FAILS if any of those keys is handable.
 * Add a new role-writing RPC gated on a new key and this goes red until the key
 * is walled — which is the only durable form of the fix.
 *
 * The maintained artifact it produces, specs/director-desk/role-writing-functions.json,
 * is the list SPEC.md points at. Regenerate deliberately with
 *   UPDATE_ROLE_WRITE_SWEEP=1 npx vitest run __tests__/director-desk
 * and READ the diff: a function appearing there is a new way to make somebody
 * permanently powerful.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { loadFunctionDefs, findRoleWriters } from './role-write-sweep';
import { loadWalls, isBlocked, WALL_MIGRATION } from './handover-wall-eval';

const ARTIFACT = 'specs/director-desk/role-writing-functions.json';

const defs = loadFunctionDefs();
const writers = findRoleWriters(defs);
const walls = loadWalls();
const authorisingKeys = [...new Set(writers.flatMap((w) => w.keys))].sort();

if (process.env.UPDATE_ROLE_WRITE_SWEEP === '1') {
  writeFileSync(
    ARTIFACT,
    `${JSON.stringify(
      {
        $comment:
          'Generated by __tests__/director-desk/role-write-sweep.test.ts. Every SECURITY ' +
          'DEFINER function in supabase/ whose body writes user_roles, custom_roles, ' +
          'profiles.role, profiles.is_super_admin or user_institution_access, with the ' +
          'permission keys that authorise it. Every key listed under ' +
          'keysAuthorisingRoleWrites MUST be walled in ' +
          WALL_MIGRATION +
          '. Regenerate with UPDATE_ROLE_WRITE_SWEEP=1 npx vitest run __tests__/director-desk ' +
          'and read the diff — a new entry is a new way to make somebody permanently powerful.',
        functionsScanned: defs.size,
        roleWritingSecdefFunctions: writers.length,
        keysAuthorisingRoleWrites: authorisingKeys,
        functions: writers
      },
      null,
      2
    )}\n`,
    'utf8'
  );
}

describe('Director handover — no handable key may authorise a role write', () => {
  it('the sweep actually found something (a silent zero here would pass everything below)', () => {
    // Non-vacuity guard. If the parser breaks, or supabase/setup stops carrying
    // function bodies, every assertion after this becomes true-by-emptiness —
    // the exact shape of a vacuous pass this repo has shipped before.
    expect(defs.size, 'parsed zero SQL function definitions').toBeGreaterThan(500);
    expect(
      writers.length,
      'parsed zero SECURITY DEFINER functions that write an access table'
    ).toBeGreaterThan(3);
    // Both of these are in supabase/setup/02_functions.sql and are not going
    // anywhere. If they stop being found, the sweep is broken, not the repo.
    expect(writers.map((w) => w.name)).toContain('assign_counselor_role');
    expect(writers.map((w) => w.name)).toContain('mirror_staff_role_to_user_roles');
  });

  it('every permission key that authorises a role write is WALLED', () => {
    const escapes = authorisingKeys
      .filter((k) => !isBlocked(k, walls))
      .map((k) => {
        const via = writers.filter((w) => w.keys.includes(k)).map((w) => w.name);
        return `  • ${k}  — authorises ${via.join(', ')}`;
      });

    expect(
      escapes,
      escapes.length === 0
        ? ''
        : [
            'These permission keys are HANDABLE and they authorise a write to an access table.',
            'A handover of one of them grants a role, and a role OUTLIVES the handover —',
            'which breaks decision 4 (access ends on done or due date) at its root.',
            '',
            ...escapes,
            '',
            `Wall each of them in ${WALL_MIGRATION}, then regenerate both artifacts:`,
            '  UPDATE_ROLE_WRITE_SWEEP=1 UPDATE_HANDOVER_CLASSIFICATION=1 npx vitest run __tests__/director-desk'
          ].join('\n')
    ).toEqual([]);
  });

  it('the maintained artifact SPEC.md points at exists and is current', () => {
    expect(
      existsSync(ARTIFACT),
      `${ARTIFACT} is missing. Generate it with:\n  UPDATE_ROLE_WRITE_SWEEP=1 npx vitest run __tests__/director-desk`
    ).toBe(true);

    const recorded = JSON.parse(readFileSync(ARTIFACT, 'utf8')) as {
      keysAuthorisingRoleWrites: string[];
      functions: { name: string }[];
    };

    expect(
      recorded.keysAuthorisingRoleWrites,
      'the recorded key list no longer matches what the SQL says'
    ).toEqual(authorisingKeys);

    expect(
      recorded.functions.map((f) => f.name).sort(),
      'a role-writing function appeared or disappeared — read the diff before regenerating'
    ).toEqual(writers.map((w) => w.name).sort());
  });

  it('the three keys the 2026-08-05 sweep found are still walled by name', () => {
    // Hard-coded so regenerating the artifact cannot bless them away. Each one
    // is a measured escalation path, not a precaution.
    //   organizations.leadership.manage -> fn_set_college_leadership (principal)
    //   admission.counselors.create     -> assign_counselor_role (counselor is
    //                                      institution_scope='all' — a cluster-wide role)
    //   staff.create                    -> mirror_staff_role_to_user_roles
    for (const key of [
      'organizations.leadership.manage',
      'admission.counselors.create',
      'staff.create'
    ]) {
      expect(isBlocked(key, walls), `${key} authorises a role write and must stay walled`).toBe(
        true
      );
    }
  });
});
