import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { BosTaDaClaim, BosClaimStatus } from '@/types/bos';
import { BosTaDaService, UpdateTaDaClaimDto } from '@/lib/services/bos/bos-ta-da-service';
import { QUERY_CONFIG } from '@/lib/config/query-config';

export const bosTaDaKeys = {
  all: ['bos-ta-da'] as const,
  byMeeting: (meetingId: string) => [...bosTaDaKeys.all, 'meeting', meetingId] as const,
  byInstitution: (institutionsId: string) =>
    [...bosTaDaKeys.all, 'institution', institutionsId] as const,
};

export function useBosTaDaClaims(params: {
  meetingId?: string;
  institutionsId?: string;
  /** CAS-expanded sibling UUIDs from useBosInstitutionScope — sent as CSV. */
  institutionsIds?: string[];
  boardId?: string;
  claimStatus?: BosClaimStatus;
  /**
   * Allow the query to run even when no institutionsId/meetingId is supplied.
   * Set true for super-admins viewing "All Institutions" — the server still
   * enforces scope, so an empty filter is safe.
   */
  enabled?: boolean;
}) {
  const hasNarrowingFilter = !!(
    params.meetingId ||
    params.institutionsId ||
    (params.institutionsIds && params.institutionsIds.length > 0) ||
    params.boardId
  );
  return useQuery<BosTaDaClaim[], Error>({
    queryKey: [...bosTaDaKeys.all, params],
    queryFn: () => BosTaDaService.getClaims(params),
    enabled: params.enabled ?? hasNarrowingFilter,
    ...QUERY_CONFIG.SEMI_STABLE_DATA,
  });
}

/**
 * Edit a TA/DA claim (bank/NEFT details, payment status, notes).
 *
 * Note: create/delete hooks were removed on 2026-05-21 — claims are now
 * auto-generated by the attendance route (POST /api/bos/meetings/[id]/attendance)
 * and auto-deleted when attendance flips to non-present. Manual lifecycle
 * management has been retired in favour of SOP-aligned auto-flow.
 */
export function useUpdateBosTaDaClaim() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateTaDaClaimDto }) =>
      BosTaDaService.updateClaim(id, data),
    onSuccess: (updated) => {
      queryClient.invalidateQueries({
        queryKey: bosTaDaKeys.byMeeting(updated.meeting_id),
      });
      queryClient.invalidateQueries({ queryKey: bosTaDaKeys.all });
    },
  });
}
