/**
 * supabase/setup/0[1-4] must carry the grievance migration exactly
 * (20271010020000_grievance_sla_escalation.sql). Hand copies drifted once — a
 * review found round-1 rules in setup while the migration had moved on — so
 * the setup region is generated by supabase/tests/grievance/mirror_setup.py,
 * and this fails CI when someone edits one side without the other.
 */
import { describe, it, expect } from 'vitest';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';

const ROOT = join(__dirname, '..', '..');

describe('grievance setup mirror', () => {
  it('supabase/setup is in step with the migration', () => {
    const r = spawnSync('python3', ['-I', join(ROOT, 'supabase/tests/grievance/mirror_setup.py'), '--check'], {
      cwd: ROOT,
      encoding: 'utf8',
    });
    expect(r.error, 'python3 must be available to run the mirror check').toBeUndefined();
    expect(r.stderr).toBe('');
    expect(r.status).toBe(0);
  });
});
