'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ContentLayout } from '@/components/layout/content-layout';
import { PageBreadcrumb } from '@/components/navigation';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/hooks/use-auth';
import { useIssueGatePass } from '@/hooks/campus-living/use-gate-passes';
import { useLearnerHostelites } from '@/hooks/campus-living/use-learner-hostelites';
import { ArrowLeft, Save, Loader2, DoorOpen } from 'lucide-react';

/**
 * navMeta — invoked from the parent listing page via the "Issue Gate Pass"
 * button (BUG-003897). Required by `scripts/assert-nav-coverage.mjs`.
 */
export const navMeta = {
  invokedFrom: '/campus-living/gate-passes',
} as const;

const passTypeOptions = [
  { value: 'regular_out', label: 'Regular (day-out)' },
  { value: 'overnight', label: 'Overnight' },
  { value: 'emergency', label: 'Emergency' },
  { value: 'visitor_accompanied', label: 'Visitor Accompanied' },
];

export default function IssueGatePassPage() {
  const router = useRouter();
  const { profile } = useAuth();
  const issuePass = useIssueGatePass();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const institutionId = profile?.institution_id ?? '';
  const { data: hostelites, isLoading: hostelitesLoading } =
    useLearnerHostelites(institutionId);

  const [formData, setFormData] = useState({
    learner_id: '',
    pass_type: 'regular_out' as
      | 'regular_out'
      | 'overnight'
      | 'emergency'
      | 'visitor_accompanied',
    destination: '',
    expected_return: '',
  });

  const handleChange = (key: keyof typeof formData, value: string) => {
    setFormData((prev) => ({ ...prev, [key]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!profile?.institution_id) return;
    if (!profile?.id) return;
    if (!formData.learner_id) return;
    // destination and expected_return are both NOT NULL on hostel_gate_passes.
    if (!formData.destination.trim() || !formData.expected_return) return;

    setIsSubmitting(true);
    try {
      // Every key below is a real column on hostel_gate_passes. This page
      // previously posted `purpose`, `valid_from`, `valid_to` and `notes` —
      // none of which exist on the table — and omitted the NOT NULL
      // `expected_return` and `approved_by`, so the insert died on PGRST204
      // and then 23502 and the table stayed permanently empty.
      //
      // `out_time` is deliberately NOT set here: it is the moment the learner
      // physically leaves, which the guard records at the gate via
      // recordExit(). Issuing a pass is not the same event as walking out.
      // pass_number, qr_code and status are generated by generateGatePass().
      await issuePass.mutateAsync({
        institution_id: profile.institution_id,
        learner_id: formData.learner_id,
        pass_type: formData.pass_type,
        destination: formData.destination.trim(),
        expected_return: new Date(formData.expected_return).toISOString(),
        approved_by: profile.id,
      } as never);
      router.push('/campus-living/gate-passes');
    } catch {
      // toast handled by the hook's onError
    } finally {
      setIsSubmitting(false);
    }
  };

  const learners = ((hostelites as { data?: unknown[] } | undefined)?.data ?? []) as Array<{
    id: string;
    first_name: string | null;
    last_name: string | null;
    roll_number: string | null;
  }>;

  return (
    <ContentLayout title="Issue Gate Pass">
      <PageBreadcrumb
        items={[
          { label: 'Home', href: '/' },
          { label: 'Campus Living', href: '/campus-living' },
          { label: 'Gate Passes', href: '/campus-living/gate-passes' },
          { label: 'New' },
        ]}
      />

      <div className="space-y-6 mt-4">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={() => router.back()}>
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back
          </Button>
          <div>
            <h1 className="text-2xl font-bold py-1">Issue New Gate Pass</h1>
            <p className="text-sm text-muted-foreground">
              Record a hostel resident leaving the campus. The pass number
              and QR code are generated automatically on submit.
            </p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Resident */}
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Resident</CardTitle>
              <CardDescription>
                Pick the hostel resident this pass is for.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                <Label htmlFor="learner_id">Resident *</Label>
                <select
                  id="learner_id"
                  required
                  value={formData.learner_id}
                  onChange={(e) => handleChange('learner_id', e.target.value)}
                  disabled={hostelitesLoading}
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background"
                >
                  <option value="">
                    {hostelitesLoading
                      ? 'Loading residents…'
                      : learners.length === 0
                        ? 'No residents available — allocate residents first'
                        : 'Select a resident'}
                  </option>
                  {learners.map((l) => {
                    const name =
                      `${l.first_name ?? ''} ${l.last_name ?? ''}`.trim() ||
                      'Unnamed';
                    return (
                      <option key={l.id} value={l.id}>
                        {name}
                        {l.roll_number ? ` — ${l.roll_number}` : ''}
                      </option>
                    );
                  })}
                </select>
              </div>
            </CardContent>
          </Card>

          {/* Pass details */}
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Pass Details</CardTitle>
              <CardDescription>
                Type, destination and when the learner is due back.
              </CardDescription>
            </CardHeader>
            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="pass_type">Pass Type *</Label>
                <select
                  id="pass_type"
                  required
                  value={formData.pass_type}
                  onChange={(e) => handleChange('pass_type', e.target.value)}
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background"
                >
                  {passTypeOptions.map((o) => (
                    <option key={o.value} value={o.value}>
                      {o.label}
                    </option>
                  ))}
                </select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="destination">Destination *</Label>
                <Input
                  id="destination"
                  required
                  placeholder="e.g., Salem, parental home"
                  value={formData.destination}
                  onChange={(e) => handleChange('destination', e.target.value)}
                />
              </div>
              <div className="space-y-2 md:col-span-2">
                <Label htmlFor="expected_return">Expected Return *</Label>
                <Input
                  id="expected_return"
                  type="datetime-local"
                  required
                  value={formData.expected_return}
                  onChange={(e) =>
                    handleChange('expected_return', e.target.value)
                  }
                />
                <p className="text-xs text-muted-foreground">
                  When the learner is due back. The actual time they leave is
                  recorded by security at the gate, not set here.
                </p>
              </div>
            </CardContent>
          </Card>

          <div className="flex justify-end gap-2">
            <Button
              type="button"
              variant="ghost"
              onClick={() => router.back()}
              disabled={isSubmitting}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={
                isSubmitting ||
                !formData.learner_id ||
                !formData.destination.trim() ||
                !formData.expected_return
              }
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Issuing…
                </>
              ) : (
                <>
                  <DoorOpen className="mr-2 h-4 w-4" />
                  Issue Gate Pass
                </>
              )}
            </Button>
          </div>
        </form>
      </div>
    </ContentLayout>
  );
}
