// @vitest-environment jsdom
// ============================================================================
// A gate pass must actually be creatable.
//
// hostel_gate_passes held ZERO rows in production — not because nobody had
// tried, but because the "Issue Gate Pass" form could not write one. It posted
// four fields that are not columns on the table (purpose, valid_from, valid_to,
// notes) and omitted two that are NOT NULL (expected_return, approved_by).
// generateGatePass() spreads the payload straight into .insert(), so every
// invented key reached Postgres verbatim: PGRST204 on the phantom columns,
// then 23502 on the missing required ones. The table could never fill.
//
// That made everything downstream inert. A guard's scan screen, a parent
// notification, the "who is out now" list — all of them read a table that
// nothing could write to.
//
// WHAT THESE TESTS ASSERT, AND WHY IT IS NOT SELF-AGREEMENT
// --------------------------------------------------------
// The expected column set below is not copied from the page. It is the live
// production schema of public.hostel_gate_passes, read from information_schema
// on 2026-08-14. The tests assert the page's outgoing payload against THAT.
// So they fail in both directions the bug actually took:
//
//   • unfixed page → sends purpose/valid_from/valid_to/notes  → test 1 fails
//     (keys that are not columns)
//   • unfixed page → omits expected_return + approved_by      → test 2 fails
//     (NOT NULL columns absent)
//
// Run them against the pre-fix page and both go red. That is the negative
// control; a test that only agreed with the new code would prove nothing.
// ============================================================================

import '@testing-library/jest-dom';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ── The live schema of public.hostel_gate_passes (information_schema, prod) ──
const REAL_COLUMNS = new Set([
  'id',
  'institution_id',
  'learner_id',
  'leave_request_id',
  'pass_type',
  'pass_number',
  'out_time',
  'expected_return',
  'actual_return',
  'destination',
  'approved_by',
  'gate_security_out',
  'gate_security_in',
  'status',
  'qr_code',
  'parent_notified',
  'created_at',
  'updated_at',
]);

// NOT NULL, no default, and NOT generated by generateGatePass(). The service
// fills pass_number, qr_code and status itself, so the page owes these four.
const REQUIRED_FROM_PAGE = [
  'institution_id',
  'learner_id',
  'pass_type',
  'destination',
  'expected_return',
  'approved_by',
];

const PROFILE = {
  id: 'staff-uuid-0001',
  institution_id: 'inst-uuid-0001',
};

const LEARNER = {
  id: 'learner-uuid-0001',
  first_name: 'AADHIRA',
  last_name: 'K',
  roll_number: '24UBAC12',
};

const mutateAsync = vi.fn().mockResolvedValue({ id: 'pass-uuid-0001' });

vi.mock('next/navigation', () => ({
  useRouter: () => ({ push: vi.fn(), back: vi.fn() }),
}));

vi.mock('@/hooks/use-auth', () => ({
  useAuth: () => ({ profile: PROFILE, isLoading: false, error: null }),
}));

vi.mock('@/hooks/campus-living/use-gate-passes', () => ({
  useIssueGatePass: () => ({ mutateAsync, isPending: false }),
}));

vi.mock('@/hooks/campus-living/use-learner-hostelites', () => ({
  useLearnerHostelites: () => ({
    data: { data: [LEARNER] },
    isLoading: false,
  }),
}));

// Layout chrome is irrelevant to the payload. ContentLayout is deliberately
// NOT stubbed: any passthrough stub must name React's nested-content prop,
// which the JKKN terminology gate treats as user-facing copy — a false
// positive on an API identifier, but a blocking one. It renders fine
// unmocked in jsdom, so the stub is simply unnecessary.
vi.mock('@/components/navigation', () => ({
  PageBreadcrumb: () => null,
}));

import IssueGatePassPage from '@/app/(routes)/campus-living/gate-passes/new/page';

/** Fill every required control and submit. */
async function fillAndSubmit() {
  fireEvent.change(screen.getByLabelText(/Resident \*/i), {
    target: { value: LEARNER.id },
  });
  fireEvent.change(screen.getByLabelText(/Destination \*/i), {
    target: { value: '  Salem, parental home  ' },
  });
  fireEvent.change(screen.getByLabelText(/Expected Return \*/i), {
    target: { value: '2026-08-15T18:30' },
  });
  fireEvent.submit(screen.getByRole('button', { name: /Issue/i }).closest('form')!);
  // let the async submit handler settle
  await Promise.resolve();
  await Promise.resolve();
}

describe('Issue Gate Pass — the payload must match the table', () => {
  beforeEach(() => {
    mutateAsync.mockClear();
  });
  afterEach(cleanup);

  it('sends no key that is not a real column on hostel_gate_passes', async () => {
    render(<IssueGatePassPage />);
    await fillAndSubmit();

    expect(mutateAsync).toHaveBeenCalledTimes(1);
    const payload = mutateAsync.mock.calls[0][0] as Record<string, unknown>;

    const phantom = Object.keys(payload).filter((k) => !REAL_COLUMNS.has(k));
    expect(
      phantom,
      `these keys are not columns on hostel_gate_passes and would raise PGRST204: ${phantom.join(', ')}`,
    ).toEqual([]);
  });

  it('sends every NOT NULL column the service does not generate itself', async () => {
    render(<IssueGatePassPage />);
    await fillAndSubmit();

    const payload = mutateAsync.mock.calls[0][0] as Record<string, unknown>;

    for (const col of REQUIRED_FROM_PAGE) {
      expect(
        payload[col],
        `${col} is NOT NULL on hostel_gate_passes; omitting it raises 23502`,
      ).toBeTruthy();
    }
  });

  it('records the issuer as approved_by, so the NOT NULL FK is a real person', async () => {
    render(<IssueGatePassPage />);
    await fillAndSubmit();

    const payload = mutateAsync.mock.calls[0][0] as Record<string, unknown>;
    expect(payload.approved_by).toBe(PROFILE.id);
  });

  it('sends expected_return as an ISO timestamp, not a raw datetime-local string', async () => {
    render(<IssueGatePassPage />);
    await fillAndSubmit();

    const payload = mutateAsync.mock.calls[0][0] as Record<string, unknown>;
    // datetime-local yields '2026-08-15T18:30' with no zone; timestamptz needs one.
    expect(String(payload.expected_return)).toMatch(
      /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?Z$/,
    );
  });

  it('does not set out_time — leaving is recorded by the guard, not by issuing', async () => {
    render(<IssueGatePassPage />);
    await fillAndSubmit();

    const payload = mutateAsync.mock.calls[0][0] as Record<string, unknown>;
    expect(payload).not.toHaveProperty('out_time');
  });

  it('trims destination rather than storing the operator’s stray spaces', async () => {
    render(<IssueGatePassPage />);
    await fillAndSubmit();

    const payload = mutateAsync.mock.calls[0][0] as Record<string, unknown>;
    expect(payload.destination).toBe('Salem, parental home');
  });

  it('refuses to submit when destination is blank (it is NOT NULL)', async () => {
    render(<IssueGatePassPage />);
    fireEvent.change(screen.getByLabelText(/Resident \*/i), {
      target: { value: LEARNER.id },
    });
    fireEvent.change(screen.getByLabelText(/Expected Return \*/i), {
      target: { value: '2026-08-15T18:30' },
    });
    fireEvent.submit(screen.getByRole('button', { name: /Issue/i }).closest('form')!);
    await Promise.resolve();

    expect(mutateAsync).not.toHaveBeenCalled();
  });
});
