'use client';

/**
 * /campus-living/maintenance/preventive/tasks — PM Tasks list
 *
 * Wired 2026-05-20 (Agent ξ). Replaces ComingSoon. Reads
 * `hostel_pm_tasks` (existing on prod) — these rows are auto-generated by
 * the upstream scheduler when an active schedule's next_run_at fires.
 *
 * Filters: status, schedule_id (from the URL ?schedule_id= query so the
 * parent /preventive page can deep-link), block_id (from a select), and
 * free-text title search. Each row has a Complete action that opens a
 * dialog for notes + actual cost.
 *
 * Permission gate: ANY hostel-warden / admin can read; complete requires
 * being the assigned tech or carrying campus_living.maintenance.complete /
 * super_admin. UI shows the button to everyone; RLS enforces server-side.
 */

import { useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import {
  ListChecks,
  Search,
  Loader2,
  ArrowLeft,
  CheckCircle2,
  AlertTriangle,
  Clock,
  CircleDashed,
  Info,
} from 'lucide-react';
import { ContentLayout } from '@/components/layout/content-layout';
import { PageBreadcrumb } from '@/components/navigation';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { useAuth } from '@/hooks/use-auth';
import {
  useCompleteHostelPmTask,
  useHostelPmTasks,
} from '@/hooks/campus-living/use-hostel-preventive-maintenance';
import type {
  HostelPmTask,
  HostelPmTaskStatus,
} from '@/types/campus-living/community';

export const navMeta = {
  invokedFrom: '/campus-living/maintenance/preventive',
} as const;

const STATUS_FILTERS: { value: 'all' | 'open_set' | HostelPmTaskStatus; label: string }[] = [
  { value: 'all', label: 'All' },
  { value: 'open_set', label: 'Open (active)' },
  { value: 'open', label: 'Open' },
  { value: 'assigned', label: 'Assigned' },
  { value: 'in_progress', label: 'In progress' },
  { value: 'pending_verification', label: 'Pending verification' },
  { value: 'resolved', label: 'Resolved' },
  { value: 'closed', label: 'Closed' },
  { value: 'reopened', label: 'Reopened' },
];

const STATUS_BADGE: Record<
  HostelPmTaskStatus,
  { className: string; label: string }
> = {
  open: { className: 'bg-blue-100 text-blue-800', label: 'Open' },
  assigned: { className: 'bg-indigo-100 text-indigo-800', label: 'Assigned' },
  in_progress: { className: 'bg-amber-100 text-amber-800', label: 'In progress' },
  pending_verification: {
    className: 'bg-violet-100 text-violet-800',
    label: 'Pending verification',
  },
  resolved: { className: 'bg-green-100 text-green-800', label: 'Resolved' },
  closed: { className: 'bg-slate-100 text-slate-700', label: 'Closed' },
  reopened: { className: 'bg-red-100 text-red-800', label: 'Reopened' },
};

const PRIORITY_BADGE: Record<string, string> = {
  critical: 'bg-red-100 text-red-800',
  high: 'bg-orange-100 text-orange-800',
  medium: 'bg-yellow-100 text-yellow-800',
  low: 'bg-slate-100 text-slate-700',
};

function daysFromToday(dateStr: string | null | undefined): number | null {
  if (!dateStr) return null;
  const target = new Date(dateStr).getTime();
  if (Number.isNaN(target)) return null;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return Math.round((target - today.getTime()) / (1000 * 60 * 60 * 24));
}

function dueLabel(dateStr: string | null | undefined): {
  text: string;
  icon: React.ReactNode;
  className: string;
} {
  const d = daysFromToday(dateStr);
  if (d === null) {
    return {
      text: '—',
      icon: <CircleDashed className="mr-1 h-3 w-3" />,
      className: 'bg-slate-100 text-slate-700',
    };
  }
  if (d < 0) {
    return {
      text: `Overdue ${Math.abs(d)}d`,
      icon: <AlertTriangle className="mr-1 h-3 w-3" />,
      className: 'bg-red-100 text-red-800',
    };
  }
  if (d === 0) {
    return {
      text: 'Due today',
      icon: <Clock className="mr-1 h-3 w-3" />,
      className: 'bg-amber-100 text-amber-800',
    };
  }
  if (d <= 7) {
    return {
      text: `Due in ${d}d`,
      icon: <Clock className="mr-1 h-3 w-3" />,
      className: 'bg-amber-100 text-amber-800',
    };
  }
  return {
    text: `In ${d}d`,
    icon: <CheckCircle2 className="mr-1 h-3 w-3" />,
    className: 'bg-green-100 text-green-800',
  };
}

const OPEN_STATUSES: HostelPmTaskStatus[] = [
  'open',
  'assigned',
  'in_progress',
  'pending_verification',
  'reopened',
];

export default function CampusLivingPreventiveMaintenanceTasksPage() {
  const { profile } = useAuth();
  const institutionId = profile?.institution_id ?? undefined;
  const searchParams = useSearchParams();
  const scheduleFilter = searchParams?.get('schedule_id') ?? undefined;

  const [statusFilter, setStatusFilter] = useState<'all' | 'open_set' | HostelPmTaskStatus>(
    'open_set',
  );
  const [search, setSearch] = useState('');

  const filters = useMemo(() => {
    const f: Record<string, unknown> = {};
    if (statusFilter === 'open_set') f.status = OPEN_STATUSES;
    else if (statusFilter !== 'all') f.status = statusFilter;
    if (scheduleFilter) f.schedule_id = scheduleFilter;
    if (search.trim()) f.search = search.trim();
    return f;
  }, [statusFilter, scheduleFilter, search]);

  const { data: tasks = [], isLoading, isError, error } = useHostelPmTasks(
    institutionId,
    filters as Parameters<typeof useHostelPmTasks>[1],
  );

  const stats = useMemo(() => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    let open = 0;
    let overdue = 0;
    let dueThisWeek = 0;
    let resolvedThisMonth = 0;
    const monthStart = new Date(today.getFullYear(), today.getMonth(), 1);
    const weekAhead = new Date(today);
    weekAhead.setDate(weekAhead.getDate() + 7);

    for (const t of tasks) {
      if (
        ['open', 'assigned', 'in_progress', 'pending_verification', 'reopened'].includes(
          t.status,
        )
      ) {
        open += 1;
        const due = t.due_date ? new Date(t.due_date) : null;
        if (due && due.getTime() < today.getTime()) overdue += 1;
        else if (due && due.getTime() <= weekAhead.getTime()) dueThisWeek += 1;
      }
      if (
        (t.status === 'resolved' || t.status === 'closed') &&
        t.completed_at
      ) {
        const c = new Date(t.completed_at);
        if (c.getTime() >= monthStart.getTime()) resolvedThisMonth += 1;
      }
    }
    return { open, overdue, dueThisWeek, resolvedThisMonth };
  }, [tasks]);

  // ── Complete dialog state ────────────────────────────────────────────
  const [completing, setCompleting] = useState<HostelPmTask | null>(null);
  const [notes, setNotes] = useState('');
  const [cost, setCost] = useState('');
  const completeMut = useCompleteHostelPmTask();

  const handleConfirmComplete = async () => {
    if (!completing) return;
    const parsedCost = cost.trim() ? Number.parseFloat(cost) : null;
    try {
      await completeMut.mutateAsync({
        id: completing.id,
        completedBy: profile?.id ?? null,
        payload: {
          completion_notes: notes.trim() || null,
          cost_actual:
            parsedCost !== null && Number.isFinite(parsedCost) ? parsedCost : null,
        },
      });
      setCompleting(null);
      setNotes('');
      setCost('');
    } catch {
      // hook toast handles
    }
  };

  return (
    <ContentLayout title="PM Tasks">
      <PageBreadcrumb
        items={[
          { label: 'Home', href: '/' },
          { label: 'Campus Living', href: '/campus-living' },
          { label: 'Maintenance', href: '/campus-living/maintenance' },
          {
            label: 'Preventive Maintenance',
            href: '/campus-living/maintenance/preventive',
          },
          { label: 'Tasks' },
        ]}
      />

      <div className="space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <Link href="/campus-living/maintenance/preventive">
              <Button variant="ghost" size="sm" className="-ml-3 mb-1">
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back to Preventive Maintenance
              </Button>
            </Link>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <ListChecks className="h-6 w-6 text-primary" />
              PM Tasks
            </h1>
            <p className="text-muted-foreground">
              Auto-generated tasks from active preventive-maintenance
              schedules. Reads <code>hostel_pm_tasks</code>.
              {scheduleFilter ? (
                <span className="ml-1">
                  Filtered to schedule{' '}
                  <code className="text-xs">{scheduleFilter.slice(0, 8)}</code>.
                </span>
              ) : null}
            </p>
          </div>
        </div>

        {!institutionId ? (
          <Alert>
            <Info className="h-4 w-4" />
            <AlertTitle>Pick an institution</AlertTitle>
            <AlertDescription>
              PM tasks are scoped per-institution. Super admins must switch
              into an institution context to view tasks.
            </AlertDescription>
          </Alert>
        ) : null}

        {/* Stats */}
        <div className="grid gap-4 grid-cols-2 sm:grid-cols-4">
          <Card>
            <CardContent className="p-4 text-center">
              <p className="text-xs text-muted-foreground">Open</p>
              <p className="text-2xl font-bold">{stats.open}</p>
            </CardContent>
          </Card>
          <Card className="border-amber-200 bg-amber-50/30">
            <CardContent className="p-4 text-center">
              <p className="text-xs text-amber-600">Due This Week</p>
              <p className="text-2xl font-bold text-amber-700">
                {stats.dueThisWeek}
              </p>
            </CardContent>
          </Card>
          <Card className="border-red-200 bg-red-50/30">
            <CardContent className="p-4 text-center">
              <p className="text-xs text-red-600">Overdue</p>
              <p className="text-2xl font-bold text-red-700">{stats.overdue}</p>
            </CardContent>
          </Card>
          <Card className="border-green-200 bg-green-50/30">
            <CardContent className="p-4 text-center">
              <p className="text-xs text-green-600">Resolved This Month</p>
              <p className="text-2xl font-bold text-green-700">
                {stats.resolvedThisMonth}
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Filters */}
        <Card>
          <CardContent className="p-4">
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search by title…"
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="pl-9"
                />
              </div>
              <Select
                value={statusFilter}
                onValueChange={(v) =>
                  setStatusFilter(v as 'all' | 'open_set' | HostelPmTaskStatus)
                }
              >
                <SelectTrigger className="w-full sm:w-[220px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {STATUS_FILTERS.map((f) => (
                    <SelectItem key={f.value} value={f.value}>
                      {f.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        {/* Table */}
        {isError ? (
          <Alert variant="destructive">
            <AlertTitle>Failed to load tasks</AlertTitle>
            <AlertDescription>
              {(error as Error)?.message ?? 'Unknown error'}
            </AlertDescription>
          </Alert>
        ) : null}

        <Card>
          <CardContent className="p-0">
            {isLoading ? (
              <div className="flex items-center justify-center py-16">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
              </div>
            ) : tasks.length === 0 ? (
              <div className="py-16 text-center">
                <ListChecks className="h-12 w-12 mx-auto text-muted-foreground mb-3" />
                <h3 className="font-medium">No PM tasks match</h3>
                <p className="text-sm text-muted-foreground max-w-md mx-auto">
                  Tasks are auto-created from active schedules on{' '}
                  <Link
                    href="/campus-living/maintenance/preventive"
                    className="underline"
                  >
                    Preventive Maintenance
                  </Link>
                  . If nothing shows here, either no schedules have triggered
                  yet, or your filter is too narrow.
                </p>
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Task</TableHead>
                    <TableHead>Category</TableHead>
                    <TableHead>Priority</TableHead>
                    <TableHead>Due</TableHead>
                    <TableHead>Assigned</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="text-right">Action</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {tasks.map((t) => {
                    const due = dueLabel(t.due_date);
                    const statusMeta = STATUS_BADGE[t.status] ?? {
                      className: 'bg-slate-100 text-slate-700',
                      label: t.status,
                    };
                    const isOpen = OPEN_STATUSES.includes(t.status);
                    return (
                      <TableRow key={t.id}>
                        <TableCell className="font-medium">
                          {t.title}
                          {t.completion_notes ? (
                            <span className="block text-xs text-muted-foreground line-clamp-1">
                              {t.completion_notes}
                            </span>
                          ) : null}
                        </TableCell>
                        <TableCell className="capitalize text-sm">
                          {t.category.replace(/_/g, ' ')}
                        </TableCell>
                        <TableCell>
                          <Badge
                            className={
                              PRIORITY_BADGE[t.priority] ??
                              'bg-slate-100 text-slate-700'
                            }
                          >
                            {t.priority}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <Badge className={due.className}>
                            {due.icon}
                            {due.text}
                          </Badge>
                          <span className="block text-xs text-muted-foreground mt-1">
                            {t.due_date
                              ? new Date(t.due_date).toLocaleDateString()
                              : '—'}
                          </span>
                        </TableCell>
                        <TableCell className="text-sm">
                          {t.assigned_to_name ?? '—'}
                          {t.assigned_to_phone ? (
                            <span className="block text-xs text-muted-foreground">
                              {t.assigned_to_phone}
                            </span>
                          ) : null}
                        </TableCell>
                        <TableCell>
                          <Badge className={statusMeta.className}>
                            {statusMeta.label}
                          </Badge>
                        </TableCell>
                        <TableCell className="text-right">
                          {isOpen ? (
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => {
                                setCompleting(t);
                                setNotes('');
                                setCost('');
                              }}
                            >
                              <CheckCircle2 className="mr-1 h-4 w-4" />
                              Complete
                            </Button>
                          ) : t.completed_at ? (
                            <span className="text-xs text-muted-foreground">
                              {new Date(t.completed_at).toLocaleDateString()}
                            </span>
                          ) : null}
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Complete dialog */}
      <Dialog
        open={!!completing}
        onOpenChange={(o) => {
          if (!o) setCompleting(null);
        }}
      >
        <DialogContent className="sm:max-w-[480px]">
          <DialogHeader>
            <DialogTitle>Complete task</DialogTitle>
            <DialogDescription>
              {completing
                ? `Marking "${completing.title}" as resolved.`
                : ''}
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="space-y-2">
              <Label htmlFor="task-notes">Completion notes</Label>
              <Textarea
                id="task-notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder="What was done? Parts replaced? Issues found?"
                rows={4}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="task-cost">Actual cost (₹)</Label>
              <Input
                id="task-cost"
                type="number"
                step="0.01"
                min="0"
                value={cost}
                onChange={(e) => setCost(e.target.value)}
                placeholder="0.00"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCompleting(null)}>
              Cancel
            </Button>
            <Button
              onClick={handleConfirmComplete}
              disabled={completeMut.isPending}
            >
              {completeMut.isPending ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <CheckCircle2 className="mr-2 h-4 w-4" />
              )}
              Mark resolved
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </ContentLayout>
  );
}
