import { AdmissionAIInsights } from '@/types/admission';
import jsPDF from 'jspdf';

/**
 * Format AI insights as Markdown text
 */
export function formatInsightsAsMarkdown(insights: AdmissionAIInsights): string {
  const markdown: string[] = [];

  // Header
  markdown.push('# Admissions Analytics - AI Insights Report\n');
  markdown.push(`**Generated:** ${new Date(insights.generatedAt).toLocaleString()}`);
  markdown.push(`**Powered by:** Claude 3.5 Haiku\n`);
  markdown.push('---\n');

  // Executive Summary
  markdown.push('## Executive Summary\n');
  markdown.push(`${insights.summary}\n`);
  markdown.push('---\n');

  // Key Findings
  if (insights.keyFindings && insights.keyFindings.length > 0) {
    markdown.push('## Key Findings\n');
    insights.keyFindings.forEach((finding, index) => {
      markdown.push(`### ${index + 1}. ${finding.title}`);
      markdown.push(`**Severity:** ${finding.severity.toUpperCase()}\n`);
      markdown.push(`${finding.description}\n`);
    });
    markdown.push('---\n');
  }

  // Strategic Recommendations
  if (insights.recommendations && insights.recommendations.length > 0) {
    markdown.push('## Strategic Recommendations\n');
    insights.recommendations.forEach((rec, index) => {
      markdown.push(`### ${index + 1}. ${rec.category}`);
      markdown.push(`**Priority:** ${rec.priority.toUpperCase()}\n`);

      markdown.push('**Data Insight:**');
      markdown.push(`${rec.insight}\n`);

      markdown.push('**Recommended Action:**');
      markdown.push(`${rec.action}\n`);

      if (rec.expectedImpact) {
        markdown.push('**Expected Impact:**');
        markdown.push(`${rec.expectedImpact}\n`);
      }

      if (rec.implementationSteps && rec.implementationSteps.length > 0) {
        markdown.push('**Implementation Steps:**');
        rec.implementationSteps.forEach((step, stepIndex) => {
          markdown.push(`${stepIndex + 1}. ${step}`);
        });
        markdown.push('');
      }
    });
    markdown.push('---\n');
  }

  // Predictive Analytics
  if (insights.predictions && insights.predictions.length > 0) {
    markdown.push('## Predictive Analytics\n');
    insights.predictions.forEach((pred, index) => {
      markdown.push(`### ${index + 1}. ${pred.metric}`);
      markdown.push(`**Confidence:** ${pred.confidence.toUpperCase()}`);
      if (pred.timeline) {
        markdown.push(`**Timeline:** ${pred.timeline}`);
      }
      markdown.push('');
      markdown.push(`**Prediction:** ${pred.prediction}\n`);

      if (pred.reasoning) {
        markdown.push(`**Reasoning:** ${pred.reasoning}\n`);
      }
    });
    markdown.push('---\n');
  }

  // Key Trends
  if (insights.trends && insights.trends.length > 0) {
    markdown.push('## Key Trends Analysis\n');
    insights.trends.forEach((trend, index) => {
      markdown.push(`### ${index + 1}. ${trend.trend}`);
      markdown.push(`**Direction:** ${trend.direction.toUpperCase()}`);
      if (trend.significance) {
        markdown.push(`**Significance:** ${trend.significance.toUpperCase()}`);
      }
      markdown.push('');
      markdown.push(`**Impact:** ${trend.impact}\n`);
    });
    markdown.push('---\n');
  }

  // Risk Assessment
  if (insights.riskAssessment && insights.riskAssessment.length > 0) {
    markdown.push('## Risk Assessment\n');
    insights.riskAssessment.forEach((risk, index) => {
      markdown.push(`### ${index + 1}. ${risk.risk}`);
      markdown.push(`**Severity:** ${risk.severity.toUpperCase()}`);
      markdown.push(`**Likelihood:** ${risk.likelihood.toUpperCase()}\n`);
      markdown.push('**Mitigation Strategy:**');
      markdown.push(`${risk.mitigation}\n`);
    });
    markdown.push('---\n');
  }

  // Growth Opportunities
  if (insights.opportunities && insights.opportunities.length > 0) {
    markdown.push('## Growth Opportunities\n');
    insights.opportunities.forEach((opp, index) => {
      markdown.push(`### ${index + 1}. ${opp.opportunity}`);
      markdown.push(`**Potential:** ${opp.potential.toUpperCase()}\n`);
      markdown.push('**Action Plan:**');
      markdown.push(`${opp.actionPlan}\n`);
    });
    markdown.push('---\n');
  }

  // Competitive Insights
  if (insights.competitiveInsights && insights.competitiveInsights.length > 0) {
    markdown.push('## Competitive Insights\n');
    insights.competitiveInsights.forEach((insight, index) => {
      markdown.push(`### ${index + 1}. ${insight.insight}`);
      markdown.push(`**Comparison:** ${insight.comparison}\n`);
      markdown.push(`**Recommendation:** ${insight.recommendation}\n`);
    });
    markdown.push('---\n');
  }

  // Footer
  markdown.push('## Disclaimer\n');
  markdown.push(
    'These insights are generated by Claude 3.5 Haiku based on current data patterns and should be used as strategic guidance alongside human expertise. Regular review and validation with domain experts and stakeholders is strongly recommended.\n'
  );

  markdown.push('---\n');
  markdown.push(`*Report generated on ${new Date(insights.generatedAt).toLocaleString()}*`);

  return markdown.join('\n');
}

/**
 * Generate PDF from AI insights
 */
export function generateInsightsPDF(insights: AdmissionAIInsights): void {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Helper function to add text with wrapping
  const addText = (text: string, fontSize: number = 10, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    pdf.setTextColor(color[0], color[1], color[2]);

    const lines = pdf.splitTextToSize(text, contentWidth);
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });
  };

  const addSpacing = (space: number = 5) => {
    yPosition += space;
  };

  const addSection = (title: string) => {
    if (yPosition > pageHeight - margin - 20) {
      pdf.addPage();
      yPosition = margin;
    }
    addSpacing(8);
    pdf.setDrawColor(0, 123, 255);
    pdf.setLineWidth(0.5);
    pdf.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 3;
    addText(title, 14, true, [0, 123, 255]);
    addSpacing(3);
  };

  // Header
  pdf.setFillColor(0, 123, 255);
  pdf.rect(0, 0, pageWidth, 40, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Admissions Analytics', margin, 15);
  pdf.setFontSize(16);
  pdf.text('AI Insights Report', margin, 25);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated: ${new Date(insights.generatedAt).toLocaleString()}`, margin, 33);

  yPosition = 50;

  // Executive Summary
  addSection('EXECUTIVE SUMMARY');
  addText(insights.summary, 10, false);

  // Key Findings
  if (insights.keyFindings && insights.keyFindings.length > 0) {
    addSection('KEY FINDINGS');
    insights.keyFindings.forEach((finding, index) => {
      addSpacing(3);
      addText(`${index + 1}. ${finding.title}`, 11, true);
      addText(`Severity: ${finding.severity.toUpperCase()}`, 9, false, [220, 53, 69]);
      addText(finding.description, 10, false);
    });
  }

  // Strategic Recommendations
  if (insights.recommendations && insights.recommendations.length > 0) {
    addSection('STRATEGIC RECOMMENDATIONS');
    insights.recommendations.forEach((rec, index) => {
      addSpacing(3);
      addText(`${index + 1}. ${rec.category}`, 11, true);
      addText(`Priority: ${rec.priority.toUpperCase()}`, 9, false, rec.priority === 'high' ? [220, 53, 69] : rec.priority === 'medium' ? [255, 193, 7] : [13, 110, 253]);

      addText('Data Insight:', 10, true);
      addText(rec.insight, 9, false);
      addSpacing(2);

      addText('Recommended Action:', 10, true);
      addText(rec.action, 9, false);
      addSpacing(2);

      if (rec.expectedImpact) {
        addText('Expected Impact:', 10, true);
        addText(rec.expectedImpact, 9, false, [25, 135, 84]);
        addSpacing(2);
      }

      if (rec.implementationSteps && rec.implementationSteps.length > 0) {
        addText('Implementation Steps:', 10, true);
        rec.implementationSteps.forEach((step, stepIndex) => {
          addText(`   ${stepIndex + 1}. ${step}`, 9, false);
        });
      }
    });
  }

  // Predictions
  if (insights.predictions && insights.predictions.length > 0) {
    addSection('PREDICTIVE ANALYTICS');
    insights.predictions.forEach((pred, index) => {
      addSpacing(3);
      addText(`${index + 1}. ${pred.metric}`, 11, true);
      addText(`Confidence: ${pred.confidence.toUpperCase()} | Timeline: ${pred.timeline || 'N/A'}`, 9, false);
      addText(pred.prediction, 10, false);
      if (pred.reasoning) {
        addText(`Reasoning: ${pred.reasoning}`, 9, false, [108, 117, 125]);
      }
    });
  }

  // Trends
  if (insights.trends && insights.trends.length > 0) {
    addSection('KEY TRENDS ANALYSIS');
    insights.trends.forEach((trend, index) => {
      addSpacing(3);
      addText(`${index + 1}. ${trend.trend}`, 11, true);
      const directionColor: [number, number, number] = trend.direction === 'up' ? [25, 135, 84] : trend.direction === 'down' ? [220, 53, 69] : [13, 110, 253];
      addText(`Direction: ${trend.direction.toUpperCase()} | Significance: ${trend.significance?.toUpperCase() || 'N/A'}`, 9, false, directionColor);
      addText(`Impact: ${trend.impact}`, 10, false);
    });
  }

  // Risk Assessment
  if (insights.riskAssessment && insights.riskAssessment.length > 0) {
    addSection('RISK ASSESSMENT');
    insights.riskAssessment.forEach((risk, index) => {
      addSpacing(3);
      addText(`${index + 1}. ${risk.risk}`, 11, true);
      addText(`Severity: ${risk.severity.toUpperCase()} | Likelihood: ${risk.likelihood.toUpperCase()}`, 9, false, [220, 53, 69]);
      addText('Mitigation Strategy:', 10, true);
      addText(risk.mitigation, 9, false);
    });
  }

  // Opportunities
  if (insights.opportunities && insights.opportunities.length > 0) {
    addSection('GROWTH OPPORTUNITIES');
    insights.opportunities.forEach((opp, index) => {
      addSpacing(3);
      addText(`${index + 1}. ${opp.opportunity}`, 11, true);
      addText(`Potential: ${opp.potential.toUpperCase()}`, 9, false, [25, 135, 84]);
      addText('Action Plan:', 10, true);
      addText(opp.actionPlan, 9, false);
    });
  }

  // Competitive Insights
  if (insights.competitiveInsights && insights.competitiveInsights.length > 0) {
    addSection('COMPETITIVE INSIGHTS');
    insights.competitiveInsights.forEach((insight, index) => {
      addSpacing(3);
      addText(`${index + 1}. ${insight.insight}`, 11, true);
      addText(`Comparison: ${insight.comparison}`, 9, false);
      addText(`Recommendation: ${insight.recommendation}`, 9, false, [0, 123, 255]);
    });
  }

  // Footer
  addSpacing(10);
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 5;
  addText('Disclaimer', 10, true);
  addText(
    'These insights are generated by Claude 3.5 Haiku based on current data patterns and should be used as strategic guidance alongside human expertise. Regular review and validation with domain experts and stakeholders is strongly recommended.',
    8,
    false,
    [108, 117, 125]
  );

  // Save PDF
  const filename = `Admissions-AI-Insights-${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(filename);
}

/**
 * Copy Markdown text to clipboard
 */
export async function copyMarkdownToClipboard(markdown: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(markdown);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Download Markdown as .md file
 */
export function downloadMarkdownFile(markdown: string): void {
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Admissions-AI-Insights-${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
