/**
 * The bulk-edit template must survive its own importer.
 *
 * Export and import are two halves of one workflow; if the header, the label
 * row or the date format drift apart the failure is SILENT -- the parser simply
 * stops finding a column and defaults the field. This feeds the generated bytes
 * straight back into parseSalarySheet() so that cannot happen unnoticed.
 *
 * Run: npx tsx scripts/salary-template-roundtrip.test.ts
 */

import { buildSalaryTemplateWorkbook } from '../app/(routes)/hr/payroll/salaries/_components/salary-template-export';
import { parseSalarySheet } from '../lib/hr/payroll/parse-salary-sheet';
import type { StaffSalaryDirectoryRow } from '../lib/services/hr/payroll/staff-salary-service';

let passed = 0, failed = 0;
function check(name: string, cond: boolean, extra = '') {
  if (cond) { passed++; console.log(`PASS  ${name}`); }
  else { failed++; console.log(`FAIL  ${name} ${extra}`); }
}

const base = (over: Partial<StaffSalaryDirectoryRow>): StaffSalaryDirectoryRow => ({
  staff_uuid: 'u1', staff_code: 'NOT100', person_name: 'GUNASEKARAN S',
  role_title: 'Professor', is_active: true,
  works_at_id: 'i1', works_at_name: 'JKKN Engineering',
  payer_org_id: 'o1', payer_org_name: 'JKKN Engineering',
  salary_id: null, salary_structure: null, monthly_gross: null, annual_gross: null,
  overtime_level: null, overtime_amount: null,
  eligible_for_pf: false, exempt_edli: false, eligible_for_insurance: false,
  eligible_for_gratuity: false, eligible_for_etf: false,
  effective_from: null, notes: null, ...over,
});

const rows: StaffSalaryDirectoryRow[] = [
  // Salaried, with flags and a date -- the full round trip.
  base({
    staff_uuid: 'u1', staff_code: 'NOT100', salary_id: 's1',
    salary_structure: 'Monthly', monthly_gross: 26500, annual_gross: 318000,
    overtime_level: 'No overtime', overtime_amount: 0,
    eligible_for_pf: true, eligible_for_insurance: true, exempt_edli: false,
    effective_from: '2026-08-01',
  }),
  // Awaiting a salary -- the common case on this screen.
  base({ staff_uuid: 'u2', staff_code: 'NOT201', person_name: 'MEENA R' }),
  // No employee code: cannot re-import, must be counted.
  base({ staff_uuid: 'u3', staff_code: null, person_name: 'NO CODE' }),
];

const { bytes, missingCode } = buildSalaryTemplateWorkbook(rows);
const parsed = parseSalarySheet(bytes);

check('sheet is named for the importer', parsed.sheet_name === 'Salary data import', parsed.sheet_name);
check('no parser warnings', parsed.warnings.length === 0, JSON.stringify(parsed.warnings));
check('label row is not read as an employee',
  !parsed.rows.some((r) => r.employee_code.toLowerCase() === 'employee id'));
check('rows with a code round-trip', parsed.rows.length === 2, `got ${parsed.rows.length}`);
check('missing-code rows are counted', missingCode === 1, String(missingCode));

const a = parsed.rows.find((r) => r.employee_code === 'NOT100');
check('amount survives', a?.monthly_gross === 26500, String(a?.monthly_gross));
check('annual survives', a?.annual_gross_in_file === 318000, String(a?.annual_gross_in_file));
check('dd/mm/yyyy is NOT read as mm/dd', a?.effective_from === '2026-08-01', String(a?.effective_from));
check('Yes/No maps back to booleans',
  a?.eligible_for_pf === true && a?.eligible_for_insurance === true && a?.exempt_edli === false,
  `pf=${a?.eligible_for_pf} ins=${a?.eligible_for_insurance} edli=${a?.exempt_edli}`);
check('structure survives', a?.salary_structure === 'Monthly', String(a?.salary_structure));

const b = parsed.rows.find((r) => r.employee_code === 'NOT201');
check('an unset salary exports BLANK, not zero', b?.monthly_gross === null, String(b?.monthly_gross));
check('an unset row still carries its name', b?.employee_name === 'MEENA R', String(b?.employee_name));

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed === 0 ? 0 : 1);
