import { type AIRoutine } from './types';
// Populated 2026-07-01 from the parallel discovery swarm (deep-read of jicate/main).
export const AI_PULSE_ROUTINES: AIRoutine[] = [
  {
    "id": "ai-pulse-tick",
    "name": "AI Pulse Cycle Tick + Engagement Acknowledgment",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Daily 01:23 UTC",
    "cronExpr": "23 1 * * *",
    "triggerPath": "/api/cron/ai-pulse-tick",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based cycle tick — the route resolves no model and enqueues no job, so no ai_job_types row applies.",
    "whatItDoes": "Creates the shell for the upcoming weekly AI Pulse session (a startup_events 'cycle' row) for each institution when one doesn't already exist. It also sends a 'you were fully engaged this week' in-app bell notification to every learner who passed all the engagement gates, once that cycle's make-up window has closed.",
    "configKnobs": "session_day=Thursday, multi_campus_mode=unified, gold_standard_count=2, bottom_n_publication_count=2, primary_language=en, secondary_language=ta, session_start_time=18:55, session_end_time=19:30, async_makeup_window_hours=48 (all read from ai_pulse_policies with these code defaults); recent-cycle acknowledgment lookback=14 days",
    "sideEffects": "DB writes: inserts startup_events cycle shells; inserts notifications + user_notifications rows (bell acknowledgments to passing learners); updates startup_events.config with engagement_acknowledged_at markers. It does NOT send outbound SMS/email/WhatsApp — only in-app bell notifications.",
    "safeToManualTrigger": false,
    "notes": "Auth: CRON_SECRET as ?secret= or Authorization: Bearer. Fully idempotent — skips cycles that already exist and cycles already acknowledged (engagement_acknowledged_at guard), so re-firing does NOT double-send. Marked unsafe only because a FIRST run against a just-closed cycle fans out real learner bell notifications. Cycle-creation is cheap/idempotent; the notification fan-out is the reason to confirm before triggering. Does not call Claude."
  },
  {
    "id": "ai-pulse-weekly-digest",
    "name": "AI Pulse Weekly Department Digest",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Tuesdays 04:17 UTC (09:47 IST)",
    "cronExpr": "17 4 * * 2",
    "triggerPath": "/api/cron/ai-pulse-weekly-digest",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based digest assembled from stored pulse rows; the route resolves no model, so no ai_job_types row applies.",
    "whatItDoes": "Rolls up the most recent AI Pulse cycle's engagement per department and delivers an in-app bell digest: one to each department's HOD (their own department) and an institution-wide roll-up of flagged departments to each principal.",
    "configKnobs": "RECENT_CYCLE_COUNT=8 (cumulative miss window), session_end_time fallback=19:30, STAY_TOLERANCE_MINUTES (from live-session-service); recipients resolved by profiles.role IN ('hod','principal','school_principal')",
    "sideEffects": "DB writes: inserts one notifications row + one user_notifications link row per recipient (HODs and principals). No outbound SMS/email/WhatsApp — in-app bell only.",
    "safeToManualTrigger": false,
    "notes": "Auth: CRON_SECRET via ?secret= or Bearer. Idempotency_key = ai_pulse_weekly_digest:<cycleId>:<userId>, so a re-fire on the same cycle is a per-recipient no-op. Marked unsafe because it messages humans (HOD/principal bell digests); the idempotency guard means it won't duplicate for the same cycle. Computes the per-department roll-up in TypeScript (no DB function). Does not call Claude."
  },
  {
    "id": "ai-pulse-rotation-tick",
    "name": "AI Pulse Rotation Draw",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Daily 02:37 UTC (draws only on the configured generation weekday)",
    "cronExpr": "37 2 * * *",
    "triggerPath": "/api/cron/ai-pulse-rotation-tick",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based rotation advance (RotationEngineService makes no model call), so no ai_job_types row applies.",
    "whatItDoes": "On the configured generation weekday it draws the upcoming cycle's Pulse teams from the front of each section's rotation queue (so 'everyone gets a turn'), then moves the drawn learners to the back of the queue.",
    "configKnobs": "rotation_auto_generate=true (master switch), rotation_generation_dow=Friday (both from ai_pulse_policies with these defaults). Query param ?force=1 bypasses the weekday gate only, never the master switch.",
    "sideEffects": "DB writes: team draws via RotationEngineService.generateTeamsForCycle (writes/advances ai_pulse_rotation_state and team rows). No human messaging.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET via ?secret= or Bearer. Idempotent per (cycle, section) — already-drawn sections are no-ops. On any non-generation weekday it returns a 200 no-op ('not_generation_day') unless you add ?force=1. Also no-op if rotation_auto_generate is off, or if there is no upcoming ai_pulse cycle. Does not call Claude."
  },
  {
    "id": "ai-pulse-anomaly-scan",
    "maxLane": true,
    "name": "AI Pulse Anomaly Scan",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Daily 03:43 UTC",
    "cronExpr": "43 3 * * *",
    "triggerPath": "/api/cron/ai-pulse-anomaly-scan",
    "callsClaude": false,
    "featureKey": "ai_pulse.anomaly_detection",
    "whatItDoes": "Scans the last 14 days of AI Pulse cycles for five integrity red-flags — passing the quiz without attending, suspiciously high reach, rubber-stamp identical poll answers, rotation-queue gaming, and excessive excused absences — and writes 'pending' anomaly flags for Champions to review.",
    "configKnobs": "SCAN_WINDOW_DAYS=14; quiz_pass_threshold_live=40, ig_reach_threshold=500, reach_outlier_multiplier=20 (reach outlier threshold = 500*20 = 10000), poll_pattern_min_responses=3, rotation_fairness_slack=12, excuse_frequency_threshold=3 (all from ai_pulse_policies with these code defaults)",
    "sideEffects": "DB writes: inserts ai_pulse_anomaly_flags rows with review_outcome='pending'. No human messaging (flags are reviewed in-app at /ai-pulse/admin/anomalies).",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET via ?secret= or Bearer. Idempotent — skips when an open (pending/null) flag of the same type+target+cycle already exists, and dedupes within a run. Honest-empty (0 flags) when no cycles in window. Optional substrates (polls, rotation_state, team attendance) degrade to 'no flags' rather than erroring. Does not call Claude — pure rule-based detectors. Max lane: the Max twin ports the anomaly scan to the runner box (headless claude -p on the subscription, ₹0 API); this cloud cron stays as the backup and defers a run when the runner heartbeat is fresh (shouldDeferToMaxLane — fail-open, inert until the maxlane:ai-pulse-anomaly-scan schedule row is enabled)."
  },
  {
    "id": "ai-pulse-pde-bridge",
    "name": "AI Pulse to PDE Bridge",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Daily 04:53 UTC",
    "cronExpr": "53 4 * * *",
    "triggerPath": "/api/cron/ai-pulse-pde-bridge",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based bridge copying pulse signals into PDE; the route resolves no model, so no ai_job_types row applies.",
    "whatItDoes": "When the pde_bridge_enabled policy is switched on, it converts AI Pulse participation signals from recent cycles into Personal Development (pde_demonstrations) records. It is OFF by default, so out of the box it just returns a no-op.",
    "configKnobs": "RECENT_WINDOW_DAYS=14; master switch pde_bridge_enabled (ai_pulse_policies, DEFAULT FALSE). Query params: ?dry_run=1 (evaluate + count, no writes), ?cycle=<uuid> (scope to one cycle).",
    "sideEffects": "DB writes: inserts pde_demonstrations rows via AiPulsePdeBridgeService.bridgeCycle (unless dry_run). No human messaging. Currently dormant — policy defaults false.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET via ?secret= or Bearer. Gated behind pde_bridge_enabled (default FALSE) → 200 no-op ('enabled:false, skipped:true') unless the Director turned it on. Supports ?dry_run=1 for a safe count-only run. Inserts are idempotent (reports found/inserted/skipped). Does not call Claude."
  },
  {
    "id": "ai-pulse-quiz-suggest",
    "name": "AI Pulse Quiz Suggest (stub)",
    "category": "ai-pulse",
    "type": "interactive",
    "schedule": "On demand",
    "triggerPath": "/api/ai-pulse/quiz/suggest",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Still a deterministic placeholder (the route returns stub:true); the LLM path is Phase 2, so there is no job type to link yet.",
    "whatItDoes": "Returns 5 placeholder bilingual (English/Tamil) quiz questions to pre-fill the Champion's quiz editor so they don't start from a blank screen. This is a v1 stub — it does not generate anything from the session, it returns fixed placeholders.",
    "configKnobs": "5 hardcoded placeholder question seeds; requires body { cycle_id: string }; permission gate aiPulse:quiz.author; allowApiKey=false",
    "sideEffects": "read-only — returns JSON ({ questions, stub:true }), writes nothing.",
    "safeToManualTrigger": true,
    "notes": "Auth is NOT CRON_SECRET — it uses withAuth and requires a signed-in user with the aiPulse:quiz.author permission (super-admin bypasses). An operator cannot hit it with a secret query param; needs an authed session + POST body with cycle_id. Read-only and safe. IMPORTANT: despite the 'AI Suggest' name it does NOT call Claude/Anthropic today — the header comment says Phase 2 will add an Anthropic.messages.create transcript pass, but the deployed code is a deterministic placeholder stub."
  },
  {
    "id": "ai-pulse-submit-domain-sync",
    "name": "AI Pulse Domain-Sync Submission",
    "category": "ai-pulse",
    "type": "endpoint",
    "schedule": "On submit (GET = context, POST = submit)",
    "triggerPath": "/api/ai-pulse/submit/domain-sync",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based domain sync over submitted answers; the route resolves no model, so no ai_job_types row applies.",
    "whatItDoes": "The learner-facing endpoint for a team's weekly Domain-Sync artifact. GET returns submit context (current cycle, the learner's team, any existing submission, and the deadline); POST saves/updates the team's submission (title, description, optional GitHub link, proof URLs).",
    "configKnobs": "domain_sync_deadline_offset_days=3 (from ai_pulse_policies), MAX_PROOF_URLS=10, description min length=20 chars, github_url must match https://github.com/. Permission gate aiPulse:submit.domain_sync.",
    "sideEffects": "POST upserts one event_submissions row (service-role write, only after proving the caller is an accepted member of the team). GET is read-only. No human messaging.",
    "safeToManualTrigger": false,
    "notes": "Auth is a signed-in user session (Supabase cookie) + the aiPulse:submit.domain_sync permission + valid accepted-team membership — NOT CRON_SECRET, so an operator can't fire it like a job. The POST writes a real team submission record on that user's behalf; the upsert is idempotent by (event_id, registration_id) but it is a user submission path, not an operator-run task. GET-context is read-only and harmless. Does not call Claude."
  },
  {
    "id": "ai-pulse-measure-verdict",
    "name": "AI Pulse Measure + Verdict (closes the loop)",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Daily 10:15 IST",
    "cronExpr": "",
    "triggerPath": "/api/cron/ai-pulse-measure-verdict",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based verdict measurement through one SQL RPC; the route resolves no model, so no ai_job_types row applies.",
    "whatItDoes": "Grades every matured weekly cycle across the whole four-stage funnel (learn → apply in your domain → AI Lab/Gold → publish on department Instagram), per department plus one lossless program-level row. Emits goal_met/goal_missed against the target dials, records stage_reached (WHERE the funnel died), and computes an engagement lift corrected for regression-to-the-mean using the untreated departments as a naturally-occurring control. This is gate 3 of the four-gate loop test, which AI Pulse never had.",
    "configKnobs": "engaged_attendance_target_pct=70, agency_yield_target_pct=10, measure_min_age_days=3, measure_min_attendance=5, measure_baseline_window=3, measure_min_rtm_pairs=5, loop_noise_band_pct=5, ig_reach_threshold=500 (all ai_pulse_policies)",
    "sideEffects": "DB writes: upserts ai_pulse_cycle_outcomes rows via a service-role SECURITY DEFINER RPC. No human messaging. Never sets the HUMAN verdict — a cron must not invent a human judgement.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET as ?secret= or Authorization: Bearer. Not in vercel.json — fired by ai-routine-dispatcher from ai_routine_schedules. Idempotent: rows that reach measure_status='measured' are never re-measured (gated in both the candidate filter and the UPDATE's WHERE); insufficient_* rows re-evaluate as more data matures. Never fabricates a baseline — a cycle with no prior comparable cycle is written insufficient_baseline with NULL lift. Returns TOP-LEVEL measured/skipped/recorded so the dispatcher's summarize() shows real numbers instead of a bare HTTP 200. Optional ?min_age_days= overrides the maturation dial for a backfill. Does not call Claude."
  },
  {
    "id": "aipulse-domain-starter",
    "name": "AI Pulse — Domain Starter generation",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Sat–Tue · 14:30 IST (editable via dispatcher)",
    "cronExpr": "8 9 * * 6,0,1,2 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/aipulse-domain-starter",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Enqueues 'ai_pulse.domain_starter' jobs on the ₹0 Max lane (drained by the external seat); the route resolves no ai_model_config row directly.",
    "whatItDoes": "Each cycle, for every ACTIVE programme, authors one copy-paste starter PACK (three job-modes, English + Tamil) via a Max-lane job seeded with how last cycle's prompt for that subject landed — the self-improvement hinge. Also emits one topic_type='general' all-subject row per cycle.",
    "configKnobs": "Candidates from fn_ai_pulse_domain_starter_candidates (active programmes across ALL institutions — deliberately NOT attendance-derived, which was empty 6 of 8 cycles). Day/time editable at /admin/ai-routines.",
    "sideEffects": "Enqueues ai_jobs rows (interactive=false, output_target=job.result). The 'did it help' signal reads the live ai_pulse_cycle_outcomes spine.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: 09:08 UTC = 14:38 IST → slot 14:30 (minute_of_day 878, days {6,0,1,2} — no IST day-shift at this hour)."
  },
  {
    "id": "aipulse-domain-starter-measure",
    "name": "AI Pulse — Domain Starter measure",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Weekly · Saturday 11:30 IST (editable via dispatcher)",
    "cronExpr": "0 6 * * 6 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/aipulse-domain-starter-measure",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based outcome measurement via fn_ai_pulse_measure_domain_starters; no model involved.",
    "whatItDoes": "The feed-forward half of the Domain Starter loop: for every starter still measure_status='pending', rolls the topic's cycle attendees up to departments, reads the LIVE ai_pulse_cycle_outcomes lift (the one spine), and stamps the starter measured (or 'insufficient'). Next cycle's generation prompt reads the stamped lift back.",
    "configKnobs": "DARK until domain_starter_enabled flips true in ai_pulse_policies. Optional ?cycle=<uuid> scopes to one cycle. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Stamps measure_status on starters. Tiny + idempotent — only 'pending' rows are touched; re-run is a no-op.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. Fail-safe config read: any error → treated as off, never throws. IST math: Sat 06:00 UTC = Sat 11:30 IST (minute_of_day 690, days {6})."
  },
  {
    "id": "aipulse-prompt-graduate",
    "name": "AI Pulse — learner-prompt graduation",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Daily · 07:00 IST (editable via dispatcher)",
    "cronExpr": "35 1 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/aipulse-prompt-graduate",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based promotion via fn_ai_pulse_graduate_prompt_builds against a score bar; no model involved.",
    "whatItDoes": "Promotes the best learner prompt-builds into the shared library: every ungraduated, graded build clearing prompt_graduation_min_score gets graduated_at stamped so it surfaces to peers on the same topic — the compounding half of the moat.",
    "configKnobs": "DARK until prompt_graduation_enabled flips true (ai_pulse_policies); the RPC is dark-gated too. prompt_graduation_min_score sets the bar. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Stamps graduated_at only. Idempotent — re-run is a no-op.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. Optional ?cycle=<uuid>. IST math: 01:35 UTC = 07:05 IST → slot 07:00 (minute_of_day 425)."
  },
  {
    "id": "aipulse-prompt-dedup",
    "name": "AI Pulse — star-prompt semantic dedup",
    "category": "ai-pulse",
    "type": "cron",
    "schedule": "Daily · 07:15 IST (editable via dispatcher)",
    "cronExpr": "50 1 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/aipulse-prompt-dedup",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Enqueues 'ai_pulse.prompt_dedup' jobs on the ₹0 claude_code Max lane; the route resolves no ai_model_config row directly.",
    "whatItDoes": "Collect-first, then submit: drains done dedup jobs (mapping the model's duplicate index back to a candidate build) and records via fn_ai_pulse_record_prompt_dedup; then enqueues one dedup job per newly-graduated build so the library can show just the best of a duplicate set.",
    "configKnobs": "DARK until prompt_dedup_enabled flips true (ai_pulse_policies); both RPCs dark-gated too. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Writes ai_pulse_prompt_builds.duplicate_of; enqueues ai_jobs. Idempotent — judged builds stay out of the enqueue set.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: 01:50 UTC = 07:20 IST → slot 07:15 (minute_of_day 440)."
  }
];
