import { type AIRoutine } from './types';
// Populated 2026-07-01 from the parallel discovery swarm (deep-read of jicate/main).
export const FEEDBACK_ADAPTER_ROUTINES: AIRoutine[] = [
  {
    "id": "feedback-adapter-session",
    "name": "Session Feedback → Spine Adapter",
    "category": "feedback-adapters",
    "type": "cron",
    "schedule": "Daily 01:12 UTC",
    "cronExpr": "12 1 * * *",
    "triggerPath": "/api/cron/feedback-adapter-session",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Pure capture — it only ingests events; the AI step is the separate feedback-classify routine (feedback.classify).",
    "whatItDoes": "Copies each student's per-class session feedback (their 'understood' rating and any written comment) into the shared feedback spine so the AI classifier can tag it later. Pure data-shuffling, no AI.",
    "configKnobs": "SELECT_LIMIT=1000 rows/run; maxDuration=120s",
    "sideEffects": "DB writes: upserts rows into public.feedback_events (source='session_feedback'). Idempotent — dedups on (source, source_ref), re-running inserts nothing new. No outbound messages.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET as ?secret=<CRON_SECRET> or Authorization: Bearer <CRON_SECRET> (or Vercel's x-vercel-cron header). Read-then-upsert only; safe to fire on demand. Reads session_feedback, only free_text rows become classifiable content (numeric-only rows carry rating=1/0)."
  },
  {
    "id": "feedback-adapter-mess",
    "name": "Mess Feedback → Spine Adapter",
    "category": "feedback-adapters",
    "type": "cron",
    "schedule": "Daily 01:22 UTC",
    "cronExpr": "22 1 * * *",
    "triggerPath": "/api/cron/feedback-adapter-mess",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Pure capture — it only ingests events; the AI step is the separate feedback-classify routine (feedback.classify).",
    "whatItDoes": "Copies each student's per-meal mess/canteen rating and comment into the shared feedback spine for later AI tagging. No AI in this step.",
    "configKnobs": "SELECT_LIMIT=1000 rows/run; maxDuration=120s",
    "sideEffects": "DB writes: upserts rows into public.feedback_events (source='mess'). Idempotent dedup on (source, source_ref). No outbound messages.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET via ?secret= / Bearer / x-vercel-cron. Reads mess_feedback; complaint rows tagged event_type='comment', others 'rating'. Only comment text is classifiable content. Idempotent — safe to run twice."
  },
  {
    "id": "feedback-adapter-parent",
    "name": "Parent Feedback → Spine Adapter",
    "category": "feedback-adapters",
    "type": "cron",
    "schedule": "Daily 01:32 UTC",
    "cronExpr": "32 1 * * *",
    "triggerPath": "/api/cron/feedback-adapter-parent",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Pure capture — it only ingests events; the AI step is the separate feedback-classify routine (feedback.classify).",
    "whatItDoes": "Copies parent-portal feedback (a parent's rating plus any message) into the shared feedback spine for later AI tagging. No AI here.",
    "configKnobs": "SELECT_LIMIT=1000 rows/run; maxDuration=120s",
    "sideEffects": "DB writes: upserts rows into public.feedback_events (source='parent'). Idempotent dedup on (source, source_ref). No outbound messages.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET via ?secret= / Bearer / x-vercel-cron. Reads pp_feedback (note: source column is misspelled 'institutions_id', mapped to spine's institution_id). Idempotent — safe to run twice."
  },
  {
    "id": "feedback-adapter-ig-dm",
    "name": "Instagram DM → Spine Adapter",
    "category": "feedback-adapters",
    "type": "cron",
    "schedule": "Daily 01:42 UTC",
    "cronExpr": "42 1 * * *",
    "triggerPath": "/api/cron/feedback-adapter-ig-dm",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Pure capture — it only ingests events; the AI step is the separate feedback-classify routine (feedback.classify).",
    "whatItDoes": "Copies inbound Instagram direct messages (people messaging our IG accounts) into the shared feedback spine for later AI tagging. Our own outbound replies and media-only DMs are skipped. No AI here.",
    "configKnobs": "SELECT_LIMIT=1000 rows/run; direction filter='in'; maxDuration=120s",
    "sideEffects": "DB writes: upserts rows into public.feedback_events (source='ig_dm'). Idempotent dedup on (source, source_ref). Reads only from local ig_dm_messages table — no Instagram/Meta API call. No outbound messages.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET via ?secret= / Bearer / x-vercel-cron. Reads the already-stored ig_dm_messages (does NOT call Meta). Only inbound rows with non-empty text are ingested. Idempotent — safe to run twice."
  },
  {
    "id": "feedback-adapter-ig-comments",
    "name": "Instagram Comments → Spine Adapter",
    "category": "feedback-adapters",
    "type": "cron",
    "schedule": "Daily 01:52 UTC",
    "cronExpr": "52 1 * * *",
    "triggerPath": "/api/cron/feedback-adapter-ig-comments",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Pure capture — it only ingests events; the AI step is the separate feedback-classify routine (feedback.classify).",
    "whatItDoes": "Reads recent Instagram comment TEXT off our owned IG posts via the Meta Graph API and copies each comment into the shared feedback spine for later AI tagging. No AI in this step (the daily classifier tags them afterward).",
    "configKnobs": "GRAPH_VERSION=v25.0; MAX_ACCOUNTS=12; POSTS_PER_ACCOUNT=15; COMMENTS_PER_POST_CAP=300; comment page size=50; maxDuration=300s",
    "sideEffects": "External read: calls Meta Graph API comments edge per post (read-only, no posting). DB writes: upserts rows into public.feedback_events (source='ig_comment'). Idempotent dedup on (source, source_ref = comment id). No outbound messages.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET via ?secret= / Bearer / x-vercel-cron. Only processes ig_accounts with metrics_source='graph' AND a stored access_token; falls back to META_IG_SYSTEM_USER_TOKEN env token. Per-post Graph errors are swallowed and skipped. Idempotent — safe to run twice; but it does hit the external Graph API, so a manual run consumes Meta API quota."
  },
  {
    "id": "mess-menu-loop",
    "name": "Choose-Your-Menu Self-Improving Loop",
    "category": "feedback-adapters",
    "type": "cron",
    "schedule": "Mondays 02:37 UTC",
    "cronExpr": "37 2 * * 1",
    "triggerPath": "/api/cron/mess-menu-loop",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based recommend/measure SQL RPCs (fn_mess_recommend_next_menu, fn_mess_measure_menu_lift); no model call.",
    "whatItDoes": "Weekly mess-menu improvement loop: for each active menu slot it proposes next Monday's menu (via a DB function that reads last cycle's measured rating/waste lift and the chairperson's verdict), then measures the lift of past cycles that have completed. Currently DARK by default — normally a no-op. No AI.",
    "configKnobs": "MEASURE_LIMIT=500 recommendations/run; gate policy_key='mess.choose.loop.master_enabled' (global scope, must equal boolean true); maxDuration=120s. RPCs: fn_mess_recommend_next_menu, fn_mess_measure_menu_lift",
    "sideEffects": "Gated OFF by default → returns {skipped:'loop dark'} and writes nothing. When the master switch is ON: DB writes — inserts 'proposed' rows into mess_menu_recommendations (one per active institution/tier/meal slot) and fills rating_lift/waste_lift on past unmeasured recommendations. No outbound human messages.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET via ?secret= / Bearer / x-vercel-cron. Dormant: skips entirely unless platform_policies row mess.choose.loop.master_enabled (scope_type='global') is exactly true. Even when live it only writes DB proposals + measurements (no messages); a manual run is safe. Reads mess_menus slots + mess_menu_recommendations."
  },
  {
    "id": "feedback-classify",
    "maxLane": true,
    "name": "Feedback Spine AI Classifier (shared service)",
    "category": "feedback-adapters",
    "type": "service",
    "schedule": "On demand (per-event; driven by the /api/cron/feedback-classify cron)",
    "triggerPath": "/api/cron/feedback-classify",
    "callsClaude": true,
    "featureKey": "feedback.classify",
    "whatItDoes": "The shared AI worker for the feedback spine: for one piece of feedback text it calls Claude to return sentiment, intent, a short topic label, and a draft reply (in the same language, English/Tamil/Tanglish). This is the AI layer the adapters feed into.",
    "configKnobs": "MODEL=claude-sonnet-4-6 (config row 'feedback.classify' — /admin/ai-models); max_tokens=400; input content capped at 4000 chars; API key from CLAUDE_API_KEY or ANTHROPIC_API_KEY. Driving cron uses BATCH=25 events/run, maxDuration=300s",
    "sideEffects": "The function itself is read-only (returns a classification object; sends NO messages — draft_reply is stored for human approval, never auto-sent). Persistence happens in its caller: /api/cron/feedback-classify writes ai_sentiment/ai_intent/ai_topic/ai_draft_reply/ai_model/ai_processed_at onto feedback_events rows where ai_processed_at IS NULL.",
    "safeToManualTrigger": false,
    "notes": "Library function lib/services/feedback/feedback-classify.ts — not an HTTP route itself; operators run classification via the /api/cron/feedback-classify cron (auth: Bearer CRON_SECRET or x-vercel-cron). Uses the paid Anthropic API (NOT the Claude subscription); each event costs a fraction of a cent. Guarded by ai_processed_at IS NULL so re-runs only classify still-unprocessed events (drained-safe, idempotent). Throws on API/parse failure per event; the cron catches per-row. Max lane: on-demand via the ⚡ button — a Mac-side runner twin executes on the Claude Max subscription (₹0 API) and is guard-idempotent with the API path."
  }
];
