import { type AIRoutine } from './types';
// Populated 2026-07-01 from the parallel discovery swarm (deep-read of jicate/main).
export const MISC_AI_ROUTINES: AIRoutine[] = [
  {
    "id": "social-engagement-nudges",
    "name": "Department IG Engagement Nudges",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 09:30 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/social-nudges",
    "callsClaude": false,
    "whatItDoes": "Two adoption nudges that keep the department-Instagram engagement loop alive: (1) a weekly 'it's your week to post for @handle' reminder to the assigned contributor, and (2) a recognition nudge when a posted contribution earns real signal (saves+shares+comments — never likes): 'your post earned N real-signal'. Without these the loop is silent and sits at 0% adoption.",
    "configKnobs": "Monday snap = Asia/Kolkata; recognition floor = real_signal >= 1; realSignal = saves+shares+comments (likes excluded). No model, no thresholds.",
    "sideEffects": "WRITES in-app notifications (notifications + user_notifications fan-out) to contributors. Idempotent: reminded_at (rota) + signal_notified_at (contribution) guard exactly one delivery each. No external messages (no email/WhatsApp/push).",
    "safeToManualTrigger": false,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'social-engagement-nudges' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer or ?secret=). Marked unsafe-to-manual because a run delivers real notifications to real contributors; re-running is safe (idempotent — repeats surface as 'duplicate' counts, deliver nothing new)."
  },
  {
    "id": "cdc-career-guidance",
    "name": "CDC AI Career Guidance",
    "category": "misc-ai",
    "type": "endpoint",
    "schedule": "On demand (POST)",
    "triggerPath": "/api/cdc/career-guidance",
    "callsClaude": true,
    "featureKey": "cdc.career_guidance",
    "whatItDoes": "A CDC counsellor picks one student; this gathers that student's career-relevant data (marks, placements, internships, training, aspirations) and asks Claude to produce career paths, skill gaps, next steps, and a list of data the CDC should record. Missing data is surfaced as gaps, not hidden.",
    "configKnobs": "MODEL=claude-sonnet-4-6 (config row 'cdc.career_guidance' — /admin/ai-models), max_tokens=2000, outcome-count tables=[obe_learner_co_marks, cdc_placements, internship_assignments, cdc_training_enrollments]",
    "sideEffects": "Upserts one row per learner into cdc_career_reports (overwrites the previous report — 'keep latest, not history'). No outbound human messages. Only career-relevant non-PII fields sent to the model.",
    "safeToManualTrigger": true,
    "notes": "Requires a logged-in user with cdc.view permission (super-admin/admin bypass built in) and institution scope covering the learner. POST body must include { learnerId }. Needs CLAUDE_API_KEY or ANTHROPIC_API_KEY (503 if missing). GET ?learnerId=<id> returns the last saved report read-only. Reads learner data via service-role client, so the cdc.view gate is the only authorization — do not expose without it. Idempotent: re-running just overwrites the latest report."
  },
  {
    "id": "rcltp-questions-generate",
    "name": "RCLTP AI Question Generation (dormant/scaffolded)",
    "category": "misc-ai",
    "type": "endpoint",
    "schedule": "On demand (POST)",
    "triggerPath": "/api/rcltp/questions/generate",
    "callsClaude": false,
    "featureKey": "rcltp.question_generation",
    "whatItDoes": "Intended to auto-generate Part B comprehension questions from a reading passage for teacher review. Currently a scaffold: it validates access and constructs the Anthropic client but does NOT yet call Claude — it returns an honest 'awaiting EKSAQ content' response because the passage-to-question prompt and competency guardrails are deferred.",
    "configKnobs": "none",
    "sideEffects": "read-only (returns an EKSAQ-gated 501-style response; writes nothing, generates no questions)",
    "safeToManualTrigger": true,
    "notes": "DORMANT. The @anthropic-ai/sdk client is wired (reuses the work-pulse/analyze pattern) but anthropic.messages.create is never invoked — so callsClaude is effectively false today. Requires rcltp.assessment.manage permission and { passage_id }; institution-scoped to the passage (global passages need platform admin). Needs ANTHROPIC_API_KEY/CLAUDE_API_KEY only to construct the client (503 if missing). Will only truly call Claude once the EKSAQ prompt is added."
  },
  {
    "id": "work-pulse-analyze",
    "maxLane": true,
    "name": "Work Pulse Weekly Analysis",
    "category": "misc-ai",
    "type": "endpoint",
    "schedule": "On demand — intended weekly, triggered externally (no Vercel cron wired)",
    "triggerPath": "/api/work-pulse/analyze",
    "callsClaude": true,
    "featureKey": "work_pulse.analyze",
    "whatItDoes": "Pulls the last 7 days of staff 'work pulse' entries plus behavioral activity logs and past patterns, then asks Claude to cluster them into automation/efficiency patterns with impact scores. Updates the pattern board and flags training opportunities.",
    "configKnobs": "MODEL=claude-sonnet-4-20250514 (config row 'work_pulse.analyze' — /admin/ai-models), max_tokens=4096, LLM_TIMEOUT=60000ms, LOOKBACK_DAYS=7, ACTIVITY_LIMIT=500, EXISTING_PATTERNS_LIMIT=50, TIER thresholds S>=100/A>=50/B>=20/else C",
    "sideEffects": "WRITES: inserts/updates rows in wp_patterns; AND for training-type patterns inserts a notifications row + fans out user_notifications to affected users (in-app 'Training Opportunity' notifications). Honest-empty (writes nothing) if no pulse entries in the past 7 days.",
    "safeToManualTrigger": false,
    "notes": "Auth: x-api-key header matching WORK_PULSE_API_KEY, OR a super_admin session. Despite the 'Weekly AI analysis' label there is NO cron for it in vercel.json — it must be fired externally (e.g. n8n/manual). Marked unsafe to fire casually because a run can push in-app training-win notifications to real users and mutate the pattern board; re-running duplicates that. Needs ANTHROPIC_API_KEY/CLAUDE_API_KEY (503 if missing). Max lane: on-demand via the ⚡ button — a Mac-side runner twin executes on the Claude Max subscription (₹0 API) and is guard-idempotent with the API path."
  },
  {
    "id": "work-pulse-translate",
    "name": "Work Pulse Tamil→English Translate",
    "category": "misc-ai",
    "type": "endpoint",
    "schedule": "On demand (POST)",
    "triggerPath": "/api/work-pulse/translate",
    "callsClaude": true,
    "featureKey": "work_pulse.translate",
    "whatItDoes": "Detects whether a work-pulse text is Tamil and, if so, translates it to English via Claude Haiku. Optionally saves the English translation back onto the pulse entry.",
    "configKnobs": "MODEL=claude-haiku-4-5-20251001 (config row 'work_pulse.translate' — /admin/ai-models), max_tokens=1024, TAMIL_THRESHOLD=0.3 (>30% Tamil chars), allowed persist fields=[talent_waste_description_en, repetition_description_en]",
    "sideEffects": "Optionally updates the given _en column on wp_pulse_entries when { pulse_entry_id, field } are supplied; otherwise read-only. No outbound human messages.",
    "safeToManualTrigger": true,
    "notes": "Any authenticated user may call it. POST body needs { text }; add { pulse_entry_id, field } to persist. Non-Tamil text returns translated:false and does nothing. Idempotent — re-running overwrites the same _en field. Needs ANTHROPIC_API_KEY/CLAUDE_API_KEY (503 if missing)."
  },
  {
    "id": "attention-bar-anthropic-client",
    "name": "Attention Bar Layer-4 LLM Client (service)",
    "category": "misc-ai",
    "type": "service",
    "schedule": "On demand — invoked internally per Attention Bar Layer-4 evaluation",
    "triggerPath": "lib/attention-bar/anthropic-client.ts (internal library — no HTTP endpoint)",
    "callsClaude": true,
    "featureKey": "attention_bar.assistant",
    "whatItDoes": "A thin singleton wrapper around Claude Haiku used by the Attention Bar's Layer 4. Given a user's context and an allowlist of quick actions, it forces Claude to pick exactly one action (via strict tool-use) and returns { action_id, reason, usage, model }.",
    "configKnobs": "LAYER_4_MODEL=claude-haiku-4-5-20251001 (config row 'attention_bar.assistant' — /admin/ai-models; fallback stays LAYER_4_MODEL), max_tokens=256, default timeoutMs=8000, tool_choice forced to 'pick_action', system+tools cache_control=ephemeral (5-min prompt cache)",
    "sideEffects": "read-only — makes one LLM call and returns a normalized result; writes no DB rows and sends no messages itself.",
    "safeToManualTrigger": false,
    "notes": "Not an HTTP route — it is a library module called by the Layer-4 resolver, so there is no operator URL to hit directly. Requires ANTHROPIC_API_KEY (throws/fails fast if unset; Layer 4 then falls through to Layer 1). Enforces allowlist enum on the tool spec as first-line defense; the evaluator double-checks the returned action_id. Has test seams (_setLLMStub, _resetAnthropicClient) that production never calls."
  },
  {
    "id": "cohort-moat-autopropose",
    "name": "Cohort Moat — Auto-Propose on Cohort Close",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 05:43 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/cohort-moat-autopropose",
    "callsClaude": false,
    "whatItDoes": "Keeps the Cohort Moat's self-improving loop alive. For every CLOSED Solve-for-100 cohort that has no open suggestion yet, it assigns experiment arms (backstop), computes the causal lift (treatment vs control), and — if the result clears the trust gate — queues a feed-forward adjustment PROPOSAL for a human to approve. Without this, the loop only produces suggestions when an admin manually clicks 'check for adjustments', so it silently sits idle.",
    "configKnobs": "Only CLOSED cohorts (status completed/archived) are considered; a causal lift is trusted only with >= 3 scored members per arm (fn_cohort_min_arm_n); the tested treatment is read from cohorts.config.experiment.treatment_params. No model, no thresholds beyond the DB gates.",
    "sideEffects": "DB writes only: may INSERT one status='pending' row into cohort_adjustment_proposals per closed cohort (proposed_by NULL = system-generated). NEVER auto-applies — a human must approve (M7) before any program change lands. Idempotent: skips cohorts that already have an open/applied proposal (a partial unique index also enforces one-open-per-cohort). No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'cohort-moat-autopropose' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer or ?secret=). Safe to manual-trigger: it only queues PENDING suggestions (no auto-apply, no messages), and re-running is a no-op for cohorts that already have one. Does nothing at all until a cohort genuinely closes with both arms scored."
  },
  {
    "id": "overnight-bugfix",
    "maxLane": true,
    "name": "Overnight Bug-Fixer (draft-PR pipeline)",
    "category": "misc-ai",
    "type": "service",
    "schedule": "Nightly · 22:00 IST · Mac launchd (com.local.overnight-v2)",
    "triggerPath": "/api/admin/ai-routines/max-run",
    "callsClaude": true,
    "whatItDoes": "While everyone sleeps, it picks up to 3 of the oldest open bugs from /admin/bug-reports, verifies each is STILL a bug in today's code (liveness gate: merged-PR search + in-code reproduction), fixes it in an isolated worktree off production main, runs the repo's bespoke CI gates locally (Step 2.7 mirror: nav-config, radix, permissions-catalog + PR-scoped typecheck), and opens a DRAFT pull request. It never merges — a human reviews in the morning.",
    "configKnobs": "MAX_BUGS=3/night (⚡ button runs 1), BUG_TIMEOUT=20min/bug, MODEL=sonnet (headless claude -p on the Max subscription — dev tooling, not product AI), forbidden paths: auth/middleware/migrations/RLS/payment/admin; routable modules mirror /fixmyjkkn",
    "sideEffects": "Opens DRAFT PRs on GitHub (Jicate-Solutions/MyJKKN) and comments on duplicates. NEVER merges, never touches production data — the bug board is read-only to it. Telegram summary per run.",
    "safeToManualTrigger": true,
    "notes": "Runs on the Mac via launchd, not Vercel — the ⚡ Run-on-Max button queues a max_lane_requests row that the Mac poller claims (button run = 1 bug, capped 30 min). Welded 2026-07-08 with the loopcraft MetaLoop: dedupe vs open PRs, gate-mirror before push, engine-limit alarm. Companion routine: overnight-judge."
  },
  {
    "id": "overnight-judge",
    "maxLane": true,
    "name": "Overnight Morning Judge (PR pile MetaLoop)",
    "category": "misc-ai",
    "type": "service",
    "schedule": "Daily · 07:15 IST · Mac launchd (com.local.overnight-judge)",
    "triggerPath": "/api/admin/ai-routines/max-run",
    "callsClaude": false,
    "whatItDoes": "The review half of the overnight loop: every morning it sweeps the open overnight PRs — closes exact duplicates (identical files + same symptom, keeps the newest), warns when two drafts touch the same file, flips clean backend-only fixes to Ready (using the Visual Proof Gate's own classifier), snapshots CI after the flip, and publishes a daily verdict to the live artifact page plus a Telegram digest. Humans stay the only merge authority.",
    "configKnobs": "Duplicate rule: identical changed-file set + title similarity >= 0.4; ready-flip only for zero-rendering-surface diffs (NON_UI_REGEX verbatim from visual-proof-gate.yml); JUDGE_MODE=dry prints the plan without acting.",
    "sideEffects": "GitHub only: closes duplicate DRAFT PRs (reversible, with explanatory comment), adds visual-proof-skip labels, flips drafts to Ready, comments on overlaps. Never merges. Telegram digest + artifact update.",
    "safeToManualTrigger": true,
    "notes": "Fully mechanical (bash + gh + python, no LLM) — it keeps working even when the Claude subscription is rate-limited. Runs on the Mac via launchd; the ⚡ button queues an on-demand pass through the same Mac poller. Built 2026-07-08 as loopcraft level-4 (spawn/review/respawn) over the nightly fixer."
  }
];
