import { type AIRoutine } from './types';
// Populated 2026-07-01 from the parallel discovery swarm (deep-read of jicate/main).
export const MISC_AI_ROUTINES: AIRoutine[] = [
  {
    "id": "social-engagement-nudges",
    "name": "Department IG Engagement Nudges",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 09:30 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/social-nudges",
    "callsClaude": false,
    "whatItDoes": "Two adoption nudges that keep the department-Instagram engagement loop alive: (1) a weekly 'it's your week to post for @handle' reminder to the assigned contributor, and (2) a recognition nudge when a posted contribution earns real signal (saves+shares+comments — never likes): 'your post earned N real-signal'. Without these the loop is silent and sits at 0% adoption.",
    "configKnobs": "Monday snap = Asia/Kolkata; recognition floor = real_signal >= 1; realSignal = saves+shares+comments (likes excluded). No model, no thresholds.",
    "sideEffects": "WRITES in-app notifications (notifications + user_notifications fan-out) to contributors. Idempotent: reminded_at (rota) + signal_notified_at (contribution) guard exactly one delivery each. No external messages (no email/WhatsApp/push).",
    "safeToManualTrigger": false,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'social-engagement-nudges' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer or ?secret=). Marked unsafe-to-manual because a run delivers real notifications to real contributors; re-running is safe (idempotent — repeats surface as 'duplicate' counts, deliver nothing new)."
  },
  {
    "id": "cdc-career-guidance",
    "name": "CDC AI Career Guidance",
    "category": "misc-ai",
    "type": "endpoint",
    "schedule": "On demand (POST)",
    "triggerPath": "/api/cdc/career-guidance",
    "callsClaude": true,
    "featureKey": "cdc.career_guidance",
    "whatItDoes": "A CDC counsellor picks one student; this gathers that student's career-relevant data (marks, placements, internships, training, aspirations) and asks Claude to produce career paths, skill gaps, next steps, and a list of data the CDC should record. Missing data is surfaced as gaps, not hidden.",
    "configKnobs": "MODEL=claude-sonnet-4-6 (config row 'cdc.career_guidance' — /admin/ai-models), max_tokens=2000, outcome-count tables=[obe_learner_co_marks, cdc_placements, internship_assignments, cdc_training_enrollments]",
    "sideEffects": "Upserts one row per learner into cdc_career_reports (overwrites the previous report — 'keep latest, not history'). No outbound human messages. Only career-relevant non-PII fields sent to the model.",
    "safeToManualTrigger": true,
    "notes": "Requires a logged-in user with cdc.view permission (super-admin/admin bypass built in) and institution scope covering the learner. POST body must include { learnerId }. Needs CLAUDE_API_KEY or ANTHROPIC_API_KEY (503 if missing). GET ?learnerId=<id> returns the last saved report read-only. Reads learner data via service-role client, so the cdc.view gate is the only authorization — do not expose without it. Idempotent: re-running just overwrites the latest report."
  },
  {
    "id": "rcltp-questions-generate",
    "name": "RCLTP AI Question Generation (dormant/scaffolded)",
    "category": "misc-ai",
    "type": "endpoint",
    "schedule": "On demand (POST)",
    "triggerPath": "/api/rcltp/questions/generate",
    "callsClaude": false,
    "featureKey": "rcltp.question_generation",
    "whatItDoes": "Intended to auto-generate Part B comprehension questions from a reading passage for Senior Learner review. Currently a scaffold: it validates access and constructs the Anthropic client but does NOT yet call Claude — it returns an honest 'awaiting MyJKKN content' response because the passage-to-question prompt and competency guardrails are deferred.",
    "configKnobs": "none",
    "sideEffects": "read-only (returns an MyJKKN-gated 501-style response; writes nothing, generates no questions)",
    "safeToManualTrigger": true,
    "notes": "DORMANT. The @anthropic-ai/sdk client is wired (reuses the work-pulse/analyze pattern) but anthropic.messages.create is never invoked — so callsClaude is effectively false today. Requires rcltp.assessment.manage permission and { passage_id }; institution-scoped to the passage (global passages need platform admin). Needs ANTHROPIC_API_KEY/CLAUDE_API_KEY only to construct the client (503 if missing). Will only truly call Claude once the MyJKKN prompt is added."
  },
  {
    "id": "work-pulse-analyze",
    "maxLane": true,
    "name": "Work Pulse Weekly Analysis",
    "category": "misc-ai",
    "type": "endpoint",
    "schedule": "On demand — intended weekly, triggered externally (no Vercel cron wired)",
    "triggerPath": "/api/work-pulse/analyze",
    "callsClaude": true,
    "featureKey": "work_pulse.analyze",
    "whatItDoes": "Pulls the last 7 days of staff 'work pulse' entries plus behavioral activity logs and past patterns, then asks Claude to cluster them into automation/efficiency patterns with impact scores. Updates the pattern board and flags training opportunities.",
    "configKnobs": "MODEL=claude-sonnet-4-20250514 (config row 'work_pulse.analyze' — /admin/ai-models), max_tokens=4096, LLM_TIMEOUT=60000ms, LOOKBACK_DAYS=7, ACTIVITY_LIMIT=500, EXISTING_PATTERNS_LIMIT=50, TIER thresholds S>=100/A>=50/B>=20/else C",
    "sideEffects": "WRITES: inserts/updates rows in wp_patterns; AND for training-type patterns inserts a notifications row + fans out user_notifications to affected users (in-app 'Training Opportunity' notifications). Honest-empty (writes nothing) if no pulse entries in the past 7 days.",
    "safeToManualTrigger": false,
    "notes": "Auth: x-api-key header matching WORK_PULSE_API_KEY, OR a super_admin session. Despite the 'Weekly AI analysis' label there is NO cron for it in vercel.json — it must be fired externally (e.g. n8n/manual). Marked unsafe to fire casually because a run can push in-app training-win notifications to real users and mutate the pattern board; re-running duplicates that. Needs ANTHROPIC_API_KEY/CLAUDE_API_KEY (503 if missing). Max lane: on-demand via the ⚡ button — a Mac-side runner twin executes on the Claude Max subscription (₹0 API) and is guard-idempotent with the API path."
  },
  {
    "id": "work-pulse-translate",
    "maxLane": true,
    "name": "Work Pulse Tamil→English Translate",
    "category": "misc-ai",
    "type": "endpoint",
    "schedule": "On demand (POST)",
    "triggerPath": "/api/work-pulse/translate",
    "callsClaude": true,
    "featureKey": "work_pulse.translate",
    "whatItDoes": "Detects whether a work-pulse text is Tamil and, if so, translates it to English via Claude Haiku. Optionally saves the English translation back onto the pulse entry.",
    "configKnobs": "MODEL=claude-haiku-4-5-20251001 (config row 'work_pulse.translate' — /admin/ai-models), max_tokens=1024, TAMIL_THRESHOLD=0.3 (>30% Tamil chars), allowed persist fields=[talent_waste_description_en, repetition_description_en]",
    "sideEffects": "Optionally updates the given _en column on wp_pulse_entries when { pulse_entry_id, field } are supplied; otherwise read-only. No outbound human messages.",
    "safeToManualTrigger": true,
    "notes": "Any authenticated user may call it. POST body needs { text }; add { pulse_entry_id, field } to persist. Non-Tamil text returns translated:false and does nothing. Idempotent — re-running overwrites the same _en field. Needs ANTHROPIC_API_KEY/CLAUDE_API_KEY (503 if missing). Max lane: backlog drain rides the Max lane (⚡ = translate all pending Tamil entries — wp_pulse_entries rows whose source text is Tamil-detected but _en column is NULL — via a runner brain on the seat, ₹0 API; brain pending next iteration); the live per-click path in the work-pulse page stays on the API. Backlog measured 2026-07-12: 0 pending (18 pulse rows total, none Tamil) — a ⚡ run is honest-empty until Tamil pulses arrive."
  },
  {
    "id": "attention-bar-anthropic-client",
    "maxLane": true,
    "name": "Attention Bar Layer-4 Action Picker (service)",
    "category": "misc-ai",
    "type": "service",
    "schedule": "On demand — invoked internally per Attention Bar Layer-4 evaluation",
    "triggerPath": "lib/attention-bar/anthropic-client.ts (internal library — no HTTP endpoint)",
    "callsClaude": true,
    "featureKey": "attention_bar.assistant",
    "whatItDoes": "The Attention Bar's Layer 4 action picker. Given the on-screen context and an allowlist of quick actions, it enqueues an attention_bar.assistant registry job (Max lane) carrying exactly { actions, context } and long-polls fn_ai_job_status for the pick, returning { action_id, reason, usage, model }. Page-context feature — the model is handed all its data, so the job runs with tool_set=none.",
    "configKnobs": "Registry-governed: prompt_template + tool_set (none) + input_schema live in ai_job_types row 'attention_bar.assistant' (set by orchestrator). Payload keys: actions, context. Poll: 2s cadence, 90s unclaimed deadline, 170s total (< resolve route maxDuration 180). No in-process model/token knobs — usage is ₹0 (Max subscription, recorded runner-side).",
    "sideEffects": "read-only — enqueues one job and returns a normalized pick; writes no feature DB rows and sends no messages itself.",
    "safeToManualTrigger": false,
    "notes": "Not an HTTP route — it is a library module called by the Layer-4 resolver via /api/attention-bar/resolve, so there is no operator URL to hit directly. Converted 2026-07-13 off direct Anthropic onto the #1998 AI-jobs registry (fn_ai_enqueue + fn_ai_job_status), mirroring app/api/work-pulse/translate/route.ts. Any enqueue/poll failure throws and Layer 4 falls open to the Layer 1 static default — that built-in cascade is the 'if slow' path (no separate inbox for an ephemeral pill). Layer 4 only fires when L0/L2/L3/L1 all returned nothing (< 2% of resolves). Has test seams (_setLLMStub, _resetAnthropicClient) that production never calls."
  },
  {
    "id": "cohort-moat-autopropose",
    "name": "Cohort Moat — Auto-Propose on Cohort Close",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 05:43 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/cohort-moat-autopropose",
    "callsClaude": false,
    "whatItDoes": "Keeps the Cohort Moat's self-improving loop alive. For every CLOSED Solve-for-100 cohort that has no open suggestion yet, it assigns experiment arms (backstop), computes the causal lift (treatment vs control), and — if the result clears the trust gate — queues a feed-forward adjustment PROPOSAL for a human to approve. Without this, the loop only produces suggestions when an admin manually clicks 'check for adjustments', so it silently sits idle.",
    "configKnobs": "Only CLOSED cohorts (status completed/archived) are considered; a causal lift is trusted only with >= 3 scored members per arm (fn_cohort_min_arm_n); the tested treatment is read from cohorts.config.experiment.treatment_params. No model, no thresholds beyond the DB gates.",
    "sideEffects": "DB writes only: may INSERT one status='pending' row into cohort_adjustment_proposals per closed cohort (proposed_by NULL = system-generated). NEVER auto-applies — a human must approve (M7) before any program change lands. Idempotent: skips cohorts that already have an open/applied proposal (a partial unique index also enforces one-open-per-cohort). No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'cohort-moat-autopropose' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer or ?secret=). Safe to manual-trigger: it only queues PENDING suggestions (no auto-apply, no messages), and re-running is a no-op for cohorts that already have one. Does nothing at all until a cohort genuinely closes with both arms scored."
  },
  {
    "id": "accreditation-committee-ai-drafts",
    "name": "Accreditation — AI Committee Assistant (agenda papers · sitting proposal · minutes prose)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 04:13 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/accreditation-committee-ai-drafts",
    "callsClaude": true,
    "whatItDoes": "Takes the desk work out of a committee sitting. Before a scheduled sitting it drafts the pre-meeting brief plus a proposed agenda; after a sitting it turns the decisions already entered into the formal minutes prose; and for a committee overdue by its configured cadence it proposes a sitting date. A human okays or confirms every one of the three — nothing is final without a person, and nothing is sent to anyone.",
    "configKnobs": "accreditation.meeting.agenda_lead_days=3 (how early the agenda is drafted), accreditation.meeting.cadence_days=90 (when a committee counts as overdue), accreditation.meeting.proposal_enabled=false (master switch for sitting proposals — OFF by default). Both AI job types ship DARK (ai_job_types.enabled=false): accreditation.cac_brief and accreditation.meeting_minutes_polish. Runs on the ₹0 Max lane (provider=anthropic, model_id='sonnet' family alias).",
    "sideEffects": "DB writes only, all human-gated. Upserts ai_drafted rows into accreditation_meeting_drafts and ai_proposed rows into accreditation_meeting_proposals, and enqueues ai_jobs on the Max lane. It NEVER creates a meeting, never writes minutes_summary, and never touches the Universal Booking engine (meeting_bookings / meeting_agendas / the webhook dispatcher / calendar sync) — that engine invites real people. NO notifications, NO emails, NO invites. Only a convener pressing Confirm creates a sitting.",
    "safeToManualTrigger": true,
    "notes": "Fires via the AI-routine dispatcher (ai_routine_schedules row 'accreditation-committee-ai-drafts' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer ONLY, constant-time — no ?secret= query param). Safe to manual-trigger: idempotent (one draft per meeting+kind, one pending proposal per committee, both guarded by unique keys) and a no-op while the job types are DARK. Three deterministic gates run on every model draft before a human can okay it: the grounding validator (no invented fact), the forbidden-agenda gate (no platform-readable figure on an agenda — the Director's doctrine), and an omission check (the minutes may not silently drop a resolution).",
    "maxLane": true
  },
  {
    "id": "accreditation-loop-evidence",
    "name": "Accreditation — Loop→AQAR Evidence Rollup (NAAC 7.3 Quality Assurance System)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 04:23 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/accreditation-loop-evidence",
    "callsClaude": false,
    "whatItDoes": "Turns every measured self-improving-loop cycle into NAAC Metric 7.3 'Quality Assurance System' accreditation evidence (Binary Accreditation Framework 2024, Attribute 7: Governance; maps to Criterion 6.5 IQAC under the outgoing framework). Each night it sweeps the four quality loops — SCF teaching suggestions, induction session-effectiveness, the induction annual playbook, and the mess Choose-Your-Menu loop — and upserts one quality_evidence_mappings row per measured outcome (baseline, result, lift, Better/Same/Worse votes) so the AQAR narrative is backed by live machine-measured evidence instead of nothing.",
    "configKnobs": "Metric mapping pinned: scf_teaching + mess_menu → 7.3.f (periodic stakeholder satisfaction with feedback), induction_session + induction_playbook → 7.3.d (audits & performance assessment fed back to the system); 7.3.e seeded RESERVED (the loop practice itself — /admin/loops Control Tower; no per-row emission). Only MEASURED cycles emit (outcome_measured_at / measured_at set); rows with no derivable institution are skipped. period_label = 'AY YYYY-YY' (June cutoff, IST). No model, no thresholds.",
    "sideEffects": "DB writes only: upserts is_auto=true rows into quality_evidence_mappings (NAAC / 7.3.d / 7.3.f), refreshing metadata + mapped_at on re-run. NEVER touches manually-curated (is_auto=false) mappings. No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'accreditation-loop-evidence' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer ONLY, constant-time — no ?secret= query param). Safe to manual-trigger: fully idempotent — re-running refreshes the same evidence rows (natural key source_table+source_id+body_code+metric_code). Loop→AQAR bridge PR 1/2; PR 2 renders these rows in the /accreditation UI by loop_key."
  },
  {
    "id": "coe-result-naac-snapshots",
    "name": "Accreditation — COE Pass-Percentage Mirror (NAAC 8.2.2)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 04:51 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/coe-result-naac-snapshots",
    "callsClaude": false,
    "whatItDoes": "Each night it mirrors the COE exam system's declared university-exam results into the accreditation evidence spine: it reads COE's per-course final-marks summary view directly from the COE database (cross-project, server-side credentials), aggregates pass percentage per institution per examination session, writes coe_naac_evidence snapshot rows (fanning the CAS campus numbers out to both its MyJKKN institutions), and maps each row to NAAC Metric 8.2.2 'Pass percentage in university examinations' in quality_evidence_mappings — so the pass-percentage narrative is backed by live COE numbers instead of nothing.",
    "configKnobs": "Emission gate pinned: only sessions with published results emit (published_count > 0 — planned/empty sessions produce nothing). Denominator = published learner-course entries; pass % = passed/published, recorded with all raw counts in row metadata. Exam-calendar adherence (deck metric 5.7) is deliberately NOT computed: COE's published_date is NULL on every final-marks row and result_declaration_date is a backfill artifact — no honest day count exists. period_label = 'AY YYYY-YY' from the session's exam window (June cutoff), falling back to the session code. No model, no thresholds.",
    "sideEffects": "DB writes only: upserts coe_naac_evidence snapshot rows (one per MyJKKN institution × metric × COE examination session) and is_auto=true quality_evidence_mappings rows (NAAC 8.2.2), refreshing metadata on re-run. NEVER touches manually-curated (is_auto=false) mappings (pre-excluded before the upsert). Aggregate counts only — no learner identities. Read-only against the COE database. No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'coe-result-naac-snapshots' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer ONLY, constant-time — no ?secret= query param). Requires the server-only COE_SUPABASE_URL + COE_SUPABASE_SERVICE_ROLE_KEY env vars (fails closed with 503 when absent — already set in Vercel prod, verified 2026-07-06). Safe to manual-trigger: fully idempotent — re-running refreshes the same snapshot + evidence rows (snapshot natural key institution_id+metric_code+session_code; junction natural key source_table+source_id+body_code+metric_code). Wave 3 of the module→evidence-spine integration."
  },
  {
    "id": "hr-naac-evidence",
    "name": "Accreditation — HR Evidence Snapshots (NAAC 2.1 / 2.2.x / 7.10.1)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 04:37 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/hr-naac-evidence",
    "callsClaude": false,
    "whatItDoes": "Recomputes one hr_naac_evidence snapshot per institution (its active Senior Learners) for the current academic year and upserts the matching quality_evidence_mappings rows: NAAC 2.1 Senior Learner-to-learner ratio (FSR), 2.2.1 cadre strength vs sanctioned posts, 2.2.2 Senior Learner PhD %, 2.2.3 average teaching experience + cadre-level distribution, and 7.10.1 three-year Senior Learner retention. HR records become live accreditation evidence instead of a manual spreadsheet exercise.",
    "configKnobs": "Teaching head-count = employment_categories.is_teaching AND the HR profile's is_active flag (role_type reads 'teacher' for everyone, including drivers — not used). Learners = learners_profiles.lifecycle_status='active'. Cadre from designation pattern match (legacy 'Reader' counts as associate level). 2.2.1 emits ONLY for institutions with sanctioned_posts rows for the current AY (managed at /hr/admin/sanctioned-posts) — never zeroed or faked. period_label = 'AY YYYY-YY' (June cutoff, IST). No model, no thresholds.",
    "sideEffects": "DB writes only: upserts hr_naac_evidence snapshots (one per institution per AY) and is_auto=true rows into quality_evidence_mappings (NAAC 2.1 / 2.2.1 / 2.2.2 / 2.2.3 / 7.10.1), refreshing metadata + mapped_at on re-run and withdrawing its own stale auto rows when an emit-condition stops holding. NEVER touches manually-curated (is_auto=false) mappings. No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'hr-naac-evidence' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer ONLY, constant-time — no ?secret= query param). Safe to manual-trigger: fully idempotent — snapshots upsert on (institution_id, academic_year), mappings on the junction natural key. Wave 2A of the module→evidence-spine integration; same snapshot-table pattern as obe_course_attainment_rollup."
  },
  {
    "id": "facility-teaching-naac-snapshots",
    "name": "Accreditation — Teaching & Facilities Evidence Snapshots (NAAC 5.1.1 / 3.1.1 / 3.4.1)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 04:37 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/facility-teaching-naac-snapshots",
    "callsClaude": false,
    "whatItDoes": "Each night it computes per-institution NAAC evidence snapshots from live module data: lesson-plan / pedagogy-tagging coverage from the lesson spine (Metric 5.1.1), facilities-in-daily-use from the resource registry plus hostel/mess/health/sports activity counts (Metric 3.1.1), and IT infrastructure with the learner:computer ratio from the resource registry's 'IT & Digital Resources' category (Metric 3.4.1). Each snapshot row fans out to quality_evidence_mappings so the accreditation narrative is backed by live counts instead of nothing.",
    "configKnobs": "Emission gates pinned: no lessons → no 5.1.1 row; no resources → no 3.1.1 row; no IT/computing resources → no 3.4.1 row (nothing fabricated for thin institutions). IT source is the resource registry — ims_item_categories carries no computing categories (surveyed 2026-07-26), so the IMS path is skipped. Ratio only where computer units > 0; units = sum(coalesce(current_stock_quantity, 1)). period_label = 'AY YYYY-YY' (June cutoff, IST). No model, no thresholds.",
    "sideEffects": "DB writes only: upserts facility_teaching_naac_evidence snapshot rows (one per institution × metric × AY) and is_auto=true quality_evidence_mappings rows (NAAC 5.1.1 / 3.1.1 / 3.4.1), refreshing metadata + mapped_at on re-run. NEVER touches manually-curated (is_auto=false) mappings. Counts only — no Senior Learner or learner identities. No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'facility-teaching-naac-snapshots' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer ONLY, constant-time — no ?secret= query param). Safe to manual-trigger: fully idempotent — re-running refreshes the same snapshot + evidence rows (snapshot natural key institution_id+metric_code+ay_label; junction natural key source_table+source_id+body_code+metric_code). Wave 2B of the module→evidence-spine integration."
  },
  {
    "id": "event-feedback-naac-evidence",
    "name": "Accreditation — Event Feedback Satisfaction Snapshots (NAAC 7.3.f)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 05:19 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/event-feedback-naac-evidence",
    "callsClaude": false,
    "whatItDoes": "Turns the events module's three feedback channels — session, day and programme — into NAAC 7.3.f evidence of a periodic stakeholder satisfaction survey. Each night it aggregates every rating per institution per academic year into response counts, distinct-respondent counts, events covered, per-channel and overall mean rating, satisfied share (rating >= 4) and the year-on-year trend, then maps that snapshot into quality_evidence_mappings. Before this, 12,510 live feedback rows reached the accreditation spine as nothing at all, because the events emitter only fires on events a human has hand-tagged with NAAC criteria and none of these were.",
    "configKnobs": "K-anonymity floor k=5, hardcoded — deliberately NOT a platform_policies row, because a floor an operator can lower to 1 is not a floor. No rating-derived statistic is stored below k, and the overall mean/share is additionally withheld unless the pooled below-k channels are empty or themselves >= k (complementary suppression, so no hidden channel mean is recoverable by subtraction). Satisfied = rating >= 4 on the live 1-5 integer scale. period_label = 'AY YYYY-YY' (June cutoff, IST) via fn_accreditation_ay_label. Trend noise band = ±0.05 rating points. No model, no thresholds.",
    "sideEffects": "DB writes only: upserts event_feedback_naac_evidence snapshots (one per institution per academic year) and is_auto=true quality_evidence_mappings rows (NAAC 7.3.f), refreshing metadata + mapped_at on re-run. A snapshot whose source feedback has disappeared is zeroed and its auto mapping withdrawn, so a zero never stands in as survey evidence. NEVER touches manually-curated (is_auto=false) mappings and never collides with the existing 7.3.f rows from scf_ai_suggestions (different source_table in the junction's natural key). Counts and means only — free-text comments are never read, and learner identities appear only inside count(DISTINCT ...). No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'event-feedback-naac-evidence' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer ONLY, constant-time — no ?secret= query param). Safe to manual-trigger: fully idempotent — snapshots upsert on (institution_id, academic_year), mappings on the junction natural key source_table+source_id+body_code+metric_code. Honest gating: an institution with no feedback for an academic year gets no snapshot and no evidence row. Wave 2C of the module→evidence-spine integration; same snapshot-table pattern as hr_naac_evidence."
  },
  {
    "id": "sustainability-naac-evidence",
    "name": "Accreditation — Sustainability Evidence Snapshots (NAAC 10.2 / 10.3)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 05:05 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/sustainability-naac-evidence",
    "callsClaude": false,
    "whatItDoes": "Reads the monthly utility meter register (electricity kWh, water kL, waste kg, solar kWh generated — entered per campus per month at /accreditation/manage/utility-readings) and computes one sustainability_naac_evidence snapshot per campus per academic year, then upserts the matching quality_evidence_mappings rows: NAAC 10.2 water & waste management, and 10.3 progress towards net zero. 10.3 is a DIRECTION, not a level — each campus is compared against its own prior months, because the assessment rewards progressing towards net zero rather than a one-off figure. This is the only substrate Attribute 10 has: before it, that attribute held zero evidence rows on prod.",
    "configKnobs": "platform_policies 'sustainability.min_months_for_trend' (default 2) is the honest-gating threshold. HONEST GATES, all three deliberate: a campus with NO readings in the AY gets no snapshot and no evidence row (absence, never a fabricated zero); 10.2 emits only when water and/or waste has been reported for at least that many distinct months; 10.3 emits only when electricity has enough months AND a direction is computable (year-on-year AVERAGE PER REPORTED MONTH when a prior AY exists, else first-vs-latest month inside this AY — raw totals are never compared, since a partial current year would report a fake ±80% swing). Expect 'skipped_thin' to be high in the first months of entry: that is correct behaviour, not a failure. NAAC 10.4 is NOT emitted here — it comes from a closed audit_cycles row with module_key='sustainability' via fn_sync_audit_cycle_evidence. period_label = 'AY YYYY-YY' (June cutoff, IST). No model, no LLM.",
    "sideEffects": "DB writes only: upserts sustainability_naac_evidence snapshots (one per campus per AY, and only for campuses that reported) and is_auto=true rows into quality_evidence_mappings (NAAC 10.2 / 10.3), refreshing metadata + mapped_at on re-run and withdrawing its own stale auto rows per metric when a gate stops holding (e.g. readings deleted → the metric disappears rather than dropping to zero). NEVER touches manually-curated (is_auto=false) mappings. Meter totals only — no learner or Senior Learner identities. No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'sustainability-naac-evidence' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer ONLY, constant-time — no ?secret= query param). Safe to manual-trigger: fully idempotent — snapshots upsert on (institution_id, academic_year), mappings on the junction natural key. Depends entirely on a named person per campus entering four numbers each month; if the register stays empty the routine correctly emits nothing. Attribute 10 green substrate; same snapshot-table pattern as hr-naac-evidence."
  },
  {
    "id": "overnight-bugfix",
    "maxLane": true,
    "name": "Overnight Bug-Fixer (draft-PR pipeline)",
    "category": "misc-ai",
    "type": "service",
    "schedule": "Nightly · 22:00 IST · Mac launchd (com.local.overnight-v2)",
    "triggerPath": "/api/admin/ai-routines/max-run",
    "callsClaude": true,
    "whatItDoes": "While everyone sleeps, it picks up to 3 of the oldest open bugs from /admin/bug-reports, verifies each is STILL a bug in today's code (liveness gate: merged-PR search + in-code reproduction), fixes it in an isolated worktree off production main, runs the repo's bespoke CI gates locally (Step 2.7 mirror: nav-config, radix, permissions-catalog + PR-scoped typecheck), and opens a DRAFT pull request. It never merges — a human reviews in the morning.",
    "configKnobs": "MAX_BUGS=3/night (⚡ button runs 1), BUG_TIMEOUT=20min/bug, MODEL=sonnet (headless claude -p on the Max subscription — dev tooling, not product AI), forbidden paths: auth/middleware/migrations/RLS/payment/admin; routable modules mirror /fixmyjkkn",
    "sideEffects": "Opens DRAFT PRs on GitHub (Jicate-Solutions/MyJKKN) and comments on duplicates. NEVER merges, never touches production data — the bug board is read-only to it. Telegram summary per run.",
    "safeToManualTrigger": true,
    "notes": "Runs on the Mac via launchd, not Vercel — the ⚡ Run-on-Max button queues a max_lane_requests row that the Mac poller claims (button run = 1 bug, capped 30 min). Welded 2026-07-08 with the loopcraft MetaLoop: dedupe vs open PRs, gate-mirror before push, engine-limit alarm. Companion routine: overnight-judge."
  },
  {
    "id": "overnight-judge",
    "maxLane": true,
    "name": "Overnight Morning Judge (PR pile MetaLoop)",
    "category": "misc-ai",
    "type": "service",
    "schedule": "Daily · 07:15 IST · Mac launchd (com.local.overnight-judge)",
    "triggerPath": "/api/admin/ai-routines/max-run",
    "callsClaude": false,
    "whatItDoes": "The review half of the overnight loop: every morning it sweeps the open overnight PRs — closes exact duplicates (identical files + same symptom, keeps the newest), warns when two drafts touch the same file, flips clean backend-only fixes to Ready (using the Visual Proof Gate's own classifier), snapshots CI after the flip, and publishes a daily verdict to the live artifact page plus a Telegram digest. Humans stay the only merge authority.",
    "configKnobs": "Duplicate rule: identical changed-file set + title similarity >= 0.4; ready-flip only for zero-rendering-surface diffs (NON_UI_REGEX verbatim from visual-proof-gate.yml); JUDGE_MODE=dry prints the plan without acting.",
    "sideEffects": "GitHub only: closes duplicate DRAFT PRs (reversible, with explanatory comment), adds visual-proof-skip labels, flips drafts to Ready, comments on overlaps. Never merges. Telegram digest + artifact update.",
    "safeToManualTrigger": true,
    "notes": "Fully mechanical (bash + gh + python, no LLM) — it keeps working even when the Claude subscription is rate-limited. Runs on the Mac via launchd; the ⚡ button queues an on-demand pass through the same Mac poller. Built 2026-07-08 as loopcraft level-4 (spawn/review/respawn) over the nightly fixer."
  },
  {
    "id": "cdc-placement-outcomes",
    "name": "CDC Placement-Outcome Measure (gates ①③ — DARK)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Weekly · Sun 03:15 IST via dispatcher (effectively monthly — idempotent per calendar-month window)",
    "triggerPath": "/api/cron/cdc-placement-outcomes",
    "callsClaude": false,
    "whatItDoes": "Measures each graduating cohort's (program × passing-out year) placement + higher-studies conversion from alumni_outcomes, compares it against the prior cohort's baseline, and files the result as NAAC 8.2.1 evidence ('Placement + higher studies progression' — the NIRF GO parameter, ~20-25% of the NIRF score). Measurement + evidence only: nobody acts on the deltas yet — that needs a named CDC owner (Director decision pending), so this is honestly NOT a self-improving loop today.",
    "configKnobs": "cdc_placement_loop.master_enabled=false (DARK — config row), cdc_placement_loop.min_cohort_size=10 (config row; labeling threshold — smaller cohorts are computed but flagged small_cohort per Director decision 2026-07-09 'Compute, but label small group'), delta deadband=±2.0pp on progression rate (fixed in fn), June AY cutoff",
    "sideEffects": "WRITES cdc_placement_outcome_cycles (one row per cohort per month, change-only; cohort AGGREGATES only, never per-student rows) and upserts quality_evidence_mappings (NAAC 8.2.1, is_auto=true, small_cohort flag in metadata). No notifications, no human messages. Full no-op while dark.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'cdc-placement-outcomes'), NOT a raw vercel.json cron. Auth: CRON_SECRET. Idempotent: re-runs within the same IST month update the same cycle rows; identical re-measures write nothing. Both data sources (cdc_placements, alumni_outcomes) had 0 rows at build time (2026-07-09) — the machinery is dark and honest about it."
  },
  {
    "id": "copo-attainment",
    "name": "CO/PO Attainment Loop — COE→OBE Direct Rollup (NBA)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Weekly · Sun 03:41 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/copo-attainment",
    "callsClaude": false,
    "whatItDoes": "The measurement leg of the NBA outcome-attainment loop. Weekly it syncs course outcomes from BoS syllabi into obe_course_outcomes, reads per-student marks READ-ONLY from the COE database for each institution's current exam term, computes per-course direct attainment (% of learners at/above the configured threshold, CIA + declared results), stores the trend vs the prior term, and emits accreditation evidence (NAAC 7.3.d + NBA T1_CO). HONEST GRAIN: COE has no assessment→CO tagging, so every number is a course-level proxy (grain=course_proxy, co_tagged=false, machine-readable) — never presented as CO-tagged attainment.",
    "configKnobs": "All methodology numbers are platform_policies rows (copo_attainment.*): master_enabled=false (DARK); threshold_pct is PER-COLLEGE — global row = FALLBACK 60, each college's Academic Council ratifies its own institution-scoped override row which wins (fn_get_policy precedence); direct_weight=0.8 + indirect_weight=0.2 RATIFIED by Director 2026-07-09 (indirect side remains OFF until poll data matures); target_level=2 and level bands 70/60/50 are DEFAULTS awaiting ratification.",
    "sideEffects": "DB writes only, all in MyJKKN (COE is read-only, never written): upserts obe_course_outcomes (never overwrites existing COs), obe_course_attainment_rollup, and is_auto=true quality_evidence_mappings rows (NAAC 7.3.d + NBA T1_CO, loop_key copo_attainment). Never clobbers manually-curated (is_auto=false) mappings. No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'copo-attainment' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer or ?secret=). Fully idempotent — re-running refreshes the same rollup + evidence rows. NO-OPS entirely while copo_attainment.master_enabled=false (ships DARK). Blocker for true CO-tagged attainment: Academic Office must author assessment→CO maps (obe_assessment_co_marks is the target substrate)."
  },
  {
    "id": "usage-rollup",
    "name": "Usage Analytics — nightly rollup + retention",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 04:07 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/usage-rollup",
    "callsClaude": false,
    "whatItDoes": "Turns raw platform usage events into the aggregates every usage dashboard actually reads. Each night it recomputes the last 2 days of module_usage_daily (which module was used, how much, by whom), feature_usage_summary, and institution_health_scores, then archives usage_events older than 12 months. Before this existed, usage_events had grown to 25,832 rows while module_usage_daily's newest row was 2026-02-06 — the day the tables were created — because nothing in the codebase ever called the four compute_/archive_ RPCs. Every usage read surface (/api/analytics/usage/dashboard, /modules, /trends via LifecycleDashboardService) queries those aggregate tables rather than raw events, so the adoption dashboards had been serving five-month-old numbers.",
    "configKnobs": "?days=N recomputes the last N days (default 2 — yesterday plus today, since today's events are still arriving and a missed run must self-heal on the next fire). Capped at 400 days; a manual trigger with ?days=180 backfills the Feb-onward history that was never rolled up. Retention fixed at 12 months (archive_old_usage_events' own default). Days are processed oldest-first so a partial failure leaves the RECENT end unprocessed, which the next default 2-day run repairs automatically. No model, no thresholds.",
    "sideEffects": "DB writes only: upserts module_usage_daily, feature_usage_summary and institution_health_scores rows for each target date, and moves usage_events rows older than 12 months into usage_events_archive. Aggregate counts only — no learner identities are emitted. No notifications, no external messages. Does not write usage_events itself.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'usage-rollup' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer ONLY, constant-time — no ?secret= query param). Safe to manual-trigger: the compute_* RPCs are idempotent per target_date and archival is a no-op when nothing is old enough. Returns HTTP 207 with an `errors[]` array when some days succeeded and some failed, so a partial run is visible instead of reading as clean. Companion to the Usage Beacon (PR #2440), which is what finally makes page views land in usage_events — the beacon fills the raw table, this routine makes it readable."
  },
  {
    "id": "measure-gap-outcomes",
    "name": "Improvement Board — Data-Gap Outcome Measurement",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 05:33 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/measure-gap-outcomes",
    "callsClaude": false,
    "whatItDoes": "The measurement leg of the data-gap self-improving loop. Each night it recomputes every filed gap's outcome from its own status and its linked improvement idea's status: accepted + idea applied/verified → produced_applied_improvement; accepted + idea still not shipped → accepted_pending_improvement; accepted + idea stalled past 30 days → accepted_stalled; dropped / not-accepted / pending. That measured outcome feeds each area's hit-rate, which the ranking cron then weights on — so the loop learns from its own results.",
    "configKnobs": "Stalled threshold = 30 days (an accepted gap whose linked idea hasn't shipped). Pure SQL via fn_mba_measure_gap_outcomes (service-role only). No model, no thresholds beyond the 30-day window.",
    "sideEffects": "DB writes only: recomputes gap_outcome + outcome_measured_at on every mba_data_gaps row via fn_mba_measure_gap_outcomes. Idempotent — safe to re-run any time. No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'measure-gap-outcomes' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer or ?secret=). Fully idempotent — re-running recomputes the same outcomes. Companion to rank-data-gaps (the feed-forward wire reads the hit-rate this produces); scheduled 18 min BEFORE it."
  },
  {
    "id": "rank-data-gaps",
    "maxLane": true,
    "name": "Improvement Board — AI Data-Gap Ranking (Max lane)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 05:51 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/rank-data-gaps",
    "callsClaude": true,
    "whatItDoes": "Ranks each institution's un-triaged MBA data gaps by value × feasibility so managers triage the highest-value first, classifies each as type_a_surface / type_b_capture / uncertain, and feeds each area's measured hit-rate into the ranking as an explore/exploit weight — proven areas up, and unproven dark departments up too for a fair shot. Collect-first: it drains the previous run's ranking jobs and writes priority_rank/reason/class back, then enqueues one ranking job per institution on the ₹0 Max lane.",
    "configKnobs": "MIN_GAPS_TO_RANK=2 (a lone gap has no comparative rank), COLLECT_CAP=50, RANKABLE_STATUSES=[filed,triaged], job_type='improvement.rank_data_gaps' (₹0 Max lane, model_id='sonnet' family alias). Per-area hit-rate is computed INLINE from mba_data_gaps (decoupled from the manager-gated fn_mba_gap_area_hit_rate). Per-institution/day dedupe key.",
    "sideEffects": "DB writes only: writes priority_rank / priority_reason / gap_class / ranked_at onto mba_data_gaps rows, and enqueues 'improvement.rank_data_gaps' jobs on the Max lane. No notifications, no external messages.",
    "safeToManualTrigger": true,
    "notes": "Fires via the AI-routine dispatcher (ai_routine_schedules row 'rank-data-gaps' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron. Auth: CRON_SECRET (Bearer or ?secret=). Async enqueue-now / collect-later: a ?mode=collect tick drains the previous run's jobs. Idempotent: per-institution/day dedupe stops double-enqueue and collect claims each job once. Scheduled AFTER measure-gap-outcomes so the ranking reads today's fresh hit-rate."
  },
  {
    "id": "learner-360-verdict",
    "maxLane": true,
    "name": "Learner 360 — Plain-Language Standing Verdict (Max lane)",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 06:37 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/learner-360-verdict",
    "callsClaude": true,
    "whatItDoes": "The platform already scores every learner twice a night and shows nobody the answer in words. This turns those numbers — risk assessment, contribution score and the 14-day attendance summary — into one plain-English standing note per learner: a band, 2-3 developmental sentences addressed to the learner, and 2-3 concrete next steps. A separate admin-only note (what the learner contributes, and where they sit relative to peers) is written to a DIFFERENT table so it reaches leadership only. Collect-first: it drains the previous run's jobs and records the verdicts, then enqueues the next cohorts on the ₹0 Max lane, highest-risk learners first.",
    "configKnobs": "LEARNERS_PER_JOB=10 (a cohort, because the admin-only value_rank_note is comparative and a batch of one cannot answer it), MAX_JOBS_PER_RUN=20 (=200 learners/night), COLLECT_CAP=50, TIER_ORDER=critical>high>moderate>low>healthy, job_type='learner.360_verdict' (₹0 Max lane, model_id='sonnet' family alias). Per-cohort/day dedupe key. Cohorts never cross an institution.",
    "sideEffects": "DB writes only: upserts learner_360_verdicts + learner_360_verdicts_admin via fn_learner_360_record_verdict (service-role), and enqueues 'learner.360_verdict' jobs on the Max lane. No notifications, no external messages, nothing sent to any learner.",
    "safeToManualTrigger": true,
    "notes": "🔒 HARD DATA BOUNDARY: reads ONLY learner_risk_assessments, learner_contribution_scores and mv_learner_attendance_summary. It must NEVER read or join session_feedback, event_session_feedback, carre_micro_impressions or scf_learner_notes — those hold feedback the learner GAVE under an explicit anonymity promise (aggregated-and-anonymous UI copy, a fully_anonymous mode stripping author_id, k>=3 suppression), so scoring the author would break it — nor any health_*/medical table. Fires via the AI-routine dispatcher (ai_routine_schedules row 'learner-360-verdict'), NOT a raw vercel.json cron: vercel.json already carries exactly 100 crons, the plan ceiling. Auth: CRON_SECRET (Bearer or ?secret=). Async enqueue-now / collect-later; a ?mode=collect tick drains the previous run. Idempotent: per-cohort/day dedupe, collect claims each job once, and the record RPC upserts on (learner_id, verdict_date). Recommendation-only — any verdict can be corrected by a human via fn_learner_360_set_override, and the override is what every surface must then display."
  },
  {
    "id": "learner-risk-staff-notifications",
    "name": "Learner Risk → Department Head Notifications",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 17:20 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/learner-risk-notifications",
    "callsClaude": false,
    "whatItDoes": "Tells the head of a learner's own department which of THEIR learners newly entered — or worsened within — high/critical risk, with the evidence attached: tier, composite score, 14-day attendance and its change, overdue bill count, and the engine's suggested actions. The risk engine has written assessments daily since its first successful run on 2026-07-30 (4,342 rows; 59 critical, 403 high) and notified nobody until this routine existed. Recipients are TEAM MEMBERS ONLY — no learner and no family is notified by any path here.",
    "configKnobs": "platform_policies keys under learner_risk.notifications.* — enabled (default on), mode (digest | individual; digest is the default and groups one message per department), include_department_staff (default off; adds 203 recipients across the affected departments), expiry_hours (72), min_score_delta (5), max_learners_per_message (25). No model, no LLM.",
    "sideEffects": "WRITES in-app notifications (notifications + user_notifications fan-out) to department heads, and one learner_risk_notification_log row per learner announced. Every notification row carries an explicit expires_at. Sends nothing when the ledger table is absent (fails closed with 503) or when enabled is false.",
    "safeToManualTrigger": false,
    "notes": "Rules-based, no LLM. Fires via the AI-routine dispatcher (ai_routine_schedules row 'learner-risk-staff-notifications'), NOT a raw vercel.json cron — `crons` is at the 100-entry plan cap and a 101st would fail the build for every deploy. Auth: CRON_SECRET (Bearer or ?secret=). Idempotent three ways: UNIQUE(learner_id, notified_on) on the ledger, a per-department-per-day idempotency_key on the notification, and a dedupe that only sends on a CHANGE in standing (new / escalated / worsening) so an unchanged learner is never re-announced. Use ?dryRun=1 to see exactly what would be sent without writing. Marked unsafe-to-manual because a run delivers messages naming real learners to real department heads."
  },
  {
    "id": "health-sports-approval-nudge",
    "name": "Tournament Squad Permission — Undecided College Reminder",
    "category": "misc-ai",
    "type": "cron",
    "schedule": "Daily · 09:33 IST (editable via dispatcher)",
    "triggerPath": "/api/cron/health-sports-approval-nudge",
    "callsClaude": false,
    "whatItDoes": "A squad request names learners from several colleges, and nobody travels until every one of those colleges' Principals has decided. Filing already notifies each Principal; this reminds any college still undecided after 48 hours, naming the tournament, the host, the dates and how many of THAT college's learners are on the squad. It never decides on a Principal's behalf.",
    "configKnobs": "p_stale_hours=48 (override per run with ?hours=), ?dry=1 reports what it would send without writing. Recipients = holders of health.sports.approve at that college, resolved via user_roles AND legacy profiles.role. Skips cancelled requests and any tournament whose end_date has passed.",
    "sideEffects": "WRITES in-app notifications (notifications + user_notifications fan-out) to each undecided college's approver(s), and stamps last_nudged_at on that approval row. Writes NO approval status of any kind. No external messages (no email/WhatsApp/push).",
    "safeToManualTrigger": false,
    "notes": "Rules-based, no LLM. All logic is in the SECURITY DEFINER RPC fn_health_tournament_nudge_stale_approvals (service_role only). Fires via the AI-routine dispatcher (ai_routine_schedules row 'health-sports-approval-nudge' — day/time editable in /admin/ai-routines), NOT a raw vercel.json cron, which is already at its 100-entry ceiling. Auth: CRON_SECRET (Bearer or ?secret=). Marked unsafe-to-manual because a run delivers real notifications to real Principals; re-running is safe (idempotent per college per day). Reports no_approver rather than pretending a reminder landed when a college has nobody holding health.sports.approve."
  }
];
