import { type AIRoutine } from './types';
// =====================================================================
// Platform operations (scheduled) — rules-based crons on the dispatcher
// =====================================================================
// Populated 2026-08-13 by the cron-cap wave: 38 daily/weekly vercel.json
// crons moved onto the AI-routine dispatcher (companion migration
// 20260825010000_move_daily_weekly_crons_to_dispatcher.sql removes the
// vercel.json entries in the same PR). None of these call an LLM — they are
// SQL sweeps, role syncs, retention pruners, reminder engines, and
// integration health checks. What moving buys: day/time editable from
// /admin/ai-routines without a redeploy, and headroom under Vercel's hard
// 100-cron cap (the file sat at exactly 100 after PR #2938's 101 overflow).
//
// TIMEZONE (same trap as super-admin-daily-digest): vercel.json cron
// expressions are UTC; ai_routine_schedules.minute_of_day is IST. Every
// schedule below shows the IST slot the seed migration encodes — several
// late-UTC crons (>= 18:30 UTC) land on the NEXT IST day, which is
// irrelevant for every-day routines but was hand-checked for weekly ones.
//
// AUTH: the dispatcher fires GET with `Authorization: Bearer <CRON_SECRET>`
// only. Every route in this file was verified (2026-08-13) to accept Bearer.
export const PLATFORM_OPS_ROUTINES: AIRoutine[] = [
  {
    "id": "improvement-rank-ideas",
    "name": "Improvement Board — rank ideas + escalation sweep",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 10:00 IST (editable via dispatcher)",
    "cronExpr": "43 4 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/improvement-rank-ideas",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Enqueues 'improvement.rank_ideas' jobs on the ₹0 Max lane (drained externally) and runs a rules-based escalation sweep; the route itself resolves no ai_model_config row.",
    "whatItDoes": "Two jobs in one route: RANK — for each institution with enough open ideas, assembles one prompt with every idea's business case and enqueues one Max-lane ranking job (a separate hourly ?mode=collect vercel cron, which stays in vercel.json, drains results into improvement_idea_rankings). ESCALATE — auto-escalates any 'approved' idea whose fix is unapplied past the configured window.",
    "configKnobs": "platform_policies improvement.escalate_after_days (default 7); MIN_IDEAS_TO_RANK gate in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Enqueues ai_jobs rows (Max lane); escalation writes one activity row (action='escalated', idempotent per approval cycle).",
    "safeToManualTrigger": false,
    "notes": "DUAL-LANE ROUTE: only the daily rank+escalate lane moved to the dispatcher. The hourly '17,47 * * * *' ?mode=collect lane REMAINS a vercel.json cron — the dispatcher cannot express sub-daily schedules and triggerPath cannot carry a query string (registry-cron-wiring test checks the path exists on disk). Auth: Bearer or ?secret=. IST math: 04:43 UTC = 10:13 IST → slot 10:00 (minute_of_day 613)."
  },
  {
    "id": "teaching-cohort-sync",
    "name": "Teaching-enterprise cohort sync",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 09:30 IST (editable via dispatcher)",
    "cronExpr": "11 4 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/teaching-cohort-sync",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based role reconciliation via SECDEF fn_teaching_cohort_sync(); no model involved.",
    "whatItDoes": "Re-derives the participant set of every active teaching-enterprise cohort from its config row and reconciles roles: adds the cohort's learner role to newly-matching learners, removes it from leavers (their filed artifacts stay), same for the department-side Senior Learner role, and keeps the analytics cohort decoration aligned. Replaces the two hardcoded MBA sweeps with one config-driven sweep.",
    "configKnobs": "Cohort definitions in teaching_enterprise_cohorts rows. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB writes: role membership adds/removes via service-role SECDEF fn. Fully idempotent — a second run the same day is a no-op.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: 04:11 UTC = 09:41 IST → slot 09:30 (minute_of_day 581)."
  },
  {
    "id": "mba-associate-sync",
    "name": "MBA Associate role sync",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 10:15 IST (editable via dispatcher)",
    "cronExpr": "53 4 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/mba-associate-sync",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based role reconciliation via SECDEF fn_mba_associate_sync(); no model involved.",
    "whatItDoes": "Re-derives the current MBA Management Associate set from the enrolment rule and reconciles the 'mba_associate' role: adds joiners, removes leavers (their filed ideas/summaries stay — RLS checks the viewer's perms, not the author's current role), and keeps the analytics-only cohort aligned.",
    "configKnobs": "None in code (the enrolment rule lives in SQL). Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB writes: role adds/removes inside the service-role SECDEF fn. Idempotent (ON CONFLICT DO NOTHING adds, NOT EXISTS removes).",
    "safeToManualTrigger": true,
    "notes": "Per its own header this sweep is slated for retirement once teaching-cohort-sync has run green — retire the schedule row then, from /admin/ai-routines, no deploy. Auth: Bearer or ?secret=. IST math: 04:53 UTC = 10:23 IST → slot 10:15 (minute_of_day 623)."
  },
  {
    "id": "mba-faculty-sync",
    "name": "MBA Senior Learner role sync",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 10:45 IST (editable via dispatcher)",
    "cronExpr": "19 5 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/mba-faculty-sync",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based role reconciliation via SECDEF fn_mba_faculty_sync(); no model involved.",
    "whatItDoes": "Re-derives the MBA-department team-member set from department membership and reconciles the 'mba_faculty' role: adds joiners, removes leavers (authored artifacts stay). The department-side twin of mba-associate-sync.",
    "configKnobs": "None in code. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB writes: role adds/removes inside the service-role SECDEF fn. Idempotent — same-day re-run is a no-op.",
    "safeToManualTrigger": true,
    "notes": "Also slated for retirement once teaching-cohort-sync generalizes it. Auth: Bearer or ?secret=. IST math: 05:19 UTC = 10:49 IST → slot 10:45 (minute_of_day 649)."
  },
  {
    "id": "mba-rotation-tick",
    "name": "MBA team-rotation tick",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 10:30 IST (editable via dispatcher)",
    "cronExpr": "7 5 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/mba-rotation-tick",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based rotation apply via SECDEF fn_mba_rotation_apply(); no model involved.",
    "whatItDoes": "Advances every active MBA rotation cycle to today's period: (re)activates each member's posting to their team's current-period area and expires the previous period's postings (access is lost on rotate-out). Blackout gaps auto-pause the cycle. The period advances implicitly — the fn derives it from today's date, so there is no stored pointer to drift.",
    "configKnobs": "Rotation cycles + blackout windows in their own tables. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB writes: department posting activate/expire per active cycle. Idempotent — re-running the same day re-asserts the same active set.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: 05:07 UTC = 10:37 IST → slot 10:30 (minute_of_day 637)."
  },
  {
    "id": "pde-case-due-soon",
    "name": "PDE clinical-case deadline reminders",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 07:45 IST (editable via dispatcher)",
    "cronExpr": "23 2 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/pde-case-due-soon",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based deadline windows via fn_pde_due_soon_reminders; no model involved.",
    "whatItDoes": "Sends 'due tomorrow' and 'due today — last chance' nudges to assigned + enrolled learners who have not passed a clinical case and still have attempts left. Several same-day cases combine into one 'N cases due' card.",
    "configKnobs": "Cap from the global clinical-reasoning policy. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES in-app notifications to learners. Idempotent via deliverInApp's idempotency_key (window + learner + due-date) — safe to run more than once a day.",
    "safeToManualTrigger": false,
    "notes": "Notifies real learners — manual fires outside the morning window would be confusing, hence unsafe-to-manual (a re-run is technically idempotent). Auth: Bearer or ?secret=. IST math: 02:23 UTC = 07:53 IST → slot 07:45 (minute_of_day 473)."
  },
  {
    "id": "work-signal-suggestions",
    "name": "Work-signal weekly suggestions (enqueue lane)",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Monday 08:30 IST (editable via dispatcher)",
    "cronExpr": "13 3 * * 1 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/work-signal-suggestions",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Enqueues ₹0 Max-lane jobs (curriculum-lesson-spine pattern); the route resolves no ai_model_config row directly.",
    "whatItDoes": "Weekly personalized suggestion loop: picks team members with real work-signal activity, assembles one grounded prompt each, and enqueues Max-lane jobs (dedupe per person-week). Doctrine: acts, not scores — the suggestion is never a rating or peer comparison, only text on the subject's own dashboard that only they can verdict.",
    "configKnobs": "Candidate window (OD approval queue, 30d) in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Enqueues ai_jobs rows only on this lane; the hourly ?mode=collect vercel cron (which stays in vercel.json) drains results via fn_work_signal_suggestion_upsert.",
    "safeToManualTrigger": true,
    "notes": "DUAL-LANE ROUTE: only the Monday enqueue lane moved; the hourly '37 * * * *' ?mode=collect lane remains a vercel.json cron. Auth: Bearer or ?secret=. IST math: Mon 03:13 UTC = Mon 08:43 IST → slot 08:30 (minute_of_day 523, days {1})."
  },
  {
    "id": "rcltp-review-chase",
    "name": "RCLTP nightly review chase",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 01:45 IST (editable via dispatcher)",
    "cronExpr": "26 20 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/rcltp-review-chase",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based chase resolved by PERMISSION via lib/services/rcltp/notify-targets.ts; no model involved.",
    "whatItDoes": "One chasing system for both unapproved remedial reading plans and unreviewed AI-drafted comprehension questions: ~7 days untouched → remind whoever may approve it; ~14 days → escalate to the head of that school (or system administrators when the escalation would land in the same inbox the reminder already reached).",
    "configKnobs": "Reminder/escalation windows in the route/spec. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES in-app notifications. Each item is reminded/escalated once each in its whole life.",
    "safeToManualTrigger": false,
    "notes": "NOTE ON SIBLING: rcltp-question-generate's daily '?mode=enqueue' lane could NOT move — triggerPath cannot carry a query string (wiring test checks path existence on disk); it stays in vercel.json with its 30-min collect lane. Auth: Bearer or ?secret=. IST math: 20:26 UTC = 01:56 IST next day → slot 01:45 (minute_of_day 116, every day)."
  },
  {
    "id": "attendance-breach-check",
    "name": "Attendance breach check (accountability meetings)",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 03:00 IST (editable via dispatcher)",
    "cronExpr": "37 21 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/attendance-breach-check",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based evaluation of meeting_trigger_rules; no model involved.",
    "whatItDoes": "Evaluates active meeting_trigger_rules (metric_key='attendance_rate_daily') for the just-completed campus day; on breach, notifies the college Principal (admin fallback) via the in-app bell. Detect + notify only. Nothing fires unless a rule is 'active' — all were seeded inactive for per-college Director review.",
    "configKnobs": "Per-college thresholds in meeting_trigger_rules rows; optional ?date=YYYY-MM-DD override for controlled tests. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES in-app notifications to Principals on breach.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret=. IST math: 21:37 UTC = 03:07 IST next day → slot 03:00 (minute_of_day 187, every day)."
  },
  {
    "id": "director-handover-chase",
    "name": "Director's Desk nightly handover chase",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 01:15 IST (editable via dispatcher)",
    "cronExpr": "53 19 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/director-handover-chase",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based state machine over handovers; no model involved.",
    "whatItDoes": "One pass per night over Director handovers: relabels orphaned handovers whose owner left (and tells the Director), opens the 24h explain-or-meet valve on overdue handovers and relabels to expired only when that window resolves, nudges the holder of every live handover once daily, and reconciles valve answers (an answer stops escalation; silence hands off to the meeting-booking pass).",
    "configKnobs": "Windows per the Director's Desk decisions (9-12); volume fuse in the service. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES handover status transitions + notifications to the Director and holders.",
    "safeToManualTrigger": false,
    "notes": "Order of operations inside the route matters (valve before relabel) — do not fire ad hoc mid-day; the nightly slot is part of the design. Auth: Bearer or ?secret=. IST math: 19:53 UTC = 01:23 IST next day → slot 01:15 (minute_of_day 83, every day)."
  },
  {
    "id": "accreditation-naac-narrative-draft",
    "name": "Accreditation NAAC narrative drafter (DARK)",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 00:45 IST (editable via dispatcher)",
    "cronExpr": "22 19 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/accreditation-naac-narrative-draft",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Enqueues 'accreditation.naac_narrative_draft' jobs on the ₹0 Max lane; does not call Claude directly (external drain runs the model).",
    "whatItDoes": "Nightly collect-then-enqueue: collects finished draft jobs, validates each against the deterministic grounding gate, records the verdict; then enqueues a grounded draft job for every evidence-backed (institution, NAAC metric) pair without a current-period draft. Output only ever lands as an 'ai_drafted' row a human must approve.",
    "configKnobs": "DARK: ai_job_types row 'accreditation.naac_narrative_draft' is enabled=false, so every enqueue is refused and the route is a safe no-op until the Director flips it (no deploy). Day/time editable at /admin/ai-routines.",
    "sideEffects": "When live: ai_jobs enqueues + draft verdict records. Today: no-op.",
    "safeToManualTrigger": true,
    "notes": "AUTH EXCEPTION: this route accepts Authorization: Bearer ONLY (constant-time; no ?secret= fallback) — exactly what the dispatcher sends. Compatible. IST math: 19:22 UTC = 00:52 IST next day → slot 00:45 (minute_of_day 52, every day)."
  },
  {
    "id": "accreditation-narrative-reminders",
    "name": "Accreditation narrative reminders + escalation",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 08:30 IST (editable via dispatcher)",
    "cronExpr": "12 3 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/accreditation-narrative-reminders",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based nudges via SECDEF fn_accreditation_narrative_reminders; no model involved.",
    "whatItDoes": "Nudges the owning Senior Learner of a draft that has been waiting on them for a few days, and escalates a long-overdue draft to super-admin oversight.",
    "configKnobs": "Waiting/escalation windows inside the RPC. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES notifications + user_notifications. Idempotent per draft per day — can run repeatedly.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret=. IST math: 03:12 UTC = 08:42 IST → slot 08:30 (minute_of_day 522)."
  },
  {
    "id": "accreditation-narrative-capout-notice",
    "name": "Accreditation narrative cap-out notice",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 01:15 IST (editable via dispatcher)",
    "cronExpr": "52 19 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/accreditation-narrative-capout-notice",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based detector (fn_accreditation_narrative_capout_pending) + notification fan-out; no model involved.",
    "whatItDoes": "Companion to the drafter: once per capped-out narrative, forever, tells the person responsible that the AI gave up on it (owner → IQAC/admin queue → every super admin; nothing is orphaned). Without this, a draft that hit the attempt cap sits silently looking like it is merely waiting its turn.",
    "configKnobs": "accreditation.narrative_max_draft_attempts policy (read by the drafter; this route reads the resulting capped state). Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES notifications via fanoutNotification. Duplicate-proof: UNIQUE partial index on idempotencyKey even across crashes.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer (route mirrors the drafter's constant-time Bearer pattern; ?secret= also present per audit). IST math: 19:52 UTC = 01:22 IST next day → slot 01:15 (minute_of_day 82, every day)."
  },
  {
    "id": "refresh-conversion-leaderboard",
    "name": "Dashboard conversion-leaderboard refresh",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 00:00 IST (editable via dispatcher)",
    "cronExpr": "30 18 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/dashboard/cron/refresh-conversion-leaderboard",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Materialized-view refresh; no model involved.",
    "whatItDoes": "Refreshes v_dashboard_conversion_monthly at midnight IST so the conversion leaderboard reads fresh data.",
    "configKnobs": "None. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB: refreshes one materialized view. No notifications.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer (route has no ?secret= fallback — dispatcher-compatible). IST math: 18:30 UTC = 00:00 IST next day (minute_of_day 0, every day)."
  },
  {
    "id": "decisions-verdict-check",
    "name": "Director decisions verdict check",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 09:30 IST (editable via dispatcher)",
    "cronExpr": "0 4 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/dashboard/cron/decisions-verdict-check",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based via SECDEF fn_decision_outcome_check() and its whitelisted metric resolver; no model involved.",
    "whatItDoes": "Grades any director_decisions whose outcome_due_at has elapsed while status='pending_outcome', emitting verdict work items. Runs after the super-admin digest by design.",
    "configKnobs": "None in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES dashboard work items via fn_create_dashboard_work_item, idempotency key 'decision_verdict:<id>:<date>' — same-day re-runs are safe.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer (no ?secret= fallback — dispatcher-compatible). IST math: 04:00 UTC = 09:30 IST (minute_of_day 570). Keep it scheduled after super-admin-daily-digest (08:30 IST slot) as its header intends."
  },
  {
    "id": "sunday-wrap",
    "name": "Doctrines Sunday 9 PM wrap",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Sunday 21:00 IST (editable via dispatcher)",
    "cronExpr": "30 15 * * 0 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/sunday-wrap",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based composite-score wrap; no model involved.",
    "whatItDoes": "Weekly wrap to every user with a Doctrines persona: refreshes both cluster leaderboard MVs, computes each user's composite score, inserts a high-priority notification, and sends a web push. No WhatsApp (spec thrash-lock).",
    "configKnobs": "None in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES one notification per persona user + web push. Idempotency key guards repeats.",
    "safeToManualTrigger": false,
    "notes": "Pushes to every persona user — never fire ad hoc. Auth: Bearer or ?secret=. IST math: Sun 15:30 UTC = Sun 21:00 IST (minute_of_day 1260, days {0})."
  },
  {
    "id": "friday-reflection",
    "name": "Doctrines Friday 4 PM reflection",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Friday 16:00 IST (editable via dispatcher)",
    "cronExpr": "30 10 * * 5 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/friday-reflection",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based reflection card drop; no model involved.",
    "whatItDoes": "Drops an in-app reflection card into the notifications feed for learners and Senior Learners only. Deliberately no web push — the quiet prompt to Sunday wrap's interrupt.",
    "configKnobs": "None. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES one card per user per ISO week (idempotent). No push, no WhatsApp.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret=. IST math: Fri 10:30 UTC = Fri 16:00 IST (minute_of_day 960, days {5})."
  },
  {
    "id": "campus-vacancy-price-drops",
    "name": "Campus Living vacancy price drops",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 07:30 IST (editable via dispatcher)",
    "cronExpr": "0 2 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/campus-living/vacancy-price-drops",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based price-drop engine (runVacancyPriceDrops); no model involved.",
    "whatItDoes": "An unfilled Premium upgrade-vacancy's differential auto-drops 20% every 60 days (policy-driven) until taken or the hostel year ends; each drop re-notifies the eligible pool.",
    "configKnobs": "Drop percentage + interval from policy. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES price changes + re-notifies eligible learners on an actual drop. The per-vacancy '>= interval_days since last_dropped_at' guard makes daily runs safe.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret=. IST math: 02:00 UTC = 07:30 IST (minute_of_day 450)."
  },
  {
    "id": "campus-occupancy-snapshot",
    "name": "Campus Living occupancy snapshot",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 07:00 IST (editable via dispatcher)",
    "cronExpr": "30 1 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/campus-living/occupancy-snapshot",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Pure SQL aggregation snapshot; no model involved.",
    "whatItDoes": "Computes per-block occupancy (rooms/beds totals, sellable, occupied) from live tables and UPSERTs one row per block into hostel_occupancy_snapshots for the day. Mandatory: allocation transfers mutate rows in place, so occupancy history is otherwise unreconstructable.",
    "configKnobs": "bed_econ.sellable_room_purposes policy. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB upserts only, idempotent on (snapshot_date, block_id). No notifications.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: 01:30 UTC = 07:00 IST (minute_of_day 420)."
  },
  {
    "id": "campus-housekeeping-task-generator",
    "name": "Campus Living housekeeping task generator",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 00:00 IST (editable via dispatcher)",
    "cronExpr": "35 18 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/campus-living/housekeeping-task-generator",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Pure SQL task generation via fn_housekeeping_generate_tasks(); no model involved.",
    "whatItDoes": "Inserts one 'scheduled' cleaning task per active, due cleaning-schedule plan for today (Asia/Kolkata) so the Tasks page is populated before team members arrive.",
    "configKnobs": "Plans in hostel_cleaning_schedules. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB inserts only, idempotent via the (schedule_id, date) unique index.",
    "safeToManualTrigger": true,
    "notes": "TIMING-SENSITIVE: 18:35 UTC = 00:05 IST — start of the Indian day on purpose. The dispatcher slot 00:00 IST preserves that. Auth: Bearer or ?secret=. minute_of_day 5, every day."
  },
  {
    "id": "attention-bar-prune",
    "name": "Attention Bar retention pruner",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 00:15 IST (editable via dispatcher)",
    "cronExpr": "47 18 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/attention-bar-prune",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Retention deletes only; no model involved (the AI cache it prunes is written elsewhere).",
    "whatItDoes": "Nightly retention pruner: quick_action_taps (90-day), quick_action_audit (30-day), quick_action_ai_cache (1-hour TTL).",
    "configKnobs": "Retention windows per spec §3. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB deletes of already-expired rows only. Idempotent — can run as often as needed.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: 18:47 UTC = 00:17 IST next day → slot 00:15 (minute_of_day 17, every day)."
  },
  {
    "id": "duty-log-retention",
    "name": "Counselor duty-log retention purge",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Sunday 08:30 IST (editable via dispatcher)",
    "cronExpr": "0 3 * * 0 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/duty-log-retention",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Retention purge, policy-driven; no model involved.",
    "whatItDoes": "Purges admission_counselor_duty_log rows older than the configured retention window, always preserving each counselor's most-recent row so fn_get_off_duty_since() keeps a baseline.",
    "configKnobs": "platform_policies compliance.duty_log.retention_days (default 90) — editable at /admin/policies, no deploy. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB deletes only. No notifications.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: Sun 03:00 UTC = Sun 08:30 IST (minute_of_day 510, days {0})."
  },
  {
    "id": "prospect-reminders",
    "name": "Solutions Hub prospect follow-up reminders",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 13:45 IST (editable via dispatcher)",
    "cronExpr": "23 8 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/prospect-reminders",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based reminder generation (sh_get_overdue_prospects RPC); no model involved.",
    "whatItDoes": "Finds overdue active prospects, groups them by assignee, and creates one dashboard work item per assignee.",
    "configKnobs": "None in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES dashboard work items (idempotent per day).",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret=. IST math: 08:23 UTC = 13:53 IST → slot 13:45 (minute_of_day 833)."
  },
  {
    "id": "whatsapp-byow-bypass-detect",
    "name": "BYOW bypass detector (weekly)",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Monday 14:30 IST (editable via dispatcher)",
    "cronExpr": "0 9 * * 1 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/whatsapp-byow-bypass-detect",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based detector; no model involved.",
    "whatItDoes": "Runs the BYOW bypass detector and captures a Sentry warning per flagged department, for the Director's digest to read later.",
    "configKnobs": "None in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Sentry events only — no user-facing notifications, no DB state changes of record.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer. IST math: Mon 09:00 UTC = Mon 14:30 IST (minute_of_day 870, days {1})."
  },
  {
    "id": "hr-document-expiry-reminders",
    "name": "HR document expiry reminders",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 12:30 IST (editable via dispatcher)",
    "cronExpr": "0 7 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/hr/document-expiry-reminders",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based threshold windows; no model involved.",
    "whatItDoes": "Emails team members + HR officers when a verified hr_employee_documents row approaches its expires_at, at the 30/14/7-day windows.",
    "configKnobs": "Threshold windows (30/14/7) in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "SENDS emails; stamps last_reminder_<N>d_at columns for idempotency.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret=. IST math: 07:00 UTC = 12:30 IST (minute_of_day 750)."
  },
  {
    "id": "hr-policy-promote-detector",
    "name": "HR policy promotion detector (weekly)",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Monday 07:30 IST (editable via dispatcher)",
    "cronExpr": "0 2 * * 1 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/hr-policy-promote-detector",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based scan of platform_policies + hr_policy_audit_log; no model involved.",
    "whatItDoes": "Scans for policy keys whose institution-scope rows have held the same value for 180+ days with no audit-log edits, and inserts a pending promotion suggestion for the Director-confirm UI. Auto-promote is deliberately NOT silent (Director lock R3-Q2).",
    "configKnobs": "180-day stability window in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB inserts into hr_policy_promotion_suggestions only; the banner surfaces the count.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: Mon 02:00 UTC = Mon 07:30 IST (minute_of_day 450, days {1})."
  },
  {
    "id": "ig-login-token-refresh",
    "name": "Instagram login-token refresh",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 08:00 IST (editable via dispatcher)",
    "cronExpr": "43 2 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/ig-login-token-refresh",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "External-API token maintenance; no model involved.",
    "whatItDoes": "Keeps Instagram Business Login tokens alive: marks connections past expires_at as 'expired', refreshes tokens expiring within the window (each refresh restarts the 60-day clock), and marks token-invalid errors so the account can reconnect.",
    "configKnobs": "REFRESH_WINDOW_DAYS in the route (wide: ~50 daily attempts before lapse). Day/time editable at /admin/ai-routines.",
    "sideEffects": "Calls graph.instagram.com; updates connection rows. No user notifications.",
    "safeToManualTrigger": true,
    "notes": "maxDuration 300 on the route itself; the dispatcher's 120s fetch timeout may abort the WAIT while the route continues serverside — last_status can read as a timeout while the refresh completed. Auth: Bearer. IST math: 02:43 UTC = 08:13 IST → slot 08:00 (minute_of_day 493)."
  },
  {
    "id": "ig-accounts-sync",
    "name": "Instagram accounts auto-discovery sync",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 10:30 IST (editable via dispatcher)",
    "cronExpr": "11 5 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/ig-accounts-sync",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "External-API discovery/classification; no model involved.",
    "whatItDoes": "Daily auto-detection of Instagram account ownership — re-enumerates /me/accounts so a newly Page-connected department account flips from 'business_discovery' (public metrics only) to fully classified. The hourly IG polls only read already-classified accounts; this is the route that closes the gap.",
    "configKnobs": "None (full auto-discovery path). Day/time editable at /admin/ai-routines.",
    "sideEffects": "Updates instagram account classification rows. No user notifications.",
    "safeToManualTrigger": true,
    "notes": "maxDuration 300 on the route; see ig-login-token-refresh note on the dispatcher's 120s wait. Auth: Bearer. IST math: 05:11 UTC = 10:41 IST → slot 10:30 (minute_of_day 641)."
  },
  {
    "id": "ig-silence-detect",
    "name": "Instagram silence detect (weekly)",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Monday 12:45 IST (editable via dispatcher)",
    "cronExpr": "23 7 * * 1 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/ig-silence-detect",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based dormancy detection; no model involved.",
    "whatItDoes": "Flags connected Instagram accounts that have posted nothing for the policy threshold and dispatches an in-app notification per silent account, rate-limited per account by the realert window.",
    "configKnobs": "platform_policies ig.alert_dormant_after_days (default 30) + ig.silence_realert_days (default 7). Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES in-app notifications (idempotent via notifications.idempotency_key).",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer. IST math: Mon 07:23 UTC = Mon 12:53 IST → slot 12:45 (minute_of_day 773, days {1})."
  },
  {
    "id": "meta-subscription-drift-check",
    "name": "Meta webhook-subscription drift check",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 03:00 IST (editable via dispatcher)",
    "cronExpr": "30 21 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/meta-subscription-drift-check",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "External-API state snapshot + drift alarm; no model involved.",
    "whatItDoes": "Snapshots each Facebook Page + linked IG account's subscribed_apps state, the app-level subscriptions state, and the page token's /debug_token; inserts one audit row per asset per run; emails the Director + fires Sentry on any drift.",
    "configKnobs": "None in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB inserts into meta_subscription_audit; email + Sentry ONLY on detected drift.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer. IST math: 21:30 UTC = 03:00 IST next day (minute_of_day 180, every day)."
  },
  {
    "id": "meta-leadgen-backfill",
    "name": "Meta leadgen backfill",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 04:15 IST (editable via dispatcher)",
    "cronExpr": "47 22 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/meta-leadgen-backfill",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "External-API lead import; no model involved.",
    "whatItDoes": "Pulls the last N days of leads for every active meta_lead_forms row with a resolved institution, catching anything Meta's best-effort webhook dropped.",
    "configKnobs": "meta.leadgen.backfill_lookback_days policy; no-op when meta.leadgen.is_enabled=false. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Lead captures (merged by phone within institution — re-import of the same lead is a no-op create + a merge-row append). UNIQUE index on fb_leadgen_id makes it idempotent.",
    "safeToManualTrigger": true,
    "notes": "Its header once recommended every-30-min; production ran it DAILY at 22:47 UTC and that daily cadence is what moved. Auth: Bearer. IST math: 22:47 UTC = 04:17 IST next day → slot 04:15 (minute_of_day 257, every day)."
  },
  {
    "id": "google-calendar-connection-check",
    "name": "Google Calendar connection health check",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 06:45 IST (editable via dispatcher)",
    "cronExpr": "19 1 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/google-calendar-connection-check",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "External-API probe; no model involved.",
    "whatItDoes": "Probes every active Google Calendar connection (Universal Booking) with a 1-minute freebusy call; a dead connection flows through markConnectionBroken → auto-hide + host email, so a silently-revoked calendar is caught before a visitor's booking exposes it.",
    "configKnobs": "None in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Updates connection state; emails the affected host ONLY on a broken connection.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer. IST math: 01:19 UTC = 06:49 IST → slot 06:45 (minute_of_day 409)."
  },
  {
    "id": "schools-visit-nudges",
    "name": "Schools Network visit nudges",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 09:30 IST (editable via dispatcher)",
    "cronExpr": "13 4 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/schools-network/visit-nudges/cron",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based nudge candidates from an RPC; no model involved.",
    "whatItDoes": "For every assigned, nudge-eligible school (slipping in the feeder ranking OR 60+ days unvisited) that is not yet done, fires ONE in-app notification to the assigned outreach coordinator.",
    "configKnobs": "7-day realert window (last_nudged_at); expiry added 2026-08-10 after 148 unexpired notices accumulated. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES notifications via the canonical two-write fan-out; stamps last_nudged_at. Idempotency key (school + date) guards same-day double-runs.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret=. IST math: 04:13 UTC = 09:43 IST → slot 09:30 (minute_of_day 583)."
  },
  {
    "id": "exam-audit-alerts",
    "name": "Exam IA audit watchdog (weekly)",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Monday 08:00 IST (editable via dispatcher)",
    "cronExpr": "43 2 * * 1 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/exam-audit-alerts",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based verdicts from lib/services/exam-audit/compute.ts (the same computation the audit page uses); no model involved.",
    "whatItDoes": "When a program sits at operator-dump / missing-CIA / no-rubric with an exam date approaching, notifies the Registrar and that college's Principal(s) — the audit runs itself weekly instead of waiting for someone to open the page.",
    "configKnobs": "Thresholds inside the shared compute service. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES in-app notifications to Registrar + Principals.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret=. IST math: Mon 02:43 UTC = Mon 08:13 IST → slot 08:00 (minute_of_day 493, days {1})."
  },
  {
    "id": "sf100-accountability",
    "name": "SF100 daily accountability sweep",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 09:00 IST (editable via dispatcher)",
    "cronExpr": "37 3 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/sf100-accountability",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based stall/deadline engine in SF100Service; no model involved.",
    "whatItDoes": "For every active SF100 program: runStallCheck escalates teams active→warning→probation→removed on check-in silence and notifies each team leader; runDeadlineWarnings notifies active teams at exactly 30 and 7 days before the program hard deadline.",
    "configKnobs": "Program state in sf100_programs. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES team status escalations + notifications. Each program guarded in its own try/catch.",
    "safeToManualTrigger": false,
    "notes": "Status escalation is stateful — an extra run advances silence-based state; do not fire ad hoc. Auth: Bearer or ?secret= (constant-time). IST math: 03:37 UTC = 09:07 IST → slot 09:00 (minute_of_day 547)."
  },
  {
    "id": "sf100-weekly-reminder",
    "name": "SF100 weekly check-in reminders",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Weekly · Sunday 20:00 IST (editable via dispatcher)",
    "cronExpr": "33 14 * * 0 (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/sf100-weekly-reminder",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based reminder engine in SF100Service; no model involved.",
    "whatItDoes": "For every active SF100 program, notifies every active/warning/probation team that has NOT checked in within the last 7 days — a nudge for the silent, not noise for the active.",
    "configKnobs": "None in the route. Day/time editable at /admin/ai-routines.",
    "sideEffects": "WRITES notifications to silent teams.",
    "safeToManualTrigger": false,
    "notes": "Auth: Bearer or ?secret= (constant-time). IST math: Sun 14:33 UTC = Sun 20:03 IST → slot 20:00 (minute_of_day 1203, days {0})."
  },
  {
    "id": "bug-cluster-scan",
    "name": "Bug-triage duplicate-cluster scan",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 02:45 IST (editable via dispatcher)",
    "cronExpr": "19 21 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/bug-cluster-scan",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Deterministic pg_trgm clustering via fn_bug_cluster_scan(); no model involved.",
    "whatItDoes": "Clusters the open /admin/bug-reports backlog into duplicate-candidate groups for the Groups tab. Confirmed/dismissed decisions are never touched.",
    "configKnobs": "None. Day/time editable at /admin/ai-routines.",
    "sideEffects": "DB writes to bug_clusters (idempotent full recompute). No notifications.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: 21:19 UTC = 02:49 IST next day → slot 02:45 (minute_of_day 169, every day)."
  },
  {
    "id": "pde-image-orphans",
    "name": "PDE clinical-image orphan sweeper",
    "category": "platform-ops",
    "type": "cron",
    "schedule": "Daily · 09:00 IST (editable via dispatcher)",
    "cronExpr": "41 3 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/pde-image-orphans",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Reference-counting storage sweep; no model involved.",
    "whatItDoes": "Deletes clinical images no case refers to any more (reference-based, not event-based — cases are archived, never hard-deleted, so imagery must survive while referenced). Mostly catches images uploaded while authoring a case that was then abandoned.",
    "configKnobs": "Grace period protects in-flight edits — an image is removed only after being unreferenced longer than someone could plausibly be mid-edit. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Deletes storage objects that pass the reference + grace checks. No notifications.",
    "safeToManualTrigger": true,
    "notes": "Director decision 2026-07-21 ('delete the images too'). Auth: Bearer or ?secret=. IST math: 03:41 UTC = 09:11 IST → slot 09:00 (minute_of_day 551)."
  }
];
