import { type AIRoutine } from './types';
// Populated 2026-07-01 from the parallel discovery swarm (deep-read of jicate/main).
export const SCF_ROUTINES: AIRoutine[] = [
  {
    "id": "scf-generate-suggestions",
    "maxLane": true,
    "name": "SCF Generate Suggestions (autonomous improve step)",
    "category": "scf-session-feedback",
    "type": "cron",
    "schedule": "Daily 05:47 UTC (approx 11:17 IST)",
    "cronExpr": "47 5 * * *",
    "triggerPath": "/api/cron/scf-generate-suggestions",
    "callsClaude": true,
    "featureKey": "scf.generate_suggestions",
    "whatItDoes": "Scans courses that had post-class feedback in the last 7 days; for classes where students understood poorly it asks Claude to write teaching-improvement advice, and for standout classes it asks Claude to capture what worked. It then measures whether earlier advice actually helped.",
    "configKnobs": "MODEL=claude-sonnet-4-6 (config row 'scf.generate_suggestions' — /admin/ai-models), BATCH_CAP=25, WINDOW_DAYS=7, MIN_RESPONSES=3, LOW_UNDERSTOOD_THRESHOLD=3, STANDOUT_THRESHOLD=4.5, BATCH_DEADLINE_MS=240000, maxDuration=300, per-call-timeout=25000ms, max_tokens=1024",
    "sideEffects": "DB writes only: inserts/upserts suggestions into scf_ai_suggestions (via fn_scf_record_suggestion) and updates outcome_lift on matured prior rows (fn_scf_measure_suggestion_outcomes). No emails/notifications/WhatsApp.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET as Authorization: Bearer <secret> or ?secret=<secret>. Needs CLAUDE_API_KEY or ANTHROPIC_API_KEY; without a key it skips generation but still runs outcome measurement (honest-empty). Regen-guarded (an UNMEASURED same-kind note within the last 7 days blocks; a measured note frees the retry early - Director 2026-07-10) with up to 5 of the 25-course cap reserved for measured-awaiting-retry courses and fails CLOSED on guard-query errors, so re-firing is safe/idempotent — watch guard_errors>0 with generated=0 for a fail-closed stall. Optional ?window_days= for backfill. Depends on RPCs fn_scf_candidate_windows, fn_scf_ai_signal, fn_scf_prior_suggestion, fn_scf_record_suggestion, fn_scf_measure_suggestion_outcomes. Known history: an earlier version read a non-existent scf_sessions relation and 500'd every run (produced zero suggestions) until fixed 2026-06-30."
  },
  {
    "id": "scf-learner-notes",
    "name": "SCF Learner Support Notes (struggling-student lane)",
    "category": "scf-session-feedback",
    "type": "cron",
    "maxLane": true,
    "schedule": "Daily 06:09 UTC (approx 11:39 IST)",
    "cronExpr": "9 6 * * *",
    "triggerPath": "/api/cron/scf-learner-notes",
    "callsClaude": true,
    "featureKey": "scf.learner_notes",
    "capPolicyKey": "scf_notes.batch_cap",
    "whatItDoes": "Finds students whose own understanding ratings for a course dropped across three classes in a row, and asks Claude to draft one short, warm, private note nudging them to seek help early. The student sees the note on their Learning Studio Feedback page.",
    "configKnobs": "MODEL=claude-sonnet-4-6 (config row 'scf.learner_notes' — /admin/ai-models), scf_notes.batch_cap=10000 (per-run cap, platform_policies, editable via the cap chip — Director 2026-07-11 'unlimited'; the Max lane honors it fully, the cloud cron clamps to 50/run for its 90s serverless window), REGEN_DAYS=7, RECENT_WITHIN_DAYS=30, BATCH_DEADLINE_MS=90000, NOTE_CONCURRENCY=10, maxDuration=300, max_tokens=300, maxRetries=1",
    "sideEffects": "Writes private per-student notes into scf_learner_notes (upsert, onConflict learner_id,course_code,week_of, ignoreDuplicates). Each note becomes student-visible in-app content. No push/bell/email/WhatsApp is sent — the student only sees it passively when they open their feedback page.",
    "safeToManualTrigger": false,
    "notes": "Marked false conservatively: a manual run can generate brand-new private notes that a struggling student will read (human-facing content on a sensitive surface). It IS idempotent within a week — the 7-day regen guard plus unique (learner,course,week_of) make re-firing in the same week a no-op — so firing twice will not duplicate. Fails CLOSED (aborts the run) if the regen-guard query errors. Auth: CRON_SECRET Bearer or ?secret=. Needs CLAUDE_API_KEY/ANTHROPIC_API_KEY; no key -> nothing generated (NO template fallback by Director decision). Note text is private to the learner; leadership only sees THAT a note was sent. Depends on service-role RPC fn_scf_downward_trend_all. Optional ?recent_days= override."
  },
  {
    "id": "scf-measure-outcomes",
    "name": "SCF Measure Outcomes (loop verifier)",
    "category": "scf-session-feedback",
    "type": "cron",
    "schedule": "Daily 02:47 UTC",
    "cronExpr": "47 2 * * *",
    "triggerPath": "/api/cron/scf-measure-outcomes",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based outcome measurement through SQL RPCs; the route imports no AI client.",
    "whatItDoes": "For each past AI suggestion whose next class has since happened, records whether the next session's understanding score rose or fell (the 'lift') so future suggestions can learn if the last advice worked. Also measures the induction feedback loop's outcomes.",
    "configKnobs": "min_age_days default=1 (session verifier), induction_min_age_days default=300. No model/Claude constants.",
    "sideEffects": "DB writes only: sets outcome/outcome_lift on scf_ai_suggestions rows via fn_scf_measure_suggestion_outcomes, and induction outcomes via fn_induction_measure_loop_outcomes. Idempotent — only rows with outcome_lift IS NULL are touched. No human messaging.",
    "safeToManualTrigger": true,
    "notes": "Auth: CRON_SECRET Bearer or ?secret=. Does NOT call Claude (no Anthropic import). Fully idempotent, so safe to re-run. Overrides for backfill: ?min_age_days= and ?induction_min_age_days=. Returns HTTP 500 only when the (daily, critical) session RPC fails; an induction-RPC failure is surfaced in the induction_error field and self-heals next run. This is the same measurement step scf-generate-suggestions also runs at the end of its batch."
  },
  {
    "id": "session-feedback-escalation",
    "maxLane": true,
    "name": "Session Feedback Weekly Escalation Digest",
    "category": "scf-session-feedback",
    "type": "cron",
    "schedule": "Mondays 07:30 UTC",
    "cronExpr": "30 7 * * 1",
    "triggerPath": "/api/cron/session-feedback-escalation",
    "callsClaude": true,
    "featureKey": "session_feedback.escalation",
    "whatItDoes": "Weekly, finds classes that escalated last week (enough responses with low average understanding), has Claude write a short leadership briefing for each, and pushes one in-app digest to the HOD (and to the Principal once a class keeps escalating).",
    "configKnobs": "MODEL=claude-sonnet-4-6 (config row 'session_feedback.escalation' — /admin/ai-models), max_tokens=220. The escalation thresholds (>=3 responses AND avg understanding < 3) live in the RPC fn_scf_compute_weekly_escalations, not hardcoded in this file.",
    "sideEffects": "Sends in-app digest notifications to leadership (HOD/Principal) via fn_scf_apply_weekly_escalation_digest. This delivers messages to humans. Idempotent per recipient per week.",
    "safeToManualTrigger": false,
    "notes": "Marked false because it pushes in-app notifications to leadership (messages humans). It IS idempotent per recipient per week, so a same-week re-run will not create duplicate digests, but a manual run for a fresh week will notify people. Auth: CRON_SECRET Bearer or ?secret=. CLAUDE_API_KEY/ANTHROPIC_API_KEY is optional — without it (or with no comments) each summary falls back to a numeric template and the run still completes. Optional ?week_start=YYYY-MM-DD for backfill. Depends on fn_scf_compute_weekly_escalations + fn_scf_apply_weekly_escalation_digest."
  },
  {
    "id": "session-feedback-nudge",
    "name": "Session Feedback Adoption Nudge",
    "category": "scf-session-feedback",
    "type": "cron",
    "schedule": "Daily 07:13 UTC",
    "cronExpr": "13 7 * * *",
    "triggerPath": "/api/cron/session-feedback-nudge",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Rules-based nudge through fn_scf_nudge_pending_learners; the route imports no AI client.",
    "whatItDoes": "Daily, finds students who were marked Present in a class in the last 14 days but have not yet confirmed their 10-second post-class feedback, and drops one in-app bell notification reminding them to confirm.",
    "configKnobs": "p_lookback_days=14. No Claude/model constants.",
    "sideEffects": "Creates in-app bell notifications plus the user_notifications fan-out for learners via fn_scf_nudge_pending_learners. This delivers messages to humans. In-app only (no email/WhatsApp). Idempotency-keyed per learner per day.",
    "safeToManualTrigger": false,
    "notes": "Marked false because it sends in-app notifications to learners (messages humans). It is idempotency-keyed per learner per day, so a same-day re-run will not duplicate, but a manual fire still nudges students. Does NOT call Claude. Auth: CRON_SECRET Bearer (Vercel cron sends this) or ?secret=. Note: Vercel does NOT substitute ${CRON_SECRET} into the vercel.json URL path, so the Bearer header is what scheduled invocations actually match. Depends on SECURITY DEFINER RPC fn_scf_nudge_pending_learners (lookback 14 days)."
  },
  {
    "id": "scf-ai-suggest-improvement",
    "name": "SCF AI Suggest Improvement (on-demand teacher assist)",
    "category": "scf-session-feedback",
    "type": "interactive",
    "schedule": "On demand (POST)",
    "triggerPath": "/api/academic/session-feedback/ai-suggest-improvement",
    "callsClaude": true,
    "featureKey": "session_feedback.suggest_improvement",
    "whatItDoes": "When a faculty member or leader clicks 'suggest improvement' for a low-scoring course, Claude returns concrete teaching adjustments (likely causes, changes to try, a quick win, and what to watch next). It also feeds back whether the class's previous advice actually helped.",
    "configKnobs": "MODEL=claude-sonnet-4-6 (config row 'session_feedback.suggest_improvement' — /admin/ai-models), max_tokens=1024, small-n floor responses<3 (skips the LLM), default window=last 30 days, LEADERSHIP_ROLES=administrator/institution_admin/dean/hod/principal/coordinator, prior-outcome confidence gates (>=5 learners=strong, >=3=weak).",
    "sideEffects": "Records the generated suggestion + its input state into scf_ai_suggestions via fn_scf_record_suggestion (best-effort; failure does not break the response). Returns the suggestion to the caller. Anonymized free-text comments are sent to the model only and are NEVER returned. No human messaging.",
    "safeToManualTrigger": true,
    "notes": "This is a POST endpoint gated by a logged-in USER SESSION (supabase.auth.getUser), NOT by CRON_SECRET — an operator cannot fire it with just the cron secret; it needs an authenticated session and a JSON body { course_code, from?, to? }. Scope is self-limiting: super-admin=all, leadership=own institution, plain faculty=own taught sessions (by email). Requires CLAUDE_API_KEY or ANTHROPIC_API_KEY (returns 503 if missing). Idempotent recording (upsert), no outbound messages, so safe to re-run. This is the human-triggered version of the improve step that scf-generate-suggestions later automated."
  },
  {
    "id": "scf-freetext-carry",
    "name": "SCF free-text carry-forward",
    "category": "scf-session-feedback",
    "type": "cron",
    "schedule": "Daily · 03:30 IST (editable via dispatcher)",
    "cronExpr": "7 22 * * * (retired from vercel.json 2026-08-13)",
    "triggerPath": "/api/cron/scf-freetext-carry",
    "callsClaude": false,
    "featureKey": null,
    "featureKeyNote": "Born on the ₹0 jobs lane — no direct Anthropic path in this route; if the lane is congested, items simply classify a night later.",
    "whatItDoes": "Nightly classify+summarize of substantive learner free-texts: COLLECTs prior runs' completed classifications from the ai_jobs Max lane and persists them via fn_scf_record_freetext_carry, then ENQUEUEs this run's junk-filtered candidates from the last 7 days.",
    "configKnobs": "Candidate window (7 days) via fn_scf_freetext_carry_candidates; sanitization + caps live inside the recording fn. Day/time editable at /admin/ai-routines.",
    "sideEffects": "Enqueues ai_jobs; records carry-forward rows. PRIVACY: a learner's text is summarized back ONLY to that learner (self-scoped RPC); Senior Learners see counts-only under a >=3-learner floor; the recorder strips [ ] so crafted text cannot spoof answer markers.",
    "safeToManualTrigger": true,
    "notes": "Auth: Bearer or ?secret=. IST math: 22:07 UTC = 03:37 IST next day → slot 03:30 (minute_of_day 217, every day)."
  }
];
