export const dynamic = 'force-dynamic';
// Long-poll window for the ₹0 max-pde coach lane (mirrors work-pulse/translate).
// The Socratic feedback is generated by the Claude Max seat drain; the poll must
// be able to finish before a hard-kill. Inert while the max-pde lane is dark.
export const maxDuration = 300;

import { NextRequest, NextResponse, connection } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import {
  generateClinicalReasoningFeedback,
  type ClinicalReasoningCoachInput,
} from '@/lib/services/pde-coach-clinical-reasoning';
import { FeedbackError } from '@/lib/services/pde-coach-errors';
import {
  recordAiuTrailDelivery,
  AIU_SURFACE_PDE_CLINICAL_COACH,
} from '@/lib/services/aiu/prompt-trail-service';

// GET /api/pde/coach?learnerId=xxx&contextType=xxx&contextId=xxx
// Returns coach conversation history
export async function GET(request: NextRequest) {
  await connection();
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const searchParams = request.nextUrl.searchParams;
    const learnerId = searchParams.get('learnerId');
    const contextType = searchParams.get('contextType');
    const contextId = searchParams.get('contextId');

    if (!learnerId) {
      return NextResponse.json(
        { error: 'learnerId query param is required' },
        { status: 400 }
      );
    }

    let query = (supabase as any)
      .from('pde_coach_conversations')
      .select('*')
      .eq('learner_id', learnerId)
      .order('created_at', { ascending: true });

    if (contextType) query = query.eq('context_type', contextType);
    if (contextId) query = query.eq('context_id', contextId);

    const { data, error } = await query;
    if (error) throw error;

    return NextResponse.json({ data: data || [] });
  } catch (error: any) {
    console.error('Error fetching coach conversations:', error);
    return NextResponse.json(
      { error: error.message || 'Internal server error' },
      { status: 500 }
    );
  }
}

// POST /api/pde/coach — send message to coach
//
// Two body shapes accepted:
//
// 1. Clinical-reasoning (Socratic) — when body has assessmentId+questionId:
//    { learnerId, assessmentId, questionId, answer }
//    Routes through lib/services/pde-coach-clinical-reasoning.ts.
//    Responses:
//      200 { feedback, provider, model, latencyMs, costInr, priorAttempts, capPerCase }
//      400 { error, code:'INVALID_INPUT' }   — bad inputs
//      404 { error, code:'NOT_FOUND' }       — case or question missing
//      429 { error, code:'CAP_REACHED' }     — lifetime attempt cap hit
//      502 { error, code:'AI_FAILURE', retryable:true } — AI provider error
//
// 2. Legacy non-clinical — when body has contextType+message:
//    { learnerId, contextType, contextId, message }
//    Existing placeholder behavior preserved for non-clinical PDE coach.
export async function POST(request: NextRequest) {
  await connection();
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();

    // ------ Clinical-reasoning branch — Socratic feedback ------
    //
    // Accept TWO body shapes for the same Socratic operation so both the
    // PDEService.sendCoachMessage caller (assessmentId/questionId/answer)
    // and Agent C's useCoachFeedback hook (contextType/contextId/message
    // /questionId) can hit this endpoint without coordination friction.
    //
    // Detection rules:
    //   - shape A: body has all of {assessmentId, questionId, answer}
    //   - shape B: body has contextType==='clinical_case' AND questionId
    //              AND (message OR answer)
    const isShapeA =
      typeof body.assessmentId === 'string' &&
      typeof body.questionId === 'string' &&
      typeof body.answer === 'string';
    const isShapeB =
      body.contextType === 'clinical_case' &&
      typeof body.questionId === 'string' &&
      (typeof body.message === 'string' || typeof body.answer === 'string');

    if (isShapeA || isShapeB) {
      const input: ClinicalReasoningCoachInput = {
        learnerId: body.learnerId,
        assessmentId: isShapeA ? body.assessmentId : body.contextId,
        questionId: body.questionId,
        answer: isShapeA ? body.answer : (body.answer ?? body.message),
      };
      try {
        const result = await generateClinicalReasoningFeedback(input);

        // AIU evidence trail — record what the AI produced BEFORE the learner
        // changes anything (rubric bands AIU-a/b/c are unmarkable without it).
        // Best-effort: a trail failure never blocks the feedback. The SESSION
        // client + the table's INSERT policy bind the row to the authenticated
        // caller (learner_id = auth.uid()), not to the body's learnerId.
        const { promptSent, ...clientResult } = result;
        await recordAiuTrailDelivery(supabase, {
          learnerId: user.id,
          surface: AIU_SURFACE_PDE_CLINICAL_COACH,
          promptSent,
          aiOutput: result.feedback,
          learnerInput: input.answer,
          context: {
            assessment_id: input.assessmentId,
            question_id: input.questionId,
            ...(input.learnerId && input.learnerId !== user.id
              ? { body_learner_id: input.learnerId }
              : {}),
          },
        });

        // promptSent stays server-side: the interpolated template embeds
        // ground_truth (the answer key), which must never reach the learner —
        // same leak class 20260723140000_rcltp_answer_key_leak_fix closed.
        return NextResponse.json(clientResult, { status: 200 });
      } catch (err) {
        if (err instanceof FeedbackError) {
          return NextResponse.json(err.toJSON(), { status: err.status });
        }
        console.error('Clinical reasoning coach error:', err);
        return NextResponse.json(
          {
            error: err instanceof Error ? err.message : 'Internal error',
            code: 'INTERNAL',
            retryable: false,
          },
          { status: 500 }
        );
      }
    }

    // ------ Legacy non-clinical branch ------
    const { learnerId, contextType, contextId, message } = body;

    if (!learnerId || !message) {
      return NextResponse.json(
        { error: 'learnerId and message are required' },
        { status: 400 }
      );
    }

    // Store user message
    const { data: userMsg, error: userErr } = await (supabase as any)
      .from('pde_coach_conversations')
      .insert({
        learner_id: learnerId,
        context_type: contextType || 'general',
        context_id: contextId || null,
        role: 'user',
        content: message,
      })
      .select()
      .single();

    if (userErr) throw userErr;

    // Generate placeholder coach reply based on coaching style
    const coachReply = generateCoachReply(message, contextType);

    const { data: coachMsg, error: coachErr } = await (supabase as any)
      .from('pde_coach_conversations')
      .insert({
        learner_id: learnerId,
        context_type: contextType || 'general',
        context_id: contextId || null,
        role: 'coach',
        content: coachReply,
      })
      .select()
      .single();

    if (coachErr) throw coachErr;

    return NextResponse.json(
      { data: { userMessage: userMsg, coachReply: coachMsg } },
      { status: 201 }
    );
  } catch (error: any) {
    console.error('Error in coach conversation:', error);
    return NextResponse.json(
      { error: error.message || 'Internal server error' },
      { status: 500 }
    );
  }
}

// Placeholder coach reply generator — will be replaced with AI in Phase 4
function generateCoachReply(message: string, contextType?: string): string {
  const lowerMsg = message.toLowerCase();

  if (lowerMsg.includes('stuck') || lowerMsg.includes('help') || lowerMsg.includes('confused')) {
    return "I can see you're working through a challenge. Let's break this down step by step. What specific part is giving you trouble? Sometimes identifying the exact sticking point makes the solution clearer.";
  }

  if (lowerMsg.includes('done') || lowerMsg.includes('finished') || lowerMsg.includes('completed')) {
    return "Great progress! Before moving on, take a moment to reflect: What was the key insight you gained? Understanding the 'why' behind your work deepens your learning.";
  }

  if (contextType === 'quest') {
    return "You're making progress on your quest. Remember, the goal isn't just completion — it's building genuine understanding. What connections can you draw between this quest and your broader learning goals?";
  }

  if (contextType === 'assessment') {
    return "As you work through this assessment, focus on understanding the underlying concepts rather than just finding the right answer. What principles are being tested here?";
  }

  return "That's a great question. Let me guide you through this: think about the fundamental principles at play here. What do you already know that might apply? Building on existing knowledge is the fastest path to understanding.";
}
