-- =====================================================================
-- Session Feedback (SCF) — Weekly tiered escalation digest + AI summary
-- Created: 2026-06-25
-- =====================================================================
-- Closes class-feedback loop gaps #2 (escalation PUSH to leadership — was
-- pull-only) and #3 (AI summary AT escalation — was only on the faculty
-- self-help card). Director decisions (2026-06-25): tiered (HOD first;
-- +Principal once the same faculty+course escalates in a SECOND week) +
-- weekly digest (ONE notification per leader per week, each flagged class
-- carrying a 2-3 sentence AI summary generated by the cron).
--
-- Escalation rule reused verbatim from fn_scf_principal_escalations:
--   a (faculty_email + course_code) "escalates" in a week when it has
--   >= 3 responses AND avg(understood) < 3 in that week.
--
-- Recipient resolution (verified live 2026-06-25):
--   department of a flagged class = staff.department_id (via session_feedback
--     .faculty_id == staff.id — faculty_id is a STAFF id, not a profile id).
--   HOD       = profiles WHERE role='hod' AND department_id = <that dept>
--               AND institution_id = <class institution>.   (departments
--               .head_of_department_id is NULL for every dept — do NOT use it.)
--   Principal = profiles WHERE role='principal' AND institution_id = <class inst>.
--   Coverage gap (surfaced, not hidden): only 35/58 staffed depts have an HOD
--   profile and 9/9 institutions have a principal — a flagged class whose dept
--   has no HOD simply yields no HOD recipient that week (reflected in the return
--   counts; principal still fires on repeat). No silent drop of the escalation.
--
-- Notification write mirrors fn_scf_nudge_pending_learners EXACTLY:
--   one `notifications` row (targeting + idempotency_key) + one
--   `user_notifications` fan-out row per recipient. No fan-out trigger exists.
--   created_by = earliest super_admin (NOT NULL system identity).
-- =====================================================================

-- ── 1. Escalation log — repeat-detection (tier ladder) + idempotency + audit ──
CREATE TABLE IF NOT EXISTS public.session_feedback_escalations (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  institution_id           uuid NOT NULL,
  department_id            uuid,
  faculty_email            text NOT NULL,           -- stored lower-cased (join key)
  course_code              text NOT NULL,
  escalation_count         int  NOT NULL DEFAULT 0, -- distinct weeks this faculty+course escalated
  first_escalated_week     date,
  last_escalated_week      date,
  hod_notified_week        date,                    -- idempotency / audit marker
  principal_notified_week  date,                    -- idempotency / audit marker
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_scf_escalation UNIQUE (institution_id, faculty_email, course_code)
);

ALTER TABLE public.session_feedback_escalations ENABLE ROW LEVEL SECURITY;

-- Read: super_admin / admin / institution-scoped leadership. Writes are
-- service-role only (the RPCs below are SECURITY DEFINER) — no INSERT/UPDATE
-- policy is granted to authenticated.
DROP POLICY IF EXISTS scf_escalations_select ON public.session_feedback_escalations;
CREATE POLICY scf_escalations_select ON public.session_feedback_escalations
FOR SELECT USING (
  is_super_admin() OR is_admin()
  OR role_has_institution_access(institution_id)
);

-- ── 2. Compute (PURE READ) — the cron uses this to know what to summarize ──────
CREATE OR REPLACE FUNCTION public.fn_scf_compute_weekly_escalations(p_week_start date)
RETURNS TABLE (
  institution_id   uuid,
  faculty_email    text,
  course_code      text,
  course_name      text,
  responses        bigint,
  avg_understood   numeric,
  free_texts       text[]
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_week_end date := p_week_start + 6;
BEGIN
  RETURN QUERY
  SELECT f.institution_id::uuid,
         lower(f.faculty_email)::text                                   AS faculty_email,
         f.course_code::text,
         max(f.course_name)::text                                       AS course_name,
         count(*)::bigint                                               AS responses,
         round(avg(f.understood)::numeric, 2)                          AS avg_understood,
         COALESCE(
           array_remove(array_agg(NULLIF(btrim(f.free_text), '')), NULL),
           '{}'::text[]
         )                                                              AS free_texts
  FROM public.session_feedback f
  WHERE f.attendance_date BETWEEN p_week_start AND v_week_end
  GROUP BY f.institution_id, lower(f.faculty_email), f.course_code
  HAVING count(*) >= 3 AND avg(f.understood) < 3
  ORDER BY avg(f.understood) ASC;
END;
$$;

-- ── 3. Apply (WRITE) — three sequential statements so each sees the prior's
--       writes (a single mega-CTE cannot: data-modifying CTEs share one
--       snapshot, so a marker-UPDATE can't see the log-UPSERT in the same stmt).
--       p_summaries: jsonb map { "<faculty_email>|<course_code>": "<AI summary>" }.
CREATE OR REPLACE FUNCTION public.fn_scf_apply_weekly_escalation_digest(
  p_week_start date,
  p_summaries  jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE (recipients_notified int, classes_flagged int)
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_week_end   date := p_week_start + 6;
  v_system     uuid;
  v_recipients int := 0;
  v_classes    int := 0;
BEGIN
  -- Stable system identity for notifications.created_by (NOT NULL).
  SELECT p.id INTO v_system
  FROM public.profiles p
  WHERE p.is_super_admin = true OR p.role = 'super_admin'
  ORDER BY p.created_at ASC NULLS LAST
  LIMIT 1;

  -- Statement 1: upsert the escalation log (increment escalation_count ONCE per
  -- new week → idempotent if the cron re-runs the same week). Resolves the
  -- department via staff so the tier ladder + recipient lookup have it.
  WITH esc AS (
    SELECT f.institution_id,
           lower(f.faculty_email)         AS faculty_email,
           f.course_code,
           (array_agg(f.faculty_id))[1]   AS faculty_id
    FROM public.session_feedback f
    WHERE f.attendance_date BETWEEN p_week_start AND v_week_end
    GROUP BY f.institution_id, lower(f.faculty_email), f.course_code
    HAVING count(*) >= 3 AND avg(f.understood) < 3
  ),
  esc_dept AS (
    SELECT esc.institution_id, s.department_id, esc.faculty_email, esc.course_code
    FROM esc LEFT JOIN public.staff s ON s.id = esc.faculty_id
  )
  INSERT INTO public.session_feedback_escalations AS e
    (institution_id, department_id, faculty_email, course_code,
     escalation_count, first_escalated_week, last_escalated_week, updated_at)
  SELECT ed.institution_id, ed.department_id, ed.faculty_email, ed.course_code,
         1, p_week_start, p_week_start, now()
  FROM esc_dept ed
  ON CONFLICT (institution_id, faculty_email, course_code) DO UPDATE
    SET escalation_count =
          e.escalation_count
          + CASE WHEN e.last_escalated_week IS NULL
                   OR e.last_escalated_week < p_week_start
                 THEN 1 ELSE 0 END,
        last_escalated_week  = GREATEST(COALESCE(e.last_escalated_week, p_week_start), p_week_start),
        first_escalated_week = LEAST(COALESCE(e.first_escalated_week, p_week_start), p_week_start),
        department_id        = COALESCE(e.department_id, EXCLUDED.department_id),
        updated_at           = now();

  GET DIAGNOSTICS v_classes = ROW_COUNT;
  IF v_classes = 0 THEN
    RETURN QUERY SELECT 0, 0;
    RETURN;
  END IF;

  -- Statement 2: resolve recipients (HOD always; +Principal once escalation_count
  -- >= 2 — the log was upserted above, so the tier is now visible) and write one
  -- digest per recipient (idempotent per recipient per week via idempotency_key).
  WITH esc AS (
    SELECT f.institution_id,
           lower(f.faculty_email)               AS faculty_email,
           f.course_code,
           max(f.course_name)                   AS course_name,
           (array_agg(f.faculty_id))[1]         AS faculty_id,
           count(*)::bigint                      AS responses,
           round(avg(f.understood)::numeric, 2) AS avg_understood
    FROM public.session_feedback f
    WHERE f.attendance_date BETWEEN p_week_start AND v_week_end
    GROUP BY f.institution_id, lower(f.faculty_email), f.course_code
    HAVING count(*) >= 3 AND avg(f.understood) < 3
  ),
  flagged AS (
    SELECT e.institution_id, l.department_id, e.faculty_email, e.course_code,
           e.course_name, e.responses, e.avg_understood, l.escalation_count,
           CASE WHEN l.escalation_count >= 2 THEN 'hod_principal' ELSE 'hod' END AS tier,
           COALESCE(p_summaries ->> (e.faculty_email || '|' || e.course_code),
                    'Average understanding ' || e.avg_understood::text
                    || '/5 across ' || e.responses::text || ' learners.') AS summary
    FROM esc e
    JOIN public.session_feedback_escalations l
      ON l.institution_id = e.institution_id
     AND l.faculty_email  = e.faculty_email
     AND l.course_code    = e.course_code
  ),
  recips AS (
    SELECT f.*, h.id AS recipient_id, 'hod'::text AS recipient_role
    FROM flagged f
    JOIN public.profiles h
      ON h.role = 'hod' AND h.department_id = f.department_id
     AND h.institution_id = f.institution_id
    UNION ALL
    SELECT f.*, pr.id AS recipient_id, 'principal'::text AS recipient_role
    FROM flagged f
    JOIN public.profiles pr
      ON pr.role = 'principal' AND pr.institution_id = f.institution_id
    WHERE f.tier = 'hod_principal'
  ),
  per_recipient AS (
    SELECT recipient_id,
           (array_agg(DISTINCT recipient_role))[1] AS recipient_role,
           count(DISTINCT (faculty_email || '|' || course_code))::int AS n_classes,
           string_agg(
             DISTINCT '• ' || COALESCE(course_name, course_code)
               || ' (avg ' || avg_understood::text || '/5, ' || responses::text
               || ' learners): ' || summary,
             E'\n'
           ) AS body_list
    FROM recips
    GROUP BY recipient_id
  ),
  ins_notif AS (
    INSERT INTO public.notifications (
      id, title, body, url, icon,
      created_by, targeting,
      priority, category, kind,
      requires_acknowledgment, is_layer_0,
      idempotency_key, metadata,
      created_at, updated_at
    )
    SELECT
      gen_random_uuid(),
      pr.n_classes || ' class' || CASE WHEN pr.n_classes = 1 THEN '' ELSE 'es' END
        || ' need your attention this week',
      'Classes flagged by learner feedback (avg understanding below 3) in your '
        || 'scope this week:' || E'\n' || pr.body_list,
      '/academic/session-feedback/principal',
      'alert-triangle',
      COALESCE(v_system, pr.recipient_id),
      jsonb_build_object('type', 'user', 'user_ids', jsonb_build_array(pr.recipient_id)),
      'high',
      'dashboard:scf_escalation',
      'work_item',
      FALSE,
      FALSE,
      'scf-esc:' || pr.recipient_id::text || ':' || p_week_start::text,
      jsonb_build_object('week_start', p_week_start, 'n_classes', pr.n_classes,
                         'role', pr.recipient_role, 'source', 'scf_escalation_digest'),
      now(), now()
    FROM per_recipient pr
    WHERE NOT EXISTS (
      SELECT 1 FROM public.notifications n2
      WHERE n2.idempotency_key =
        'scf-esc:' || pr.recipient_id::text || ':' || p_week_start::text
    )
    RETURNING id, (targeting -> 'user_ids' ->> 0)::uuid AS recipient_id
  ),
  ins_user AS (
    INSERT INTO public.user_notifications (id, notification_id, user_id, created_at)
    SELECT gen_random_uuid(), n.id, n.recipient_id, now()
    FROM ins_notif n
    RETURNING 1
  )
  SELECT COUNT(*)::int INTO v_recipients FROM ins_user;

  -- Statement 3: stamp the per-class notified_week markers (separate statement →
  -- sees the notifications written above). A class is HOD-notified this week iff
  -- one of its HODs holds a digest notification for this week; same for Principal.
  UPDATE public.session_feedback_escalations e
  SET hod_notified_week = p_week_start
  WHERE e.last_escalated_week = p_week_start
    AND EXISTS (
      SELECT 1 FROM public.profiles h
      WHERE h.role = 'hod' AND h.department_id = e.department_id
        AND h.institution_id = e.institution_id
        AND EXISTS (SELECT 1 FROM public.notifications n
                    WHERE n.idempotency_key = 'scf-esc:' || h.id::text || ':' || p_week_start::text)
    );

  UPDATE public.session_feedback_escalations e
  SET principal_notified_week = p_week_start
  WHERE e.last_escalated_week = p_week_start
    AND e.escalation_count >= 2
    AND EXISTS (
      SELECT 1 FROM public.profiles pr
      WHERE pr.role = 'principal' AND pr.institution_id = e.institution_id
        AND EXISTS (SELECT 1 FROM public.notifications n
                    WHERE n.idempotency_key = 'scf-esc:' || pr.id::text || ':' || p_week_start::text)
    );

  RETURN QUERY SELECT v_recipients, v_classes;
END;
$$;

-- ── Anon-lock: both RPCs are service-role only (cron context) ──────────────────
REVOKE EXECUTE ON FUNCTION public.fn_scf_compute_weekly_escalations(date)            FROM anon, PUBLIC, authenticated;
GRANT  EXECUTE ON FUNCTION public.fn_scf_compute_weekly_escalations(date)            TO service_role;
REVOKE EXECUTE ON FUNCTION public.fn_scf_apply_weekly_escalation_digest(date, jsonb) FROM anon, PUBLIC, authenticated;
GRANT  EXECUTE ON FUNCTION public.fn_scf_apply_weekly_escalation_digest(date, jsonb) TO service_role;

COMMENT ON TABLE public.session_feedback_escalations IS
  'SCF weekly escalation log: one row per (institution, faculty_email, course_code); '
  'escalation_count drives the HOD->Principal tier ladder; *_notified_week give '
  'per-recipient weekly idempotency. Written only by fn_scf_apply_weekly_escalation_digest.';
COMMENT ON FUNCTION public.fn_scf_compute_weekly_escalations(date) IS
  'Pure read: this week''s escalated (faculty+course) groups (>=3 responses, avg<3) '
  'with anonymized free_texts — the cron uses this to generate per-class AI summaries.';
COMMENT ON FUNCTION public.fn_scf_apply_weekly_escalation_digest(date, jsonb) IS
  'Writes the weekly tiered escalation digest: upserts the log (tier = HOD if first '
  'week, +Principal on repeat), resolves recipients, writes one notification + '
  'user_notifications per recipient (idempotent per recipient per week). service_role only.';
