-- ============================================================================
-- HR Recruitment Jobs — extend with location, specification and display fields
-- Created: 2026-06-27
--
-- Adds columns to support the full-page job-create form:
--   Basic Details : job_code, job_type, industry, employer_type
--   Location      : country, state, city, zip_code
--   Specification : education_level, min/max_experience_years
--   Salary display: salary_currency, salary_duration, display_salary
--
-- The existing requirements JSONB already holds qualifications[] and skills[].
-- ============================================================================

ALTER TABLE public.hr_recruitment_jobs
  ADD COLUMN IF NOT EXISTS job_code              text,
  ADD COLUMN IF NOT EXISTS job_type              text CHECK (job_type IN (
                             'full_time','part_time','contract','internship','freelance'
                           )),
  ADD COLUMN IF NOT EXISTS industry              text,
  ADD COLUMN IF NOT EXISTS employer_type         text CHECK (employer_type IN (
                             'government','private','public_sector','non_profit','educational'
                           )),
  ADD COLUMN IF NOT EXISTS country               text DEFAULT 'India',
  ADD COLUMN IF NOT EXISTS state                 text,
  ADD COLUMN IF NOT EXISTS city                  text,
  ADD COLUMN IF NOT EXISTS zip_code              text,
  ADD COLUMN IF NOT EXISTS education_level       text CHECK (education_level IN (
                             'high_school','diploma','bachelors','masters','phd','any'
                           )),
  ADD COLUMN IF NOT EXISTS min_experience_years  integer CHECK (min_experience_years >= 0),
  ADD COLUMN IF NOT EXISTS max_experience_years  integer CHECK (max_experience_years >= 0),
  ADD COLUMN IF NOT EXISTS salary_currency       text NOT NULL DEFAULT 'INR',
  ADD COLUMN IF NOT EXISTS salary_duration       text NOT NULL DEFAULT 'per_month' CHECK (salary_duration IN (
                             'per_hour','per_day','per_month','per_year'
                           )),
  ADD COLUMN IF NOT EXISTS display_salary        boolean NOT NULL DEFAULT false;

-- UNIQUE on job_code (NULLs are exempt from UNIQUE in Postgres)
ALTER TABLE public.hr_recruitment_jobs
  DROP CONSTRAINT IF EXISTS hr_recruitment_jobs_job_code_unique;
ALTER TABLE public.hr_recruitment_jobs
  ADD CONSTRAINT hr_recruitment_jobs_job_code_unique UNIQUE (job_code);

-- Experience range guard
ALTER TABLE public.hr_recruitment_jobs
  DROP CONSTRAINT IF EXISTS hr_recruitment_jobs_experience_range_chk;
ALTER TABLE public.hr_recruitment_jobs
  ADD CONSTRAINT hr_recruitment_jobs_experience_range_chk CHECK (
    min_experience_years IS NULL
    OR max_experience_years IS NULL
    OR min_experience_years <= max_experience_years
  );

CREATE INDEX IF NOT EXISTS idx_hr_recruitment_jobs_job_type
  ON public.hr_recruitment_jobs(job_type);
CREATE INDEX IF NOT EXISTS idx_hr_recruitment_jobs_industry
  ON public.hr_recruitment_jobs(industry);
CREATE INDEX IF NOT EXISTS idx_hr_recruitment_jobs_city
  ON public.hr_recruitment_jobs(city);

COMMENT ON COLUMN public.hr_recruitment_jobs.job_code IS
  'Human-readable code (e.g. JOB-001). Auto-generated by service if left NULL.';
COMMENT ON COLUMN public.hr_recruitment_jobs.job_type IS
  'Employment type: full_time, part_time, contract, internship, freelance.';
COMMENT ON COLUMN public.hr_recruitment_jobs.industry IS
  'Industry sector for the role (from a fixed list or free-text).';
COMMENT ON COLUMN public.hr_recruitment_jobs.employer_type IS
  'Type of employer: government, private, public_sector, non_profit, educational.';
COMMENT ON COLUMN public.hr_recruitment_jobs.education_level IS
  'Minimum education level required: high_school, diploma, bachelors, masters, phd, any.';
COMMENT ON COLUMN public.hr_recruitment_jobs.display_salary IS
  'When true, the salary range is shown to applicants on the /careers page.';
COMMENT ON COLUMN public.hr_recruitment_jobs.salary_currency IS
  'Currency code for the salary range (e.g. INR, USD). Defaults to INR.';
COMMENT ON COLUMN public.hr_recruitment_jobs.salary_duration IS
  'Pay period for the salary range: per_hour, per_day, per_month, per_year.';
