-- ============================================================================
-- T6.2 — HR Disciplinary Case Tracking
-- ============================================================================
-- Per specs/hr-module-decomposition-2026-05-09.md §T6.2.
--
-- DISTINCT FROM:
--   * T6.1 hr_memos (warnings — counts toward termination threshold)
--   * T6.4 hr_offboarding_cases (separation/exit, including post-termination)
--
-- A disciplinary case is the FORMAL multi-stage proceeding that may sit BETWEEN
-- a third memo and an actual termination. Stages: initiated → enquiry →
-- hearing → decision. Decisions: warning | suspension | termination |
-- exonerated. On `termination` outcome the service writes an
-- hr_offboarding_cases row (separation_type='termination', current_step_index=1,
-- status='open') so the existing γ Wave-1 offboarding workflow takes over from
-- there. No hr_offboarding_cases schema change — additive write only.
--
-- Three tables:
--   1. hr_disciplinary_cases     — one row per formal proceeding
--   2. hr_disciplinary_events    — append-only timeline (initiated/enquiry/...)
--   3. hr_disciplinary_witnesses — optional witness statements per case
--
-- Standing rules honored
--   * staff.profile_id = auth.uid()  (not auth_user_id — see PR #924 fix)
--   * RLS enabled on all 3 tables — super_admin full, staff sees own
--   * No staging DB — TIER-1 DDL, applied to prod via Management API
--   * Smoke test is RAISE-EXCEPTION-only (no ROLLBACK TO SAVEPOINT — invalid
--     in PL/pgSQL; see PR #925 fix)
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. hr_disciplinary_cases — the formal proceeding
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.hr_disciplinary_cases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    staff_id UUID NOT NULL,                       -- public.staff.id
    case_number TEXT NOT NULL UNIQUE,             -- human-readable e.g. DC-2026-0001
    alleged_misconduct TEXT NOT NULL,             -- plain-English summary
    initiated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    initiated_by UUID,                            -- profiles.id of HR admin
    status TEXT NOT NULL DEFAULT 'active',        -- active | closed
    current_stage TEXT NOT NULL DEFAULT 'initiated', -- initiated | enquiry | hearing | decision | closed
    evidence JSONB NOT NULL DEFAULT '{}'::jsonb,  -- {memo_ids: [...], attachments: [...], notes: ...}
    outcome TEXT,                                 -- warning | suspension | termination | exonerated (NULL until decided)
    outcome_date TIMESTAMPTZ,                     -- set when outcome != NULL
    outcome_note TEXT,                            -- HR's English rationale
    suspension_start_date DATE,                   -- when outcome='suspension'
    suspension_end_date DATE,                     -- when outcome='suspension'
    organization_id UUID,                         -- institution_id; nullable for cross-org if needed
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_disc_case_status CHECK (status IN ('active', 'closed')),
    CONSTRAINT chk_disc_case_stage CHECK (
        current_stage IN ('initiated', 'enquiry', 'hearing', 'decision', 'closed')
    ),
    CONSTRAINT chk_disc_case_outcome CHECK (
        outcome IS NULL
        OR outcome IN ('warning', 'suspension', 'termination', 'exonerated')
    ),
    -- If outcome is set, outcome_date must be set too
    CONSTRAINT chk_disc_case_outcome_date_pair CHECK (
        (outcome IS NULL AND outcome_date IS NULL)
        OR (outcome IS NOT NULL AND outcome_date IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_hr_disc_cases_staff ON public.hr_disciplinary_cases(staff_id);
CREATE INDEX IF NOT EXISTS idx_hr_disc_cases_status ON public.hr_disciplinary_cases(status);
CREATE INDEX IF NOT EXISTS idx_hr_disc_cases_stage ON public.hr_disciplinary_cases(current_stage);
CREATE INDEX IF NOT EXISTS idx_hr_disc_cases_initiated_at ON public.hr_disciplinary_cases(initiated_at DESC);
CREATE INDEX IF NOT EXISTS idx_hr_disc_cases_outcome ON public.hr_disciplinary_cases(outcome) WHERE outcome IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_hr_disc_cases_org ON public.hr_disciplinary_cases(organization_id);

COMMENT ON TABLE public.hr_disciplinary_cases IS
    'T6.2 — FORMAL disciplinary proceeding (distinct from T6.1 memos and T6.4 separation). Stage state machine: initiated → enquiry → hearing → decision → closed. Outcome on termination triggers an additive write to hr_offboarding_cases via service code.';
COMMENT ON COLUMN public.hr_disciplinary_cases.case_number IS
    'Human-readable case number e.g. DC-2026-0001. Unique. Generated by service code on initiate.';
COMMENT ON COLUMN public.hr_disciplinary_cases.evidence IS
    'JSONB structure: {memo_ids: [...uuid], attachments: [{name,url}], notes: text}. Memos are cross-referenced (not duplicated) from hr_memos.';
COMMENT ON COLUMN public.hr_disciplinary_cases.outcome IS
    'NULL until decision stage. warning | suspension | termination | exonerated. termination triggers offboarding case creation.';

-- ---------------------------------------------------------------------------
-- 2. hr_disciplinary_events — append-only audit timeline
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.hr_disciplinary_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id UUID NOT NULL REFERENCES public.hr_disciplinary_cases(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,                     -- initiated | enquiry_started | enquiry_finding | hearing_scheduled | hearing_held | decision | note | stage_change | evidence_added
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    description TEXT NOT NULL,                    -- plain-English description
    recorded_by UUID,                             -- profiles.id of who logged the event
    attachments JSONB NOT NULL DEFAULT '[]'::jsonb, -- [{name, url}, ...]
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_disc_event_type CHECK (
        event_type IN (
            'initiated', 'enquiry_started', 'enquiry_finding',
            'hearing_scheduled', 'hearing_held', 'decision',
            'note', 'stage_change', 'evidence_added'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_hr_disc_events_case ON public.hr_disciplinary_events(case_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_hr_disc_events_type ON public.hr_disciplinary_events(event_type);

COMMENT ON TABLE public.hr_disciplinary_events IS
    'T6.2 — append-only audit trail for a disciplinary case. Service writes one event per stage transition + ad-hoc notes.';

-- ---------------------------------------------------------------------------
-- 3. hr_disciplinary_witnesses — optional witness statements
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.hr_disciplinary_witnesses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id UUID NOT NULL REFERENCES public.hr_disciplinary_cases(id) ON DELETE CASCADE,
    witness_name TEXT NOT NULL,
    witness_role TEXT,                            -- e.g. 'colleague', 'supervisor', 'external'
    witness_statement TEXT NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_by UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_hr_disc_witnesses_case ON public.hr_disciplinary_witnesses(case_id);

COMMENT ON TABLE public.hr_disciplinary_witnesses IS
    'T6.2 — optional witness statements. Multiple witnesses per case allowed. Statement text is free-form English.';

-- ---------------------------------------------------------------------------
-- 4. updated_at trigger
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_hr_disciplinary_cases_touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_hr_disciplinary_cases_touch ON public.hr_disciplinary_cases;
CREATE TRIGGER trg_hr_disciplinary_cases_touch
    BEFORE UPDATE ON public.hr_disciplinary_cases
    FOR EACH ROW EXECUTE FUNCTION public.fn_hr_disciplinary_cases_touch_updated_at();

-- ---------------------------------------------------------------------------
-- 5. RLS policies
-- ---------------------------------------------------------------------------
ALTER TABLE public.hr_disciplinary_cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_disciplinary_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hr_disciplinary_witnesses ENABLE ROW LEVEL SECURITY;

-- super_admin full access on all 3 tables
DROP POLICY IF EXISTS p_hr_disc_cases_super_admin_all ON public.hr_disciplinary_cases;
CREATE POLICY p_hr_disc_cases_super_admin_all ON public.hr_disciplinary_cases
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_super_admin = true
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_super_admin = true
        )
    );

DROP POLICY IF EXISTS p_hr_disc_events_super_admin_all ON public.hr_disciplinary_events;
CREATE POLICY p_hr_disc_events_super_admin_all ON public.hr_disciplinary_events
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_super_admin = true
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_super_admin = true
        )
    );

DROP POLICY IF EXISTS p_hr_disc_witnesses_super_admin_all ON public.hr_disciplinary_witnesses;
CREATE POLICY p_hr_disc_witnesses_super_admin_all ON public.hr_disciplinary_witnesses
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_super_admin = true
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE id = auth.uid() AND is_super_admin = true
        )
    );

-- Staff can read their own cases (read-only)
DROP POLICY IF EXISTS p_hr_disc_cases_staff_read_own ON public.hr_disciplinary_cases;
CREATE POLICY p_hr_disc_cases_staff_read_own ON public.hr_disciplinary_cases
    FOR SELECT TO authenticated
    USING (
        staff_id IN (
            SELECT id FROM public.staff WHERE profile_id = auth.uid()
        )
    );

-- Staff can read events on their own cases (read-only)
DROP POLICY IF EXISTS p_hr_disc_events_staff_read_own ON public.hr_disciplinary_events;
CREATE POLICY p_hr_disc_events_staff_read_own ON public.hr_disciplinary_events
    FOR SELECT TO authenticated
    USING (
        case_id IN (
            SELECT id FROM public.hr_disciplinary_cases
            WHERE staff_id IN (
                SELECT id FROM public.staff WHERE profile_id = auth.uid()
            )
        )
    );

-- Staff can read witness statements on their own cases (read-only)
DROP POLICY IF EXISTS p_hr_disc_witnesses_staff_read_own ON public.hr_disciplinary_witnesses;
CREATE POLICY p_hr_disc_witnesses_staff_read_own ON public.hr_disciplinary_witnesses
    FOR SELECT TO authenticated
    USING (
        case_id IN (
            SELECT id FROM public.hr_disciplinary_cases
            WHERE staff_id IN (
                SELECT id FROM public.staff WHERE profile_id = auth.uid()
            )
        )
    );

-- ---------------------------------------------------------------------------
-- 6. Smoke test — verify all 3 tables exist + key columns + constraints
-- ---------------------------------------------------------------------------
-- SELECT-only verification (no INSERT) per locked rule against NOT-NULL-column
-- omission breaking smoke INSERTs.
DO $$
DECLARE
    v_table_count INT;
    v_outcome_check_present BOOLEAN;
BEGIN
    SELECT COUNT(*) INTO v_table_count
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name IN (
          'hr_disciplinary_cases',
          'hr_disciplinary_events',
          'hr_disciplinary_witnesses'
      );

    IF v_table_count <> 3 THEN
        RAISE EXCEPTION 'T6.2 smoke FAILED: expected 3 disciplinary tables, found %', v_table_count;
    END IF;

    -- Verify outcome enum check exists
    SELECT EXISTS (
        SELECT 1 FROM information_schema.check_constraints
        WHERE constraint_schema = 'public'
          AND constraint_name = 'chk_disc_case_outcome'
    ) INTO v_outcome_check_present;

    IF NOT v_outcome_check_present THEN
        RAISE EXCEPTION 'T6.2 smoke FAILED: chk_disc_case_outcome constraint not found';
    END IF;

    RAISE NOTICE 'T6.2 smoke OK — 3 tables + RLS + outcome constraint verified.';
END $$;

COMMIT;
