-- SUPERSEDED BY 20261213100000_instasolver_substrate_v2.sql.
--
-- THIS FILE IS NOW EMPTY ON PURPOSE. It declares nothing, creates nothing and
-- changes nothing. Applying it is a no-op that records version 20261103000000
-- in supabase_migrations.schema_migrations and moves on.
--
-- ---------------------------------------------------------------------------
-- WHY IT IS EMPTY RATHER THAN DELETED, AND WHY IT NO LONGER RAISES
-- ---------------------------------------------------------------------------
--
-- This file was never applied to production and never will be. Its premise was
-- reversed by the Director on 2026-09-14 (specs/instasolver-2026-09-14.md):
-- `issue_type` on grievance_tickets has no reader, so tagging broken-thing
-- reports instead of separating them would have counted every one of them as a
-- learner grievance in the NAAC and UGC exports; and the requirement_requests
-- island duplicates the Procurement module. Broken things now go to Campus Walk
-- (I4) and purchases to Procurement (I3/I5).
--
-- The first attempt at making "do not apply" enforceable put a `RAISE EXCEPTION`
-- at the top of this file's transaction. That did stop this file — and it
-- stopped everything behind it. `supabase db push` applies pending migrations in
-- version order and halts on the first error, so an unconditional raise at
-- 20261103000000 means 20261103020000_campus_walk_step_days.sql and
-- 20261213100000_instasolver_substrate_v2.sql never run. The spec says
-- campus_walk_step_days is unaffected and must still apply, so that guard broke
-- the very deployment it was meant to protect. A file that cannot be applied
-- wrongly because it does nothing is strictly safer than a file that refuses to
-- be applied and takes the queue down with it.
--
-- Deleting the file outright was the other option and is worse: the version
-- would go missing from the migration history that
-- supabase_migrations.schema_migrations is reconciled against, and
-- __tests__/ci/check-migration-rename-applied.test.ts depends on this body
-- existing. Both are handled — see below.
--
-- ---------------------------------------------------------------------------
-- WHERE THE BODY WENT
-- ---------------------------------------------------------------------------
--
-- The 1,193 lines that used to live here are preserved verbatim at
--   __tests__/ci/fixtures/instasolver-substrate-20261103000000.sql
-- copied from jicate/main at the commit that superseded them. That copy exists
-- for exactly one consumer: the rename-guard regression test, which needs a real
-- 60 KB migration body to prove the guard still lands on the shape it was
-- written for. It is a test fixture, not a migration — nothing applies it, and
-- it sits outside supabase/migrations/ so no DDL gate reads it as pending work.
--
-- If you are deliberately resurrecting this premise, read
-- specs/instasolver-2026-09-14.md first: `issue_type` still has no reader, so
-- every broken-thing row would still be counted as a learner grievance in the
-- NAAC and UGC exports. The v2 migration's verification block raises if
-- grievance_tickets ever acquires `issue_type` or `requirement_id`, so that
-- mistake is still caught — at the file that is actually being applied, which is
-- where an error belongs.
--
-- RENAME-SAFE: 20260504 -> 20261103000000. The source version never applied
-- (20260504_ai_pulse_rls_hardening.sql parses to the same version string
-- `20260504`, and supabase_migrations.schema_migrations keys on version ALONE,
-- so one recorded as applied and this one never executed). The rename is now
-- doubly moot: this file declares no objects, so there is nothing to strand.
--
-- No transaction is opened and no statement is issued. Intentionally.
