-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: 20260521_bos_ta_da_sop_redesign.sql
--
-- Purpose
--   Re-shape bos_ta_da_claims around the new SOP for BoS remuneration:
--     • External members: honorarium ₹1,500 + TA ₹5/km (round-trip)
--     • Internal members: honorarium ₹1,000 (no TA)
--   The previous schema modelled DA (daily allowance) per day × rate, which
--   no longer matches policy. Claims are now auto-generated by the
--   attendance route on 'present' status — manual create/delete is removed.
--
-- Changes
--   1. bos_external_experts: + distance_km (one-way km to institution; the
--      runtime compute step doubles it for round-trip TA).
--   2. bos_members: + display_distance_km snapshot column (matches the
--      existing display_* mirror pattern from 20260521_sync_bos_members_from_expert).
--   3. Extend the bos_external_experts → bos_members sync trigger to include
--      distance_km, plus a one-time backfill of any existing values.
--   4. bos_ta_da_claims: rename da_days → honorarium_units, da_rate →
--      honorarium_rate, da_amount → honorarium_amount. Drop & re-add
--      total_amount GENERATED with the renamed expression.
--   5. Drop NOT NULL on expert_id — internal members now also receive
--      auto-generated claims (₹1,000 honorarium, no TA).
--
-- Backfill / data semantics
--   Existing bos_ta_da_claims rows keep their da_* values, which after the
--   rename are re-interpreted as honorarium_*. Deliberate semantic shift
--   accepted for rollout — this is a fresh SOP cutover, in-flight test data
--   is not actively in payment.
--
-- RLS note (informational; not changed here)
--   bos_tada_insert / bos_tada_delete require bos.ta_da.create / admin
--   respectively. The auto-claim post-step in the attendance route
--   (Phase 3) will use a service-role client so an editor with
--   bos.meetings.edit can still trigger create/delete via 'mark present'
--   without being granted explicit claim permissions.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── 1. bos_external_experts: distance_km ────────────────────────────────────
ALTER TABLE bos_external_experts
  ADD COLUMN IF NOT EXISTS distance_km NUMERIC(6,2);

COMMENT ON COLUMN bos_external_experts.distance_km IS
  'One-way distance (km) from expert location to the institution. The TA '
  'compute step doubles this for round-trip (TA = distance_km × 2 × ₹5). '
  'NULL = no TA component; the claim still receives honorarium.';


-- ── 2. bos_members: display_distance_km snapshot ────────────────────────────
ALTER TABLE bos_members
  ADD COLUMN IF NOT EXISTS display_distance_km NUMERIC(6,2);

COMMENT ON COLUMN bos_members.display_distance_km IS
  'Snapshot of bos_external_experts.distance_km, kept in sync by '
  'trg_sync_bos_members_from_expert. NULL for internal (staff) members.';


-- ── 3. Extend sync function + trigger to mirror distance_km ─────────────────
-- Re-define the function additively — previously synced columns are kept;
-- distance_km is added. SECURITY DEFINER + locked search_path retained
-- from the original 20260521_sync_bos_members_from_expert.sql definition.
CREATE OR REPLACE FUNCTION public.sync_bos_members_from_expert()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  UPDATE bos_members
  SET
    display_name = CASE
      WHEN NEW.title IS NOT NULL AND NEW.title <> ''
        THEN NEW.title || ' ' || NEW.name
      ELSE NEW.name
    END,
    display_designation  = NEW.designation,
    display_institution  = NEW.institution_name,
    display_department   = NEW.department_name,
    display_distance_km  = NEW.distance_km,
    address              = NEW.address,
    contact_no           = NEW.contact_no,
    email                = NEW.email,
    updated_at           = now()
  WHERE expert_id = NEW.id;

  RETURN NEW;
END;
$$;

-- Recreate the trigger so the WHEN clause also fires on distance_km changes.
DROP TRIGGER IF EXISTS trg_sync_bos_members_from_expert ON bos_external_experts;

CREATE TRIGGER trg_sync_bos_members_from_expert
  AFTER UPDATE ON bos_external_experts
  FOR EACH ROW
  WHEN (
    OLD.title             IS DISTINCT FROM NEW.title             OR
    OLD.name              IS DISTINCT FROM NEW.name              OR
    OLD.designation       IS DISTINCT FROM NEW.designation       OR
    OLD.institution_name  IS DISTINCT FROM NEW.institution_name  OR
    OLD.department_name   IS DISTINCT FROM NEW.department_name   OR
    OLD.distance_km       IS DISTINCT FROM NEW.distance_km       OR
    OLD.address           IS DISTINCT FROM NEW.address           OR
    OLD.contact_no        IS DISTINCT FROM NEW.contact_no        OR
    OLD.email             IS DISTINCT FROM NEW.email
  )
  EXECUTE FUNCTION public.sync_bos_members_from_expert();

-- One-time backfill for any experts that might already have a distance_km
-- value (unlikely on first run, but the WHERE makes this idempotent and
-- a no-op if re-applied).
UPDATE bos_members AS m
SET
  display_distance_km = e.distance_km,
  updated_at = now()
FROM bos_external_experts AS e
WHERE m.expert_id = e.id
  AND m.display_distance_km IS DISTINCT FROM e.distance_km;


-- ── 4. bos_ta_da_claims: rename DA columns, recompute total ─────────────────
-- DROP the GENERATED column first. Postgres refuses to rename a column
-- that's referenced in a generated expression — the dependency in the
-- pg_attrdef catalog blocks the rename. Dropping first lets us rename
-- the inputs cleanly, then re-add the generated column with the new
-- expression.
ALTER TABLE bos_ta_da_claims DROP COLUMN IF EXISTS total_amount;

ALTER TABLE bos_ta_da_claims RENAME COLUMN da_days   TO honorarium_units;
ALTER TABLE bos_ta_da_claims RENAME COLUMN da_rate   TO honorarium_rate;
ALTER TABLE bos_ta_da_claims RENAME COLUMN da_amount TO honorarium_amount;

-- Re-add the generated total. The SOP only uses honorarium + travel,
-- but other_amount stays in the expression so admin overrides still flow
-- through to the displayed total without further schema changes.
ALTER TABLE bos_ta_da_claims
  ADD COLUMN total_amount NUMERIC(10,2) GENERATED ALWAYS AS (
    travel_amount + honorarium_amount + other_amount
  ) STORED;


-- ── 5. Allow internal-member claims ─────────────────────────────────────────
-- The old schema required expert_id NOT NULL because claims were external-
-- only. The new SOP grants internal members ₹1,000 honorarium per meeting,
-- so claim rows must accept a NULL expert_id (member_id alone identifies
-- the recipient; member.expert_id IS NULL is the discriminator).
ALTER TABLE bos_ta_da_claims
  ALTER COLUMN expert_id DROP NOT NULL;


-- ── 6. Column-level documentation ───────────────────────────────────────────
COMMENT ON COLUMN bos_ta_da_claims.honorarium_amount IS
  'Per-meeting honorarium per SOP. ₹1,500 for external members '
  '(expert_id IS NOT NULL), ₹1,000 for internal members (expert_id IS NULL). '
  'Rates centralised in lib/bos/ta-da-rates.ts; recomputed by the attendance '
  'route on every present-status save.';

COMMENT ON COLUMN bos_ta_da_claims.travel_amount IS
  'TA = distance_km × 2 × ₹5 for external members; 0 for internal members. '
  'distance_km is sourced from bos_external_experts via the display_distance_km '
  'snapshot on bos_members at claim-generation time.';

COMMENT ON COLUMN bos_ta_da_claims.honorarium_units IS
  'Legacy column from the DA-days/rate model, kept for backward read '
  'compatibility on historical rows. New auto-generated claims set this to 1.';

COMMENT ON COLUMN bos_ta_da_claims.honorarium_rate IS
  'Legacy column from the DA-days/rate model, kept for backward read '
  'compatibility on historical rows. New auto-generated claims set this to '
  'the honorarium amount (rate × units = amount).';
