-- v_hr_staff gains staff.attendance_mode, APPENDED as the last column.
--
-- CREATE OR REPLACE VIEW can only add columns at the end, and this view backs
-- ~29 files plus the HR inclusion gate (ec.included_in_hr AND o.included_in_hr),
-- so every existing column keeps its name, type and position exactly. The only
-- change is the final line.
CREATE OR REPLACE VIEW public.v_hr_staff AS
 SELECT s.id,
    s.first_name,
    s.last_name,
    s.gender,
    s.date_of_birth,
    s.marital_status,
    s.blood_group,
    s.email,
    s.phone,
    s.staff_id,
    s.profile_picture,
    s.address,
    s.state,
    s.district,
    s.pincode,
    s.date_of_joining,
    s.designation,
    s.category_id,
    s.institution_id,
    s.department_id,
    s.is_active,
    s.created_at,
    s.updated_at,
    s.created_by,
    s.updated_by,
    s.institution_email,
    s.profile_id,
    s.role_type,
    s.facilitator_certification,
    s.outcome_metrics,
    s.role_key,
    s.has_extended_profile,
    s.slug,
    s.status,
    s.display_order,
    s.experience_years,
    s.research_papers,
    s.phd_scholars,
    s.awards_won,
    s.pg_dissertations_guided,
    s.ug_projects_guided,
    s.qualification_summary,
    s.professional_summary,
    s.mentoring_description,
    s.google_scholar_url,
    s.researchgate_url,
    s.orcid_url,
    s.badges,
    s.qualifications,
    s.specialisations,
    s.experience_entries,
    s.research_focus_areas,
    s.publications,
    s.funded_projects,
    s.certifications,
    s.awards,
    s.memberships,
    s.phd_scholars_list,
    s.faqs,
    s.achievements,
    s.login_enabled,
    s.employment_type,
    s.bus_required,
    s.transport_route_id,
    s.transport_stop_id,
    s.tags,
    s.biometric_id,
    s.biometric_institution_id,
    s.attendance_mode
   FROM staff s
     JOIN employment_categories ec ON ec.id = s.category_id
     JOIN hr_organizations o ON o.institution_id = s.institution_id
  WHERE ec.included_in_hr AND o.included_in_hr;
