// ============================================================================
// AICTE Mandatory Disclosure + UGC-AISHE Seed Data
// Source: REGULATORY-FRAMEWORK-ENGINE-SPEC.md
// AICTE: 9 categories (compliance/disclosure — no scoring)
// UGC-AISHE: 9 data sections (reporting — no scoring)
// ============================================================================

import type { FrameworkSeed, CriteriaSeed, MetricSeed } from './naac-binary-2024'

// ── AICTE MANDATORY DISCLOSURE FRAMEWORK ──

export const aicteFramework: FrameworkSeed = {
  code: 'AICTE_MANDATORY_DISCLOSURE_2025',
  name: 'AICTE Mandatory Disclosure 2025',
  body: 'AICTE',
  framework_type: 'compliance',
  institution_type: null,
  version: '2025',
  year_type: 'academic',
  total_max_score: 0, // compliance — no scoring
  description: 'AICTE Mandatory Disclosure for all AICTE-approved institutions (Engineering, Pharmacy, Management). Annual structured data disclosure on institution website + AICTE portal. Primarily a data EXPORT — no scoring or grading.',
  status: 'active',
  submission_portal_url: 'https://www.aicte-india.org',
  metadata: { applicable_to: ['Engineering', 'Pharmacy', 'Management'], output_format: 'HTML + PDF', no_scoring: true },
}

export const aicteCriteria: CriteriaSeed[] = [
  {
    code: 'AICTE-C1',
    name: 'Institution Information',
    description: 'Name, address, approval status, university affiliation, year of establishment, NAAC/NBA accreditation status.',
    weight: 0,
    max_score: 0,
    sort_order: 1,
    is_qualitative: true,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AICTE-C2',
    name: 'Programme Information',
    description: 'Approved intake per programme, courses offered, fee structure, duration, medium of instruction.',
    weight: 0,
    max_score: 0,
    sort_order: 2,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AICTE-C3',
    name: 'Faculty Information',
    description: 'Name, qualification, designation, experience, pay scale, date of joining, photograph of each faculty member.',
    weight: 0,
    max_score: 0,
    sort_order: 3,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AICTE-C4',
    name: 'Student Information',
    description: 'Enrollment data: gender-wise, category-wise (SC/ST/OBC/General), lateral entry, NRI/foreign students.',
    weight: 0,
    max_score: 0,
    sort_order: 4,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AICTE-C5',
    name: 'Infrastructure',
    description: 'Land area, built-up area, classrooms, labs, library, hostel, sports facilities, canteen.',
    weight: 0,
    max_score: 0,
    sort_order: 5,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AICTE-C6',
    name: 'Placement Records',
    description: 'Students placed (company-wise, package details), higher education progression, self-employment data.',
    weight: 0,
    max_score: 0,
    sort_order: 6,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AICTE-C7',
    name: 'Financial Information',
    description: 'Fee collected, salary expenditure, infrastructure expenditure, audited financial statements.',
    weight: 0,
    max_score: 0,
    sort_order: 7,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'AICTE-C8',
    name: 'Governance',
    description: 'Board of Governors composition, Academic Council, Faculty committees, organizational chart.',
    weight: 0,
    max_score: 0,
    sort_order: 8,
    is_qualitative: true,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AICTE-C9',
    name: 'AICTE Compliance',
    description: 'Anti-ragging measures, grievance mechanisms, mandatory committee constitution (ICC, anti-ragging, grievance cell).',
    weight: 0,
    max_score: 0,
    sort_order: 9,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
]

export const aicteMetrics: MetricSeed[] = [
  // ── Category 1: Institution Information ──
  {
    criteria_code: 'AICTE-C1',
    code: 'A1.1',
    name: 'Institution Name & Address',
    description: 'Full legal name, registered address, pin code, state, contact details, website URL.',
    max_marks: 0,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-13',
    sort_order: 1,
    metadata: { disclosure_field: true },
  },
  {
    criteria_code: 'AICTE-C1',
    code: 'A1.2',
    name: 'Approval & Affiliation Status',
    description: 'AICTE approval number, affiliating university, NAAC/NBA status with validity dates.',
    max_marks: 0,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-13',
    sort_order: 2,
    metadata: { disclosure_field: true },
  },
  {
    criteria_code: 'AICTE-C1',
    code: 'A1.3',
    name: 'Year of Establishment & Trust Details',
    description: 'Year of establishment, trust/society/company name, registration details.',
    max_marks: 0,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-13',
    sort_order: 3,
    metadata: { disclosure_field: true },
  },

  // ── Category 2: Programme Information ──
  {
    criteria_code: 'AICTE-C2',
    code: 'A2.1',
    name: 'Programme-wise Intake',
    description: 'Approved intake per programme (UG/PG/Diploma), sanctioned vs actual admission, lateral entry quota.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-05',
    sort_order: 1,
    metadata: { secondary_connectors: ['DC-13'] },
  },
  {
    criteria_code: 'AICTE-C2',
    code: 'A2.2',
    name: 'Fee Structure',
    description: 'Programme-wise fee structure: tuition fees, hostel fees, other charges as approved by fee fixation committee.',
    max_marks: 0,
    data_type: 'currency',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-06',
    sort_order: 2,
    metadata: { feeds: ['billing_student_bills'] },
  },

  // ── Category 3: Faculty Information ──
  {
    criteria_code: 'AICTE-C3',
    code: 'A3.1',
    name: 'Faculty List with Qualifications',
    description: 'Name, designation, qualifications, experience, date of joining, pay scale, photograph for each faculty.',
    max_marks: 0,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-02',
    sort_order: 1,
    metadata: { secondary_connectors: ['DC-16'], note: 'staff table may need pay_scale column for AICTE' },
  },
  {
    criteria_code: 'AICTE-C3',
    code: 'A3.2',
    name: 'Faculty-Student Ratio',
    description: 'Department-wise and programme-wise faculty-student ratio.',
    max_marks: 0,
    data_type: 'ratio',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-02',
    sort_order: 2,
    metadata: { secondary_connectors: ['DC-01'] },
  },

  // ── Category 4: Student Information ──
  {
    criteria_code: 'AICTE-C4',
    code: 'A4.1',
    name: 'Enrollment by Gender & Category',
    description: 'Programme-wise enrollment: male/female breakdown, SC/ST/OBC/General/EWS/PwD distribution.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-01',
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'AICTE-C4',
    code: 'A4.2',
    name: 'NRI & Foreign Students',
    description: 'Number of NRI and foreign students enrolled, country-wise distribution.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-01',
    sort_order: 2,
    metadata: {},
  },

  // ── Category 5: Infrastructure ──
  {
    criteria_code: 'AICTE-C5',
    code: 'A5.1',
    name: 'Land & Building Details',
    description: 'Total land area (acres), built-up area (sq.ft.), floor-wise details of buildings.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-14',
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'AICTE-C5',
    code: 'A5.2',
    name: 'Lab & Equipment Inventory',
    description: 'Department-wise lab list, major equipment, student capacity, utilization records.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-14',
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'AICTE-C5',
    code: 'A5.3',
    name: 'Library & Computing Facilities',
    description: 'Total books, journals, e-resources, computers, internet bandwidth, digital library.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-20',
    sort_order: 3,
    metadata: { secondary_connectors: ['DC-28'] },
  },

  // ── Category 6: Placement Records ──
  {
    criteria_code: 'AICTE-C6',
    code: 'A6.1',
    name: 'Placement Data (Company-wise)',
    description: 'Company name, number placed, package offered (min/max/average), sector-wise distribution.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-04',
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'AICTE-C6',
    code: 'A6.2',
    name: 'Higher Education & Self-Employment',
    description: 'Students progressing to higher education (institution, programme), self-employed/entrepreneur count.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-04',
    sort_order: 2,
    metadata: {},
  },

  // ── Category 7: Financial Information ──
  {
    criteria_code: 'AICTE-C7',
    code: 'A7.1',
    name: 'Revenue & Expenditure Statement',
    description: 'Income (fees, grants, donations) and expenditure (salary, infrastructure, maintenance) for last 3 years.',
    max_marks: 0,
    data_type: 'currency',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-21',
    sort_order: 1,
    metadata: { secondary_connectors: ['DC-06'] },
  },
  {
    criteria_code: 'AICTE-C7',
    code: 'A7.2',
    name: 'Audited Financial Statements',
    description: 'Audited balance sheet and income-expenditure statement, CA-certified, for last 3 financial years.',
    max_marks: 0,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-33',
    sort_order: 2,
    metadata: {},
  },

  // ── Category 8: Governance ──
  {
    criteria_code: 'AICTE-C8',
    code: 'A8.1',
    name: 'Governing Body Composition',
    description: 'Board of Governors: name, designation, affiliation, category (industry/academic/nominee). Meeting frequency and minutes.',
    max_marks: 0,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: false,
    data_connector_code: null,
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'AICTE-C8',
    code: 'A8.2',
    name: 'Organizational Chart',
    description: 'Institutional hierarchy, reporting structure, administrative officers, academic heads.',
    max_marks: 0,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: false,
    data_connector_code: null,
    sort_order: 2,
    metadata: {},
  },

  // ── Category 9: AICTE Compliance ──
  {
    criteria_code: 'AICTE-C9',
    code: 'A9.1',
    name: 'Anti-Ragging Compliance',
    description: 'Anti-ragging committee constitution, affidavit collection, awareness programs, incident tracking.',
    max_marks: 0,
    data_type: 'boolean',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-09',
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'AICTE-C9',
    code: 'A9.2',
    name: 'Grievance & ICC Mechanisms',
    description: 'Grievance redressal cell, Internal Complaints Committee (Prevention of Sexual Harassment), student welfare committee.',
    max_marks: 0,
    data_type: 'boolean',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-09',
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'AICTE-C9',
    code: 'A9.3',
    name: 'Mandatory Committee Constitution',
    description: 'Constitution of mandatory committees: anti-ragging, ICC, grievance cell, SC/ST committee, OBC cell, PwD committee.',
    max_marks: 0,
    data_type: 'boolean',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 3,
    metadata: {},
  },
]

// ── UGC-AISHE FRAMEWORK ──

export const ugcAisheFramework: FrameworkSeed = {
  code: 'UGC_AISHE_2025',
  name: 'UGC-AISHE Data Submission 2025',
  body: 'UGC',
  framework_type: 'reporting',
  institution_type: null,
  version: '2025',
  year_type: 'academic',
  total_max_score: 0, // reporting — no scoring
  description: 'All India Survey on Higher Education (AISHE) — mandatory annual data submission to MHRD for all higher education institutions. Data feeds into NIRF, national policy decisions, and budget allocation. Format: online portal at aishe.gov.in. Typically submitted December-February.',
  status: 'active',
  submission_portal_url: 'https://aishe.gov.in',
  metadata: { mandatory: true, all_institutions: true, output_format: 'CSV portal upload', onod_future_integration: true },
}

export const ugcAisheCriteria: CriteriaSeed[] = [
  {
    code: 'AISHE-S1',
    name: 'Institution Profile',
    description: 'Type, management, year of establishment, affiliating university, NAAC/NBA accreditation status, NIRF rank.',
    weight: 0,
    max_score: 0,
    sort_order: 1,
    is_qualitative: true,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AISHE-S2',
    name: 'Programme-wise Enrollment',
    description: 'Students by programme, year, gender, category (SC/ST/OBC/General), PwD, Muslim minority, state domicile.',
    weight: 0,
    max_score: 0,
    sort_order: 2,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AISHE-S3',
    name: 'Student Intake',
    description: 'Sanctioned intake vs admitted (programme-wise, gender-wise), reservation compliance.',
    weight: 0,
    max_score: 0,
    sort_order: 3,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AISHE-S4',
    name: 'Examination Results',
    description: 'Students appeared vs passed (programme-wise, gender-wise), distinction rate.',
    weight: 0,
    max_score: 0,
    sort_order: 4,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AISHE-S5',
    name: 'Faculty Information',
    description: 'Full-time, part-time, contractual, guest — by gender, category, qualification, designation, department.',
    weight: 0,
    max_score: 0,
    sort_order: 5,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AISHE-S6',
    name: 'Infrastructure',
    description: 'Classrooms, labs, computers, internet bandwidth, library books/journals, hostels, sports facilities.',
    weight: 0,
    max_score: 0,
    sort_order: 6,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AISHE-S7',
    name: 'Financial Information',
    description: 'Receipts (fees, grants, donations) + Expenditure (salary, infrastructure, scholarships) for the year.',
    weight: 0,
    max_score: 0,
    sort_order: 7,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AISHE-S8',
    name: 'Scholarship Data',
    description: 'Students receiving scholarships by type (central/state/institutional), amount, gender, category.',
    weight: 0,
    max_score: 0,
    sort_order: 8,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
  {
    code: 'AISHE-S9',
    name: 'Placement Data',
    description: 'Students placed, median salary, top recruiting companies, campus visit statistics.',
    weight: 0,
    max_score: 0,
    sort_order: 9,
    is_qualitative: false,
    evidence_required: false,
    parent_criteria_code: null,
  },
]

export const ugcAisheMetrics: MetricSeed[] = [
  // ── Section 1: Institution Profile ──
  {
    criteria_code: 'AISHE-S1',
    code: 'AI1.1',
    name: 'Institutional Profile Data',
    description: 'Institution type, management type, year established, affiliating university, accreditation status.',
    max_marks: 0,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-13',
    sort_order: 1,
    metadata: { reporting_only: true },
  },

  // ── Section 2: Programme-wise Enrollment ──
  {
    criteria_code: 'AISHE-S2',
    code: 'AI2.1',
    name: 'Enrollment by Programme & Gender',
    description: 'Total enrollment in each programme disaggregated by gender and year of study.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-01',
    sort_order: 1,
    metadata: { reporting_only: true },
  },
  {
    criteria_code: 'AISHE-S2',
    code: 'AI2.2',
    name: 'Enrollment by Social Category',
    description: 'Enrollment disaggregated by SC/ST/OBC/General/EWS, PwD, Muslim minority, transgender.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-01',
    sort_order: 2,
    metadata: { reporting_only: true },
  },
  {
    criteria_code: 'AISHE-S2',
    code: 'AI2.3',
    name: 'Enrollment by State Domicile',
    description: 'Students enrolled from each state/UT and international students by country.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-01',
    sort_order: 3,
    metadata: { reporting_only: true },
  },

  // ── Section 3: Student Intake ──
  {
    criteria_code: 'AISHE-S3',
    code: 'AI3.1',
    name: 'Sanctioned vs Actual Intake',
    description: 'Programme-wise sanctioned intake, actual admissions, and fill rate. Gender-wise breakdown.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-05',
    sort_order: 1,
    metadata: { reporting_only: true },
  },

  // ── Section 4: Examination Results ──
  {
    criteria_code: 'AISHE-S4',
    code: 'AI4.1',
    name: 'Exam Results by Programme',
    description: 'Students appeared vs passed per programme per year, disaggregated by gender.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-17',
    sort_order: 1,
    metadata: { reporting_only: true },
  },

  // ── Section 5: Faculty Information ──
  {
    criteria_code: 'AISHE-S5',
    code: 'AI5.1',
    name: 'Faculty by Type & Gender',
    description: 'Faculty count: full-time, part-time, contractual, guest. Male/female breakdown. Category-wise.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-02',
    sort_order: 1,
    metadata: { reporting_only: true },
  },
  {
    criteria_code: 'AISHE-S5',
    code: 'AI5.2',
    name: 'Faculty Qualifications Distribution',
    description: 'Faculty by highest qualification: PhD, M.Phil, PG, UG. Department-wise distribution.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-16',
    sort_order: 2,
    metadata: { reporting_only: true },
  },

  // ── Section 6: Infrastructure ──
  {
    criteria_code: 'AISHE-S6',
    code: 'AI6.1',
    name: 'Physical Infrastructure Summary',
    description: 'Classrooms, labs, computers, internet bandwidth, library books, hostel beds, sports area.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-14',
    sort_order: 1,
    metadata: { secondary_connectors: ['DC-20', 'DC-28'], reporting_only: true },
  },

  // ── Section 7: Financial Information ──
  {
    criteria_code: 'AISHE-S7',
    code: 'AI7.1',
    name: 'Revenue & Expenditure Summary',
    description: 'Total receipts (tuition, govt grants, donations, other) and expenditure (salary, infra, scholarships, other).',
    max_marks: 0,
    data_type: 'currency',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-21',
    sort_order: 1,
    metadata: { secondary_connectors: ['DC-06'], reporting_only: true },
  },

  // ── Section 8: Scholarship Data ──
  {
    criteria_code: 'AISHE-S8',
    code: 'AI8.1',
    name: 'Scholarship Distribution',
    description: 'Students receiving scholarships: central govt, state govt, institutional. By type, amount, gender, category.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-09',
    sort_order: 1,
    metadata: { reporting_only: true },
  },

  // ── Section 9: Placement Data ──
  {
    criteria_code: 'AISHE-S9',
    code: 'AI9.1',
    name: 'Placement Summary',
    description: 'Total placed, median salary, number of recruiting companies, campus placement drives conducted.',
    max_marks: 0,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-04',
    sort_order: 1,
    metadata: { reporting_only: true },
  },
]
