// ============================================================================
// NAAC 2022 Revised (Old QIF) Seed Data
// Source: REGULATORY-FRAMEWORK-ENGINE-SPEC.md (NAACManual.txt)
// 7 Criteria, 32 Key Indicators, 56 Metrics (22 QlM + 34 QnM)
// Total Score: 1050 marks
// Grading: Metric → KI GPA → Criterion GPA → Overall CGPA (1.00-4.00) → Grade
// ============================================================================

import type { FrameworkSeed, CriteriaSeed, MetricSeed } from './naac-binary-2024'

// ── FRAMEWORK DEFINITION ──

export const naacOldFramework: FrameworkSeed = {
  code: 'NAAC_2022_REVISED',
  name: 'NAAC SSR 2022 Revised (QIF)',
  body: 'NAAC',
  framework_type: 'accreditation',
  institution_type: null, // universal — institution_type-specific weights can be added later
  version: '2022-rev',
  year_type: 'academic',
  total_max_score: 1050,
  description: 'NAAC Quality Indicator Framework (QIF) for Autonomous Colleges — 2022 Revised. 7 Criteria with 32 Key Indicators and 56 metrics. Being phased out in favor of Binary 2024 framework. DVV (Data Validation & Verification) applies to all QnM metrics.',
  status: 'active',
  submission_portal_url: 'https://assessmentonline.naac.gov.in',
  metadata: {
    grading_scale: 'CGPA 1.00-4.00',
    grades: { 'A++': '3.76-4.00', 'A+': '3.51-3.75', 'A': '3.26-3.50', 'B++': '3.01-3.25', 'B+': '2.76-3.00', 'B': '2.51-2.75', 'C': '1.51-2.50' },
    dvv_applicable: true,
    peer_team_visit: true,
  },
}

// ── CRITERIA (7) with Key Indicators as sub-criteria ──

export const naacOldCriteria: CriteriaSeed[] = [
  // Criterion I
  { code: 'CR-I', name: 'Curricular Aspects', description: 'Curriculum design, academic flexibility, enrichment, and feedback system.', weight: 150, max_score: 150, sort_order: 1, is_qualitative: false, evidence_required: true, parent_criteria_code: null },
  { code: 'KI-1.1', name: 'Curricular Planning & Implementation', description: null, weight: 70, max_score: 70, sort_order: 1, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-I' },
  { code: 'KI-1.2', name: 'Academic Flexibility', description: null, weight: 30, max_score: 30, sort_order: 2, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-I' },
  { code: 'KI-1.3', name: 'Curriculum Enrichment', description: null, weight: 30, max_score: 30, sort_order: 3, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-I' },
  { code: 'KI-1.4', name: 'Feedback System', description: null, weight: 20, max_score: 20, sort_order: 4, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-I' },

  // Criterion II
  { code: 'CR-II', name: 'Teaching-Learning & Evaluation', description: 'Student enrollment, teacher quality, teaching process, evaluation, student performance, and satisfaction.', weight: 350, max_score: 350, sort_order: 2, is_qualitative: false, evidence_required: true, parent_criteria_code: null },
  { code: 'KI-2.1', name: 'Student Enrolment & Profile', description: null, weight: 40, max_score: 40, sort_order: 1, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-II' },
  { code: 'KI-2.2', name: 'Student-Teacher Ratio', description: null, weight: 40, max_score: 40, sort_order: 2, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-II' },
  { code: 'KI-2.3', name: 'Teaching-Learning Process', description: null, weight: 40, max_score: 40, sort_order: 3, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-II' },
  { code: 'KI-2.4', name: 'Teacher Profile & Quality', description: null, weight: 40, max_score: 40, sort_order: 4, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-II' },
  { code: 'KI-2.5', name: 'Evaluation Process & Reforms', description: null, weight: 40, max_score: 40, sort_order: 5, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-II' },
  { code: 'KI-2.6', name: 'Student Performance & Learning Outcomes', description: null, weight: 90, max_score: 90, sort_order: 6, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-II' },
  { code: 'KI-2.7', name: 'Student Satisfaction Survey', description: null, weight: 60, max_score: 60, sort_order: 7, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-II' },

  // Criterion III
  { code: 'CR-III', name: 'Research, Innovations & Extension', description: 'Resource mobilization, innovation ecosystem, publications, extension activities, and collaborations.', weight: 110, max_score: 110, sort_order: 3, is_qualitative: false, evidence_required: true, parent_criteria_code: null },
  { code: 'KI-3.1', name: 'Resource Mobilization for Research', description: null, weight: 10, max_score: 10, sort_order: 1, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-III' },
  { code: 'KI-3.2', name: 'Innovation Ecosystem', description: null, weight: 15, max_score: 15, sort_order: 2, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-III' },
  { code: 'KI-3.3', name: 'Research Publications & Awards', description: null, weight: 25, max_score: 25, sort_order: 3, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-III' },
  { code: 'KI-3.4', name: 'Extension Activities', description: null, weight: 40, max_score: 40, sort_order: 4, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-III' },
  { code: 'KI-3.5', name: 'Collaboration', description: null, weight: 20, max_score: 20, sort_order: 5, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-III' },

  // Criterion IV
  { code: 'CR-IV', name: 'Infrastructure & Learning Resources', description: 'Physical facilities, library, IT infrastructure, campus maintenance.', weight: 100, max_score: 100, sort_order: 4, is_qualitative: false, evidence_required: true, parent_criteria_code: null },
  { code: 'KI-4.1', name: 'Physical Facilities', description: null, weight: 30, max_score: 30, sort_order: 1, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-IV' },
  { code: 'KI-4.2', name: 'Library as a Learning Resource', description: null, weight: 20, max_score: 20, sort_order: 2, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-IV' },
  { code: 'KI-4.3', name: 'IT Infrastructure', description: null, weight: 30, max_score: 30, sort_order: 3, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-IV' },
  { code: 'KI-4.4', name: 'Campus Maintenance', description: null, weight: 20, max_score: 20, sort_order: 4, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-IV' },

  // Criterion V
  { code: 'CR-V', name: 'Student Support & Progression', description: 'Student support, progression, activities, and alumni engagement.', weight: 140, max_score: 140, sort_order: 5, is_qualitative: false, evidence_required: true, parent_criteria_code: null },
  { code: 'KI-5.1', name: 'Student Support', description: null, weight: 50, max_score: 50, sort_order: 1, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-V' },
  { code: 'KI-5.2', name: 'Student Progression', description: null, weight: 35, max_score: 35, sort_order: 2, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-V' },
  { code: 'KI-5.3', name: 'Student Participation & Activities', description: null, weight: 45, max_score: 45, sort_order: 3, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-V' },
  { code: 'KI-5.4', name: 'Alumni Engagement', description: null, weight: 10, max_score: 10, sort_order: 4, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-V' },

  // Criterion VI
  { code: 'CR-VI', name: 'Governance, Leadership & Management', description: 'Vision, strategy, faculty empowerment, financial management, and IQAS.', weight: 100, max_score: 100, sort_order: 6, is_qualitative: false, evidence_required: true, parent_criteria_code: null },
  { code: 'KI-6.1', name: 'Vision & Leadership', description: null, weight: 15, max_score: 15, sort_order: 1, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-VI' },
  { code: 'KI-6.2', name: 'Strategy Development & Deployment', description: null, weight: 12, max_score: 12, sort_order: 2, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-VI' },
  { code: 'KI-6.3', name: 'Faculty Empowerment Strategies', description: null, weight: 33, max_score: 33, sort_order: 3, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-VI' },
  { code: 'KI-6.4', name: 'Financial Management & Resource Mobilization', description: null, weight: 10, max_score: 10, sort_order: 4, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-VI' },
  { code: 'KI-6.5', name: 'Internal Quality Assurance System', description: null, weight: 30, max_score: 30, sort_order: 5, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-VI' },

  // Criterion VII
  { code: 'CR-VII', name: 'Institutional Values & Best Practices', description: 'Values, social responsibility, best practices, and institutional distinctiveness.', weight: 100, max_score: 100, sort_order: 7, is_qualitative: false, evidence_required: true, parent_criteria_code: null },
  { code: 'KI-7.1', name: 'Institutional Values & Social Responsibilities', description: null, weight: 50, max_score: 50, sort_order: 1, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-VII' },
  { code: 'KI-7.2', name: 'Best Practices', description: null, weight: 30, max_score: 30, sort_order: 2, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-VII' },
  { code: 'KI-7.3', name: 'Institutional Distinctiveness', description: null, weight: 20, max_score: 20, sort_order: 3, is_qualitative: false, evidence_required: true, parent_criteria_code: 'CR-VII' },
]

// ── METRICS (56 total: 22 QlM + 34 QnM) ──

export const naacOldMetrics: MetricSeed[] = [
  // ── Criterion I — Curricular Aspects (150 marks, 6 metrics) ──
  {
    criteria_code: 'KI-1.1',
    code: '1.1.1',
    name: 'Curriculum Design & Development',
    description: 'Curriculum design and development process — institution\'s approach to curriculum planning, BoS involvement, stakeholder input, alignment with industry/NEP.',
    max_marks: 70,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 1,
    metadata: { metric_type: 'QlM', ki_code: '1.1', ki_weight: 70 },
  },
  {
    criteria_code: 'KI-1.2',
    code: '1.2.1',
    name: 'Add-on/Certificate/Value-Added/MOOC Programs',
    description: 'Number of Add-on/Certificate/Value-added programs and MOOC courses offered during the last 5 years.',
    max_marks: 15,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-12',
    sort_order: 2,
    metadata: { metric_type: 'QnM', ki_code: '1.2', ki_weight: 30, secondary_connectors: ['DC-29'], period: '5_years' },
  },
  {
    criteria_code: 'KI-1.2',
    code: '1.2.2',
    name: 'Students in Certificate/Add-on/MOOC Programs (%)',
    description: 'Percentage of students enrolled in Certificate/Add-on/MOOC programs during the last 5 years.',
    max_marks: 15,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-12',
    sort_order: 3,
    metadata: { metric_type: 'QnM', ki_code: '1.2', ki_weight: 30, secondary_connectors: ['DC-29'], period: '5_years' },
  },
  {
    criteria_code: 'KI-1.3',
    code: '1.3.1',
    name: 'Cross-cutting Issues in Curriculum',
    description: 'Integration of crosscutting issues relevant to Ethics, Gender, Human Values, Environment and Sustainability into the curriculum.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 4,
    metadata: { metric_type: 'QlM', ki_code: '1.3', ki_weight: 30 },
  },
  {
    criteria_code: 'KI-1.3',
    code: '1.3.2',
    name: 'Students in Project Work/Field Work/Internships (%)',
    description: 'Percentage of students undertaking project work/field work/internships.',
    max_marks: 10,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-01',
    sort_order: 5,
    metadata: { metric_type: 'QnM', ki_code: '1.3', ki_weight: 30, secondary_connectors: ['DC-08'] },
  },
  {
    criteria_code: 'KI-1.4',
    code: '1.4.1',
    name: 'Stakeholder Feedback System',
    description: 'Structured feedback from stakeholders: (A) Feedback collected, analysed, action taken, and feedback on action (B-E scale descending).',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-10',
    sort_order: 6,
    metadata: { metric_type: 'QnM', ki_code: '1.4', ki_weight: 20, scale: 'A-E', feeds: ['nps_surveys', 'nps_responses'] },
  },

  // ── Criterion II — Teaching-Learning & Evaluation (350 marks, 11 metrics) ──
  {
    criteria_code: 'KI-2.1',
    code: '2.1.1',
    name: 'Enrolment Percentage',
    description: 'Enrolment percentage: students admitted against sanctioned seats (average of last 5 years).',
    max_marks: 20,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-01',
    sort_order: 1,
    metadata: { metric_type: 'QnM', ki_code: '2.1', ki_weight: 40, secondary_connectors: ['DC-05'], period: '5_years' },
  },
  {
    criteria_code: 'KI-2.1',
    code: '2.1.2',
    name: 'Reserved Category Seats Filled (%)',
    description: 'Percentage of seats filled against reserved categories (SC/ST/OBC) as per government norms (average of last 5 years).',
    max_marks: 20,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-01',
    sort_order: 2,
    metadata: { metric_type: 'QnM', ki_code: '2.1', ki_weight: 40, secondary_connectors: ['DC-05'], period: '5_years' },
  },
  {
    criteria_code: 'KI-2.2',
    code: '2.2.1',
    name: 'Student-Teacher Ratio',
    description: 'Student : Full-time teacher ratio for the latest completed academic year.',
    max_marks: 40,
    data_type: 'ratio',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-02',
    sort_order: 3,
    metadata: { metric_type: 'QnM', ki_code: '2.2', ki_weight: 40, secondary_connectors: ['DC-01'], formula: 'student_count / faculty_count' },
  },
  {
    criteria_code: 'KI-2.3',
    code: '2.3.1',
    name: 'Student-Centric Teaching Methods',
    description: 'Student centric methods such as experiential learning, participative learning, problem solving methodologies, ICT-enabled learning.',
    max_marks: 40,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 4,
    metadata: { metric_type: 'QlM', ki_code: '2.3', ki_weight: 40 },
  },
  {
    criteria_code: 'KI-2.4',
    code: '2.4.1',
    name: 'Full-time Teachers vs Sanctioned Posts (%)',
    description: 'Percentage of full-time teachers against sanctioned posts (average of last 5 years).',
    max_marks: 20,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-02',
    sort_order: 5,
    metadata: { metric_type: 'QnM', ki_code: '2.4', ki_weight: 40, period: '5_years' },
  },
  {
    criteria_code: 'KI-2.4',
    code: '2.4.2',
    name: 'Teachers with NET/SET/PhD (%)',
    description: 'Percentage of full-time teachers with NET/SET/SLET/PhD/D.Sc./D.Litt. (average of last 5 years).',
    max_marks: 20,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-16',
    sort_order: 6,
    metadata: { metric_type: 'QnM', ki_code: '2.4', ki_weight: 40, period: '5_years', new_table_required: 'staff_qualifications' },
  },
  {
    criteria_code: 'KI-2.5',
    code: '2.5.1',
    name: 'Evaluation Process & Reforms',
    description: 'Mechanism of internal/external assessment — transparent, robust, and outcome-aligned. Includes grievance redressal for examinations.',
    max_marks: 40,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 7,
    metadata: { metric_type: 'QlM', ki_code: '2.5', ki_weight: 40 },
  },
  {
    criteria_code: 'KI-2.6',
    code: '2.6.1',
    name: 'Programme Outcomes & Course Outcomes',
    description: 'Programme Outcomes (POs) and Course Outcomes (COs) stated, displayed, and communicated to stakeholders. Evaluation aligned with outcomes.',
    max_marks: 25,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 8,
    metadata: { metric_type: 'QlM', ki_code: '2.6', ki_weight: 90 },
  },
  {
    criteria_code: 'KI-2.6',
    code: '2.6.2',
    name: 'PO/CO Attainment with Evidence',
    description: 'Attainment of Programme Outcomes and Course Outcomes evaluated by institution with verifiable evidence and action taken on gaps.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 9,
    metadata: { metric_type: 'QlM', ki_code: '2.6', ki_weight: 90 },
  },
  {
    criteria_code: 'KI-2.6',
    code: '2.6.3',
    name: 'Pass Percentage (5-year)',
    description: 'Pass percentage of students (programme-wise, 5-year data). DVV-critical metric.',
    max_marks: 45,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-17',
    sort_order: 10,
    metadata: { metric_type: 'QnM', ki_code: '2.6', ki_weight: 90, period: '5_years', new_table_required: 'exam_results', dvv_critical: true },
  },
  {
    criteria_code: 'KI-2.7',
    code: '2.7.1',
    name: 'Student Satisfaction Survey',
    description: 'Online student satisfaction survey conducted by NAAC. Not institution-generated — NAAC conducts independently.',
    max_marks: 60,
    data_type: 'number',
    is_auto_calculable: false,
    requires_evidence: false,
    data_connector_code: null,
    sort_order: 11,
    metadata: { metric_type: 'QnM', ki_code: '2.7', ki_weight: 60, external_survey: true, conducted_by: 'NAAC', partial_data: 'DC-10 (nps_surveys)' },
  },

  // ── Criterion III — Research, Innovations & Extension (110 marks, 9 metrics) ──
  {
    criteria_code: 'KI-3.1',
    code: '3.1.1',
    name: 'Research Grants (INR Lakhs)',
    description: 'Grants received from government and non-government agencies for research projects during the last 5 years (in INR Lakhs).',
    max_marks: 10,
    data_type: 'currency',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-18',
    sort_order: 1,
    metadata: { metric_type: 'QnM', ki_code: '3.1', ki_weight: 10, period: '5_years', new_table_required: 'research_projects', unit: 'INR Lakhs' },
  },
  {
    criteria_code: 'KI-3.2',
    code: '3.2.1',
    name: 'Innovation Ecosystem',
    description: 'Institution has created an ecosystem for innovations — incubation centres, knowledge transfer, patents, technology transfer, industry partnerships.',
    max_marks: 10,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: 'DC-19',
    sort_order: 2,
    metadata: { metric_type: 'QlM', ki_code: '3.2', ki_weight: 15, partial_auto: true },
  },
  {
    criteria_code: 'KI-3.2',
    code: '3.2.2',
    name: 'Research Methodology Workshops',
    description: 'Number of workshops/seminars on Research Methodology, IPR, and Entrepreneurship conducted during last 5 years.',
    max_marks: 5,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-02',
    sort_order: 3,
    metadata: { metric_type: 'QnM', ki_code: '3.2', ki_weight: 15, period: '5_years', feeds: ['facilitator_development'] },
  },
  {
    criteria_code: 'KI-3.3',
    code: '3.3.1',
    name: 'Research Papers per Teacher (UGC CARE)',
    description: 'Number of research papers per teacher published in UGC CARE-listed journals during last 5 years.',
    max_marks: 10,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-03',
    sort_order: 4,
    metadata: { metric_type: 'QnM', ki_code: '3.3', ki_weight: 25, period: '5_years', formula: 'ugc_papers / faculty_count' },
  },
  {
    criteria_code: 'KI-3.3',
    code: '3.3.2',
    name: 'Books & Chapters Published per Teacher',
    description: 'Number of books and chapters in edited volumes/books published per teacher during last 5 years.',
    max_marks: 15,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-03',
    sort_order: 5,
    metadata: { metric_type: 'QnM', ki_code: '3.3', ki_weight: 25, period: '5_years' },
  },
  {
    criteria_code: 'KI-3.4',
    code: '3.4.1',
    name: 'Extension Activities for Community',
    description: 'Extension activities in the neighbourhood community for holistic development of students and contributing to good citizenship.',
    max_marks: 15,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 6,
    metadata: { metric_type: 'QlM', ki_code: '3.4', ki_weight: 40 },
  },
  {
    criteria_code: 'KI-3.4',
    code: '3.4.2',
    name: 'Awards for Extension Activities',
    description: 'Awards and recognitions received for extension activities from government or recognised bodies.',
    max_marks: 5,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 7,
    metadata: { metric_type: 'QlM', ki_code: '3.4', ki_weight: 40 },
  },
  {
    criteria_code: 'KI-3.4',
    code: '3.4.3',
    name: 'Extension/Outreach Programs (5-year)',
    description: 'Number of extension and outreach programs conducted through NSS/NCC/Red Cross/industry collaboration/NGO collaboration in last 5 years.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-25',
    sort_order: 8,
    metadata: { metric_type: 'QnM', ki_code: '3.4', ki_weight: 40, period: '5_years', secondary_connectors: ['DC-22'] },
  },
  {
    criteria_code: 'KI-3.5',
    code: '3.5.1',
    name: 'MoUs/Collaborations (5-year)',
    description: 'Number of functional MoUs/collaborations with institutions of national/international importance, other universities, industry, corporate houses for exchange, internship, research, and training in last 5 years.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-08',
    sort_order: 9,
    metadata: { metric_type: 'QnM', ki_code: '3.5', ki_weight: 20, period: '5_years', secondary_connectors: ['DC-36'] },
  },

  // ── Criterion IV — Infrastructure & Learning Resources (100 marks, 6 metrics) ──
  {
    criteria_code: 'KI-4.1',
    code: '4.1.1',
    name: 'Physical Facilities Adequacy',
    description: 'Adequacy of physical facilities (classrooms, labs, ICT facilities, cultural and sports) and optimum utilization.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-14',
    sort_order: 1,
    metadata: { metric_type: 'QlM', ki_code: '4.1', ki_weight: 30, partial_auto: true },
  },
  {
    criteria_code: 'KI-4.1',
    code: '4.1.2',
    name: 'Infrastructure Augmentation Expenditure (%)',
    description: 'Percentage of expenditure for infrastructure augmentation excluding salary component during the last 5 years.',
    max_marks: 10,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-21',
    sort_order: 2,
    metadata: { metric_type: 'QnM', ki_code: '4.1', ki_weight: 30, period: '5_years', new_table_required: 'institutional_budgets' },
  },
  {
    criteria_code: 'KI-4.2',
    code: '4.2.1',
    name: 'Library as Learning Resource',
    description: 'Library automation (ILMS), subscription to e-resources (e-journals, databases), OER, and annual book/journal purchases.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-20',
    sort_order: 3,
    metadata: { metric_type: 'QlM', ki_code: '4.2', ki_weight: 20, partial_auto: true },
  },
  {
    criteria_code: 'KI-4.3',
    code: '4.3.1',
    name: 'IT Infrastructure & Facilities',
    description: 'Institution has IT facilities including Wi-Fi, internet bandwidth, CCTV, ERP, with frequent updates.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-28',
    sort_order: 4,
    metadata: { metric_type: 'QlM', ki_code: '4.3', ki_weight: 30, partial_auto: true },
  },
  {
    criteria_code: 'KI-4.3',
    code: '4.3.2',
    name: 'Student-Computer Ratio',
    description: 'Student : Computer ratio for the latest completed academic year.',
    max_marks: 10,
    data_type: 'ratio',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-28',
    sort_order: 5,
    metadata: { metric_type: 'QnM', ki_code: '4.3', ki_weight: 30, new_table_required: 'ict_infrastructure' },
  },
  {
    criteria_code: 'KI-4.4',
    code: '4.4.1',
    name: 'Maintenance Expenditure (%)',
    description: 'Percentage of expenditure on infrastructure maintenance excluding salary component during the last 5 years.',
    max_marks: 20,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-21',
    sort_order: 6,
    metadata: { metric_type: 'QnM', ki_code: '4.4', ki_weight: 20, period: '5_years', new_table_required: 'institutional_budgets' },
  },

  // ── Criterion V — Student Support & Progression (140 marks, 9 metrics) ──
  {
    criteria_code: 'KI-5.1',
    code: '5.1.1',
    name: 'Scholarships/Freeships (%)',
    description: 'Percentage of students benefitted by government and non-government scholarships/freeships during the last 5 years.',
    max_marks: 20,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-09',
    sort_order: 1,
    metadata: { metric_type: 'QnM', ki_code: '5.1', ki_weight: 50, period: '5_years' },
  },
  {
    criteria_code: 'KI-5.1',
    code: '5.1.2',
    name: 'Capacity Building Programs',
    description: 'Institution has facilities and activities for capacity building: soft skills, language and communication, life skills, ICT/computing, yoga/physical fitness.',
    max_marks: 10,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-12',
    sort_order: 2,
    metadata: { metric_type: 'QnM', ki_code: '5.1', ki_weight: 50, scale: 'A-E' },
  },
  {
    criteria_code: 'KI-5.1',
    code: '5.1.3',
    name: 'Competitive Exam Guidance (%)',
    description: 'Percentage of students benefitted by career counseling and competitive exam guidance during the last 5 years.',
    max_marks: 10,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-25',
    sort_order: 3,
    metadata: { metric_type: 'QnM', ki_code: '5.1', ki_weight: 50, new_table_required: 'career_services' },
  },
  {
    criteria_code: 'KI-5.1',
    code: '5.1.4',
    name: 'Grievance Redressal Mechanisms',
    description: 'Grievance redressal mechanisms: sexual harassment and ragging cases mechanisms (A-E scale based on implementation level).',
    max_marks: 10,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-09',
    sort_order: 4,
    metadata: { metric_type: 'QnM', ki_code: '5.1', ki_weight: 50, scale: 'A-E' },
  },
  {
    criteria_code: 'KI-5.2',
    code: '5.2.1',
    name: 'Placement & Higher Education (%)',
    description: 'Percentage of outgoing students placed or progressing to higher education during the last 5 years.',
    max_marks: 25,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-04',
    sort_order: 5,
    metadata: { metric_type: 'QnM', ki_code: '5.2', ki_weight: 35, period: '5_years' },
  },
  {
    criteria_code: 'KI-5.2',
    code: '5.2.2',
    name: 'Qualifying Exam Pass Rate (%)',
    description: 'Percentage of students qualifying in JAM/CLAT/GATE/GMAT/CAT/GRE/TOEFL/Civil Services/state eligibility tests during the last 5 years.',
    max_marks: 10,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-17',
    sort_order: 6,
    metadata: { metric_type: 'QnM', ki_code: '5.2', ki_weight: 35, period: '5_years', new_table_required: 'exam_results' },
  },
  {
    criteria_code: 'KI-5.3',
    code: '5.3.1',
    name: 'Awards in Sports/Cultural',
    description: 'Number of awards/medals for outstanding performance in sports/cultural activities at university/state/national/international levels during the last 5 years.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-25',
    sort_order: 7,
    metadata: { metric_type: 'QnM', ki_code: '5.3', ki_weight: 45, period: '5_years', secondary_connectors: ['DC-23'] },
  },
  {
    criteria_code: 'KI-5.3',
    code: '5.3.2',
    name: 'Sports/Cultural Programs (5-year avg)',
    description: 'Average number of sports and cultural programs/competitions organized during the last 5 years with student participation.',
    max_marks: 25,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-25',
    sort_order: 8,
    metadata: { metric_type: 'QnM', ki_code: '5.3', ki_weight: 45, period: '5_years' },
  },
  {
    criteria_code: 'KI-5.4',
    code: '5.4.1',
    name: 'Alumni Association Contributions',
    description: 'Registered Alumni Association and its contributions — financial support, mentoring, placement assistance, institutional development.',
    max_marks: 10,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: 'DC-04',
    sort_order: 9,
    metadata: { metric_type: 'QlM', ki_code: '5.4', ki_weight: 10, partial_auto: true },
  },

  // ── Criterion VI — Governance, Leadership & Management (100 marks, 9 metrics) ──
  {
    criteria_code: 'KI-6.1',
    code: '6.1.1',
    name: 'Vision-Mission Aligned Governance',
    description: 'Governance aligned with institutional vision/mission with effective decentralization and participative management.',
    max_marks: 15,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: 'DC-10',
    sort_order: 1,
    metadata: { metric_type: 'QlM', ki_code: '6.1', ki_weight: 15, partial_auto: true, feeds: ['okr_objectives'] },
  },
  {
    criteria_code: 'KI-6.2',
    code: '6.2.1',
    name: 'Strategic/Perspective Plan',
    description: 'Effective functioning of institutional bodies (Governing Body, Academic Council, BoS) and implementation of strategic/perspective plan.',
    max_marks: 8,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 2,
    metadata: { metric_type: 'QlM', ki_code: '6.2', ki_weight: 12 },
  },
  {
    criteria_code: 'KI-6.2',
    code: '6.2.2',
    name: 'e-Governance Implementation',
    description: 'e-Governance areas: (A) Administration, Finance, Student Admission, Examination (A-E scale).',
    max_marks: 4,
    data_type: 'number',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 3,
    metadata: { metric_type: 'QnM', ki_code: '6.2', ki_weight: 12, scale: 'A-E', myjkkn_is_evidence: true },
  },
  {
    criteria_code: 'KI-6.3',
    code: '6.3.1',
    name: 'Faculty Welfare Measures',
    description: 'Welfare measures for teaching and non-teaching staff, and performance appraisal system.',
    max_marks: 6,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: 'DC-02',
    sort_order: 4,
    metadata: { metric_type: 'QlM', ki_code: '6.3', ki_weight: 33, partial_auto: true },
  },
  {
    criteria_code: 'KI-6.3',
    code: '6.3.2',
    name: 'Financial Support for Conferences (%)',
    description: 'Percentage of teachers provided with financial support for conferences, professional memberships, and development programs.',
    max_marks: 12,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-02',
    sort_order: 5,
    metadata: { metric_type: 'QnM', ki_code: '6.3', ki_weight: 33, feeds: ['facilitator_development'] },
  },
  {
    criteria_code: 'KI-6.3',
    code: '6.3.3',
    name: 'Staff in FDPs/Professional Development (%)',
    description: 'Percentage of teaching and non-teaching staff participating in FDPs, admin training, and professional development programs during the last 5 years.',
    max_marks: 15,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-02',
    sort_order: 6,
    metadata: { metric_type: 'QnM', ki_code: '6.3', ki_weight: 33, period: '5_years', feeds: ['facilitator_development'] },
  },
  {
    criteria_code: 'KI-6.4',
    code: '6.4.1',
    name: 'Resource Mobilization & Financial Audits',
    description: 'Institutional strategies for resource mobilization, and regular financial audits (internal and external).',
    max_marks: 10,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-33',
    sort_order: 7,
    metadata: { metric_type: 'QlM', ki_code: '6.4', ki_weight: 10, partial_auto: true },
  },
  {
    criteria_code: 'KI-6.5',
    code: '6.5.1',
    name: 'IQAC Quality Strategies',
    description: 'IQAC contribution to institutionalizing quality assurance strategies, academic reviews, and incremental improvements.',
    max_marks: 15,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: 'DC-24',
    sort_order: 8,
    metadata: { metric_type: 'QlM', ki_code: '6.5', ki_weight: 30, partial_auto: true },
  },
  {
    criteria_code: 'KI-6.5',
    code: '6.5.2',
    name: 'Quality Initiatives',
    description: 'Quality initiatives: IQAC meetings conducted, NIRF participation, NBA/other accreditation obtained, collaborative quality initiatives.',
    max_marks: 15,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-24',
    sort_order: 9,
    metadata: { metric_type: 'QnM', ki_code: '6.5', ki_weight: 30, new_table_required: 'iqac_meetings' },
  },

  // ── Criterion VII — Institutional Values & Best Practices (100 marks, 6 metrics) ──
  {
    criteria_code: 'KI-7.1',
    code: '7.1.1',
    name: 'Gender Equity & Values',
    description: 'Measures for gender equity promotion, celebrations of national and international commemorative days, and other sensitization programs.',
    max_marks: 10,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 1,
    metadata: { metric_type: 'QlM', ki_code: '7.1', ki_weight: 50 },
  },
  {
    criteria_code: 'KI-7.1',
    code: '7.1.2',
    name: 'Environmental Consciousness',
    description: 'Environmental consciousness: alternate energy, waste management, water harvesting/conservation, green campus, disabled-friendly (A-E scale).',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-32',
    sort_order: 2,
    metadata: { metric_type: 'QnM', ki_code: '7.1', ki_weight: 50, scale: 'A-E' },
  },
  {
    criteria_code: 'KI-7.1',
    code: '7.1.3',
    name: 'Quality Audits',
    description: 'Quality audits on environment/energy — green audit, energy audit, clean audit, environment audit (A-E scale).',
    max_marks: 10,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-32',
    sort_order: 3,
    metadata: { metric_type: 'QnM', ki_code: '7.1', ki_weight: 50, scale: 'A-E' },
  },
  {
    criteria_code: 'KI-7.1',
    code: '7.1.4',
    name: 'Inclusivity & Constitutional Values',
    description: 'Inclusivity, tolerance, harmony, and promotion of constitutional obligations, human values, and professional ethics.',
    max_marks: 10,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 4,
    metadata: { metric_type: 'QlM', ki_code: '7.1', ki_weight: 50 },
  },
  {
    criteria_code: 'KI-7.2',
    code: '7.2.1',
    name: 'Two Best Practices',
    description: 'Two best practices described in NAAC prescribed format (7-section structure: Title, Objectives, Context, Practice, Evidence, Problems, Resources).',
    max_marks: 30,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 5,
    metadata: { metric_type: 'QlM', ki_code: '7.2', ki_weight: 30 },
  },
  {
    criteria_code: 'KI-7.3',
    code: '7.3.1',
    name: 'Institutional Distinctiveness',
    description: 'Distinctive performance in ONE priority area chosen by the institution (limit 1000 words). Showcases unique contribution to higher education.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 6,
    metadata: { metric_type: 'QlM', ki_code: '7.3', ki_weight: 20 },
  },
]
