// ============================================================================
// NBA SAR (Self-Assessment Report) Seed Data — Engineering Programs
// Source: REGULATORY-FRAMEWORK-ENGINE-SPEC.md (NBA Accreditation Manual, Tier-I)
// 1 framework (Engineering) + Pharmacy placeholder
// 10 Criteria, PO1-PO12 Programme Outcomes
// Total Score: 1000
// ============================================================================

import type { FrameworkSeed, CriteriaSeed, MetricSeed } from './naac-binary-2024'

// ── FRAMEWORK DEFINITIONS ──

export const nbaSarEngineeringFramework: FrameworkSeed = {
  code: 'NBA_SAR_ENGINEERING',
  name: 'NBA SAR Engineering (Tier-I, Washington Accord)',
  body: 'NBA',
  framework_type: 'accreditation',
  institution_type: null,
  version: '2025',
  year_type: 'academic',
  total_max_score: 1000,
  description: 'NBA Self-Assessment Report for Engineering programs (Tier-I, Washington Accord aligned). Program-level accreditation (not institution-level). Cycle: every 3 years per program (B.Tech/M.Tech). Evaluates individual programs at JKKN College of Engineering & Technology.',
  status: 'active',
  submission_portal_url: 'https://www.nbaind.org',
  metadata: { program_type: 'B.Tech', tier: 'Tier-I', accord: 'Washington Accord', cycle_years: 3 },
}

export const nbaSarPharmacyFramework: FrameworkSeed = {
  code: 'NBA_SAR_PHARMACY',
  name: 'NBA SAR Pharmacy (PCI Aligned)',
  body: 'NBA',
  framework_type: 'accreditation',
  institution_type: null,
  version: '2025',
  year_type: 'academic',
  total_max_score: 1000,
  description: 'NBA Self-Assessment Report for Pharmacy programs. Same 10 criteria as Engineering but with Pharmacy-specific Programme Outcomes (PhO1-PhO12) defined by Pharmacy Council of India (PCI). Exact PhO definitions pending verification.',
  status: 'active',
  submission_portal_url: 'https://www.nbaind.org',
  metadata: { program_type: 'B.Pharm', tier: 'Tier-I', council: 'Pharmacy Council of India', pho_definitions_pending: true },
}

export const nbaFrameworks: FrameworkSeed[] = [nbaSarEngineeringFramework, nbaSarPharmacyFramework]

// ── CRITERIA (10 for Engineering) ──

export const nbaSarCriteria: CriteriaSeed[] = [
  {
    code: 'NBA-C1',
    name: 'Vision, Mission & Programme Educational Objectives (PEOs)',
    description: 'Alignment of programme with institution vision/mission. PEOs defined with stakeholder input, published, and periodically reviewed. Mapping of PEOs to mission statements.',
    weight: 60,
    max_score: 60,
    sort_order: 1,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C2',
    name: 'Programme Curriculum & Teaching-Learning Processes',
    description: 'Curriculum design aligned with POs and PEOs. Teaching-learning processes, course delivery, assessment methods, and use of ICT. Includes curriculum revision frequency and industry relevance.',
    weight: 120,
    max_score: 120,
    sort_order: 2,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C3',
    name: 'Course Outcomes & Programme Outcomes',
    description: 'CO-PO mapping, attainment measurement methodology, direct and indirect assessment tools, continuous improvement based on attainment gaps. Core of OBE assessment.',
    weight: 150,
    max_score: 150,
    sort_order: 3,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C4',
    name: "Students' Performance",
    description: 'Academic performance analysis, success rates, university exam results, student progression, placement and higher education statistics.',
    weight: 120,
    max_score: 120,
    sort_order: 4,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C5',
    name: 'Faculty Information & Contributions',
    description: 'Faculty qualifications, experience, publications, funded projects, FDP participation, student-faculty ratio, faculty retention and development.',
    weight: 100,
    max_score: 100,
    sort_order: 5,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C6',
    name: 'Facilities & Technical Support',
    description: 'Laboratories, equipment, computing facilities, library resources, classrooms, technical staff support. Adequacy and utilization of infrastructure.',
    weight: 80,
    max_score: 80,
    sort_order: 6,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C7',
    name: 'Continuous Improvement',
    description: 'Processes for continuous quality improvement: action on feedback, attainment gap analysis, curriculum revision, outcome-based improvements, benchmarking.',
    weight: 100,
    max_score: 100,
    sort_order: 7,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C8',
    name: 'First Year Academics',
    description: 'First year academic performance, bridge courses, mentoring, student induction program, remedial classes, transition support from school to engineering.',
    weight: 70,
    max_score: 70,
    sort_order: 8,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C9',
    name: 'Student Support Systems',
    description: 'Scholarships, mentoring, career guidance, counselling, placement cell, entrepreneurship support, grievance redressal, alumni interaction.',
    weight: 80,
    max_score: 80,
    sort_order: 9,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
  {
    code: 'NBA-C10',
    name: 'Governance, Institutional Support & Financial Resources',
    description: 'Governance structure, budget allocation to program, industry advisory board, financial sustainability, institutional support for program development.',
    weight: 120,
    max_score: 120,
    sort_order: 10,
    is_qualitative: false,
    evidence_required: true,
    parent_criteria_code: null,
  },
]

// ── METRICS ──
// Includes criterion-specific metrics + PO1-PO12 under Criterion 3

export const nbaSarMetrics: MetricSeed[] = [
  // ── Criterion 1: Vision, Mission & PEOs (60 marks) ──
  {
    criteria_code: 'NBA-C1',
    code: 'C1.1',
    name: 'Vision-Mission Statement Clarity',
    description: 'Institution and department vision/mission statements are clearly defined, published, and communicated to stakeholders.',
    max_marks: 15,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C1',
    code: 'C1.2',
    name: 'PEO Definition & Stakeholder Alignment',
    description: 'Programme Educational Objectives defined with stakeholder participation (industry, alumni, parents, academic community) and mapped to institution mission.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: 'DC-10',
    sort_order: 2,
    metadata: { feeds: ['okr_objectives'] },
  },
  {
    criteria_code: 'NBA-C1',
    code: 'C1.3',
    name: 'PEO Review & Revision Process',
    description: 'Periodic review of PEOs with documented revision history, stakeholder feedback integration, and evidence of continuous alignment.',
    max_marks: 15,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 3,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C1',
    code: 'C1.4',
    name: 'PEO-Mission Mapping',
    description: 'Documented mapping matrix showing PEOs aligned to institution/department mission with justification.',
    max_marks: 10,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 4,
    metadata: {},
  },

  // ── Criterion 2: Programme Curriculum & Teaching-Learning (120 marks) ──
  {
    criteria_code: 'NBA-C2',
    code: 'C2.1',
    name: 'Curriculum Structure & Credit Distribution',
    description: 'Curriculum structure showing credit distribution across theory, practical, project, and elective courses. Compliance with regulation credits.',
    max_marks: 30,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-07',
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C2',
    code: 'C2.2',
    name: 'Course Delivery & Pedagogical Methods',
    description: 'Teaching-learning methods employed: lectures, tutorials, labs, projects, industry visits, guest lectures, flipped classroom, case studies.',
    max_marks: 30,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C2',
    code: 'C2.3',
    name: 'CO-Curriculum Mapping',
    description: 'Every course has defined Course Outcomes with mapping to Programme Outcomes via competency matrix.',
    max_marks: 30,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 3,
    metadata: { feeds: ['competency_catalog', 'course_competency_mapping'] },
  },
  {
    criteria_code: 'NBA-C2',
    code: 'C2.4',
    name: 'Curriculum Revision & Industry Relevance',
    description: 'Frequency of curriculum revision, BoS meetings, industry advisory board input, alignment with emerging technologies and industry needs.',
    max_marks: 30,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-27',
    sort_order: 4,
    metadata: { secondary_connectors: ['DC-08'] },
  },

  // ── Criterion 3: Course Outcomes & Programme Outcomes (150 marks) ──
  // This is the core OBE criterion. Includes PO1-PO12 as individual metrics.
  {
    criteria_code: 'NBA-C3',
    code: 'C3.1',
    name: 'CO Attainment Methodology',
    description: 'Methodology for measuring Course Outcome attainment: direct assessment (exams, assignments, labs) and indirect assessment (surveys, exit interviews).',
    max_marks: 30,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 1,
    metadata: { feeds: ['learner_competencies'] },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'C3.2',
    name: 'PO Attainment Summary',
    description: 'Overall Programme Outcome attainment levels computed from CO-PO mapping and individual CO attainments. Target: 60%+ attainment across all POs.',
    max_marks: 30,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 2,
    metadata: { target_attainment_pct: 60 },
  },

  // PO1 through PO12 (Washington Accord Programme Outcomes)
  {
    criteria_code: 'NBA-C3',
    code: 'PO1',
    name: 'Engineering Knowledge',
    description: 'Apply the knowledge of mathematics, science, engineering fundamentals, and an engineering specialization to the solution of complex engineering problems.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 3,
    metadata: { po_type: 'washington_accord', measured_via: 'CO attainment in core courses' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO2',
    name: 'Problem Analysis',
    description: 'Identify, formulate, review research literature, and analyze complex engineering problems reaching substantiated conclusions using first principles of mathematics, natural sciences, and engineering sciences.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 4,
    metadata: { po_type: 'washington_accord', measured_via: 'CO attainment + project evaluations' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO3',
    name: 'Design/Development of Solutions',
    description: 'Design solutions for complex engineering problems and design system components or processes that meet the specified needs with appropriate consideration for public health and safety, and cultural, societal, and environmental considerations.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 5,
    metadata: { po_type: 'washington_accord', measured_via: 'Capstone projects, design courses' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO4',
    name: 'Conduct Investigations of Complex Problems',
    description: 'Use research-based knowledge and research methods including design of experiments, analysis and interpretation of data, and synthesis of the information to provide valid conclusions.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 6,
    metadata: { po_type: 'washington_accord', measured_via: 'Lab courses, research projects' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO5',
    name: 'Modern Tool Usage',
    description: 'Create, select, and apply appropriate techniques, resources, and modern engineering and IT tools including prediction and modeling to complex engineering activities with an understanding of the limitations.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 7,
    metadata: { po_type: 'washington_accord', measured_via: 'Software/simulation lab performance' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO6',
    name: 'The Engineer and Society',
    description: 'Apply reasoning informed by the contextual knowledge to assess societal, health, safety, legal, and cultural issues and the consequent responsibilities relevant to the professional engineering practice.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 8,
    metadata: { po_type: 'washington_accord', measured_via: 'Humanities/ethics course COs' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO7',
    name: 'Environment and Sustainability',
    description: 'Understand the impact of the professional engineering solutions in societal and environmental contexts, and demonstrate the knowledge of, and need for sustainable development.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 9,
    metadata: { po_type: 'washington_accord', measured_via: 'Environmental engineering COs' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO8',
    name: 'Ethics',
    description: 'Apply ethical principles and commit to professional ethics and responsibilities and norms of the engineering practice.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 10,
    metadata: { po_type: 'washington_accord', measured_via: 'Professional ethics course + activity' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO9',
    name: 'Individual and Team Work',
    description: 'Function effectively as an individual, and as a member or leader in diverse teams, and in multidisciplinary settings.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 11,
    metadata: { po_type: 'washington_accord', measured_via: 'Project courses, team assignments' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO10',
    name: 'Communication',
    description: 'Communicate effectively on complex engineering activities with the engineering community and with society at large, such as being able to comprehend and write effective reports and design documentation, make effective presentations, and give and receive clear instructions.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 12,
    metadata: { po_type: 'washington_accord', measured_via: 'Presentation scores, report quality' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO11',
    name: 'Project Management and Finance',
    description: 'Demonstrate knowledge and understanding of the engineering and management principles and apply these to one\'s own work, as a member and leader in a team, to manage projects and in multidisciplinary environments.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 13,
    metadata: { po_type: 'washington_accord', measured_via: 'Management course + capstone' },
  },
  {
    criteria_code: 'NBA-C3',
    code: 'PO12',
    name: 'Life-long Learning',
    description: 'Recognize the need for, and have the preparation and ability to engage in independent and life-long learning in the broadest context of technological change.',
    max_marks: 7.5,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-11',
    sort_order: 14,
    metadata: { po_type: 'washington_accord', measured_via: 'Self-learning initiatives, MOOC completion' },
  },

  // ── Criterion 4: Students' Performance (120 marks) ──
  {
    criteria_code: 'NBA-C4',
    code: 'C4.1',
    name: 'Academic Results Analysis',
    description: 'Semester-wise and year-wise academic performance analysis: pass rates, distinction rates, CGPA distribution.',
    max_marks: 40,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-17',
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C4',
    code: 'C4.2',
    name: 'Student Progression & Success Rate',
    description: 'Year-on-year student progression rates, dropout rates, lateral entry performance, time-to-degree analysis.',
    max_marks: 30,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-01',
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C4',
    code: 'C4.3',
    name: 'Placement & Higher Education Outcomes',
    description: 'Placement percentage, median salary, companies recruited from, higher education admissions, entrepreneurship.',
    max_marks: 30,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-04',
    sort_order: 3,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C4',
    code: 'C4.4',
    name: 'Professional Achievements',
    description: 'Students qualifying GATE, GRE, civil services, professional certifications, awards at national/international levels.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-17',
    sort_order: 4,
    metadata: { secondary_connectors: ['DC-23'] },
  },

  // ── Criterion 5: Faculty Information & Contributions (100 marks) ──
  {
    criteria_code: 'NBA-C5',
    code: 'C5.1',
    name: 'Faculty Qualifications & Experience',
    description: 'Faculty profile: PhD percentage, NET/SET qualification, industry experience, years of teaching experience distribution.',
    max_marks: 30,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-16',
    sort_order: 1,
    metadata: { secondary_connectors: ['DC-02'] },
  },
  {
    criteria_code: 'NBA-C5',
    code: 'C5.2',
    name: 'Faculty Publications & Research',
    description: 'Faculty publications in indexed journals, conference proceedings, books, patents, h-index.',
    max_marks: 30,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-03',
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C5',
    code: 'C5.3',
    name: 'Faculty Development & Training',
    description: 'FDP participation, workshops conducted, industrial training, membership in professional bodies.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-02',
    sort_order: 3,
    metadata: { feeds: ['facilitator_development'] },
  },
  {
    criteria_code: 'NBA-C5',
    code: 'C5.4',
    name: 'Student-Faculty Ratio & Cadre Ratio',
    description: 'Student to faculty ratio, professor:associate:assistant ratio, faculty retention rates.',
    max_marks: 20,
    data_type: 'ratio',
    is_auto_calculable: true,
    requires_evidence: false,
    data_connector_code: 'DC-02',
    sort_order: 4,
    metadata: { secondary_connectors: ['DC-01'] },
  },

  // ── Criterion 6: Facilities & Technical Support (80 marks) ──
  {
    criteria_code: 'NBA-C6',
    code: 'C6.1',
    name: 'Laboratory & Equipment',
    description: 'Adequacy and currency of laboratory equipment, utilization rates, maintenance records, safety compliance.',
    max_marks: 30,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-14',
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C6',
    code: 'C6.2',
    name: 'Computing Facilities',
    description: 'Computer labs, software licenses, internet bandwidth, student-computer ratio, licensed software for program needs.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-28',
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C6',
    code: 'C6.3',
    name: 'Library & Information Resources',
    description: 'Program-relevant books, journals, e-resources, digital library, OPAC, DELNET/INFLIBNET membership.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-20',
    sort_order: 3,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C6',
    code: 'C6.4',
    name: 'Technical Support Staff',
    description: 'Lab technicians, IT support staff, their qualifications, training, and adequacy for program support.',
    max_marks: 10,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-02',
    sort_order: 4,
    metadata: {},
  },

  // ── Criterion 7: Continuous Improvement (100 marks) ──
  {
    criteria_code: 'NBA-C7',
    code: 'C7.1',
    name: 'Action on Attainment Gaps',
    description: 'Documented actions taken when PO/CO attainment falls below targets. Closing-the-loop evidence.',
    max_marks: 35,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: 'DC-10',
    sort_order: 1,
    metadata: { feeds: ['okr_objectives'] },
  },
  {
    criteria_code: 'NBA-C7',
    code: 'C7.2',
    name: 'Curriculum Improvement Cycle',
    description: 'Periodic curriculum revision based on OBE data, industry feedback, BoS recommendations, and attainment analysis.',
    max_marks: 35,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-27',
    sort_order: 2,
    metadata: { secondary_connectors: ['DC-24'] },
  },
  {
    criteria_code: 'NBA-C7',
    code: 'C7.3',
    name: 'Quality Benchmarking',
    description: 'Benchmarking with peer institutions, participation in rankings, accreditation improvements, IQAC integration.',
    max_marks: 30,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-24',
    sort_order: 3,
    metadata: {},
  },

  // ── Criterion 8: First Year Academics (70 marks) ──
  {
    criteria_code: 'NBA-C8',
    code: 'C8.1',
    name: 'First Year Induction & Orientation',
    description: 'Student induction program, orientation activities, mentor assignment, campus familiarization.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C8',
    code: 'C8.2',
    name: 'Bridge/Remedial Courses',
    description: 'Bridge courses for academically weaker students, remedial teaching, foundation courses in math/science/language.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-12',
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C8',
    code: 'C8.3',
    name: 'First Year Academic Performance',
    description: 'First year pass rates, dropout rates, performance distribution, correlation with entry qualification.',
    max_marks: 30,
    data_type: 'percentage',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-17',
    sort_order: 3,
    metadata: { secondary_connectors: ['DC-01'] },
  },

  // ── Criterion 9: Student Support Systems (80 marks) ──
  {
    criteria_code: 'NBA-C9',
    code: 'C9.1',
    name: 'Scholarships & Financial Support',
    description: 'Scholarships, fee concessions, financial aid, education loans facilitated for economically weaker students.',
    max_marks: 20,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-09',
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C9',
    code: 'C9.2',
    name: 'Career Guidance & Placement Support',
    description: 'Training and placement cell activities, career counselling, mock interviews, resume building, aptitude training.',
    max_marks: 25,
    data_type: 'number',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-25',
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C9',
    code: 'C9.3',
    name: 'Mentoring & Counselling',
    description: 'Faculty mentor-mentee system, professional counsellor availability, student wellness programs.',
    max_marks: 15,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 3,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C9',
    code: 'C9.4',
    name: 'Grievance Redressal & Safety',
    description: 'Anti-ragging measures, sexual harassment committee, grievance portal, safety mechanisms, student insurance.',
    max_marks: 20,
    data_type: 'boolean',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-09',
    sort_order: 4,
    metadata: {},
  },

  // ── Criterion 10: Governance, Institutional Support & Financial Resources (120 marks) ──
  {
    criteria_code: 'NBA-C10',
    code: 'C10.1',
    name: 'Governance Structure',
    description: 'Board of Governors, Academic Council, BoS composition and functioning. Decentralized decision-making.',
    max_marks: 30,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 1,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C10',
    code: 'C10.2',
    name: 'Budget Allocation to Program',
    description: 'Annual budget allocation for the specific program: equipment, consumables, library, faculty development, student activities.',
    max_marks: 30,
    data_type: 'currency',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-21',
    sort_order: 2,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C10',
    code: 'C10.3',
    name: 'Industry Advisory Board',
    description: 'Composition and functioning of Industry Advisory Board, frequency of meetings, industry input on curriculum and placements.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-08',
    sort_order: 3,
    metadata: {},
  },
  {
    criteria_code: 'NBA-C10',
    code: 'C10.4',
    name: 'Financial Sustainability & Audits',
    description: 'Fee collection efficiency, financial audit compliance, infrastructure investment trends, resource optimization.',
    max_marks: 20,
    data_type: 'currency',
    is_auto_calculable: true,
    requires_evidence: true,
    data_connector_code: 'DC-33',
    sort_order: 4,
    metadata: { secondary_connectors: ['DC-06'] },
  },
  {
    criteria_code: 'NBA-C10',
    code: 'C10.5',
    name: 'Institutional Support for Program',
    description: 'Institutional policies supporting program quality: sabbatical, seed grants, conference travel, publication incentives.',
    max_marks: 20,
    data_type: 'text',
    is_auto_calculable: false,
    requires_evidence: true,
    data_connector_code: null,
    sort_order: 5,
    metadata: {},
  },
]
